### ISSUE TITLE
[Dynmap Render Thread/FATAL] [Dynmap/Dynmap]: [Dynmap] Error while raytracing tile:

### ISSUE THREAD

**Issue by cg49me** [webbukkit/dynmap#1722]
Running an admittedly heavily modded Forge server...  At first I thought it was simply due to missing textures, but I ran DynmapModScraper 2.0.0 and copied everything into my server's renderdata/custom folder, and I still have the same problem.  The server still runs, but it becomes progressively bogged down with time, and after a few hours, starts throwing heap memory errors.

I believe the pertinent part of the log is below:

[11:55:13] [Dynmap Render Thread/FATAL] [Dynmap/Dynmap]: [Dynmap] Error while raytracing tile: perspective=iso_NE_30_hires, coord=-311,163,236, blockid=541:1, lighting=15:0, biome=NULL
java.lang.ArrayIndexOutOfBoundsException: 541
	at org.dynmap.hdmap.DefaultHDShader$OurShaderState.getBlockColors(DefaultHDShader.java:142) ~[DefaultHDShader$OurShaderState.class:?]
	at org.dynmap.hdmap.DefaultHDShader$OurShaderState.processBlock(DefaultHDShader.java:157) ~[DefaultHDShader$OurShaderState.class:?]
	at org.dynmap.hdmap.IsoHDPerspective$OurPerspectiveState.handlePatches(IsoHDPerspective.java:496) ~[IsoHDPerspective$OurPerspectiveState.class:?]
	at org.dynmap.hdmap.IsoHDPerspective$OurPerspectiveState.visit_block(IsoHDPerspective.java:543) ~[IsoHDPerspective$OurPerspectiveState.class:?]
	at org.dynmap.hdmap.IsoHDPerspective$OurPerspectiveState.raytrace(IsoHDPerspective.java:648) ~[IsoHDPerspective$OurPerspectiveState.class:?]
	at org.dynmap.hdmap.IsoHDPerspective$OurPerspectiveState.access$300(IsoHDPerspective.java:84) ~[IsoHDPerspective$OurPerspectiveState.class:?]
	at org.dynmap.hdmap.IsoHDPerspective.render(IsoHDPerspective.java:1155) [IsoHDPerspective.class:?]
	at org.dynmap.hdmap.HDMapTile.render(HDMapTile.java:79) [HDMapTile.class:?]
	at org.dynmap.MapManager$FullWorldRenderState.processTile(MapManager.java:700) [MapManager$FullWorldRenderState.class:?]
	at org.dynmap.MapManager$FullWorldRenderState.run(MapManager.java:641) [MapManager$FullWorldRenderState.class:?]
	at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1.run(MapManager.java:190) [MapManager$DynmapScheduledThreadPoolExecutor$1.class:?]
	at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$2.run(MapManager.java:206) [MapManager$DynmapScheduledThreadPoolExecutor$2.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_25]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_25]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [?:1.8.0_25]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:1.8.0_25]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_25]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_25]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_25]
[11:55:13] [Dynmap Render Thread/FATAL] [Dynmap/Dynmap]: [Dynmap] Error while raytracing tile: perspective=iso_NE_30_hires, coord=-311,163,236, blockid=541:1, lighting=15:0, biome=NULL
java.lang.ArrayIndexOutOfBoundsException: 541
	at org.dynmap.hdmap.DefaultHDShader$OurShaderState.getBlockColors(DefaultHDShader.java:142) ~[DefaultHDShader$OurShaderState.class:?]
	at org.dynmap.hdmap.DefaultHDShader$OurShaderState.processBlock(DefaultHDShader.java:157) ~[DefaultHDShader$OurShaderState.class:?]
	at org.dynmap.hdmap.IsoHDPerspective$OurPerspectiveState.handlePatches(IsoHDPerspective.java:496) ~[IsoHDPerspective$OurPerspectiveState.class:?]
	at org.dynmap.hdmap.IsoHDPerspective$OurPerspectiveState.visit_block(IsoHDPerspective.java:543) ~[IsoHDPerspective$OurPerspectiveState.class:?]
	at org.dynmap.hdmap.IsoHDPerspective$OurPerspectiveState.raytrace(IsoHDPerspective.java:648) ~[IsoHDPerspective$OurPerspectiveState.class:?]
	at org.dynmap.hdmap.IsoHDPerspective$OurPerspectiveState.access$300(IsoHDPerspective.java:84) ~[IsoHDPerspective$OurPerspectiveState.class:?]
	at org.dynmap.hdmap.IsoHDPerspective.render(IsoHDPerspective.java:1155) [IsoHDPerspective.class:?]
	at org.dynmap.hdmap.HDMapTile.render(HDMapTile.java:79) [HDMapTile.class:?]
	at org.dynmap.MapManager$FullWorldRenderState.processTile(MapManager.java:700) [MapManager$FullWorldRenderState.class:?]
	at org.dynmap.MapManager$FullWorldRenderState.run(MapManager.java:641) [MapManager$FullWorldRenderState.class:?]
	at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1.run(MapManager.java:190) [MapManager$DynmapScheduledThreadPoolExecutor$1.class:?]
	at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$2.run(MapManager.java:206) [MapManager$DynmapScheduledThreadPoolExecutor$2.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_25]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_25]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [?:1.8.0_25]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:1.8.0_25]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_25]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_25]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_25]
[11:55:13] [Dynmap Render Thread/FATAL] [Dynmap/Dynmap]: [Dynmap] Error while raytracing tile: perspective=iso_NE_30_hires, coord=-311,163,236, blockid=541:1, lighting=15:0, biome=NULL
java.lang.ArrayIndexOutOfBoundsException: 541
	at org.dynmap.hdmap.DefaultHDShader$OurShaderState.getBlockColors(DefaultHDShader.java:142) ~[DefaultHDShader$OurShaderState.class:?]
	at org.dynmap.hdmap.DefaultHDShader$OurShaderState.processBlock(DefaultHDShader.java:157) ~[DefaultHDShader$OurShaderState.class:?]
	at org.dynmap.hdmap.IsoHDPerspective$OurPerspectiveState.handlePatches(IsoHDPerspective.java:496) ~[IsoHDPerspective$OurPerspectiveState.class:?]
	at org.dynmap.hdmap.IsoHDPerspective$OurPerspectiveState.visit_block(IsoHDPerspective.java:543) ~[IsoHDPerspective$OurPerspectiveState.class:?]
	at org.dynmap.hdmap.IsoHDPerspective$OurPerspectiveState.raytrace(IsoHDPerspective.java:648) ~[IsoHDPerspective$OurPerspectiveState.class:?]
	at org.dynmap.hdmap.IsoHDPerspective$OurPerspectiveState.access$300(IsoHDPerspective.java:84) ~[IsoHDPerspective$OurPerspectiveState.class:?]
	at org.dynmap.hdmap.IsoHDPerspective.render(IsoHDPerspective.java:1155) [IsoHDPerspective.class:?]
	at org.dynmap.hdmap.HDMapTile.render(HDMapTile.java:79) [HDMapTile.class:?]
	at org.dynmap.MapManager$FullWorldRenderState.processTile(MapManager.java:700) [MapManager$FullWorldRenderState.class:?]
	at org.dynmap.MapManager$FullWorldRenderState.run(MapManager.java:641) [MapManager$FullWorldRenderState.class:?]
	at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1.run(MapManager.java:190) [MapManager$DynmapScheduledThreadPoolExecutor$1.class:?]
	at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$2.run(MapManager.java:206) [MapManager$DynmapScheduledThreadPoolExecutor$2.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_25]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_25]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [?:1.8.0_25]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:1.8.0_25]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_25]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_25]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_25]
[11:55:13] [Dynmap Render Thread/FATAL] [Dynmap/Dynmap]: [Dynmap] Error while raytracing tile: perspective=iso_NE_30_hires, coord=-311,163,236, blockid=541:1, lighting=15:0, biome=NULL
java.lang.ArrayIndexOutOfBoundsException: 541
	at org.dynmap.hdmap.DefaultHDShader$OurShaderState.getBlockColors(DefaultHDShader.java:142) ~[DefaultHDShader$OurShaderState.class:?]
	at org.dynmap.hdmap.DefaultHDShader$OurShaderState.processBlock(DefaultHDShader.java:157) ~[DefaultHDShader$OurShaderState.class:?]
	at org.dynmap.hdmap.IsoHDPerspective$OurPerspectiveState.handlePatches(IsoHDPerspective.java:496) ~[IsoHDPerspective$OurPerspectiveState.class:?]
	at org.dynmap.hdmap.IsoHDPerspective$OurPerspectiveState.visit_block(IsoHDPerspective.java:543) ~[IsoHDPerspective$OurPerspectiveState.class:?]
	at org.dynmap.hdmap.IsoHDPerspective$OurPerspectiveState.raytrace(IsoHDPerspective.java:648) ~[IsoHDPerspective$OurPerspectiveState.class:?]
	at org.dynmap.hdmap.IsoHDPerspective$OurPerspectiveState.access$300(IsoHDPerspective.java:84) ~[IsoHDPerspective$OurPerspectiveState.class:?]
	at org.dynmap.hdmap.IsoHDPerspective.render(IsoHDPerspective.java:1155) [IsoHDPerspective.class:?]
	at org.dynmap.hdmap.HDMapTile.render(HDMapTile.java:79) [HDMapTile.class:?]
	at org.dynmap.MapManager$FullWorldRenderState.processTile(MapManager.java:700) [MapManager$FullWorldRenderState.class:?]
	at org.dynmap.MapManager$FullWorldRenderState.run(MapManager.java:641) [MapManager$FullWorldRenderState.class:?]
	at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1.run(MapManager.java:190) [MapManager$DynmapScheduledThreadPoolExecutor$1.class:?]
	at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$2.run(MapManager.java:206) [MapManager$DynmapScheduledThreadPoolExecutor$2.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_25]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_25]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [?:1.8.0_25]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:1.8.0_25]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_25]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_25]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_25]
[11:55:13] [Dynmap Render Thread/FATAL] [Dynmap/Dynmap]: [Dynmap] Error while raytracing tile: perspective=iso_NE_30_hires, coord=-311,163,236, blockid=541:1, lighting=15:0, biome=NULL
java.lang.ArrayIndexOutOfBoundsException
[11:55:13] [Dynmap Render Thread/FATAL] [Dynmap/Dynmap]: [Dynmap] Error while raytracing tile: perspective=iso_NE_30_hires, coord=-311,163,236, blockid=541:1, lighting=15:0, biome=NULL
java.lang.ArrayIndexOutOfBoundsException
[11:55:13] [Dynmap Render Thread/FATAL] [Dynmap/Dynmap]: [Dynmap] Error while raytracing tile: perspective=iso_NE_30_hires, coord=-311,163,236, blockid=541:1, lighting=15:0, biome=NULL
java.lang.ArrayIndexOutOfBoundsException
[11:55:13] [Dynmap Render Thread/FATAL] [Dynmap/Dynmap]: [Dynmap] Error while raytracing tile: perspective=iso_NE_30_hires, coord=-311,163,236, blockid=541:1, lighting=15:0, biome=NULL
java.lang.ArrayIndexOutOfBoundsException

It keeps throwing those last few lines.  I traced some of those block ID's to the Metallurgy, Artifice, and Engineer's Toolbox mods...  As I said though, I ran DynModScraper, and I can see earlier in the log where it loaded everything that I copied over.

SPECTACULAR mod, worked great on my previous Bukkit server.  Moving things over to Forge, hence the issues.  Thanks!

**Comment by mikeprimm** [comment]
Give new dev build of 2.2 a spin - problem is associated with using default shader (one that uses the color schema files, versus a resource pack) in conjunction with Forge mods providing custom blocks above 256.  The new code should fix it, but the color schema files will still not have colors defined for non-vanilla blocks, so they'll wind up being black.  Best option is to shift to a RP based shader, like stdtexture.

**Comment by cg49me** [comment]
That seems to have fixed it - thanks!
