### ISSUE TITLE
Crash on Server-Stop-Event

### ISSUE THREAD

**Issue by ReneMuetti** [webbukkit/dynmap#1741]
[16:28:14] [Server thread/ERROR] [FML/]: Fatal errors were detected during the transition from SERVER_STARTED to SERVER_STOPPING. Loading cannot continue
[16:28:14] [Server thread/ERROR] [FML/]: 
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	FML{7.10.85.1291} [Forge Mod Loader] (minecraft_server.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	Forge{10.13.2.1291} [Minecraft Forge] (minecraft_server.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	<CoFH ASM>{000} [CoFH ASM Data Initialization] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	IC2{2.2.676-experimental} [IndustrialCraft 2] (IndustrialCraft 2 2.2.676 exp.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	AdvancedSolarPanel{1.7.10-3.5.1} [Advanced Solar Panels] (Advanced Solar Panels 3.5.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	AdvancedMachines{1.1.3} [IC2 Advanced Machines Addon] (AdvancedMachinesAS 1.1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	ArchimedesShips{1.7.10 v1.7.1} [Archimedes' Ships] (ArchimedesShips 1.7.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	Backpack{2.0.1} [Backpack] (Backpack 2.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	BattleTowers{1.5.1} [Battle Towers] (BattleTowers-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	BetterAnvil{4.0.0.0} [Better Anvil] (BetterAnvil 4.0.0.0 alpha-1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	BiblioCraft{1.9.2} [BiblioCraft] (BiblioCraft 1.9.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	CoFHCore{1.7.10R3.0.0B9} [CoFH Core] (CoFHCore 3.0.0B9-40.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	BuildCraft|Core{6.3.6} [BuildCraft] (BuildCraft 6.3.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	Forestry{3.4.0.7} [Forestry for Minecraft] (Forestry 3.4.0.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	BiblioWoodsForestry{1.5} [BiblioWoods Forestry Edition] (BiblioWoods Forestry v1.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	BinnieCore{2.0-pre6b} [Binnie Core] (Binnie Mods 2.0 pre 6b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	Botany{2.0-pre6b} [Botany] (Binnie Mods 2.0 pre 6b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	ExtraBees{2.0-pre6b} [Extra Bees] (Binnie Mods 2.0 pre 6b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	ExtraTrees{2.0-pre6b} [Extra Trees] (Binnie Mods 2.0 pre 6b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	Genetics{2.0-pre6b} [Genetics] (Binnie Mods 2.0 pre 6b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	BuildCraft|Compat{6.3.0} [BuildCraft Compat] (BuildCraft 6.3.1 Compat.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	BuildCraft|Transport{6.3.6} [BC Transport] (BuildCraft 6.3.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	BuildCraft|Silicon{6.3.6} [BC Silicon] (BuildCraft 6.3.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	BuildCraft|Builders{6.3.6} [BC Builders] (BuildCraft 6.3.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	BuildCraft|Energy{6.3.6} [BC Energy] (BuildCraft 6.3.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	BuildCraft|Factory{6.3.6} [BC Factory] (BuildCraft 6.3.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	ChickenChunks{1.3.4.16} [ChickenChunks] (ChickenChunks 1.3.4.16 universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	ComputerCraft{1.65} [ComputerCraft] (ComputerCraft 1.65.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	craftguide{1.6.8.1} [CraftGuide] (CraftGuide 1.6.8.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	customnpcs{1.7.10b} [CustomNpcs] (CustomNPCs 1.7.10b 2014-09-20.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	dungeonpack{1.7.10-1.0} [Dungeon Pack] (DungeonPack 1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	Dynmap{2.2-alpha-1-106} [Dynmap] (Dynmap-2.2.0-alpha-1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Errored
	eplus{3.0.2-d} [Enchanting Plus] (EnchantingPlus 3.0.2d.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	EnderStorage{1.4.5.27} [EnderStorage] (EnderStorage 1.4.5.27.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	factorization.notify{1.0} [Factorization Notification System] (Factorization 0.8.88.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	factorization{1.7.10-0.8.88.7} [Factorization] (Factorization 0.8.88.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	factorization.misc{1.7.10-0.8.88.7} [Factorization Miscellaneous Nonsense] (Factorization 0.8.88.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	GraviSuite{1.7.10-2.0.3} [Graviation Suite] (GraviSuite 2.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	IronChest{6.0.62.742} [Iron Chest] (IronChest 6.0.62.742.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	JABBA{1.2.0a} [JABBA] (Jabba 1.2.0a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	Thaumcraft{4.2.3.4} [Thaumcraft] (Thaumcraft 4.2.3.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	Railcraft{9.5.0.0} [Railcraft] (Railcraft 9.5.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	ThermalFoundation{1.7.10R1.0.0RC1} [Thermal Foundation] (ThermalFoundation 1.0.0RC1-13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	ThermalExpansion{1.7.10R4.0.0B8} [Thermal Expansion] (ThermalExpansion 4.0.0B8-23.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	MagicBees{1.7.10-2.1.22} [Magic Bees] (MagicBees 2.1.22.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	cfm{3.3.5} [Â§6MrCrayfish's Furniture Mod] (MrCrayfishs Furniture Mod v3.3.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	MultiPageChest{1.3.4} [Multi Page Chest] (MultiPageChest 1.3.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	Mystcraft{0.11.0.00} [Mystcraft] (Mystcraft 0.11.0.00.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	NetherOres{1.7.10R2.3.0RC4} [Nether Ores] (NetherOres 2.3.0RC4-4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	RedstoneArsenal{1.7.10R1.1.0RC1} [Redstone Arsenal] (RedstoneArsenal 1.1.0 RC1-19.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	libsandstone{1.0.0} [libsandstone] (LibSandstone-1.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	xreliquary{1.2.DEV} [Reliquary] (Reliquary 1.2.160.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	SSR{rc3} [Soul Shards Reborn] (Soul Shards - Reborn rc3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	StevesCarts{2.0.0.b18} [Steve's Carts 2] (StevesCarts 2.0.0 b18.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	ThaumcraftMobAspects{1.7.x-2B} [Thaumcraft Mob Aspects] (Thaumcraft Mob Aspects 1.7.x 2B Sapshot 17.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	TwilightForest{2.3.2} [The Twilight Forest] (The Twilight Forest 2.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	Treecapitator{1.7.10} [Treecapitator] (Treecapitator 2.0.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
	AS_UpdateCheck{1.1.6} [AtomicStryker Update Check Mod] (UpdateCheckerMod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
[16:28:14] [Server thread/ERROR] [FML/]: The following problems were captured during this phase
[16:28:14] [Server thread/ERROR] [FML/]: Caught exception from Dynmap
java.lang.NoClassDefFoundError: org/dynmap/snakeyaml/serializer/Serializer
	at org.dynmap.snakeyaml.Yaml.dumpAll(Yaml.java:265) ~[Yaml.class:?]
	at org.dynmap.snakeyaml.Yaml.dumpAll(Yaml.java:261) ~[Yaml.class:?]
	at org.dynmap.snakeyaml.Yaml.dump(Yaml.java:248) ~[Yaml.class:?]
	at org.dynmap.ConfigurationNode.save(ConfigurationNode.java:123) ~[ConfigurationNode.class:?]
	at org.dynmap.ConfigurationNode.save(ConfigurationNode.java:106) ~[ConfigurationNode.class:?]
	at org.dynmap.forge.DynmapPlugin.saveWorlds(DynmapPlugin.java:1870) ~[DynmapPlugin.class:?]
	at org.dynmap.forge.DynmapPlugin.onDisable(DynmapPlugin.java:1431) ~[DynmapPlugin.class:?]
	at org.dynmap.forge.Proxy.stopServer(Proxy.java:20) ~[Proxy.class:?]
	at org.dynmap.forge.DynmapMod.serverStopping(DynmapMod.java:133) ~[DynmapMod.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_15]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_15]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_15]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_15]
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513) ~[FMLModContainer.class:?]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_15]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_15]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.7.10.jar:?]
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208) ~[LoadController.class:?]
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187) ~[LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_15]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_15]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_15]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_15]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.7.10.jar:?]
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118) [LoadController.class:?]
	at cpw.mods.fml.common.Loader.serverStopping(Loader.java:758) [Loader.class:?]
	at cpw.mods.fml.common.FMLCommonHandler.handleServerStopping(FMLCommonHandler.java:289) [FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:434) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Caused by: java.lang.ClassNotFoundException: org.dynmap.snakeyaml.serializer.Serializer
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_15]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_15]
	... 38 more
Caused by: java.lang.OutOfMemoryError: PermGen space
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_15]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.7.0_15]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.7.0_15]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_15]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_15]
	at org.dynmap.snakeyaml.Yaml.dumpAll(Yaml.java:265) ~[Yaml.class:?]
	at org.dynmap.snakeyaml.Yaml.dumpAll(Yaml.java:261) ~[Yaml.class:?]
	at org.dynmap.snakeyaml.Yaml.dump(Yaml.java:248) ~[Yaml.class:?]
	at org.dynmap.ConfigurationNode.save(ConfigurationNode.java:123) ~[ConfigurationNode.class:?]
	at org.dynmap.ConfigurationNode.save(ConfigurationNode.java:106) ~[ConfigurationNode.class:?]
	at org.dynmap.forge.DynmapPlugin.saveWorlds(DynmapPlugin.java:1870) ~[DynmapPlugin.class:?]
	at org.dynmap.forge.DynmapPlugin.onDisable(DynmapPlugin.java:1431) ~[DynmapPlugin.class:?]
	at org.dynmap.forge.Proxy.stopServer(Proxy.java:20) ~[Proxy.class:?]
	at org.dynmap.forge.DynmapMod.serverStopping(DynmapMod.java:133) ~[DynmapMod.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_15]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_15]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_15]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_15]
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513) ~[FMLModContainer.class:?]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_15]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_15]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.7.10.jar:?]
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208) ~[LoadController.class:?]
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187) ~[LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_15]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_15]
[16:28:15] [Server thread/DEBUG] [FML/]: Reverting to frozen data state.
[16:28:15] [Server thread/INFO] [FML/]: Applying holder lookups
[16:28:15] [Server thread/INFO] [FML/]: Holder lookups applied

**Comment by mikeprimm** [comment]
That is due to the JAR file having been replaced, updated, or deleted while the server was running.
