### ISSUE TITLE
CTD with new base Forge #13XX and up: Null Fluidstack exception (game crashing!)

### ISSUE THREAD

**Issue by cocopuffs99** [webbukkit/dynmap#1767]
Getting this crash when right clicking a ferment barrel (crashes like a charm every time).  I know many mods are getting this crash with the new way Forge handles fluids since Forge 13XX builds; is there an expected update for Growthcraft any time soon?  I love the mod and it is great! Thanks =)

Unexpected error
java.lang.IllegalArgumentException: Cannot create a fluidstack from a null fluid
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:29)
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:59)
	at growthcraft.cellar.tileentity.TileEntityFermentBarrel.getGUINetworkData(TileEntityFermentBarrel.java:381)
	at growthcraft.cellar.container.ContainerFermentBarrel.func_75137_b(ContainerFermentBarrel.java:128)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147245_a(NetHandlerPlayClient.java:1151)
	at net.minecraft.network.play.server.S31PacketWindowProperty.func_148833_a(SourceFile:26)
	at net.minecraft.network.play.server.S31PacketWindowProperty.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1590)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

Full crash log: http://pastebin.com/Th4HDiQM

**Comment by tylerhoot** [comment]
well im having the same issue but with canarymod and with any type of water when land is being generated by the dynmap and when updating tiles with water in them. same issue with water.
https://github.com/webbukkit/dynmap/issues/1771

**Comment by mikeprimm** [comment]
Nothing in this exception to suggest that Dynmap has anything to do with it.... it looks like a GrowthCraft problem

**Comment by swamp-iv** [comment]
I Got Probelms While Placing Temparate Fluiduct Crashed World
java.null.exeption

Cannot Create Fluidstack From Null Fluid
