### ISSUE TITLE
error canarydynmap 2.1+

### ISSUE THREAD

**Issue by tylerhoot** [webbukkit/dynmap#1771]
16:00:09] [CanaryMod] [ERROR]: Exception while executing Hook: LiquidDestroyHook in PluginListener: OurLiquidDestroyTrigger (Plugin: dynmap)
java.lang.NoSuchMethodError: net.canarymod.api.world.blocks.Block.getData()S
        at org.dynmap.canary.DynmapPlugin.checkBlock(DynmapPlugin.java:1107) ~[?:?]
        at org.dynmap.canary.DynmapPlugin.access$2300(DynmapPlugin.java:98) ~[?:?]
        at org.dynmap.canary.DynmapPlugin$OurLiquidDestroyTrigger.onLiquidDestroy(DynmapPlugin.java:1464) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_45]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]
        at net.canarymod.hook.HookExecutor$1.execute(HookExecutor.java:59) ~[CanaryMod.jar:1.8.0-1.2.1-SNAPSHOT]
        at net.canarymod.plugin.RegisteredPluginListener.execute(RegisteredPluginListener.java:52) ~[CanaryMod.jar:1.8.0-1.2.1-SNAPSHOT]
        at net.canarymod.hook.HookExecutor.callHook(HookExecutor.java:129) [CanaryMod.jar:1.8.0-1.2.1-SNAPSHOT]
        at net.canarymod.hook.Hook.call(Hook.java:37) [CanaryMod.jar:1.8.0-1.2.1-SNAPSHOT]
        at net.canarymod.hook.CancelableHook.call(CancelableHook.java:26) [CanaryMod.jar:1.8.0-1.2.1-SNAPSHOT]
        at net.minecraft.block.BlockDynamicLiquid.h(BlockDynamicLiquid.java:267) [CanaryMod.jar:1.8.0-1.2.1-SNAPSHOT]
        at net.minecraft.block.BlockDynamicLiquid.b(BlockDynamicLiquid.java:112) [CanaryMod.jar:1.8.0-1.2.1-SNAPSHOT]
        at net.minecraft.world.WorldServer.a(WorldServer.java:532) [CanaryMod.jar:1.8.0-1.2.1-SNAPSHOT]
        at net.minecraft.world.WorldServer.c(WorldServer.java:191) [CanaryMod.jar:1.8.0-1.2.1-SNAPSHOT]
        at net.minecraft.server.MinecraftServer.z(MinecraftServer.java:671) [CanaryMod.jar:1.8.0-1.2.1-SNAPSHOT]
        at net.minecraft.server.dedicated.DedicatedServer.z(DedicatedServer.java:446) [CanaryMod.jar:1.8.0-1.2.1-SNAPSHOT]
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:589) [CanaryMod.jar:1.8.0-1.2.1-SNAPSHOT]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:491) [CanaryMod.jar:1.8.0-1.2.1-SNAPSHOT]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]

**Comment by tylerhoot** [comment]
issue when dynmap is generating land and when dynmap is updating tiles with water. when I unload the plugin dynmap errors stops. this error also makes canarymod crash too

**Comment by tylerhoot** [comment]
at net.canarymod.hook.HookExecutor.callHook(HookExecutor.java:129) [CanaryMod.jar:1.8.0-1.2.1-SNAPSHOT]
        at net.canarymod.hook.Hook.call(Hook.java:37) [CanaryMod.jar:1.8.0-1.2.1-SNAPSHOT]
        at net.canarymod.hook.CancelableHook.call(CancelableHook.java:26) [CanaryMod.jar:1.8.0-1.2.1-SNAPSHOT]
        at net.minecraft.block.BlockDynamicLiquid.h(BlockDynamicLiquid.java:267) [CanaryMod.jar:1.8.0-1.2.1-SNAPSHOT]
        at net.minecraft.block.BlockDynamicLiquid.b(BlockDynamicLiquid.java:112) [CanaryMod.jar:1.8.0-1.2.1-SNAPSHOT]
        at net.minecraft.world.WorldServer.a(WorldServer.java:532) [CanaryMod.jar:1.8.0-1.2.1-SNAPSHOT]
        at net.minecraft.world.WorldServer.c(WorldServer.java:191) [CanaryMod.jar:1.8.0-1.2.1-SNAPSHOT]
        at net.minecraft.server.MinecraftServer.z(MinecraftServer.java:671) [CanaryMod.jar:1.8.0-1.2.1-SNAPSHOT]
        at net.minecraft.server.dedicated.DedicatedServer.z(DedicatedServer.java:446) [CanaryMod.jar:1.8.0-1.2.1-SNAPSHOT]
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:589) [CanaryMod.jar:1.8.0-1.2.1-SNAPSHOT]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:491) [CanaryMod.jar:1.8.0-1.2.1-SNAPSHOT]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]

**Comment by tylerhoot** [comment]
https://github.com/CanaryModTeam/CanaryMod/issues/215#issuecomment-98689738

**Comment by mikeprimm** [comment]
Are you running the DynmapCanary for 1.8.0 (v1.2.1 canarymod), or the 1.7.10 one?  That looks like the 1.7.10 one....

**Comment by tylerhoot** [comment]
Last time I checked it was the 1.8 one yes im running CanaryMod 1.8 (1.2.1)

**Comment by Psy-Virus** [comment]
MC Versions < 1.8.9 are not supported anymore. If you have further issues regarding this, pls reopen or recreate this issue with updated Versions and Details.
