### ISSUE TITLE
Marker API Impl Error?

### ISSUE THREAD

**Issue by CLGREEN94** [webbukkit/dynmap#1793]
Good Afternoon, 

So I keep getting this error after I do a reload of the plugin and I have to re-download the .jar file in order to fix it. 

Has anyone got any idea what the issue might be or how to fix it? 
- Thanks

Callum. 

`[11:18:53 ERROR]: Error occurred while enabling dynmap v2.2-SNAPSHOT-1110 (Is it up to date?)
java.lang.LinkageError: loader constraint violation in interface itable initialization: when resolving method "org.dynmap.markers.impl.MarkerAPIImpl.getMarkerIcon(Ljava/lang/String;)Lorg/dynmap/markers/MarkerIcon;" the class loader (instance of org/bukkit/plugin/java/PluginClassLoader) of the current class, org/dynmap/markers/impl/MarkerAPIImpl, and the class loader (instance of org/bukkit/plugin/java/PluginClassLoader) for interface org/dynmap/markers/MarkerAPI have different Class objects for the type org/dynmap/markers/MarkerIcon used in the signature
        at org.dynmap.DynmapCore.initConfiguration(DynmapCore.java:423) ~[?:?]
        at org.dynmap.bukkit.DynmapPlugin.onEnable(DynmapPlugin.java:826) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-870264a-0a645a2]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [spigot.jar:git-Spigot-870264a-0a645a2]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-870264a-0a645a2]
        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:286) [PlugMan.jar:?]
        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:239) [PlugMan.jar:?]
        at com.rylinaux.plugman.util.PluginUtil.reload(PluginUtil.java:300) [PlugMan.jar:?]
        at com.rylinaux.plugman.command.ReloadCommand.execute(ReloadCommand.java:122) [PlugMan.jar:?]
        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:104) [PlugMan.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot.jar:git-Spigot-870264a-0a645a2]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot.jar:git-Spigot-870264a-0a645a2]
        at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchCommand(CraftServer.java:646) [spigot.jar:git-Spigot-870264a-0a645a2]
        at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchServerCommand(CraftServer.java:632) [spigot.jar:git-Spigot-870264a-0a645a2]
        at net.minecraft.server.v1_8_R2.DedicatedServer.aN(DedicatedServer.java:405) [spigot.jar:git-Spigot-870264a-0a645a2]
        at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:369) [spigot.jar:git-Spigot-870264a-0a645a2]
        at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot.jar:git-Spigot-870264a-0a645a2]
        at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot.jar:git-Spigot-870264a-0a645a2]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]`

**Comment by Wqrld** [comment]
i have this same problem rn

**Comment by Psy-Virus** [comment]
Is this still a problem? Then please create a new issue with updated details and by using the template.

**Comment by Pangamma** [comment]
@Psy-Virus  This is still a problem.

**Comment by KingMcPro** [comment]
@Pangamma @Psy-Virus me to :(

annyone who can help?

thanks!

**Comment by Pangamma** [comment]
@KingMcPro   Try erasing your entire dynmap folder and deleting it entirely and then restarting the server. That's the best we could do.
