### ISSUE TITLE
 java.util.ConcurrentModificationException under server restart.

### ISSUE THREAD

**Issue by Rocologo** [webbukkit/dynmap#1822]
08.08 08:24:18 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]
08.08 08:24:18 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot.jar:git-Spigot-d97e08b-880a532]
08.08 08:24:18 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigot.jar:git-Spigot-d97e08b-880a532]
08.08 08:24:18 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-d97e08b-880a532]
08.08 08:24:18 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:722) [spigot.jar:git-Spigot-d97e08b-880a532]
08.08 08:24:18 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-d97e08b-880a532]
08.08 08:24:18 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-d97e08b-880a532]
08.08 08:24:18 [Server] INFO at org.dynmap.markers.impl.MarkerAPIImpl$DoFileWrites.run(MarkerAPIImpl.java:346) ~[?:?]
08.08 08:24:18 [Server] INFO at java.util.HashMap$KeyIterator.next(HashMap.java:956) ~[?:1.7.0_79]
08.08 08:24:18 [Server] INFO at java.util.HashMap$HashIterator.nextEntry(HashMap.java:922) ~[?:1.7.0_79]
08.08 08:24:18 [Server] INFO java.util.ConcurrentModificationException
08.08 08:24:18 [Server] WARN [dynmap] Task #886 for dynmap v2.2-1118 generated an exception

**Comment by RedstoneFuture** [comment]
This? I have this problem too.

`[01:36:07 WARN]: [dynmap] Task #104915 for dynmap v2.5-Dev201706100405 generated an exception
java.util.ConcurrentModificationException: null
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437) ~[?:1.8.0_144]
        at java.util.HashMap$KeyIterator.next(HashMap.java:1461) ~[?:1.8.0_144]
        at org.dynmap.markers.impl.MarkerAPIImpl$DoFileWrites.run(MarkerAPIImpl.java:345) ~[?:?]
        at com.massivecraft.massivelag.inject.MassiveLagRunnable.run(MassiveLagRunnable.java:56) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.12.2.jar:git-Paper-1209]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356) [patched_1.12.2.jar:git-Paper-1209]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:833) [patched_1.12.2.jar:git-Paper-1209]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:424) [patched_1.12.2.jar:git-Paper-1209]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1209]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1209]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
`

**Comment by Psy-Virus** [comment]
Please retry with the latest versions of Dynmap http://www.dynmap.us/builds/dynmap/
