### ISSUE TITLE
DynmapCBBridge not work

### ISSUE THREAD

**Issue by origamerpro** [webbukkit/dynmap#1825]
not work plugin on KCauldron-1.7.10-1492.150 all versions plugin

error:
[06:20:06] [Server thread/ERROR]: Could not load 'plugins/DynmapCBBridge-2.1.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.IllegalStateException: JavaPlugin requires org.bukkit.plugin.java.PluginClassLoader
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:149) ~[JavaPluginLoader.class:1.7.10-1492.150]
    at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:334) ~[SimplePluginManager.class:1.7.10-1492.150]
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:256) [SimplePluginManager.class:1.7.10-1492.150]
    at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugins(CraftServer.java:320) [CraftServer.class:1.7.10-1492.150]
    at net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:461) [ayq.class:?]
    at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:137) [ayq.class:?]
    at net.minecraft.world.World.<init>(World.java:360) [ahb.class:?]
    at net.minecraft.world.WorldServer.<init>(WorldServer.java:158) [mt.class:?]
    at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:367) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336) [lt.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.IllegalStateException: JavaPlugin requires org.bukkit.plugin.java.PluginClassLoader
    at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:64) ~[JavaPlugin.class:1.7.10-1492.150]
    at org.dynmap.bukkitbridge.DynmapCBBridgePlugin.<init>(DynmapCBBridgePlugin.java:28) ~[DynmapCBBridgePlugin.class:?]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_51]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_51]
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_51]
    at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_51]
    at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_51]
    at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:201) ~[PluginClassLoader.class:1.7.10-1492.150]
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:145) ~[JavaPluginLoader.class:1.7.10-1492.150]
    ... 11 more

**Comment by Psy-Virus** [comment]
Still relevant with latest versions? Then please open a new issue with updated detail by using the issue template.
