### ISSUE TITLE
Render Fails with Terrain Control custom biomes

### ISSUE THREAD

**Issue by Rasor1911** [webbukkit/dynmap#1908]
Running Spigot 1.9
Running Dynmap 2-3-alpha
Running Terrain control 2.8.0 snapshot
   With biome bundle 

dynmap works normally but map is not rendered at all

```
[11:46:36] [Dynmap Render Thread/ERROR]: [dynmap] Exception during render job: world=bbundle, map=null

[11:46:36] [Dynmap Render Thread/WARN]: java.lang.IllegalArgumentException: No enum constant org.bukkit.block.Biome.FORESTENCHANTED

[11:46:36] [Dynmap Render Thread/WARN]: 	at java.lang.Enum.valueOf(Enum.java:238)

[11:46:36] [Dynmap Render Thread/WARN]: 	at org.bukkit.block.Biome.valueOf(Biome.java:1)

[11:46:36] [Dynmap Render Thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.block.CraftBlock.biomeBaseToBiome(CraftBlock.java:313)

[11:46:36] [Dynmap Render Thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.CraftChunkSnapshot.getBiome(CraftChunkSnapshot.java:79)

[11:46:36] [Dynmap Render Thread/WARN]: 	at org.dynmap.bukkit.NewMapChunkCache$OurMapIterator.biomePrep(NewMapChunkCache.java:171)

[11:46:36] [Dynmap Render Thread/WARN]: 	at org.dynmap.bukkit.NewMapChunkCache$OurMapIterator.<init>(NewMapChunkCache.java:81)

[11:46:36] [Dynmap Render Thread/WARN]: 	at org.dynmap.bukkit.NewMapChunkCache.getIterator(NewMapChunkCache.java:1011)

[11:46:36] [Dynmap Render Thread/WARN]: 	at org.dynmap.hdmap.IsoHDPerspective.render(IsoHDPerspective.java:1079)

[11:46:36] [Dynmap Render Thread/WARN]: 	at org.dynmap.hdmap.HDMapTile.render(HDMapTile.java:79)

[11:46:36] [Dynmap Render Thread/WARN]: 	at org.dynmap.MapManager$FullWorldRenderState.processTile(MapManager.java:700)

[11:46:36] [Dynmap Render Thread/WARN]: 	at org.dynmap.MapManager$FullWorldRenderState.run(MapManager.java:641)

[11:46:36] [Dynmap Render Thread/WARN]: 	at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$2.run(MapManager.java:206)

[11:46:36] [Dynmap Render Thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

[11:46:36] [Dynmap Render Thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)

[11:46:36] [Dynmap Render Thread/WARN]: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)

[11:46:36] [Dynmap Render Thread/WARN]: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)

[11:46:36] [Dynmap Render Thread/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)

[11:46:36] [Dynmap Render Thread/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

[11:46:36] [Dynmap Render Thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)

[11:46:36] [Dynmap Render Thread/ERROR]: [dynmap] Exception during render job: world=bbundle, map=org.dynmap.hdmap.HDMap@37e93f7c

[11:46:36] [Dynmap Render Thread/WARN]: java.lang.IllegalArgumentException: No enum constant org.bukkit.block.Biome.FORESTENCHANTED

[11:46:36] [Dynmap Render Thread/WARN]: 	at java.lang.Enum.valueOf(Enum.java:238)

[11:46:36] [Dynmap Render Thread/WARN]: 	at org.bukkit.block.Biome.valueOf(Biome.java:1)

[11:46:36] [Dynmap Render Thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.block.CraftBlock.biomeBaseToBiome(CraftBlock.java:313)

[11:46:36] [Dynmap Render Thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.CraftChunkSnapshot.getBiome(CraftChunkSnapshot.java:79)

[11:46:36] [Dynmap Render Thread/WARN]: 	at org.dynmap.bukkit.NewMapChunkCache$OurMapIterator.biomePrep(NewMapChunkCache.java:171)

[11:46:36] [Dynmap Render Thread/WARN]: 	at org.dynmap.bukkit.NewMapChunkCache$OurMapIterator.<init>(NewMapChunkCache.java:81)

[11:46:36] [Dynmap Render Thread/WARN]: 	at org.dynmap.bukkit.NewMapChunkCache.getIterator(NewMapChunkCache.java:1011)

[11:46:36] [Dynmap Render Thread/WARN]: 	at org.dynmap.hdmap.IsoHDPerspective.render(IsoHDPerspective.java:1079)

[11:46:36] [Dynmap Render Thread/WARN]: 	at org.dynmap.hdmap.HDMapTile.render(HDMapTile.java:79)

[11:46:36] [Dynmap Render Thread/WARN]: 	at org.dynmap.MapManager$FullWorldRenderState.processTile(MapManager.java:708)

[11:46:36] [Dynmap Render Thread/WARN]: 	at org.dynmap.MapManager$FullWorldRenderState.run(MapManager.java:641)

[11:46:36] [Dynmap Render Thread/WARN]: 	at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$2.run(MapManager.java:206)

[11:46:36] [Dynmap Render Thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

[11:46:36] [Dynmap Render Thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)

[11:46:36] [Dynmap Render Thread/WARN]: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)

[11:46:36] [Dynmap Render Thread/WARN]: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)

[11:46:36] [Dynmap Render Thread/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)

[11:46:36] [Dynmap Render Thread/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

[11:46:36] [Dynmap Render Thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)

[11:46:36] [Dynmap Render Thread/ERROR]: [dynmap] Exception during render job: world=bbundle, map=null

[11:46:36] [Dynmap Render Thread/WARN]: java.lang.IllegalArgumentException: No enum constant org.bukkit.block.Biome.FORESTENCHANTED

[11:46:36] [Dynmap Render Thread/WARN]: 	at java.lang.Enum.valueOf(Enum.java:238)

[11:46:36] [Dynmap Render Thread/WARN]: 	at org.bukkit.block.Biome.valueOf(Biome.java:1)

[11:46:36] [Dynmap Render Thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.block.CraftBlock.biomeBaseToBiome(CraftBlock.java:313)

[11:46:36] [Dynmap Render Thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.CraftChunkSnapshot.getBiome(CraftChunkSnapshot.java:79)

[11:46:36] [Dynmap Render Thread/WARN]: 	at org.dynmap.bukkit.NewMapChunkCache$OurMapIterator.biomePrep(NewMapChunkCache.java:171)

[11:46:36] [Dynmap Render Thread/WARN]: 	at org.dynmap.bukkit.NewMapChunkCache$OurMapIterator.<init>(NewMapChunkCache.java:81)

[11:46:36] [Dynmap Render Thread/WARN]: 	at org.dynmap.bukkit.NewMapChunkCache.getIterator(NewMapChunkCache.java:1011)

[11:46:36] [Dynmap Render Thread/WARN]: 	at org.dynmap.hdmap.IsoHDPerspective.render(IsoHDPerspective.java:1079)

[11:46:36] [Dynmap Render Thread/WARN]: 	at org.dynmap.hdmap.HDMapTile.render(HDMapTile.java:79)

[11:46:36] [Dynmap Render Thread/WARN]: 	at org.dynmap.MapManager$FullWorldRenderState.processTile(MapManager.java:700)

[11:46:36] [Dynmap Render Thread/WARN]: 	at org.dynmap.MapManager$FullWorldRenderState.run(MapManager.java:641)

[11:46:36] [Dynmap Render Thread/WARN]: 	at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1.run(MapManager.java:190)

[11:46:36] [Dynmap Render Thread/WARN]: 	at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$2.run(MapManager.java:206)

[11:46:36] [Dynmap Render Thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

[11:46:36] [Dynmap Render Thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)

[11:46:36] [Dynmap Render Thread/WARN]: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)

[11:46:36] [Dynmap Render Thread/WARN]: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)

[11:46:36] [Dynmap Render Thread/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)

[11:46:36] [Dynmap Render Thread/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

[11:46:36] [Dynmap Render Thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by gbl** [comment]
Same problem here. This patch fixed it for me by assuming all unknown biomes are plains (which isn't perfect, but at least something is rendered):

```
@@ -168,7 +168,13 @@ public class NewMapChunkCache extends MapChunkCache {
                         bm = BiomeMap.byBiomeID(helper.getBiomeBaseID(biomebase[bz << 4 | bx]));
                     }
                     else {
-                        Biome bb = snap.getBiome(bx, bz);
+                        Biome bb;
+                       try {
+                               bb = snap.getBiome(bx, bz);
+                       } catch (IllegalArgumentException ex) {
+                               // Log.info("Using plains for unknown biome :"+ex.getMessage());
+                               bb = Biome.PLAINS;
+                       }
                         if(bb == null)
                             bm = BiomeMap.NULL;
                         else

```

(Not making a fork/pull request from this because it's such a small patch, and it isn't the "correct" solution to the problem either, which would be avoiding the org.bukkit.block enum altogether instead of catching the exception. But maybe this helps someone who's able to compile the plugin themselves).

**Comment by mikeprimm** [comment]
This is ultimately a bug in CraftBukkit/Spigot (or, an incompatibility between TC and them) - the call that is failing is a standard CB API call - nothing funky on our part: it's not bypassing API or anything - just standard ChunkSnapshot stuff.  In any case, catching the exception is an option to work-around the bug (so long as you don't want biome information in the render, like grass color shading and the like), but the true fix is either in CB or in TC (probably the later, since it is the one hacking CB with custom biomes).

**Comment by Rasor1911** [comment]
Seems to be talked about here: https://github.com/MCTCP/TerrainControl/issues/395
Yeap, seems to be an issue on TC's side.

**Comment by Rasor1911** [comment]
Works with latest build of https://github.com/MCTCP/TerrainControl

**Comment by mikeprimm** [comment]
Give latest dynmap dev build a try - worked on a work-around last night, and I think it should be working now.
