### ISSUE TITLE
Json files being writen too wrong location

### ISSUE THREAD

**Issue by Twillen** [webbukkit/dynmap#1909]
I have updated to version 2.3-alpha 1. Upon updating, I started to  revive the following error for multiple files. I have stopped the errors, by manually creating a standalone folder in the tiles folder, but the web pages are not looking for files in `/tiles/standalone/`, but in `/standalone/`.

> [10:01:33] [Dynmap Render Thread/ERROR]: [dynmap] Exception while writing JSON-file - D:\DynMap\Web_1.9\tiles\standalone\dynmap_world.json.new
java.io.FileNotFoundException: D:\DynMap\Web_1.9\tiles\standalone\dynmap_world.json.new (The system cannot find the path specified)
	at java.io.RandomAccessFile.open0(Native Method) ~[?:1.8.0_73]
	at java.io.RandomAccessFile.open(Unknown Source) ~[?:1.8.0_73]
	at java.io.RandomAccessFile.<init>(Unknown Source) ~[?:1.8.0_73]
	at org.dynmap.storage.MapStorage.setStandaloneFile(MapStorage.java:263) [dynmap-2.3-alpha-1.jar:?]
	at org.dynmap.JsonFileClientUpdateComponent$FileProcessor.run(JsonFileClientUpdateComponent.java:88) [dynmap-2.3-alpha-1.jar:?]
	at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1.run(MapManager.java:190) [dynmap-2.3-alpha-1.jar:?]
	at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$2.run(MapManager.java:206) [dynmap-2.3-alpha-1.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_73]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_73]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [?:1.8.0_73]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:1.8.0_73]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_73]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_73]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_73]
[10:01:33] [Dynmap Render Thread/ERROR]: [dynmap] Exception while writing JSON-file - dynmap_world.json

**Comment by Twillen** [comment]
Sorry for the premature ticket. I see how I messed up the configuration. I had both the tilespath and the webpath set to the same directory.

**Comment by pquerner** [comment]
Then please close this issue. ;) @Twillen
