### ISSUE TITLE
Dynmap vs PEX

### ISSUE THREAD

**Issue by pkarolyi** [webbukkit/dynmap#1969]
I tried to install dynmap today, but I got an error while enabling it. (This was the 2.3 version) I tried the 2.4 beta version and I get the same eror:

[11:33:34] [Server thread/ERROR]: Error occurred while enabling dynmap v2.4-SNAPSHOT-1143 (Is it up to date?)
java.lang.NoClassDefFoundError: ru/tehkode/permissions/bukkit/PermissionsEx
        at org.dynmap.bukkit.permissions.PEXPermissions.<init>(PEXPermissions.java:36) ~[?:?]
        at org.dynmap.bukkit.permissions.PEXPermissions.create(PEXPermissions.java:31) ~[?:?]
        at org.dynmap.bukkit.DynmapPlugin.onEnable(DynmapPlugin.java:794) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[spigot.jar:git-Spigot-3ccadba-7f1a322]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-3ccadba-7f1a322]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-3ccadba-7f1a322]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugin(CraftServer.java:362) [spigot.jar:git-Spigot-3ccadba-7f1a322]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:322) [spigot.jar:git-Spigot-3ccadba-7f1a322]
        at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:416) [spigot.jar:git-Spigot-3ccadba-7f1a322]
        at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:381) [spigot.jar:git-Spigot-3ccadba-7f1a322]
        at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:336) [spigot.jar:git-Spigot-3ccadba-7f1a322]
        at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:270) [spigot.jar:git-Spigot-3ccadba-7f1a322]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:539) [spigot.jar:git-Spigot-3ccadba-7f1a322]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.ClassNotFoundException: ru.tehkode.permissions.bukkit.PermissionsEx
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_91]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-3ccadba-7f1a322]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-3ccadba-7f1a322]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_91]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_91]
        ... 14 more

What could I do?

**Comment by LupiAcubens** [comment]
I'm also appearing to have a similar problem. would appreciate some assistance on this if possible.

`[11:24:23] [Server thread/INFO]: [dynmap] Enabling dynmap v2.3-1142
[11:24:24] [Server thread/INFO]: [dynmap] Added 1 custom biome mappings
[11:24:24] [Server thread/INFO]: [dynmap] Using PermissionsEx 2.0-SNAPSHOT for access control
[11:24:24] [Server thread/ERROR]: Error occurred while enabling dynmap v2.3-1142 (Is it up to date?)
java.lang.NoClassDefFoundError: ru/tehkode/permissions/bukkit/PermissionsEx
	at org.dynmap.bukkit.permissions.PEXPermissions.<init>(PEXPermissions.java:36) ~[?:?]
	at org.dynmap.bukkit.permissions.PEXPermissions.create(PEXPermissions.java:31) ~[?:?]
	at org.dynmap.bukkit.DynmapPlugin.onEnable(DynmapPlugin.java:794) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[spigot-1.10.2.jar:git-Spigot-a9631d2-67b2424]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.10.2.jar:git-Spigot-a9631d2-67b2424]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.10.2.jar:git-Spigot-a9631d2-67b2424]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugin(CraftServer.java:362) [spigot-1.10.2.jar:git-Spigot-a9631d2-67b2424]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:322) [spigot-1.10.2.jar:git-Spigot-a9631d2-67b2424]
	at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:417) [spigot-1.10.2.jar:git-Spigot-a9631d2-67b2424]
	at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot-1.10.2.jar:git-Spigot-a9631d2-67b2424]
	at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot-1.10.2.jar:git-Spigot-a9631d2-67b2424]
	at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:270) [spigot-1.10.2.jar:git-Spigot-a9631d2-67b2424]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:540) [spigot-1.10.2.jar:git-Spigot-a9631d2-67b2424]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
Caused by: java.lang.ClassNotFoundException: ru.tehkode.permissions.bukkit.PermissionsEx
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_91]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.10.2.jar:git-Spigot-a9631d2-67b2424]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.10.2.jar:git-Spigot-a9631d2-67b2424]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_91]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_91]
	... 14 more
`

This appears to be specifically when handling PEX v2.0 I didn't attempt version 2.4 (given the report here i assume this is the same)

happy to try any beta builds and return a verdict to assist in the bug fixing process, I'm running a casual small server so shouldn't impact on our operations too much.

**Comment by nodar86** [comment]
I searched around the internet and everybody seemed to have problems with PEX so I switched that out. Now dnymap is working perfectly.

**Comment by LupiAcubens** [comment]
Out of interest which permissions plugin did you switch to?

**Comment by nodar86** [comment]
Powerful Perms, which is a payed plugin, but it was worth it :)

**Comment by LupiAcubens** [comment]
okay, thanks. I think i'll give bpermissions a try. seems to have more or less the same functionality for free.

**Comment by EvilOlaf** [comment]
Why don't you use Pex 1.23?
