### ISSUE TITLE
Dynmap doesnt start on 1.11

### ISSUE THREAD

**Issue by KingHorse2015** [webbukkit/dynmap#2021]
Spigot version: Latest
Plugins: Dynmap
Ubuntu server 16.04

**Comment by wioxjk** [comment]
Could you please provide us with the logs?

**Comment by KingHorse2015** [comment]
Spigot:
`[16:49:01] [Server thread/ERROR]: Could not start metrics service
java.io.IOException: Unable to create parent directories of plugins/PluginMetrics/config.yml
	at com.google.common.io.Files.createParentDirs(Files.java:645) ~[spigot-1.11.jar:git-Spigot-0f17cfb-b5b0a97]
	at org.bukkit.configuration.file.FileConfiguration.save(FileConfiguration.java:66) ~[spigot-1.11.jar:git-Spigot-0f17cfb-b5b0a97]
	at org.spigotmc.Metrics.<init>(Metrics.java:137) ~[spigot-1.11.jar:git-Spigot-0f17cfb-b5b0a97]
	at org.spigotmc.SpigotConfig.registerCommands(SpigotConfig.java:88) [spigot-1.11.jar:git-Spigot-0f17cfb-b5b0a97]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:184) [spigot-1.11.jar:git-Spigot-0f17cfb-b5b0a97]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:542) [spigot-1.11.jar:git-Spigot-0f17cfb-b5b0a97]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]`

Dynmap:
`[16:49:01] [Server thread/INFO]: [dynmap] Loading dynmap v2.4-SNAPSHOT-1146
[16:49:01] [Server thread/INFO]: [dynmap] version=git-Spigot-0f17cfb-b5b0a97 (MC: 1.11)
[16:49:01] [Server thread/INFO]: [dynmap] Mod Support API available`
`[16:49:05] [Server thread/INFO]: [dynmap] Enabling dynmap v2.4-SNAPSHOT-1146
[16:49:05] [Server thread/INFO]: [dynmap] Using Bukkit Permissions (superperms) for access control
[16:49:05] [Server thread/INFO]: [dynmap] Web interface permissions only available for online users
[16:49:05] [Server thread/ERROR]: [dynmap] ERROR creatomg default for plugins/dynmap/configuration.txt
[16:49:05] [Server thread/INFO]: [dynmap] Unloaded 0 components.
[16:49:05] [Server thread/INFO]: [dynmap] Disabled`

**Comment by EvilOlaf** [comment]
Check your file system permissions and make sure that your plugins directory is writable for the spigot user.

**Comment by KingHorse2015** [comment]
Thanks Sudo in front of the command works.

**Comment by wioxjk** [comment]
@KingHorse2015 
Please check that the owners of all the files is the same.

**Comment by EvilOlaf** [comment]
Please tell me you are not going to run your CB as superuser...

**Comment by KingHorse2015** [comment]
It is currently running as a super user.
While change the permissions later this day.

**Comment by rautamiekka** [comment]
You don't see ppl shooting themselves in the foot too often ...

**Comment by KingHorse2015** [comment]
Have moved the folder, to a normal place, now it is fixed. Server now running in normal mode!

**Comment by Kainzo** [comment]
My files are being written to a backup network drive. I dont want all of these files on the live server, is this not doable in another way?

**Comment by jwshields** [comment]
1. This issue is nearly two years old and closed
2. Why not create your own issue?
3. Your ask is somewhat unrelated (even though tangentially it is) to the original question
