### ISSUE TITLE
Path can't be found

### ISSUE THREAD

**Issue by StealWonders** [webbukkit/dynmap#2057]
Getting the following error when trying to use dynmap with an external webserver (nginx):

`> [17:30:29 INFO]: [dynmap] Using PermissionsEx 1.23.4 for access control
> [17:30:30 WARN]: [dynmap] Could not create directory for tiles ('/var/www/subdomain.example.come/html/public/web/tiles').
> [17:30:30 INFO]: [dynmap] Opening MySQL database XXX.XXX.XXX.XXX:3306/s15_livemap as map st
ore
> [17:30:31 ERROR]: [dynmap] Error writing MySQL_config.php
java.io.FileNotFoundException: /var/www/subdomain.example.com/html/public/web/standalone/My
SQL_config.php (No such file or directory)
    at java.io.FileOutputStream.open0(Native Method) ~[?:1.8.0_112]
    at java.io.FileOutputStream.open(FileOutputStream.java:270) ~[?:1.8.0_112]
    at java.io.FileOutputStream.<init>(FileOutputStream.java:213) ~[?:1.8.0_112]
    at java.io.FileOutputStream.<init>(FileOutputStream.java:162) ~[?:1.8.0_112]
    at java.io.FileWriter.<init>(FileWriter.java:90) ~[?:1.8.0_112]
    at org.dynmap.storage.mysql.MySQLMapStorage.writeConfigPHP(MySQLMapStorage.java:307) [
dynmap-2.4.jar:?]
    at org.dynmap.storage.mysql.MySQLMapStorage.init(MySQLMapStorage.java:301) [dynmap-2.4
.jar:?]
    at org.dynmap.DynmapCore.initConfiguration(DynmapCore.java:416) [dynmap-2.4.jar:?]
    at org.dynmap.bukkit.DynmapPlugin.onEnable(DynmapPlugin.java:826) [dynmap-2.4.jar:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) [spigot-1.11.2.ja
r:git-Spigot-b4417b8-a1d3777]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [sp
igot-1.11.2.jar:git-Spigot-b4417b8-a1d3777]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [s
pigot-1.11.2.jar:git-Spigot-b4417b8-a1d3777]
    at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:376) [spi
got-1.11.2.jar:git-Spigot-b4417b8-a1d3777]
    at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:326) [sp
igot-1.11.2.jar:git-Spigot-b4417b8-a1d3777]
    at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot-1
.11.2.jar:git-Spigot-b4417b8-a1d3777]
    at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot-1
.11.2.jar:git-Spigot-b4417b8-a1d3777]
    at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot-1
.11.2.jar:git-Spigot-b4417b8-a1d3777]
    at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:272) [spigo
t-1.11.2.jar:git-Spigot-b4417b8-a1d3777]
    at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot
-1.11.2.jar:git-Spigot-b4417b8-a1d3777]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
> [17:30:31 ERROR]: [dynmap] Map storage initialization failure`

**Comment by Louis-D** [comment]
https://gyazo.com/cd41f881c5feb507ebb44443e1891e7e
https://gyazo.com/86b7b214747f61b9f5517beb9ad2d101

**Comment by wioxjk** [comment]
Check permissions.

**Comment by jwshields** [comment]
You have two options here.
1. Make sure the user your MC server is running as has permissions to read/write/traverse to the folder in which your standalone files are stored in (normally owned by your www-data user or root)
2. Create a soft-symlink from your html dir to the original location like below (this way your httpd will be the one to traverse the fs to your maps location)
```
# ls -lah /var/www/html/map
lrwxrwxrwx 1 root root 45 Dec  7 07:23 /var/www/html/map -> /home/minecraft/minecraft/plugins/dynmap/web/
```

**Comment by Louis-D** [comment]
I fixed it - I'm using Docker, so the container can't access the files outside of this containers (/var/www) so I directed my vhost into the container (plugins/dynmap/web) which works perfectly fine.

**Comment by StealWonders** [comment]
Please close fixed a long time ago.

**Comment by jwshields** [comment]
You can close issues that you create.

**Comment by StealWonders** [comment]
Ah sorry... never saw that button @jwshields
