### ISSUE TITLE
1.12

### ISSUE THREAD

**Issue by ardentcrest** [webbukkit/dynmap#2094]
Can we have a 1.12 update please

**Comment by smmmadden** [comment]
Spigot 1.12 PreRelease exception with Dynmap 2.4-1148 build
[08:56:24] [Server thread/INFO]: [dynmap] Loading dynmap v2.4-1148
[08:56:24] [Server thread/INFO]: [dynmap] version=git-Spigot-1ffab67-45102fc (MC: 1.12-pre2)
[08:56:24] [Server thread/ERROR]: [dynmap] Unable to find field humidity for net.minecraft.server.v1_12_R1.BiomeBase
[08:56:24] [Server thread/ERROR]: Error initializing dynmap - bukkit version incompatible! initializing dynmap v2.4-1148 (Is it up to date?)
java.lang.IllegalArgumentException: Error initializing dynmap - bukkit version incompatible!
	at org.dynmap.bukkit.BukkitVersionHelperGeneric.<init>(BukkitVersionHelperGeneric.java:129) ~[?:?]
	at org.dynmap.bukkit.BukkitVersionHelperCB.<init>(BukkitVersionHelperCB.java:39) ~[?:?]
	at org.dynmap.bukkit.BukkitVersionHelper.getHelper(BukkitVersionHelper.java:42) ~[?:?]
	at org.dynmap.bukkit.DynmapPlugin.onLoad(DynmapPlugin.java:756) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:306) [spigot-1.12-pre2.jar:git-Spigot-1ffab67-45102fc]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:205) [spigot-1.12-pre2.jar:git-Spigot-1ffab67-45102fc]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot-1.12-pre2.jar:git-Spigot-1ffab67-45102fc]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]

**Comment by ardentcrest** [comment]
PLEASE, please, please make a jar file for us who cant.......

**Comment by smmmadden** [comment]
he's already made it available to download through his site until it is ready for GA. Look at Issue 2097.

**Comment by mikeprimm** [comment]
It's available - closing this issue
