### ISSUE TITLE
Exception while fetching chunks:  java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by mibby** [webbukkit/dynmap#2101]
Paper dev 1104 (Spigot 1.11.2)
dynmap v2.5-SNAPSHOT-1151

```
[13:45:55] [Dynmap Render Thread/ERROR]: [dynmap] Exception while fetching chunks: 
java.lang.ArrayIndexOutOfBoundsException: -945
	at org.bukkit.craftbukkit.v1_11_R1.CraftChunkSnapshot.getBlockTypeId(CraftChunkSnapshot.java:56) ~[patched_1.11.2.jar:git-Paper-1104]
	at org.dynmap.bukkit.NewMapChunkCache.loadChunks(NewMapChunkCache.java:836) ~[?:?]
	at org.dynmap.bukkit.DynmapPlugin$BukkitServer$6.call(DynmapPlugin.java:458) ~[?:?]
	at org.dynmap.bukkit.DynmapPlugin$BukkitServer$6.call(DynmapPlugin.java:445) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftFuture.run(CraftFuture.java:89) ~[patched_1.11.2.jar:git-Paper-1104]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356) ~[patched_1.11.2.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:829) ~[patched_1.11.2.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) ~[patched_1.11.2.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:763) ~[patched_1.11.2.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:661) ~[patched_1.11.2.jar:git-Paper-1104]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
[13:45:57] [Dynmap Render Thread/ERROR]: [dynmap] Exception while fetching chunks: 
java.lang.ArrayIndexOutOfBoundsException: -945
	at org.bukkit.craftbukkit.v1_11_R1.CraftChunkSnapshot.getBlockTypeId(CraftChunkSnapshot.java:56) ~[patched_1.11.2.jar:git-Paper-1104]
	at org.dynmap.bukkit.NewMapChunkCache.loadChunks(NewMapChunkCache.java:836) ~[?:?]
	at org.dynmap.bukkit.DynmapPlugin$BukkitServer$6.call(DynmapPlugin.java:458) ~[?:?]
	at org.dynmap.bukkit.DynmapPlugin$BukkitServer$6.call(DynmapPlugin.java:445) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftFuture.run(CraftFuture.java:89) ~[patched_1.11.2.jar:git-Paper-1104]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356) ~[patched_1.11.2.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:829) ~[patched_1.11.2.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) ~[patched_1.11.2.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:763) ~[patched_1.11.2.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:661) ~[patched_1.11.2.jar:git-Paper-1104]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```

**Comment by mibby** [comment]
```
[12:49:17] [Dynmap Render Thread/ERROR]: [dynmap] Exception while fetching chunks: 
java.lang.ArrayIndexOutOfBoundsException: -1569
	at org.bukkit.craftbukkit.v1_11_R1.CraftChunkSnapshot.getBlockTypeId(CraftChunkSnapshot.java:56) ~[patched_1.11.2.jar:git-Paper-1104]
	at org.dynmap.bukkit.NewMapChunkCache.loadChunks(NewMapChunkCache.java:836) ~[?:?]
	at org.dynmap.bukkit.DynmapPlugin$BukkitServer$6.call(DynmapPlugin.java:458) ~[?:?]
	at org.dynmap.bukkit.DynmapPlugin$BukkitServer$6.call(DynmapPlugin.java:445) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftFuture.run(CraftFuture.java:89) ~[patched_1.11.2.jar:git-Paper-1104]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356) ~[patched_1.11.2.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:829) ~[patched_1.11.2.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) ~[patched_1.11.2.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:763) ~[patched_1.11.2.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:661) ~[patched_1.11.2.jar:git-Paper-1104]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```

**Comment by mikeprimm** [comment]
This is a bug in the CraftChunkSnapshot code in Spigot 1.11.2 - very little I can do to fix it.
