### ISSUE TITLE
Unhandled exception while parsing console command 'dynmap'

### ISSUE THREAD

**Issue by Koohiisan** [webbukkit/dynmap#2118]
Since upgrading from 1.11 to 1.12, I am no longer able to get dynmap running on my server.  I've tried various snapshots (currently 2.6-snapshot linked to from somewhere here in a different issue).  The webserver is down when I try to reach it from that server's loopback or from externally.  When I try to use 'dynmap' on the command line I get this output:

[15:57:03] [Server thread/WARN]: Unexpected exception while parsing console command "dynmap"
org.bukkit.command.CommandException: Unhandled exception executing command 'dynmap' in plugin dynmap v2.6-SNAPSHOT-Dev201706182128
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:644) ~[spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:630) [spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37]
	at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:443) [spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.NullPointerException
	at org.dynmap.bukkit.DynmapPlugin.onCommand(DynmapPlugin.java:937) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.12.jar:git-Spigot-4df3c0c-03f1e37]
	... 8 more

Anyone else having the same issue?  Ideas?

**Comment by Koohiisan** [comment]
Here's the list of plugins on my server:

[16:01:20 INFO]: Plugins (21): dynmap, WorldEdit, AlchemicalArrows, TitleWelcomeMessage, MythicLib, PermissionsEx, SmartGiants, Vault, EasyBackup, Multiverse-Core, ProtocolLib, VoidSpawn, WorldGuard, LibsDisguises, PhatLoots, AutoAnnouncer, PerWorldInventory, Multiverse-Portals, MythicMobs, Multiverse-NetherPortals, MythicArtifacts

**Comment by Koohiisan** [comment]
This turned out to be resolved by updating to the latest Multiverse files (core, nether portals, portals), as well as the latest dynmap snapshot.
