### ISSUE TITLE
Constant exceptions generated by Dynmap, but DiscordSRV errors turn up?

### ISSUE THREAD

**Issue by PsychoNavigator** [webbukkit/dynmap#2123]
Not terribly certain if the issue lies with Dynmap or DiscordSRV, figured that I'd start here.

````
07/10/2017 10:01:29
10:01:29[dynmap] Task #4552 for dynmap v2.6-SNAPSHOT-Dev201707061526 generated an exception
Console 07/10/2017 10:01:29
10:01:29java.lang.NoClassDefFoundError: github/scarsz/discordsrv/dependencies/json/simple/JSONObject
at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_131]
at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[?:1.8.0_131]
at java.lang.Class.privateGetMethodRecursive(Class.java:3048) ~[?:1.8.0_131]
at java.lang.Class.getMethod0(Class.java:3018) ~[?:1.8.0_131]
at java.lang.Class.getMethod(Class.java:1784) ~[?:1.8.0_131]
at org.dynmap.Metrics.submitData(Metrics.java:242) ~[?:?]
at org.dynmap.Metrics.access$100(Metrics.java:33) ~[?:?]
at org.dynmap.Metrics$1$1.run(Metrics.java:152) ~[?:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.jar:git-Spigot-7228328-50b75cd]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.12.jar:git-Spigot-7228328-50b75cd]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot-1.12.jar:git-Spigot-7228328-50b75cd]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot-1.12.jar:git-Spigot-7228328-50b75cd]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.12.jar:git-Spigot-7228328-50b75cd]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.12.jar:git-Spigot-7228328-50b75cd]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.ClassNotFoundException: github.scarsz.discordsrv.dependencies.json.simple.JSONObject
at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_131]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.12.jar:git-Spigot-7228328-50b75cd]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.12.jar:git-Spigot-7228328-50b75cd]
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_131]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_131]
... 15 more`
```

**Comment by PsychoNavigator** [comment]
Bump.

**Comment by aycgit** [comment]
i guess dynmap has a old discordsrv dependency?
