### ISSUE TITLE
NullPointerException while attempting to render the Nether

### ISSUE THREAD

**Issue by miiichael** [webbukkit/dynmap#2132]
I successfully added dynmap 2.4-3 to my existing server (Minecraft 1.11.2, forge 13.20.1.2429, and a bunch of other mods). All settings are default.

Seems to work enough for `/dynmap fullrender` of the overworld to work, but rendering of the nether doesn't work:

```> /dynmap fullrender DIM-1
[20:37:43] [Server thread/INFO]: Full render starting on world 'DIM-1'...
[20:37:43] [Dynmap Render Thread/FATAL] [Dynmap]: [Dynmap] Exception while loading chunks
java.lang.NullPointerException
        at com.google.common.collect.ImmutableSetMultimap$Builder.putAll(ImmutableSetMultimap.java:228) ~[minecraft_server.1.11.2.jar:?]
        at net.minecraftforge.common.ForgeChunkManager.forceChunk(ForgeChunkManager.java:815) ~[ForgeChunkManager.class:?]
        at org.dynmap.forge.DynmapPlugin.setBusy(DynmapPlugin.java:262) ~[DynmapPlugin.class:?]
        at org.dynmap.forge.DynmapPlugin.setBusy(DynmapPlugin.java:246) ~[DynmapPlugin.class:?]
        at org.dynmap.forge.DynmapPlugin.access$1500(DynmapPlugin.java:98) ~[DynmapPlugin.class:?]
        at org.dynmap.forge.DynmapPlugin$ForgeServer$1.call(DynmapPlugin.java:757) ~[DynmapPlugin$ForgeServer$1.class:?]
        at org.dynmap.forge.DynmapPlugin$ForgeServer$1.call(DynmapPlugin.java:753) ~[DynmapPlugin$ForgeServer$1.class:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_131]
        at org.dynmap.forge.DynmapPlugin$ForgeServer.tickEvent(DynmapPlugin.java:845) ~[DynmapPlugin$ForgeServer.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_574_ForgeServer_tickEvent_ServerTickEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) ~[EventBus.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:265) ~[FMLCommonHandler.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) ~[MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```
I'm unsure whether automatic re-rendering of existing tiles is actually occurring.

**Comment by aycgit** [comment]
do you have a mod that changes the nether?

**Comment by miiichael** [comment]
Hmm. I suspect the answer is "Not in a way that affects terrain generation". I am using Quark's Realistic world type for worldgen, but I'm unsure if that has an effect on nether terrain gen.

(FWIW I haven't seen this error reoccur, and automatic map rendering does seem to mostly work, though there are lots of missing tiles in the [map](http://minecraft2017.ucc.asn.au/map/two/) (until I manually force a re-render).)

**Comment by aycgit** [comment]
i see you are having world/nether, is that something you specified or could it be a mod doing that

**Comment by miiichael** [comment]
world/nether instead of...?

All dynmap configuration is completely as default.

**Comment by katzenpapst** [comment]
Happens for me, too:

https://pastebin.com/ZUexPdq0

DIM1 is the End, DIM7 should be twilight forest, DIM20 Betweenlands, and DIM-343800852 is that "spectral dimension" from random things. Which has no real terrain, since it just gives you one chunk with indestructible walls, which can be acessed with a special item.

I also have a lot of renderdata TXTs, which were generated by http://www.dynmap.us/builds/DynmapBlockScan/
Blocks from those dimensions work fine when placed in the OW, though.

**Comment by Psy-Virus** [comment]
Have you tried the latest versions of Dynmap and The Block scanner? There were some important fixed in the last days.
https://dynmap.us/builds/DynmapBlockScan/
https://dynmap.us/builds/dynmap/

**Comment by katzenpapst** [comment]
Updated to beta-3. Now it doesn't crash, but puts fullrender on pause for unloaded worlds. We'll see what happens when someone actually enters the dimension in question
