### ISSUE TITLE
DynmapModScraper doesn't work

### ISSUE THREAD

**Issue by xXFreeFunXx** [webbukkit/dynmap#2143]
Hello,

the DynmapModScraper doesn't work.

I used the current FTB Infinity Evolved v3.0.2 + DynmapForge v2.4 & DynmapModScraper 2.0.0-alpha-1-3 for MC 1.7.10 Version.

```
[16:21:09] [Server thread/TRACE] [Dynmap/Dynmap]: Sending event FMLConstructionEvent to mod Dynmap
[16:21:09] [Server thread/INFO] [Dynmap/Dynmap]: [Dynmap] Mod Support API available
[16:21:09] [Server thread/TRACE] [FML/Dynmap]: Mod Dynmap is using network checker : Invoking method netCheckHandler
[16:21:09] [Server thread/TRACE] [FML/Dynmap]: Testing mod Dynmap to verify it accepts its own version in a remote connection
[16:21:09] [Server thread/TRACE] [FML/Dynmap]: The mod Dynmap accepts its own version (2.4-169)
[16:21:09] [Server thread/DEBUG] [FML/Dynmap]: Attempting to inject @SidedProxy classes into Dynmap
[16:21:09] [Server thread/TRACE] [Dynmap/Dynmap]: Sent event FMLConstructionEvent to mod Dynmap
[16:21:09] [Server thread/DEBUG] [FML/]: Bar Step: Construction - Dynmap took 0.039s
[16:21:09] [Server thread/TRACE] [DynmapModScraper/DynmapModScraper]: Sending event FMLConstructionEvent to mod DynmapModScraper
[16:21:09] [Server thread/TRACE] [FML/DynmapModScraper]: Mod DynmapModScraper is using network checker : Accepting version 2.0.0-alpha-1-3
[16:21:09] [Server thread/TRACE] [FML/DynmapModScraper]: Testing mod DynmapModScraper to verify it accepts its own version in a remote connection
[16:21:09] [Server thread/TRACE] [FML/DynmapModScraper]: The mod DynmapModScraper accepts its own version (2.0.0-alpha-1-3)
[16:21:09] [Server thread/DEBUG] [FML/DynmapModScraper]: Attempting to inject @SidedProxy classes into DynmapModScraper
[16:21:09] [Server thread/ERROR] [FML/DynmapModScraper]: An error occured trying to load a proxy into {clientSide=org.dynmap.modscraper.ClientProxy}.org.dynmap.modscraper.DynmapModScraper
java.lang.ClassNotFoundException: 
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_131]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_131]
	at cpw.mods.fml.common.ProxyInjector.inject(ProxyInjector.java:59) [ProxyInjector.class:?]
	at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:512) [FMLModContainer.class:?]
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [guava-17.0.jar:?]
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) [LoadController.class:?]
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) [LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [guava-17.0.jar:?]
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) [LoadController.class:?]
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:513) [Loader.class:?]
	at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87) [FMLServerHandler.class:?]
	at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:314) [FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[16:21:10] [Server thread/TRACE] [DynmapModScraper/DynmapModScraper]: Sent event FMLConstructionEvent to mod DynmapModScraper
```

**Comment by xXFreeFunXx** [comment]
Sry my fail :/

DynmapModScraper is a Client Mod!
