### ISSUE TITLE
Minecraft downloads on first start up but is stuck on "Launching"

### ISSUE THREAD

**Issue by KnightRider878** [webbukkit/dynmap#2149]
I have a message in the launcher log appearing like this. I have no idea why or what causes this problem 
to occur. Any help will be appreciated.

[22:50:57 INFO]: Launching game
[22:50:57 INFO]: Unpacking natives to C:\Users\Administrator-25\AppData\Roaming\.minecraft\versions\1.12.2\1.12.2-natives-4482112116100
[22:50:57 FATAL]: Fatal error launching game. Report this to http://bugs.mojang.com please!
java.lang.NoSuchMethodError: net.minecraft.launcher.updater.CompleteMinecraftVersion.getRelevantLibraries()Ljava/util/Collection;
	at net.minecraft.launcher.game.MinecraftGameRunner.unpackNatives(MinecraftGameRunner.java:344) ~[launcher_mcpatched.jar:1.6.84-j]
	at net.minecraft.launcher.game.MinecraftGameRunner.launchGame(MinecraftGameRunner.java:120) ~[launcher_mcpatched.jar:1.6.84-j]
	at com.mojang.launcher.game.runner.AbstractGameRunner.onDownloadJobFinished(AbstractGameRunner.java:186) [launcher_mcpatched.jar:1.6.84-j]
	at com.mojang.launcher.updater.download.DownloadJob.popAndDownload(DownloadJob.java:122) [launcher_mcpatched.jar:1.6.84-j]
	at com.mojang.launcher.updater.download.DownloadJob.access$000(DownloadJob.java:12) [launcher_mcpatched.jar:1.6.84-j]
	at com.mojang.launcher.updater.download.DownloadJob$1.run(DownloadJob.java:86) [launcher_mcpatched.jar:1.6.84-j]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_151]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_151]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]

**Comment by jwshields** [comment]
This isn't a dynmap issue.
Please close this ticket and report it to the proper area as listed in your error.
