### ISSUE TITLE
Error, im getting spammed in console, dynmap quiet doesnt work on console either

### ISSUE THREAD

**Issue by Fyrlex** [webbukkit/dynmap#2153]
[20:58:52 ERROR]: [dynmap] Error parsing plugins/dynmap/configuration.txt. Use http://yamllint.com to debug the YAML syntax.
[20:58:52 ERROR]: Error occurred while enabling dynmap v2.5-Dev201706100405 (Is it up to date?)
org.dynmap.snakeyaml.parser.ParserException: while parsing a block mapping; expected <block end>, but found Scalar
        at org.dynmap.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:575) ~[?:?]
        at org.dynmap.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:161) ~[?:?]
        at org.dynmap.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:146) ~[?:?]
        at org.dynmap.snakeyaml.composer.Composer.composeMappingNode(Composer.java:230) ~[?:?]
        at org.dynmap.snakeyaml.composer.Composer.composeNode(Composer.java:160) ~[?:?]
        at org.dynmap.snakeyaml.composer.Composer.composeMappingNode(Composer.java:237) ~[?:?]
        at org.dynmap.snakeyaml.composer.Composer.composeNode(Composer.java:160) ~[?:?]
        at org.dynmap.snakeyaml.composer.Composer.composeDocument(Composer.java:123) ~[?:?]
        at org.dynmap.snakeyaml.composer.Composer.getSingleNode(Composer.java:106) ~[?:?]
        at org.dynmap.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:121) ~[?:?]
        at org.dynmap.snakeyaml.Yaml.loadFromReader(Yaml.java:480) ~[?:?]
        at org.dynmap.snakeyaml.Yaml.load(Yaml.java:423) ~[?:?]
        at org.dynmap.ConfigurationNode.load(ConfigurationNode.java:86) ~[?:?]
        at org.dynmap.DynmapCore.initConfiguration(DynmapCore.java:389) ~[?:?]
        at org.dynmap.bukkit.DynmapPlugin.onEnable(DynmapPlugin.java:826) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at org.dynmap.bukkit.DynmapPlugin$BukkitServer.reload(DynmapPlugin.java:228) [dynmap-2.5.jar:?]
        at org.dynmap.DynmapCore.processCommand(DynmapCore.java:1441) [dynmap-2.5.jar:?]
        at org.dynmap.bukkit.DynmapPlugin.onCommand(DynmapPlugin.java:937) [dynmap-2.5.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:627) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:412) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:375) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]

**Comment by jwshields** [comment]
Read the first line.
Your configuration YAML syntax is bad.
Why would you make three issues at the same time?

**Comment by jwshields** [comment]
Please close this issue.
