### ISSUE TITLE
Error in console (getting spammed

### ISSUE THREAD

**Issue by Fyrlex** [webbukkit/dynmap#2154]
`[21:38:58 WARN]: java.io.FileNotFoundException: ./Hub/level.dat_new (Disk quota exceeded)
[21:38:58 WARN]:        at java.io.FileOutputStream.open0(Native Method)
[21:38:58 WARN]:        at java.io.FileOutputStream.open(FileOutputStream.java:270)
[21:38:58 WARN]:        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
[21:38:58 WARN]:        at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
[21:38:58 WARN]:        at net.minecraft.server.v1_8_R3.WorldNBTStorage.saveWorldData(WorldNBTStorage.java:127)
[21:38:58 WARN]:        at net.minecraft.server.v1_8_R3.ServerNBTManager.saveWorldData(SourceFile:43)
[21:38:58 WARN]:        at net.minecraft.server.v1_8_R3.WorldServer.a(WorldServer.java:965)
[21:38:58 WARN]:        at net.minecraft.server.v1_8_R3.WorldServer.save(WorldServer.java:923)
[21:38:58 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.save(CraftWorld.java:753)
[21:38:58 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:679)
[21:38:58 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[21:38:58 WARN]:        at java.lang.Thread.run(Thread.java:745)
[21:38:58 WARN]: java.io.FileNotFoundException: ./Dustbowl/level.dat_new (Disk quota exceeded)
[21:38:58 WARN]:        at java.io.FileOutputStream.open0(Native Method)
[21:38:58 WARN]:        at java.io.FileOutputStream.open(FileOutputStream.java:270)
[21:38:58 WARN]:        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
[21:38:58 WARN]:        at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
[21:38:58 WARN]:        at net.minecraft.server.v1_8_R3.WorldNBTStorage.saveWorldData(WorldNBTStorage.java:127)
[21:38:58 WARN]:        at net.minecraft.server.v1_8_R3.ServerNBTManager.saveWorldData(SourceFile:43)
[21:38:58 WARN]:        at net.minecraft.server.v1_8_R3.WorldServer.a(WorldServer.java:965)
[21:38:58 WARN]:        at net.minecraft.server.v1_8_R3.WorldServer.save(WorldServer.java:923)
[21:38:58 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.save(CraftWorld.java:753)
[21:38:58 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:679)
[21:38:58 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[21:38:58 WARN]:        at java.lang.Thread.run(Thread.java:745)
[21:38:58 WARN]: java.io.FileNotFoundException: ./Temple/level.dat_new (Disk quota exceeded)
[21:38:58 WARN]:        at java.io.FileOutputStream.open0(Native Method)
[21:38:58 WARN]:        at java.io.FileOutputStream.open(FileOutputStream.java:270)
[21:38:58 WARN]:        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
[21:38:58 WARN]:        at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
[21:38:58 WARN]:        at net.minecraft.server.v1_8_R3.WorldNBTStorage.saveWorldData(WorldNBTStorage.java:127)
[21:38:58 WARN]:        at net.minecraft.server.v1_8_R3.ServerNBTManager.saveWorldData(SourceFile:43)
[21:38:58 WARN]:        at net.minecraft.server.v1_8_R3.WorldServer.a(WorldServer.java:965)
[21:38:58 WARN]:        at net.minecraft.server.v1_8_R3.WorldServer.save(WorldServer.java:923)
[21:38:58 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.save(CraftWorld.java:753)
[21:38:58 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:679)
[21:38:58 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[21:38:58 WARN]:        at java.lang.Thread.run(Thread.java:745)
[21:38:58 WARN]: java.io.FileNotFoundException: ./Outpost/level.dat_new (Disk quota exceeded)
[21:38:58 WARN]:        at java.io.FileOutputStream.open0(Native Method)
[21:38:58 WARN]:        at java.io.FileOutputStream.open(FileOutputStream.java:270)
[21:38:58 WARN]:        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
[21:38:58 WARN]:        at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
[21:38:58 WARN]:        at net.minecraft.server.v1_8_R3.WorldNBTStorage.saveWorldData(WorldNBTStorage.java:127)
[21:38:58 WARN]:        at net.minecraft.server.v1_8_R3.ServerNBTManager.saveWorldData(SourceFile:43)
[21:38:58 WARN]:        at net.minecraft.server.v1_8_R3.WorldServer.a(WorldServer.java:965)
[21:38:58 WARN]:        at net.minecraft.server.v1_8_R3.WorldServer.save(WorldServer.java:923)
[21:38:58 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.save(CraftWorld.java:753)
[21:38:58 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:679)
[21:38:58 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[21:38:58 WARN]:        at java.lang.Thread.run(Thread.java:745)
[21:38:58 WARN]: java.io.FileNotFoundException: ./Factions/level.dat_new (Disk quota exceeded)
[21:38:58 WARN]:        at java.io.FileOutputStream.open0(Native Method)
[21:38:58 WARN]:        at java.io.FileOutputStream.open(FileOutputStream.java:270)
[21:38:58 WARN]:        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
[21:38:58 WARN]:        at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
[21:38:58 WARN]:        at net.minecraft.server.v1_8_R3.WorldNBTStorage.saveWorldData(WorldNBTStorage.java:127)
[21:38:58 WARN]:        at net.minecraft.server.v1_8_R3.ServerNBTManager.saveWorldData(SourceFile:43)
[21:38:58 WARN]:        at net.minecraft.server.v1_8_R3.WorldServer.a(WorldServer.java:965)
[21:38:58 WARN]:        at net.minecraft.server.v1_8_R3.WorldServer.save(WorldServer.java:923)
[21:38:58 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.save(CraftWorld.java:753)
[21:38:58 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:679)
[21:38:58 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[21:38:58 WARN]:        at java.lang.Thread.run(Thread.java:745)
[21:38:58 WARN]: java.io.FileNotFoundException: ./Sushi/level.dat_new (Disk quota exceeded)
[21:38:58 WARN]:        at java.io.FileOutputStream.open0(Native Method)
[21:38:58 WARN]:        at java.io.FileOutputStream.open(FileOutputStream.java:270)
[21:38:58 WARN]:        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
[21:38:58 WARN]:        at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
[21:38:58 WARN]:        at net.minecraft.server.v1_8_R3.WorldNBTStorage.saveWorldData(WorldNBTStorage.java:127)
[21:38:58 WARN]:        at net.minecraft.server.v1_8_R3.ServerNBTManager.saveWorldData(SourceFile:43)
[21:38:58 WARN]:        at net.minecraft.server.v1_8_R3.WorldServer.a(WorldServer.java:965)
[21:38:58 WARN]:        at net.minecraft.server.v1_8_R3.WorldServer.save(WorldServer.java:923)
[21:38:58 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.save(CraftWorld.java:753)
[21:38:58 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:679)
[21:38:58 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[21:38:58 WARN]:        at java.lang.Thread.run(Thread.java:745)`

**Comment by jwshields** [comment]
Read the first line.
Your disk is full or you have exceeded quota.
And why would you make three tickets for similar issues within quick succession?

**Comment by jwshields** [comment]
Please close this issue
