### ISSUE TITLE
Dynmap trying to write after map is completed.

### ISSUE THREAD

**Issue by bluekomde** [webbukkit/dynmap#2162]
HI, so dynmap has just finished filling the world border of the map, but in console it keeps showing the "unable to write" error even though it should be done. I type /dynmap cancelrender in chat but it doesn't stop. I have uninstalled and installed dynmap multiple times and each time after it is done with the map it keeps showing the errors. Sometimes I can't even log on because I guess it is messing with CPU or something. I even upgraded from 1GB to 2GB hoping it would fix the problem. Here is dynmap link: http://167.114.208.2:10118

Here are the errors: 
[02:31:44 INFO]: [dynmap] Image file plugins/dynmap/web/tiles/nationsmap/t/63_0/2038_28.png - unable to write - failed (there are just tens of hundreds of these so I'm not going to put all of them.)

[02:31:40 WARN]: java.io.FileNotFoundException: ./nationsmap/level.dat_new (Disk quota exceeded)
[02:31:40 WARN]:        at java.io.FileOutputStream.open0(Native Method)
[02:31:40 WARN]:        at java.io.FileOutputStream.open(FileOutputStream.java:270)
[02:31:40 WARN]:        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
[02:31:40 WARN]:        at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
[02:31:40 WARN]:        at net.minecraft.server.v1_10_R1.WorldNBTStorage.saveWorldData(WorldNBTStorage.java:119)
[02:31:40 WARN]:        at net.minecraft.server.v1_10_R1.ServerNBTManager.saveWorldData(SourceFile:45)
[02:31:40 WARN]:        at net.minecraft.server.v1_10_R1.WorldServer.a(WorldServer.java:1070)
[02:31:40 WARN]:        at net.minecraft.server.v1_10_R1.WorldServer.save(WorldServer.java:1013)
[02:31:40 WARN]:        at org.bukkit.craftbukkit.v1_10_R1.CraftWorld.save(CraftWorld.java:744)
[02:31:40 WARN]:        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:693)
[02:31:40 WARN]:        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567)
[02:31:40 WARN]:        at java.lang.Thread.run(Thread.java:745)
[02:31:40 WARN]: java.io.FileNotFoundException: ./nationsmap_nether/level.dat_new (Disk quota exceeded)
[02:31:40 WARN]:        at java.io.FileOutputStream.open0(Native Method)
[02:31:40 WARN]:        at java.io.FileOutputStream.open(FileOutputStream.java:270)
[02:31:40 WARN]:        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
[02:31:40 WARN]:        at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
[02:31:40 WARN]:        at net.minecraft.server.v1_10_R1.WorldNBTStorage.saveWorldData(WorldNBTStorage.java:119)
[02:31:40 WARN]:        at net.minecraft.server.v1_10_R1.ServerNBTManager.saveWorldData(SourceFile:45)
[02:31:40 WARN]:        at net.minecraft.server.v1_10_R1.WorldServer.a(WorldServer.java:1070)
[02:31:40 WARN]:        at net.minecraft.server.v1_10_R1.WorldServer.save(WorldServer.java:1013)
[02:31:40 WARN]:        at org.bukkit.craftbukkit.v1_10_R1.CraftWorld.save(CraftWorld.java:744)
[02:31:40 WARN]:        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:693)
[02:31:40 WARN]:        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567)
[02:31:40 WARN]:        at java.lang.Thread.run(Thread.java:745)
[02:31:40 WARN]: java.io.FileNotFoundException: ./nationsmap_the_end/level.dat_new (Disk quota exceeded)
[02:31:40 WARN]:        at java.io.FileOutputStream.open0(Native Method)
[02:31:40 WARN]:        at java.io.FileOutputStream.open(FileOutputStream.java:270)
[02:31:40 WARN]:        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
[02:31:40 WARN]:        at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
[02:31:40 WARN]:        at net.minecraft.server.v1_10_R1.WorldNBTStorage.saveWorldData(WorldNBTStorage.java:119)
[02:31:40 WARN]:        at net.minecraft.server.v1_10_R1.ServerNBTManager.saveWorldData(SourceFile:45)
[02:31:40 WARN]:        at net.minecraft.server.v1_10_R1.WorldServer.a(WorldServer.java:1070)
[02:31:40 WARN]:        at net.minecraft.server.v1_10_R1.WorldServer.save(WorldServer.java:1013)
[02:31:40 WARN]:        at org.bukkit.craftbukkit.v1_10_R1.CraftWorld.save(CraftWorld.java:744)
[02:31:40 WARN]:        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:693)
[02:31:40 WARN]:        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567)
[02:31:40 WARN]:        at java.lang.Thread.run(Thread.java:745)
(I also found this warning in console)

**Comment by bluekomde** [comment]
Ah never mind! It fixed by itself.
