### ISSUE TITLE
Garbage Collection issue

### ISSUE THREAD

**Issue by adracamas** [webbukkit/dynmap#2196]
[crash-2018-02-10_08.09.15-server.txt](https://github.com/webbukkit/dynmap/files/1713399/crash-2018-02-10_08.09.15-server.txt)
Hi there. Hot her running on spigot-1.12.2.jar:git-Spigot-4bd94dc-015bda4 just fine.

Issue is I have a massive world and it seems GC doesn't seems to be co-operating.

3.8 ghz, 4 core system (through vmWare) with 32GB ram ( 16~15GB assigned to server VM )
Running MineOS
spigot-1.12.2.jar:git-Spigot-4bd94dc-015bda4

`[08:03:28] [Server thread/INFO]: Saving...
[08:03:28] [Server thread/INFO]: Saved the world
[08:03:35] [Dynmap Render Thread/INFO]: Full render of map 'flat' of 'EarthSurvival' in progress - 142900 tiles rendered (61.82 msec/tile, 74.32 msec per render)[m
[08:03:50] [Dynmap Render Thread/INFO]: Full render of map 'flat' of 'EarthSurvival' in progress - 143000 tiles rendered (61.88 msec/tile, 74.43 msec per render)[m
[08:04:39] [Dynmap Render Thread/INFO]: Full render of map 'flat' of 'EarthSurvival' in progress - 143100 tiles rendered (62.01 msec/tile, 74.59 msec per render)[m
[08:05:39] [Dynmap Render Thread/INFO]: Full render of map 'flat' of 'EarthSurvival' in progress - 143200 tiles rendered (62.15 msec/tile, 74.80 msec per render)[m
[08:05:48] [Dynmap Render Thread/INFO]: Full render of map 'flat' of 'EarthSurvival' in progress - 143300 tiles rendered (62.16 msec/tile, 74.87 msec per render)[m
[08:06:13] [Dynmap Render Thread/INFO]: Full render of map 'flat' of 'EarthSurvival' in progress - 143400 tiles rendered (62.24 msec/tile, 75.02 msec per render)[m
[08:06:58] [Dynmap Render Thread/INFO]: Full render of map 'flat' of 'EarthSurvival' in progress - 143500 tiles rendered (62.41 msec/tile, 75.28 msec per render)[m
[08:07:07] [Dynmap Render Thread/INFO]: Full render of map 'flat' of 'EarthSurvival' in progress - 143600 tiles rendered (62.42 msec/tile, 75.36 msec per render)[m
[08:07:39] [Dynmap Render Thread/INFO]: Full render of map 'flat' of 'EarthSurvival' in progress - 143700 tiles rendered (62.51 msec/tile, 75.53 msec per render)[m
[08:08:06] [Dynmap Render Thread/INFO]: Full render of map 'flat' of 'EarthSurvival' in progress - 143800 tiles rendered (62.59 msec/tile, 75.65 msec per render)[m
[08:08:20] [Dynmap Render Thread/INFO]: Full render of map 'flat' of 'EarthSurvival' in progress - 143900 tiles rendered (62.65 msec/tile, 75.68 msec per render)[m
[08:09:15] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_12_R1.ReportedException: Exception ticking world
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:812) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-015bda4]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-015bda4]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-015bda4]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-4bd94dc-015bda4]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at net.minecraft.server.v1_12_R1.WorldNBTStorage.checkSession(WorldNBTStorage.java:74) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-015bda4]
	at net.minecraft.server.v1_12_R1.World.checkSession(World.java:2812) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-015bda4]
	at net.minecraft.server.v1_12_R1.ChunkRegionLoader.saveChunk(ChunkRegionLoader.java:127) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-015bda4]
	at net.minecraft.server.v1_12_R1.ChunkProviderServer.saveChunk(ChunkProviderServer.java:209) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-015bda4]
	at net.minecraft.server.v1_12_R1.ChunkProviderServer.unloadChunk(ChunkProviderServer.java:316) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-015bda4]
	at net.minecraft.server.v1_12_R1.ChunkProviderServer.unloadChunks(ChunkProviderServer.java:268) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-015bda4]
	at net.minecraft.server.v1_12_R1.WorldServer.doTick(WorldServer.java:294) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-015bda4]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:801) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-015bda4]
	... 4 more
[08:09:15] [Server thread/ERROR]: 	Cause of unexpected exception was
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at net.minecraft.server.v1_12_R1.WorldNBTStorage.checkSession(WorldNBTStorage.java:74) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-015bda4]
	at net.minecraft.server.v1_12_R1.World.checkSession(World.java:2812) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-015bda4]
	at net.minecraft.server.v1_12_R1.ChunkRegionLoader.saveChunk(ChunkRegionLoader.java:127) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-015bda4]
	at net.minecraft.server.v1_12_R1.ChunkProviderServer.saveChunk(ChunkProviderServer.java:209) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-015bda4]
	at net.minecraft.server.v1_12_R1.ChunkProviderServer.unloadChunk(ChunkProviderServer.java:316) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-015bda4]
	at net.minecraft.server.v1_12_R1.ChunkProviderServer.unloadChunks(ChunkProviderServer.java:268) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-015bda4]
	at net.minecraft.server.v1_12_R1.WorldServer.doTick(WorldServer.java:294) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-015bda4]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:801) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-015bda4]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-015bda4]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-015bda4]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-4bd94dc-015bda4]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
[08:09:15] [Server thread/ERROR]: This crash report has been saved to: /var/games/minecraft/servers/Ends_Beginning/./crash-reports/crash-2018-02-10_08.09.15-server.txt
[08:09:15] [Server thread/INFO]: Stopping server

[crash-2018-02-10_08.09.15-server.txt](https://github.com/webbukkit/dynmap/files/1713397/crash-2018-02-10_08.09.15-server.txt)
`

**Comment by mikeprimm** [comment]
Error doesn't imply any role of dynmap - its crapping out on normal chunk saving.  VM isn't out of memory - isn't even short on it (Memory: 1764340752 bytes (1682 MB) / 13981188096 bytes (13333 MB) up to 13981188096 bytes (13333 MB) - hardly any use out of the total pool).  Your VM probably needs to be using a different GC - may want to try -XX:+UseParallelGC or -XX:+UseG1GC or -XX:+UseConcMarkSweepGC .  It's not an OOM error - its just that the GC is taking longer than the VM prefers, which I honestly cannot do anything about, even if dynmap were involved.

**Comment by adracamas** [comment]
Thank you boss for responding. Still pretty new to this and learning a lot thanks to people like you.
