### ISSUE TITLE
Cannot fullrender another world than overworld

### ISSUE THREAD

**Issue by ExDomino** [webbukkit/dynmap#2233]
Minecraft: 1.12.2
Forge: 14.23.3.2669
Dynmap: 2.6-alpha-2

Cannot pastebin this part of log, sorry.

[16:58:49] [Dynmap Render Thread/FATAL] [Dynmap]: [Dynmap] Exception while loading chunks
java.lang.NullPointerException: null
	at com.google.common.collect.ImmutableSetMultimap$Builder.putAll(ImmutableSetMultimap.java:317) ~[minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.common.ForgeChunkManager.forceChunk(ForgeChunkManager.java:817) ~[ForgeChunkManager.class:?]
	at org.dynmap.forge.DynmapPlugin.setBusy(DynmapPlugin.java:270) ~[DynmapPlugin.class:?]
	at org.dynmap.forge.DynmapPlugin.setBusy(DynmapPlugin.java:254) ~[DynmapPlugin.class:?]
	at org.dynmap.forge.DynmapPlugin.access$1500(DynmapPlugin.java:106) ~[DynmapPlugin.class:?]
	at org.dynmap.forge.DynmapPlugin$ForgeServer$1.call(DynmapPlugin.java:765) ~[DynmapPlugin$ForgeServer$1.class:?]
	at org.dynmap.forge.DynmapPlugin$ForgeServer$1.call(DynmapPlugin.java:761) ~[DynmapPlugin$ForgeServer$1.class:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_162]
	at org.dynmap.forge.DynmapPlugin$ForgeServer.tickEvent(DynmapPlugin.java:853) ~[DynmapPlugin$ForgeServer.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_868_ForgeServer_tickEvent_ServerTickEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:265) ~[FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:710) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) ~[MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]

**Comment by BonaireDreams** [comment]
#2223  Had the Same issue. Mike suggestion in that thread fixed it for me.

**Comment by ExDomino** [comment]
Tryed to set 'UseForcedChunks' to false: not working.
