### ISSUE TITLE
Error when trying to render custom dimension

### ISSUE THREAD

**Issue by philipjholm** [webbukkit/dynmap#2256]
I am using the mod [Just Enough Dimensions](https://minecraft.curseforge.com/projects/just-enough-dimensions) to create a new dimension (DIM30000) and it works like a charm. When I am trying to render it with dynmap however I get the following error in the log and nothing is rendered. Is there any fix for this? Can someone help me?

I am using:
Dynmap-2.6-beta-1-forge-1.12.jar
DynmapBlockScan-3.0-alpha-1-forge-1.12.2.jar

`[16:31:45] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Full render starting on world 'DIM30000'...§r
[16:31:45] [Dynmap Render Thread/FATAL] [Dynmap]: [Dynmap] Exception during render job: world=DIM30000, map=org.dynmap.hdmap.HDMap@58c74842
[16:31:45] [Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:193]: java.lang.ArrayIndexOutOfBoundsException: 0
[16:31:45] [Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:193]: 	at org.dynmap.forge.ChunkSnapshot.getBiome(ChunkSnapshot.java:215)
[16:31:45] [Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:193]: 	at org.dynmap.forge.ForgeMapChunkCache$OurMapIterator.biomePrep(ForgeMapChunkCache.java:227)
[16:31:45] [Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:193]: 	at org.dynmap.forge.ForgeMapChunkCache$OurMapIterator.<init>(ForgeMapChunkCache.java:122)
[16:31:45] [Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:193]: 	at org.dynmap.forge.ForgeMapChunkCache.getIterator(ForgeMapChunkCache.java:1554)
[16:31:45] [Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:193]: 	at org.dynmap.hdmap.IsoHDPerspective.render(IsoHDPerspective.java:1079)
[16:31:45] [Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:193]: 	at org.dynmap.hdmap.HDMapTile.render(HDMapTile.java:79)
[16:31:45] [Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:193]: 	at org.dynmap.MapManager$FullWorldRenderState.processTile(MapManager.java:708)
[16:31:45] [Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:193]: 	at org.dynmap.MapManager$FullWorldRenderState.run(MapManager.java:641)
[16:31:45] [Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:193]: 	at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1.run(MapManager.java:190)
[16:31:45] [Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:193]: 	at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$2.run(MapManager.java:206)
[16:31:45] [Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:193]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[16:31:45] [Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:193]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[16:31:45] [Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:193]: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
[16:31:45] [Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:193]: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
[16:31:45] [Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:193]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[16:31:45] [Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:193]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[16:31:45] [Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:193]: 	at java.lang.Thread.run(Unknown Source)`

**Comment by mikeprimm** [comment]
I see that JED supports some sort of biome override to use a single biome for the whole dimension - is it the case that you are using this?  It looks like the biome data for the chunk is missing.

**Comment by philipjholm** [comment]
Hi Mike,
Thanks for your fast response but no it shouldn't as I have this setting according to the instructions on their page "B:enableOverrideBiomeProvider=false".

To add to the problem... It seems to happen with new worlds not defined by JED as well. I today created a overworld orbiting space station with the mod GalactiCraft. Trying to render it gives the same error message as well. I then tried to do a small radius render on the overworld and it is also giving the same message :(
Is there anything else you need from me to be able to troubleshoot. I am super grateful for all your help!

**Comment by philipjholm** [comment]
I have tried re-installing everything again and removing mods but I still have this problem. It's really sad because this mod is so awesome and I really miss its features.

**Comment by squid-box** [comment]
Trying to use Dynmap with [All The Mods 3 Remix](https://github.com/AllTheMods/ATM3-Remix) (also featuring Just Enough Dimensions) I'm getting the same error. 

Happy to provide any additional info.

```
[Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Full render starting on world 'world'...
[Dynmap Render Thread/FATAL] [Dynmap]: [Dynmap] Exception during render job: world=world, map=org.dynmap.hdmap.HDMap@480aa242
[Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:193]: java.lang.ArrayIndexOutOfBoundsException: 0
[Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:193]:   at org.dynmap.forge.ChunkSnapshot.getBiome(ChunkSnapshot.java:215)
[Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:193]:   at org.dynmap.forge.ForgeMapChunkCache$OurMapIterator.biomePrep(ForgeMapChunkCache.java:227)
[Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:193]:   at org.dynmap.forge.ForgeMapChunkCache$OurMapIterator.<init>(ForgeMapChunkCache.java:122)
[Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:193]:   at org.dynmap.forge.ForgeMapChunkCache.getIterator(ForgeMapChunkCache.java:1554)
[Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:193]:   at org.dynmap.hdmap.IsoHDPerspective.render(IsoHDPerspective.java:1079)
[Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:193]:   at org.dynmap.hdmap.HDMapTile.render(HDMapTile.java:79)
[Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:193]:   at org.dynmap.MapManager$FullWorldRenderState.processTile(MapManager.java:708)
[Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:193]:   at org.dynmap.MapManager$FullWorldRenderState.run(MapManager.java:641)
[Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:193]:   at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1.run(MapManager.java:190)
[Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:193]:   at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$2.run(MapManager.java:206)
[Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:193]:   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:193]:   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:193]:   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
[Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:193]:   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
[Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:193]:   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:193]:   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:193]:   at java.lang.Thread.run(Thread.java:748)
```

**Comment by FedUpWith-Tech** [comment]
Closing due to age, please open a new issue if this is still relevant.
