### ISSUE TITLE
NullPointerException when rendering a dimension that was deleted and recreated

### ISSUE THREAD

**Issue by lucom** [webbukkit/dynmap#2260]
After deleting my Twilight Forest dimension, but right now also with the nether, whenever I try to start rendering the dimension I get a NullPointerException. This also seems to happen with "badly initialized?" worlds after starting a new server with a new world.

Steps to reproduce:
- Run a server witch a new world
- Render the different dimensions
- Stop the server
- Delete one dimension (region files and the whole folder, e.g. DIM7)
- Start the server
- "dynmap fullrender DIM7"

Result
```
> dynmap fullrender DIM7
[10:00:23] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Full render starting on world 'DIM7'...
[10:00:23] [Dynmap Render Thread/FATAL] [Dynmap]: [Dynmap] Exception while loading chunks
java.lang.NullPointerException: null
        at com.google.common.collect.ImmutableSetMultimap$Builder.putAll(ImmutableSetMultimap.java:317) ~[minecraft_server.1.12.2.jar:?]
        at net.minecraftforge.common.ForgeChunkManager.forceChunk(ForgeChunkManager.java:817) ~[ForgeChunkManager.class:?]
        at org.dynmap.forge.DynmapPlugin.setBusy(DynmapPlugin.java:271) ~[DynmapPlugin.class:?]
        at org.dynmap.forge.DynmapPlugin.setBusy(DynmapPlugin.java:255) ~[DynmapPlugin.class:?]
        at org.dynmap.forge.DynmapPlugin.access$1500(DynmapPlugin.java:107) ~[DynmapPlugin.class:?]
        at org.dynmap.forge.DynmapPlugin$ForgeServer$1.call(DynmapPlugin.java:771) ~[DynmapPlugin$ForgeServer$1.class:?]
        at org.dynmap.forge.DynmapPlugin$ForgeServer$1.call(DynmapPlugin.java:767) ~[DynmapPlugin$ForgeServer$1.class:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_171]
        at org.dynmap.forge.DynmapPlugin$ForgeServer.tickEvent(DynmapPlugin.java:859) ~[DynmapPlugin$ForgeServer.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_412_ForgeServer_tickEvent_ServerTickEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:265) ~[FMLCommonHandler.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:712) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) ~[MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]

```

**Comment by FedUpWith-Tech** [comment]
Closing due to age, please open a new issue if this is still relevant.
