### ISSUE TITLE
Dynmap 3.0 alpha crashes modded 1.12.2 server on startup

### ISSUE THREAD

**Issue by squid-box** [webbukkit/dynmap#2314]
Server is running [All The Mods 3 Remix (0.0.2)](https://github.com/AllTheMods/ATM3-Remix), and **Dynmap-3.0-SNAPSHOT-forge-1.12.2.jar** (built 2018-08-29)

With **Dynmap-2.6-beta-1-forge-1.12.2.jar** the server will start and run Dynmap, which will render whatever blocks it manages to, I haven't been able to run the ModScraper, so I'd really like to run the 3.0 alpha with the BlockScan instead.

Error stated is:
```
Description: Exception in server tick loop

java.lang.ArrayIndexOutOfBoundsException: 76752
        at org.dynmap.forge_1_12_2.DynmapPlugin$ForgeServer.tickEvent(DynmapPlugin.java:870)
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2665_ForgeServer_tickEvent_ServerTickEvent.invoke(.dynamic)
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
        at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:266)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:712)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
        at java.lang.Thread.run(Thread.java:748)
```

The crash report is attached: [crash-2018-08-31_23.13.32-server.txt](https://github.com/webbukkit/dynmap/files/2341639/crash-2018-08-31_23.13.32-server.txt)

As a side-note for BlockScan I had to increase the `max-tick-time` setting because it seems to block the server while scanning blocks, causing the watchdog to kill the server after a minute (default setting).

**Comment by autumnfire** [comment]
I get the same thing. I'm pretty sure it's due to the NotEnoughIDs mod. Dynmap probably wasn't designed for the extended IDs so it crashes. I have noticed that in my case the crash didn't actually happen until someone actually logged onto the server. Until then I was able to let it fully render the world.

Crash report: https://pastebin.com/zNahiAsC

Modpack: FTB Revelation 2.4.0
Using 8-25-18 snapshot of Dynmap 3.0 and DynmapBlockScan

**Comment by squid-box** [comment]
In my case it would crash immediately after the server startup was complete, and once it was running long enough for me to try to start a dynmap render (without players logged in) and it still crashed 🤷‍♂️ .

**Comment by squid-box** [comment]
Issue remains with Dynmap 3.0 alpha 3, but yesterday, but might be a little harder to reproduce.

**Comment by mikeprimm** [comment]
Please check with latest dev build - https://dynmap.us/builds/dynmap/Dynmap-3.0-SNAPSHOT-forge-1.12.2.jar - and let us know if you are still having problems?
