### ISSUE TITLE
Dynmap not rendering other worlds

### ISSUE THREAD

**Issue by xorinzor** [webbukkit/dynmap#2360]
For some reason Dynmap won't render anything except the default world, not even when using the command manually while inside of the dimension.

For the end dimension, for example,  it does create a "DIM1.pending" file, but just doesn't do anything aside of that.

I double checked the worlds.txt and forgeworlds.yml, but nothing stands out as configured incorrectly.

Why is this happening?

Using Dynmap 3.0 beta-1-forge-1.12.2

**Comment by JonathanBourassa** [comment]
I have the same here, Running DynMap on a FTB Revelation server only Overworld renders.

**Comment by BonaireDreams** [comment]
I had that happening,  try editing /config/dynmap.cfg file, and change UseForcedChunks setting from 'true' to 'false'. Fixed it for me.

**Comment by xorinzor** [comment]
That actually fixed it for me, Thanks!

**Comment by prenetic** [comment]
Workaround resolved the issue for me as well. Here's an excerpt from the logs when a fullrender is issued in one of the affected dimensions:

`[17:59:08] [Dynmap Render Thread/FATAL] [Dynmap]: [Dynmap] Exception while loading chunks
java.lang.NullPointerException: null
	at com.google.common.collect.ImmutableSetMultimap$Builder.putAll(ImmutableSetMultimap.java:317) ~[minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.common.ForgeChunkManager.forceChunk(ForgeChunkManager.java:817) ~[ForgeChunkManager.class:?]
	at org.dynmap.forge_1_12_2.DynmapPlugin.setBusy(DynmapPlugin.java:345) ~[DynmapPlugin.class:?]
	at org.dynmap.forge_1_12_2.DynmapPlugin.setBusy(DynmapPlugin.java:329) ~[DynmapPlugin.class:?]
	at org.dynmap.forge_1_12_2.DynmapPlugin.access$1500(DynmapPlugin.java:110) ~[DynmapPlugin.class:?]
	at org.dynmap.forge_1_12_2.DynmapPlugin$ForgeServer$1.call(DynmapPlugin.java:840) ~[DynmapPlugin$ForgeServer$1.class:?]
	at org.dynmap.forge_1_12_2.DynmapPlugin$ForgeServer$1.call(DynmapPlugin.java:836) ~[DynmapPlugin$ForgeServer$1.class:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_191]
	at org.dynmap.forge_1_12_2.DynmapPlugin$ForgeServer.tickEvent(DynmapPlugin.java:928) ~[DynmapPlugin$ForgeServer.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1947_ForgeServer_tickEvent_ServerTickEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:266) ~[FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:712) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) ~[MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]`

**Comment by generrosity** [comment]
OP confirmed resolved using "UseForcedChunks" option. Unless @mikeprimm wants to tackle the 'Exception while loading chunks java.lang.NullPointerException' more directly, closing ticket. 

Thanks for reporting, and confirming it was fixed!
