### ISSUE TITLE
Unable to find method getById for net.minecraft.server.v1_13_R2.Block

### ISSUE THREAD

**Issue by NatoBoram** [webbukkit/dynmap#2371]
Hello~
Basically I have my server on auto-update, and I was recently met with an error message.

Please let me know if you need anything else!

```yaml
[19:49:36] [Server thread/INFO]: [dynmap] Loading dynmap v3.0-beta-1-129
[19:49:36] [Server thread/INFO]: [dynmap] version=git-Paper-409 (MC: 1.13.2)
[19:49:36] [Server thread/ERROR]: [dynmap] Unable to find method getById for net.minecraft.server.v1_13_R2.Block
[19:49:37] [Server thread/INFO]: [dynmap] Unload queue not found - default to unload all chunks
[19:49:37] [Server thread/ERROR]: [org.bukkit.craftbukkit.v1_13_R2.CraftServer] Error initializing dynmap - bukkit version incompatible! initializing dynmap v3.0-beta-1-129 (Is it up to date?)
java.lang.IllegalArgumentException: Error initializing dynmap - bukkit version incompatible!
        at org.dynmap.bukkit.helper.BukkitVersionHelperGeneric.<init>(BukkitVersionHelperGeneric.java:159) ~[?:?]
        at org.dynmap.bukkit.helper.BukkitVersionHelperCB.<init>(BukkitVersionHelperCB.java:43) ~[?:?]
        at org.dynmap.bukkit.Helper.getHelper(Helper.java:42) ~[?:?]
        at org.dynmap.bukkit.DynmapPlugin.onLoad(DynmapPlugin.java:779) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.loadPlugins(CraftServer.java:331) ~[patched_1.13.2.jar:git-Paper-409]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:235) ~[patched_1.13.2.jar:git-Paper-409]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:791) ~[patched_1.13.2.jar:git-Paper-409]
        at java.lang.Thread.run(Thread.java:844) [?:?]
```
```yaml
[19:56:01 INFO]: This server is running Paper version git-Paper-409 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
[19:56:01 INFO]: Previous version: git-Paper-387 (MC: 1.13.2)
[19:56:01 INFO]: Checking version, please wait...
[19:56:03 INFO]: You are running the latest version
```
```yaml
OS: Ubuntu 18.04.1 LTS x86_64 
Host: Droplet 20171212 
Kernel: 4.15.0-34-generic 
Uptime: 42 days, 23 hours, 2 mins 
Packages: 757 
Shell: bash 4.4.19 
Terminal: /dev/pts/0 
CPU: Intel Xeon E5-2650 v4 (1) @ 2.200GHz 
GPU: Red Hat, Inc. QXL paravirtual graphic card 
Memory: 976MiB / 1993MiB 
```
```yaml
openjdk version "10.0.2" 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.3)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.3, mixed mode)
```

**Comment by mikeprimm** [comment]
I don't currently support 'Paper' - I'll give it a look and see if it can be made to work easily enough.

**Comment by mikeprimm** [comment]
1.13.2 requires dynmap 3.0-beta-2 or later (latest dev build, which includes workaround for an issue with rendering worlds created pre-1.13 on 1.13.2 is here - http://dynmap.us/builds/dynmap/Dynmap-3.0-SNAPSHOT-spigot.jar)
