### ISSUE TITLE
Wooden stair not rendered

### ISSUE THREAD

**Issue by Crysalix** [webbukkit/dynmap#2380]
Hi, 

I have found that the "Oak Wood Stairs" is not rendered. (ID 53)

![dynmap](https://user-images.githubusercontent.com/13493414/48312790-38864e00-e5b4-11e8-927a-764e7b9e8993.jpg)

Tested with default worlds.txt config and custom.
Spigot : 1.12.2
Dynmap : version 3.0-beta-2-138

**Comment by StevenGann** [comment]
I'm having the same issue using Dynmap for Forge.

**Comment by StevenGann** [comment]
@Crysalix Have you found a solution for this? It is a minor inconvenience, but one I'd like to get fixed.

**Comment by mikeprimm** [comment]
Should be fixed in latest dev builds - look for SNAPSHOT builds at http://dynmap.us/builds/dynmap/

**Comment by Crysalix** [comment]
Yeah ! Thanks :p

**Comment by Crysalix** [comment]
I got this now, but all work perfectly for now. Trying some renders, nothing wrong.

```
[11:50:57] [Server thread/ERROR]: [dynmap] Error loading maptype
java.lang.ClassNotFoundException: org.dynmap.hdmap.TexturePackHDUnderwaterShader
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_181]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:156) ~[patched_1.12.2.jar:git-Paper-1589]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[patched_1.12.2.jar:git-Paper-1589]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_181]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_181]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_181]
        at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_181]
        at org.dynmap.ConfigurationNode.createInstance(ConfigurationNode.java:316) ~[?:?]
        at org.dynmap.ConfigurationNode.createInstances(ConfigurationNode.java:341) ~[?:?]
        at org.dynmap.hdmap.HDMapManager.loadHDShaders(HDMapManager.java:39) ~[?:?]
        at org.dynmap.MapManager.<init>(MapManager.java:918) ~[?:?]
        at org.dynmap.DynmapCore.enableCore(DynmapCore.java:521) ~[?:?]
        at org.dynmap.bukkit.DynmapPlugin.doEnable(DynmapPlugin.java:877) ~[?:?]
        at org.dynmap.bukkit.DynmapPlugin.onEnable(DynmapPlugin.java:857) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1589]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) ~[patched_1.12.2.jar:git-Paper-1589]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.12.2.jar:git-Paper-1589]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) ~[patched_1.12.2.jar:git-Paper-1589]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) ~[patched_1.12.2.jar:git-Paper-1589]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) ~[patched_1.12.2.jar:git-Paper-1589]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) ~[patched_1.12.2.jar:git-Paper-1589]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) ~[patched_1.12.2.jar:git-Paper-1589]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289) ~[patched_1.12.2.jar:git-Paper-1589]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[patched_1.12.2.jar:git-Paper-1589]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
[11:50:57] [Server thread/WARN]: java.lang.ClassNotFoundException: org.dynmap.hdmap.TexturePackHDUnderwaterShader
[11:50:57] [Server thread/WARN]:        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
[11:50:57] [Server thread/WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:156)
[11:50:57] [Server thread/WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104)
[11:50:57] [Server thread/WARN]:        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[11:50:57] [Server thread/WARN]:        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[11:50:57] [Server thread/WARN]:        at java.lang.Class.forName0(Native Method)
[11:50:57] [Server thread/WARN]:        at java.lang.Class.forName(Class.java:264)
[11:50:57] [Server thread/WARN]:        at org.dynmap.ConfigurationNode.createInstance(ConfigurationNode.java:316)
[11:50:57] [Server thread/WARN]:        at org.dynmap.ConfigurationNode.createInstances(ConfigurationNode.java:341)
[11:50:57] [Server thread/WARN]:        at org.dynmap.hdmap.HDMapManager.loadHDShaders(HDMapManager.java:39)
[11:50:57] [Server thread/WARN]:        at org.dynmap.MapManager.<init>(MapManager.java:918)
[11:50:57] [Server thread/WARN]:        at org.dynmap.DynmapCore.enableCore(DynmapCore.java:521)
[11:50:57] [Server thread/WARN]:        at org.dynmap.bukkit.DynmapPlugin.doEnable(DynmapPlugin.java:877)
[11:50:57] [Server thread/WARN]:        at org.dynmap.bukkit.DynmapPlugin.onEnable(DynmapPlugin.java:857)
[11:50:57] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[11:50:57] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[11:50:57] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[11:50:57] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395)
[11:50:57] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344)
[11:50:57] [Server thread/WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442)
[11:50:57] [Server thread/WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403)
[11:50:57] [Server thread/WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341)
[11:50:57] [Server thread/WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289)
[11:50:57] [Server thread/WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
[11:50:57] [Server thread/WARN]:        at java.lang.Thread.run(Thread.java:748)
```
