### ISSUE TITLE
Spigot 1.13.2 renders nothing with IllegalArgumentException

### ISSUE THREAD

**Issue by mikesbytes** [webbukkit/dynmap#2386]
I can open the web UI but nothing renders. I can see player positions but every time it tries to render chunks, the console spits out the following error

```
[05:01:52 ERROR]: [dynmap] Exception during render job: org.dynmap.MapManager$CheckWorldTimes@67504b37
[05:01:52 WARN]: java.lang.IllegalArgumentException: Task must be Runnable or Consumer
[05:01:52 WARN]:        at org.apache.commons.lang.Validate.isTrue(Validate.java:136)
[05:01:52 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.validate(CraftScheduler.java:442)
[05:01:52 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.callSyncMethod(CraftScheduler.java:213)
[05:01:52 WARN]:        at org.dynmap.bukkit.DynmapPlugin$BukkitServer.callSyncMethod(DynmapPlugin.java:248)
[05:01:52 WARN]:        at org.dynmap.MapManager$CheckWorldTimes.run(MapManager.java:779)
[05:01:52 WARN]:        at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$2.run(MapManager.java:207)
[05:01:52 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[05:01:52 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[05:01:52 WARN]:        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
[05:01:52 WARN]:        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
[05:01:52 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[05:01:52 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[05:01:52 WARN]:        at java.lang.Thread.run(Thread.java:748)
```

I am using the latest spigot build for 1.13.2 with Java 8

**Comment by Quavelen** [comment]
I'd like to retract the above comment of mine, and say that this seems to have been an issue with the specific version of spigot I was on. After updating again today, the issue is gone and everything functions normally. 

So to reiterate...

* **Problem version:**
  * CraftBukkit version git-Spigot-bc4adcb-8cd538e (MC: 1.13.2)
* **Fixed version:**
  * CraftBukkit version git-Spigot-a1f2566-97b0057 (MC: 1.13.2)

This is not an issue on Dynmap's end.

**Comment by mikesbytes** [comment]
Thanks, I suspected it might be a spigot issue. Closing this.

**Comment by hammypants** [comment]
From a fresh install today...
```
This server is running CraftBukkit version git-Spigot-a1f2566-8cd538e (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
```
I am seeing this issue.

**Comment by hammypants** [comment]
Damn-- I just did a full recompile as a sanity check and I guess my build from even earlier today was bad.

Do either of you on this issue know what was fixed? Should I be expecting Spigot to be breaking this frequently?
