### ISSUE TITLE
Will not render

### ISSUE THREAD

**Issue by JamesB84** [webbukkit/dynmap#2387]
This is the error I get when I try to do a render. I've looked everywhere for a solution, but nothing seems to apply to this. Can anyone help? The webpage is black besides the players, clock, menu, etc. Nothing renders, and the log shows me this when I try to do a full render. Thanks in advance for your help.

[08:09:23] [Dynmap Render Thread/ERROR]: [dynmap] Exception during render job: org.dynmap.MapManager$CheckWorldTimes@7ccf7e5b
[08:09:23] [Dynmap Render Thread/WARN]: java.lang.IllegalArgumentException: Task must be Runnable or Consumer
[08:09:23] [Dynmap Render Thread/WARN]: 	at org.apache.commons.lang.Validate.isTrue(Validate.java:136)
[08:09:23] [Dynmap Render Thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.validate(CraftScheduler.java:442)
[08:09:23] [Dynmap Render Thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.callSyncMethod(CraftScheduler.java:213)
[08:09:23] [Dynmap Render Thread/WARN]: 	at org.dynmap.bukkit.DynmapPlugin$BukkitServer.callSyncMethod(DynmapPlugin.java:248)
[08:09:23] [Dynmap Render Thread/WARN]: 	at org.dynmap.MapManager$CheckWorldTimes.run(MapManager.java:779)
[08:09:23] [Dynmap Render Thread/WARN]: 	at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$2.run(MapManager.java:207)
[08:09:23] [Dynmap Render Thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[08:09:23] [Dynmap Render Thread/WARN]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[08:09:23] [Dynmap Render Thread/WARN]: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
[08:09:23] [Dynmap Render Thread/WARN]: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
[08:09:23] [Dynmap Render Thread/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[08:09:23] [Dynmap Render Thread/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[08:09:23] [Dynmap Render Thread/WARN]: 	at java.lang.Thread.run(Unknown Source)

**Comment by Psy-Virus** [comment]
#2386 ?

> I've looked everywhere for a solution, but nothing seems to apply to this

aha!?

**Comment by JamesB84** [comment]
Thank you very much, I don't know how I missed that. You're a lifesaver.

**Comment by Psy-Virus** [comment]
You're welcome and pls don't forget to close this issue.
