### ISSUE TITLE
Unable to render maps (1.13.2)

### ISSUE THREAD

**Issue by SaintIsaiah** [webbukkit/dynmap#2388]
I have Spigot installed on version 1.13.2 and I'm having issues rendering.

If I do a render in my area, it says it's been queued but nothing processes.

If I try to do a full render, regardless of whether or not I have specified the world name and map, I get the following error in the logs:

`
[21:16:22] [Server thread/INFO]: SaintIsaiah issued server command: /dynmap fullrender world:surface
[21:16:22] [Dynmap Render Thread/ERROR]: [dynmap] Exception during render job: world=world, map=org.dynmap.hdmap.HDMap@4525c257
[21:16:22] [Dynmap Render Thread/WARN]: java.lang.IllegalArgumentException: Task must be Runnable or Consumer
[21:16:22] [Dynmap Render Thread/WARN]: 	at org.apache.commons.lang.Validate.isTrue(Validate.java:136)
[21:16:22] [Dynmap Render Thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.validate(CraftScheduler.java:442)
[21:16:22] [Dynmap Render Thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.callSyncMethod(CraftScheduler.java:213)
[21:16:22] [Dynmap Render Thread/WARN]: 	at org.dynmap.bukkit.DynmapPlugin$BukkitServer.callSyncMethod(DynmapPlugin.java:248)
[21:16:22] [Dynmap Render Thread/WARN]: 	at org.dynmap.bukkit.DynmapPlugin$BukkitServer.createMapChunkCache(DynmapPlugin.java:448)
[21:16:22] [Dynmap Render Thread/WARN]: 	at org.dynmap.MapManager$FullWorldRenderState.processTile(MapManager.java:683)
[21:16:22] [Dynmap Render Thread/WARN]: 	at org.dynmap.MapManager$FullWorldRenderState.run(MapManager.java:642)
[21:16:22] [Dynmap Render Thread/WARN]: 	at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1.run(MapManager.java:191)
[21:16:22] [Dynmap Render Thread/WARN]: 	at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$2.run(MapManager.java:207)
[21:16:22] [Dynmap Render Thread/WARN]: 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
[21:16:22] [Dynmap Render Thread/WARN]: 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[21:16:22] [Dynmap Render Thread/WARN]: 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
[21:16:22] [Dynmap Render Thread/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
[21:16:22] [Dynmap Render Thread/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[21:16:22] [Dynmap Render Thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:844)
`

Not sure if this is a configuration issue or something with the plugin. I'm not really experienced with Java, so any help would be greatly appreciated.

**Comment by TheDarknessEmperor** [comment]
1.13.2 is broken on the current version, it latest it works on is only 1.13.1

**Comment by mikeprimm** [comment]
Anything before 3.0-beta-2 will not work on 1.13.2 - which are you running?

**Comment by mikeprimm** [comment]
(latest dev build is at http://dynmap.us/builds/dynmap/Dynmap-3.0-SNAPSHOT-spigot.jar)

**Comment by mikeprimm** [comment]
Beta-3 release candidate is here - https://dynmap.us/builds/dynmap/Dynmap-3.0-beta-3-spigot.jar - please give this a try and reopen if more action is needed
