### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: Coordinate out of bounds!

### ISSUE THREAD

**Issue by Genskao** [webbukkit/dynmap#2402]
Hi,

I use the tag v3.0.
The error below appear in the logs when an user connect to the server (v1.13.2 spigot).

```
[09:43:29 ERROR]: [dynmap] Exception during render job: org.dynmap.PlayerFaces$LoadPlayerImages@1ee3584b
[09:43:29 WARN]: java.lang.ArrayIndexOutOfBoundsException: Coordinate out of bounds!
[09:43:29 WARN]:        at sun.awt.image.ByteInterleavedRaster.getDataElements(ByteInterleavedRaster.java:318)
[09:43:29 WARN]:        at java.awt.image.BufferedImage.getRGB(BufferedImage.java:986)
[09:43:29 WARN]:        at org.dynmap.PlayerFaces.copyLayersToTarget(PlayerFaces.java:68)
[09:43:29 WARN]:        at org.dynmap.PlayerFaces.access$300(PlayerFaces.java:24)
[09:43:29 WARN]:        at org.dynmap.PlayerFaces$LoadPlayerImages.run(PlayerFaces.java:199)
[09:43:29 WARN]:        at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1.run(MapManager.java:193)
[09:43:29 WARN]:        at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$2.run(MapManager.java:209)
[09:43:29 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[09:43:29 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[09:43:29 WARN]:        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
[09:43:29 WARN]:        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
[09:43:29 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[09:43:29 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[09:43:29 WARN]:        at java.lang.Thread.run(Thread.java:748)
```

I removed the dynmap directory and retry, but I'have the same error :'(

**Comment by mikeprimm** [comment]
Can we identify some specific user names with the skins in question?

**Comment by mikeprimm** [comment]
Please give latest dev snapshot a try -https://dynmap.us/builds/dynmap/

**Comment by Genskao** [comment]
Working fine! 💃

**Comment by Psy-Virus** [comment]
Well, the error is gone now but the faces of those players are not fetched anymore. With the error, they were fetched. If it had to do with those layers, can't you just ignore the layer when it's not existing?

One of the players, triggering the error is `Seeadler4000` He at least gave me permissions to write his name into the issue.

**Comment by mikeprimm** [comment]
OK - please give latest dev build a try

**Comment by Psy-Virus** [comment]
Works as it should. All player faces are fetched now.
Thanks Mike

~closing this~
