### ISSUE TITLE
bukkit version incompatible! initializing dynmap v3.0-beta-1-129 (Is it up to date?)

### ISSUE THREAD

**Issue by scysys** [webbukkit/dynmap#2405]
Any newer Version that are Working?

`[22:58:42 INFO]: [dynmap] Loading dynmap v3.0-beta-1-129
[22:58:42 INFO]: [dynmap] version=git-Paper-488 (MC: 1.13.2)
[22:58:42 ERROR]: [dynmap] Unable to find method getById for net.minecraft.server.v1_13_R2.Block
[22:58:42 INFO]: [dynmap] Unload queue not found - default to unload all chunks
[22:58:42 ERROR]: [org.bukkit.craftbukkit.v1_13_R2.CraftServer] Error initializing dynmap - bukkit version incompatible! initializing dynmap v3.0-beta-1-129 (Is it up to date?)
java.lang.IllegalArgumentException: Error initializing dynmap - bukkit version incompatible!
	at org.dynmap.bukkit.helper.BukkitVersionHelperGeneric.<init>(BukkitVersionHelperGeneric.java:159) ~[?:?]
	at org.dynmap.bukkit.helper.BukkitVersionHelperCB.<init>(BukkitVersionHelperCB.java:43) ~[?:?]
	at org.dynmap.bukkit.Helper.getHelper(Helper.java:42) ~[?:?]
	at org.dynmap.bukkit.DynmapPlugin.onLoad(DynmapPlugin.java:779) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.loadPlugins(CraftServer.java:334) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:235) ~[patched_1.13.2.jar:git-Paper-488]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:791) ~[patched_1.13.2.jar:git-Paper-488]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]`

**Comment by scysys** [comment]
Sorry, found this one: http://dynmap.us/builds/dynmap/Dynmap-3.0-SNAPSHOT-spigot.jar
From: https://github.com/webbukkit/dynmap/issues/2371#issuecomment-443479844

It seems to be working.

Only 1 Message left
`[23:03:30 ERROR]: [dynmap] Error reading plugins/dynmap/markers.yml`
