### ISSUE TITLE
Crash report in full render.

### ISSUE THREAD

**Issue by spylor** [webbukkit/dynmap#2416]
Dynmap crashed after a few full render tiles.
/dynmap fullrender world
forge-1.12.2-14.23.5.2768-universal
Dynmap-3.0-beta-3-forge-1.12.2
DynmapBlockScan-3.0-beta-1-forge-1.12.2

The crash happens at the end of the log.
+++++++
The crash:
[15:35:46] [Dynmap Render Thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Full render of map 'flat' of 'world' in progress - 600 tiles rendered (59.96 msec/tile, 23.92 msec per render)
[15:35:51] [Dynmap Render Thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Full render of map 'flat' of 'world' in progress - 700 tiles rendered (59.22 msec/tile, 23.30 msec per render)
[15:35:52] [Dynmap Render Thread/FATAL] [Dynmap]: [Dynmap] Exception during render job: world=world, map=org.dynmap.hdmap.HDMap@154c6d9e
[15:35:52] [Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]: java.lang.ArrayIndexOutOfBoundsException: 65535
[15:35:52] [Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]: 	at org.dynmap.forge_1_12_2.ChunkSnapshot.<init>(ChunkSnapshot.java:229)
[15:35:52] [Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]: 	at org.dynmap.forge_1_12_2.ForgeMapChunkCache.prepChunkSnapshot(ForgeMapChunkCache.java:1241)
[15:35:52] [Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]: 	at org.dynmap.forge_1_12_2.ForgeMapChunkCache.readChunks(ForgeMapChunkCache.java:1407)
[15:35:52] [Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]: 	at org.dynmap.forge_1_12_2.DynmapPlugin$ForgeServer.createMapChunkCache(DynmapPlugin.java:887)
[15:35:52] [Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]: 	at org.dynmap.MapManager$FullWorldRenderState.processTile(MapManager.java:685)
[15:35:52] [Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]: 	at org.dynmap.MapManager$FullWorldRenderState.run(MapManager.java:644)
[15:35:52] [Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]: 	at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1.run(MapManager.java:193)
[15:35:52] [Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]: 	at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$2.run(MapManager.java:209)
[15:35:52] [Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[15:35:52] [Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[15:35:52] [Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
[15:35:52] [Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
[15:35:52] [Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[15:35:52] [Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[15:35:52] [Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]: 	at java.lang.Thread.run(Unknown Source)

+++++++
I'm using all standard files and this is my world file:
worlds:
-   name: world
    title: world/overworld
    enabled: true
    protected: false
    showborder: true
    sendposition: true
    sendhealth: true
    extrazoomout: 3
    visibilitylimits: [
        ]
    hiddenlimits: [
        ]
    hidestyle: stone
    maps:
    -   class: org.dynmap.hdmap.HDMap
        name: flat
        title: Flat
        prefix: flat
        perspective: iso_S_90_vlowres
        shader: stdtexture
        lighting: shadows
        mapzoomin: 2
-   name: DIM1
    title: world/the_end
    enabled: false
-   name: DIM-1
    title: world/the_nether
    enabled: false
-   name: DIM7
    title: world/twilight_forest
    enabled: false
-   name: DIM-28
    title: Moon
    enabled: false
-   name: DIM-29
    title: Mars
    enabled: false
-   name: DIM-30
    title: Venus
    enabled: false
-   name: DIM-31
    title: Asteroids
    enabled: false

**Comment by Selkie707** [comment]
also encountering this bug with All The Mods 3 server

**Comment by FedUpWith-Tech** [comment]
Assuming this is fixed in a later release or otherwise no longer relevant- please open a new issue if this persists.
