### ISSUE TITLE
Dynmap doesn't work on ubuntu (2.5+)

### ISSUE THREAD

**Issue by cat768** [webbukkit/dynmap#2420]
## Server Information

- I can reproduce this issue consistently
     - [ ] Reinstalling bukkit on ubuntu, dragging in jar file and starting the server
- [ ] I have searched for this issue previously and it was either or a different OS or using a previous version of Bukkit/minecraft
- [ ] I am crashing and can provide my crash report(s)
[dynmap] Enabling dynmap v3.0-alpha-3-111
[dynmap] Dynmap is disabled (unsupported platform)
<!-->

**Comment by cat768** [comment]
Yes, v2.5-Dev201706100405

My apologies for the incorrect crash reports, this should be it:

[13:50:01] [Server thread/INFO]: Starting minecraft server version 1.13.2
[13:50:01] [Server thread/INFO]: Loading properties
[13:50:01] [Server thread/INFO]: Default game type: SURVIVAL
[13:50:01] [Server thread/INFO]: Generating keypair
[13:50:01] [Server thread/INFO]: Starting Minecraft server on *:25565
[13:50:01] [Server thread/INFO]: Using epoll channel type
[13:50:02] [Server thread/INFO]: This server is running CraftBukkit version git-Bukkit-a5b9c7b (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
[13:50:06] [Server thread/INFO]: [dynmap] Loading dynmap v2.5-Dev201706100405
[13:50:06] [Server thread/INFO]: [dynmap] version=git-Bukkit-a5b9c7b (MC: 1.13.2)
[13:50:06] [Server thread/ERROR]: [dynmap] Unable to find method getById for net.minecraft.server.v1_13_R2.Block
[13:50:06] [Server thread/ERROR]: [dynmap] Unable to find method a for net.minecraft.server.v1_13_R2.BiomeBase
[13:50:07] [Server thread/ERROR]: [dynmap] Unable to find field temperature for net.minecraft.server.v1_13_R2.BiomeBase
[13:50:07] [Server thread/ERROR]: [dynmap] Unable to find field humidity for net.minecraft.server.v1_13_R2.BiomeBase
[13:50:07] [Server thread/ERROR]: [dynmap] Unable to find field y for net.minecraft.server.v1_13_R2.BiomeBase
[13:50:07] [Server thread/INFO]: [dynmap] Unload queue not found - default to unload all chunks
[13:50:07] [Server thread/INFO]: [dynmap] inhabitedTicks field not found - inhabited shader not functional
[13:50:07] [Server thread/ERROR]: Error initializing dynmap - bukkit version incompatible! initializing dynmap v2.5-Dev201706100405 (Is it up to date?)
java.lang.IllegalArgumentException: Error initializing dynmap - bukkit version incompatible!
	at org.dynmap.bukkit.BukkitVersionHelperGeneric.<init>(BukkitVersionHelperGeneric.java:129) ~[?:?]
	at org.dynmap.bukkit.BukkitVersionHelperCB.<init>(BukkitVersionHelperCB.java:39) ~[?:?]
	at org.dynmap.bukkit.BukkitVersionHelper.getHelper(BukkitVersionHelper.java:42) ~[?:?]
	at org.dynmap.bukkit.DynmapPlugin.onLoad(DynmapPlugin.java:756) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.loadPlugins(CraftServer.java:327) [craftbukkit-1.13.2.jar:git-Bukkit-a5b9c7b]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:196) [craftbukkit-1.13.2.jar:git-Bukkit-a5b9c7b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:675) [craftbukkit-1.13.2.jar:git-Bukkit-a5b9c7b]
	at java.lang.Thread.run(Thread.java:844) [?:?]
[13:50:07] [Server thread/INFO]: Preparing level "world"
[13:50:07] [Server thread/INFO]: Reloading ResourceManager: Default, bukkit
[13:50:08] [Server thread/INFO]: Loaded 524 recipes
[13:50:09] [Server thread/INFO]: Preparing start region for level minecraft:the_nether (Seed: -3056757603607152718)
[13:50:09] [Server thread/INFO]: Preparing spawn area: 4%
[13:50:09] [Server thread/INFO]: Preparing spawn area: 8%
[13:50:09] [Server thread/INFO]: Preparing spawn area: 12%
[13:50:10] [Server thread/INFO]: Preparing spawn area: 16%
[13:50:10] [Server thread/INFO]: Preparing spawn area: 20%
[13:50:10] [Server thread/INFO]: Preparing spawn area: 24%
[13:50:10] [Server thread/INFO]: Preparing spawn area: 28%
[13:50:10] [Server thread/INFO]: Preparing spawn area: 32%
[13:50:10] [Server thread/INFO]: Preparing spawn area: 36%
[13:50:11] [Server thread/INFO]: Preparing spawn area: 40%
[13:50:11] [Server thread/INFO]: Preparing spawn area: 44%
[13:50:11] [Server thread/INFO]: Preparing spawn area: 48%
[13:50:11] [Server thread/INFO]: Preparing spawn area: 52%
[13:50:11] [Server thread/INFO]: Preparing spawn area: 56%
[13:50:11] [Server thread/INFO]: Preparing spawn area: 60%
[13:50:11] [Server thread/INFO]: Preparing spawn area: 64%
[13:50:11] [Server thread/INFO]: Preparing spawn area: 68%
[13:50:12] [Server thread/INFO]: Preparing spawn area: 72%
[13:50:12] [Server thread/INFO]: Preparing spawn area: 76%
[13:50:12] [Server thread/INFO]: Preparing spawn area: 80%
[13:50:12] [Server thread/INFO]: Preparing spawn area: 84%
[13:50:12] [Server thread/INFO]: Preparing spawn area: 88%
[13:50:12] [Server thread/INFO]: Preparing spawn area: 92%
[13:50:12] [Server thread/INFO]: Preparing spawn area: 96%
[13:50:12] [Server thread/INFO]: Preparing spawn area: 100%
[13:50:12] [Server thread/INFO]: Preparing start region for level minecraft:the_end (Seed: -3056757603607152718)
[13:50:12] [Server thread/INFO]: Preparing spawn area: 4%
[13:50:12] [Server thread/INFO]: Preparing spawn area: 8%
[13:50:12] [Server thread/INFO]: Preparing spawn area: 12%
[13:50:12] [Server thread/INFO]: Preparing spawn area: 16%
[13:50:12] [Server thread/INFO]: Preparing spawn area: 20%
[13:50:12] [Server thread/INFO]: Preparing spawn area: 24%
[13:50:12] [Server thread/INFO]: Preparing spawn area: 28%
[13:50:12] [Server thread/INFO]: Preparing spawn area: 32%
[13:50:12] [Server thread/INFO]: Preparing spawn area: 36%
[13:50:12] [Server thread/INFO]: Preparing spawn area: 40%
[13:50:12] [Server thread/INFO]: Preparing spawn area: 44%
[13:50:12] [Server thread/INFO]: Preparing spawn area: 48%
[13:50:12] [Server thread/INFO]: Preparing spawn area: 52%
[13:50:12] [Server thread/INFO]: Preparing spawn area: 56%
[13:50:12] [Server thread/INFO]: Preparing spawn area: 60%
[13:50:13] [Server thread/INFO]: Preparing spawn area: 64%
[13:50:13] [Server thread/INFO]: Preparing spawn area: 68%
[13:50:13] [Server thread/INFO]: Preparing spawn area: 72%
[13:50:13] [Server thread/INFO]: Preparing spawn area: 76%
[13:50:13] [Server thread/INFO]: Preparing spawn area: 80%
[13:50:13] [Server thread/INFO]: Preparing spawn area: 84%
[13:50:13] [Server thread/INFO]: Preparing spawn area: 88%
[13:50:13] [Server thread/INFO]: Preparing spawn area: 92%
[13:50:13] [Server thread/INFO]: Preparing spawn area: 96%
[13:50:13] [Server thread/INFO]: Preparing spawn area: 100%
[13:50:13] [Server thread/INFO]: Preparing start region for level minecraft:overworld (Seed: -4554394974020616877)
[13:50:13] [Server thread/INFO]: Preparing spawn area: 4%
[13:50:13] [Server thread/INFO]: Preparing spawn area: 8%
[13:50:13] [Server thread/INFO]: Preparing spawn area: 12%
[13:50:13] [Server thread/INFO]: Preparing spawn area: 16%
[13:50:14] [Server thread/INFO]: Preparing spawn area: 20%
[13:50:14] [Server thread/INFO]: Preparing spawn area: 24%
[13:50:14] [Server thread/INFO]: Preparing spawn area: 28%
[13:50:14] [Server thread/INFO]: Preparing spawn area: 32%
[13:50:14] [Server thread/INFO]: Preparing spawn area: 36%
[13:50:14] [Server thread/INFO]: Preparing spawn area: 40%
[13:50:14] [Server thread/INFO]: Preparing spawn area: 44%
[13:50:14] [Server thread/INFO]: Preparing spawn area: 48%
[13:50:14] [Server thread/INFO]: Preparing spawn area: 52%
[13:50:15] [Server thread/INFO]: Preparing spawn area: 56%
[13:50:15] [Server thread/INFO]: Preparing spawn area: 60%
[13:50:15] [Server thread/INFO]: Preparing spawn area: 64%
[13:50:15] [Server thread/INFO]: Preparing spawn area: 68%
[13:50:15] [Server thread/INFO]: Preparing spawn area: 72%
[13:50:15] [Server thread/INFO]: Preparing spawn area: 76%
[13:50:15] [Server thread/INFO]: Preparing spawn area: 80%
[13:50:15] [Server thread/INFO]: Preparing spawn area: 84%
[13:50:15] [Server thread/INFO]: Preparing spawn area: 88%
[13:50:15] [Server thread/INFO]: Preparing spawn area: 92%
[13:50:15] [Server thread/INFO]: Preparing spawn area: 96%
[13:50:15] [Server thread/INFO]: Preparing spawn area: 100%
[13:50:15] [Server thread/INFO]: Time elapsed: 6357 ms
[13:50:15] [Server thread/INFO]: [dynmap] Enabling dynmap v2.5-Dev201706100405
[13:50:15] [Server thread/INFO]: [dynmap] Dynmap is disabled (unsupported platform)
[13:50:15] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[13:50:15] [Server thread/INFO]: Done (8.754s)! For help, type "help"
[13:50:18] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 2028ms or 40 ticks behind

**Comment by Psy-Virus** [comment]
> [13:50:15] [Server thread/INFO]: [dynmap] Dynmap is disabled (unsupported platform)

You say you use Dynmap 3.0
>  Latest Bukkit Plugin
>    Version: 3.0
> Latest Bukkit jar
>    Version: 1.13.2


But the log says you're trying to use Dynmap 2.5 with Bukkit 1.13.X

try with latest Dynmap http://dynmap.us/builds/dynmap/Dynmap-HEAD-spigot.jar
