### ISSUE TITLE
Dynmap 3.0 (1.10.2) Fatal error on render attempt (Exception while loading chunks)

### ISSUE THREAD

**Issue by tukib** [webbukkit/dynmap#2421]
## Server Information

- I can reproduce this issue consistently
     - [x] In Multiplayer 
     - [x] After deleting/renaming the DYNMAP folder
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [x] I am crashing and can provide my crash report(s) **only on 3.0-beta-3; fatal error on snapshot**
- I have tried the following diagnostics;
     - [x] Re-rendered missing chunks using /dynmap fullrender
     - [x] Cleared cached tiles using /dynmap purgeworld [world] (especially if using a map from an older version)
     - [x] Deleted/Renamed the dynmap folder to regenerate configs and files fresh
     - [x] Tested using the 'HEAD' version from dynmap.us/builds (these are stable to use)
     - [ ] Rechecked the Minecraft Server and Webserver Config (If using an external Webserver)

## Issue Description
ArrayIndexOutOfBoundsException is thrown every time a new render queue is created, whether it's the automatic one on startup or by /dynmap fullrender/radiusrender (etc).
The map renders a few chunks around spawn but stops rendering entirely after the first exception. This happens regardless of whether players connect. This is occuring on DIM0, all other dimensions are disabled.

## Reproduce Steps
1. Start 1.10.2 forge server with mods (see additional information)
2. Wait for less than a minute from startup.

## Additional Information
View of web map after exception: https://i.imgur.com/bK9Qn6O.png
First exception:
```
[14:58:47] [Dynmap Render Thread/FATAL] [Dynmap]: [Dynmap] Exception while loading chunks
java.lang.ArrayIndexOutOfBoundsException: 78240
        at org.dynmap.forge_1_10_2.ChunkSnapshot.<init>(ChunkSnapshot.java:228) ~[ChunkSnapshot.class:?]
        at org.dynmap.forge_1_10_2.ForgeMapChunkCache.prepChunkSnapshot(ForgeMapChunkCache.java:1241) ~[ForgeMapChunkCache.class:?]
        at org.dynmap.forge_1_10_2.ForgeMapChunkCache.getLoadedChunks(ForgeMapChunkCache.java:1320) ~[ForgeMapChunkCache.class:?]
        at org.dynmap.forge_1_10_2.DynmapPlugin$ForgeServer$1.call(DynmapPlugin.java:847) ~[DynmapPlugin$ForgeServer$1.class:?]
        at org.dynmap.forge_1_10_2.DynmapPlugin$ForgeServer$1.call(DynmapPlugin.java:842) ~[DynmapPlugin$ForgeServer$1.class:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_191]
        at org.dynmap.forge_1_10_2.DynmapPlugin$ForgeServer.tickEvent(DynmapPlugin.java:934) ~[DynmapPlugin$ForgeServer.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1642_ForgeServer_tickEvent_ServerTickEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) ~[EventBus.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:261) ~[FMLCommonHandler.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:657) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) ~[MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
```
Subsequent exceptions: (when using commands such as fullrender)
```
[14:58:53] [Dynmap Render Thread/FATAL] [Dynmap]: [Dynmap] Exception while loading chunks
java.lang.ArrayIndexOutOfBoundsException
```
It is worth noting that this same error crashed the server when using `v3.0-beta-3`. I switched to the latest snapshot (164) hoping to resolve the issue, but while the error was somewhat suppressed, the map did not render. v3.0-beta-3 crash report: https://pastebin.com/DqY1Ytae
The server is running [All The Mods](https://minecraft.curseforge.com/projects/all-the-mods/files/2632108) (v4.2 for 1.10.2), with Aroma1997Core-1.9.4-1.1.1.2 and Aroma1997s-Dimensional-World-1.9.4-1.2.0.7 added. The installed version of forge is forge-1.10.2-12.18.3.2511.
This modpack is using NotEnoughIDs which looks like has had a fair amount of issues with dynmap in the past, so that could be related.
The server is loading a [pre-made 1.8 map](https://www.planetminecraft.com/project/le-monde---a-16k-blocks-wide-gigantic-survival-world-map-18-ready/). No retrogen for ores is being used except draconicevolution (by default).

**Comment by tukib** [comment]
I have tested the HEAD build (2.6-SNAPSHOT-Dev201807081550) and this issue does not occur.

**Comment by mikeprimm** [comment]
1.10.2 didn't have support for handling extended block IDs (beyond 4096, as done by JEIDs or NEIDs) - give new build a try: https://dynmap.us/builds/dynmap/Dynmap-3.0-SNAPSHOT-forge-1.10.2.jar

**Comment by mikeprimm** [comment]
(2.6 will not be updated to support JEIDs/NEIDs - if you want that, go to 3.0...)
