### ISSUE TITLE
processWorldEvent(WORLD_LOAD,org.dynmap.bukkit.helper.BukkitWorld@6c11b92

### ISSUE THREAD

**Issue by Blueeyestar** [webbukkit/dynmap#2455]
DynmapVersion:  **3.0-beta-3-160**

Spigotversion: **CraftBukkit version git-Spigot-e6eb36f-d3ed151 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)**

[09:29:22] [Server thread/WARN]: [dynmap] processWorldEvent(WORLD_LOAD,org.dynmap.bukkit.helper.BukkitWorld@6c11b92) - exception
java.lang.NullPointerException: null
	at org.dynmap.bukkit.helper.v113_2.BukkitVersionHelperSpigot113_2.getWorldBorder(BukkitVersionHelperSpigot113_2.java:177) ~[?:?]
	at org.dynmap.bukkit.helper.BukkitWorld.getWorldBorder(BukkitWorld.java:245) ~[?:?]
	at org.dynmap.MarkersComponent.addUpdateWorld(MarkersComponent.java:258) ~[?:?]
	at org.dynmap.MarkersComponent.access$000(MarkersComponent.java:23) ~[?:?]
	at org.dynmap.MarkersComponent$1.worldEvent(MarkersComponent.java:67) ~[?:?]
	at org.dynmap.common.DynmapListenerManager.processWorldEvent(DynmapListenerManager.java:71) ~[?:?]
	at org.dynmap.bukkit.DynmapPlugin.doEnable(DynmapPlugin.java:903) ~[?:?]
	at org.dynmap.bukkit.DynmapPlugin.onEnable(DynmapPlugin.java:870) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[minecraft_server.jar:git-Spigot-e6eb36f-d3ed151]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:347) ~[minecraft_server.jar:git-Spigot-e6eb36f-d3ed151]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) ~[minecraft_server.jar:git-Spigot-e6eb36f-d3ed151]
	at org.dynmap.bukkit.DynmapPlugin$BukkitServer.reload(DynmapPlugin.java:231) ~[?:?]
	at org.dynmap.DynmapCore.processCommand(DynmapCore.java:1403) ~[?:?]
	at org.dynmap.bukkit.DynmapPlugin.onCommand(DynmapPlugin.java:962) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[minecraft_server.jar:git-Spigot-e6eb36f-d3ed151]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[minecraft_server.jar:git-Spigot-e6eb36f-d3ed151]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:704) ~[minecraft_server.jar:git-Spigot-e6eb36f-d3ed151]
	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1620) ~[minecraft_server.jar:git-Spigot-e6eb36f-d3ed151]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1460) ~[minecraft_server.jar:git-Spigot-e6eb36f-d3ed151]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[minecraft_server.jar:git-Spigot-e6eb36f-d3ed151]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[minecraft_server.jar:git-Spigot-e6eb36f-d3ed151]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:9) ~[minecraft_server.jar:git-Spigot-e6eb36f-d3ed151]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_201]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_201]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [minecraft_server.jar:git-Spigot-e6eb36f-d3ed151]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896) [minecraft_server.jar:git-Spigot-e6eb36f-d3ed151]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [minecraft_server.jar:git-Spigot-e6eb36f-d3ed151]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [minecraft_server.jar:git-Spigot-e6eb36f-d3ed151]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [minecraft_server.jar:git-Spigot-e6eb36f-d3ed151]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]

**Comment by FedUpWith-Tech** [comment]
Assuming this is fixed in a later release or otherwise no longer relevant- please open a new issue if this persists.
