### ISSUE TITLE
[Dynmap Render Thread/ERROR] DynMap 3.0 Beta 3 SQLException: Connection has already been closed

### ISSUE THREAD

**Issue by ReaperCrewGreen** [webbukkit/dynmap#2462]
## Server Information

- I can reproduce this issue consistently
     - [ x ] In Multiplayer 
     - [ ] After deleting/renaming the DYNMAP folder
- [ x ] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- I have tried the following diagnostics;
     - [ ] Re-rendered missing chunks using /dynmap fullrender
     - [ ] Cleared cached tiles using /dynmap purgeworld [world] (especially if using a map from an older version)
     - [ ] Deleted/Renamed the dynmap folder to regenerate configs and files fresh
     - [ ] Tested using the 'HEAD' version from dynmap.us/builds (these are stable to use)
     - [x ] Rechecked the Minecraft Server and Webserver Config (If using an external Webserver)

## Issue Description
I am getting the error: 
```
[Dynmap Render Thread/ERROR]: [dynmap] Face exists error - Communications link failure
```

I am not 100% sure on this but it seems to only happen after one of the players connects, it has happened a couple times now with the same person.

After that I get the following warning every 4 seconds until I restart the server:
```
[06:26:55] [Timer-4/WARN]: java.sql.SQLException: Connection has already been closed
[06:26:55] [Timer-4/WARN]: 	at com.j256.ormlite.jdbc.JdbcConnectionSource.getReadWriteConnection(JdbcConnectionSource.java:182)
[06:26:55] [Timer-4/WARN]: 	at com.j256.ormlite.dao.BaseDaoImpl.create(BaseDaoImpl.java:326)
[06:26:55] [Timer-4/WARN]: 	at com.j256.ormlite.dao.BaseDaoImpl.createOrUpdate(BaseDaoImpl.java:387)
[06:26:55] [Timer-4/WARN]: 	at nl.zandervdm.stayput.Repositories.PositionRepository.updateLocationForPlayer(PositionRepository.java:45)
[06:26:55] [Timer-4/WARN]: 	at nl.zandervdm.stayput.Main.syncPlayerstoDatabase(Main.java:163)
[06:26:55] [Timer-4/WARN]: 	at nl.zandervdm.stayput.Main$AutoSyncDb.run(Main.java:29)
[06:26:55] [Timer-4/WARN]: 	at java.util.TimerThread.mainLoop(Timer.java:555)
[06:26:55] [Timer-4/WARN]: 	at java.util.TimerThread.run(Timer.java:505)
```

I am going to try removing his face entries from the SQL server and see if that fixes anything. If I find that fixes it I will update this issue.

## Reproduce Steps
1. Since I am not sure how this happened originally I cannot provide a way to reproduce.
2.
...

## Additional Information
I am running paper-588 https://papermc.io/

I am running the list of following plugins:
- armor stand editor 1.13-21
- custom crafting 0.0.9.83
- dynmap 3.0 beta 3
- essentialsX 2.16.1.80
- essentialsXchat 2.16.1.80
- Keep Chunks 1.5.11
- LuckPerms 4.3.73
- MCGUIControl Premium
- MobHeads 2.4
- Multiverse Core 3.0.0
- Multiverse Nether Portals 3.0.0
- MyCommand
- NetworkCore 2.20.9
- OnePlayerSleep
- PlayerVaultsX
- Slime Chunk 1.0.12
- Stayput Reloaded 1.1
- Vault
- WolfyUtilities 0.1.5.0
- worldedit 7.0.0 beta 05

**Comment by ReaperCrewGreen** [comment]
I just looked at the error again and noticed it is an error with Stay Put... my bad.
