### ISSUE TITLE
Support for 1.14.2

### ISSUE THREAD

**Issue by Blueeyestar** [webbukkit/dynmap#2490]
Now the 1.14.2 is out and there is unfortunately already directly a problem..but Mojang knows like it never bores us

[00:28:34] [Server thread/INFO]: [dynmap] inhabitedTicks field not found - inhabited shader not functional
[00:28:34] [Server thread/ERROR]: Error initializing dynmap - bukkit version incompatible! initializing dynmap v3.0-SNAPSHOT-201 (Is it up to date?)
java.lang.IllegalArgumentException: Error initializing dynmap - bukkit version incompatible!
	at org.dynmap.bukkit.helper.BukkitVersionHelperGeneric.<init>(BukkitVersionHelperGeneric.java:159) ~[?:?]
	at org.dynmap.bukkit.helper.BukkitVersionHelperCB.<init>(BukkitVersionHelperCB.java:45) ~[?:?]
	at org.dynmap.bukkit.Helper.getHelper(Helper.java:54) ~[?:?]
	at org.dynmap.bukkit.DynmapPlugin.onLoad(DynmapPlugin.java:785) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.loadPlugins(CraftServer.java:352) [Spigot-latest.jar:git-Spigot-093165d-cb3d14c]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:194) [Spigot-latest.jar:git-Spigot-093165d-cb3d14c]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:761) [Spigot-latest.jar:git-Spigot-093165d-cb3d14c]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]

**___________________________________________________________________________________________________________**

[00:49:29] [Server thread/INFO]: Blueeyestar issued server command: /dynmap
[00:49:29] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'dynmap' in plugin dynmap v3.0-SNAPSHOT-201
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[Spigot-latest.jar:git-Spigot-093165d-cb3d14c]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[Spigot-latest.jar:git-Spigot-093165d-cb3d14c]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:707) ~[Spigot-latest.jar:git-Spigot-093165d-cb3d14c]
	at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1670) ~[Spigot-latest.jar:git-Spigot-093165d-cb3d14c]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1510) ~[Spigot-latest.jar:git-Spigot-093165d-cb3d14c]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[Spigot-latest.jar:git-Spigot-093165d-cb3d14c]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[Spigot-latest.jar:git-Spigot-093165d-cb3d14c]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13) ~[Spigot-latest.jar:git-Spigot-093165d-cb3d14c]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [Spigot-latest.jar:git-Spigot-093165d-cb3d14c]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135) [Spigot-latest.jar:git-Spigot-093165d-cb3d14c]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [Spigot-latest.jar:git-Spigot-093165d-cb3d14c]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114) [Spigot-latest.jar:git-Spigot-093165d-cb3d14c]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:895) [Spigot-latest.jar:git-Spigot-093165d-cb3d14c]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:888) [Spigot-latest.jar:git-Spigot-093165d-cb3d14c]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(SourceFile:99) [Spigot-latest.jar:git-Spigot-093165d-cb3d14c]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:871) [Spigot-latest.jar:git-Spigot-093165d-cb3d14c]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:805) [Spigot-latest.jar:git-Spigot-093165d-cb3d14c]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.NullPointerException
	at org.dynmap.bukkit.DynmapPlugin$BukkitPlayer.<init>(DynmapPlugin.java:582) ~[?:?]
	at org.dynmap.bukkit.DynmapPlugin.onCommand(DynmapPlugin.java:964) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[Spigot-latest.jar:git-Spigot-093165d-cb3d14c]

**Comment by Resi23** [comment]
Same here with Paper 1.14.2 Build 53 

`[15:20:24] [Server thread/ERROR]: [org.bukkit.craftbukkit.v1_14_R1.CraftServer] Error initializing dynmap - bukkit version incompatible! initializing dynmap v3.0-SNAPSHOT-186 (Is it up to date?)
java.lang.IllegalArgumentException: Error initializing dynmap - bukkit version incompatible!
	at org.dynmap.bukkit.helper.BukkitVersionHelperGeneric.<init>(BukkitVersionHelperGeneric.java:159) ~[?:?]
	at org.dynmap.bukkit.helper.BukkitVersionHelperCB.<init>(BukkitVersionHelperCB.java:45) ~[?:?]
	at org.dynmap.bukkit.Helper.getHelper(Helper.java:54) ~[?:?]
	at org.dynmap.bukkit.DynmapPlugin.onLoad(DynmapPlugin.java:785) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.loadPlugins(CraftServer.java:357) ~[patched_1.14.2.jar:git-Paper-53]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:216) ~[patched_1.14.2.jar:git-Paper-53]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:855) ~[patched_1.14.2.jar:git-Paper-53]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]`

**Comment by ReeZey** [comment]
i guess we just have to wait

**Comment by Blueeyestar** [comment]
There is now also a version for the 1.14.2 .

Many thanks for the fast adaptation :)

https://dynmap.us/builds/dynmap/Dynmap-3.0-SNAPSHOT-spigot.jar
