### ISSUE TITLE
worldborder console error

### ISSUE THREAD

**Issue by successed** [webbukkit/dynmap#2493]
[00:21:28 ERROR]: [dynmap] Unable to find method getById for net.minecraft.server.v1_14_R1.Block
[00:21:28 ERROR]: [dynmap] Unable to find method a for net.minecraft.server.v1_14_R1.BiomeBase
[00:21:28 ERROR]: [dynmap] Unable to find field y for net.minecraft.server.v1_14_R1.BiomeBase
[00:21:28 INFO]: [dynmap] Unload queue not found - default to unload all chunks
[00:21:28 INFO]: [dynmap] inhabitedTicks field not found - inhabited shader not functional
[00:21:28 ERROR]: [dynmap] Unable to find method b for net.minecraft.server.v1_14_R1.WorldBorder
[00:21:28 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'plugman' in plugin PlugMan v2.1.6
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.14.2.jar:git-Paper-55]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.14.2.jar:git-Paper-55]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:736) ~[patched_1.14.2.jar:git-Paper-55]
        at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1830) ~[patched_1.14.2.jar:git-Paper-55]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1638) ~[patched_1.14.2.jar:git-Paper-55]
        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.14.2.jar:git-Paper-55]
        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.14.2.jar:git-Paper-55]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:18) ~[patched_1.14.2.jar:git-Paper-55]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.2.jar:git-Paper-55]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:127) ~[patched_1.14.2.jar:git-Paper-55]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.2.jar:git-Paper-55]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:105) ~[patched_1.14.2.jar:git-Paper-55]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:998) ~[patched_1.14.2.jar:git-Paper-55]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:991) ~[patched_1.14.2.jar:git-Paper-55]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:91) ~[patched_1.14.2.jar:git-Paper-55]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:974) ~[patched_1.14.2.jar:git-Paper-55]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:908) ~[patched_1.14.2.jar:git-Paper-55]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.IllegalArgumentException: Error initializing dynmap - bukkit version incompatible!
        at org.dynmap.bukkit.helper.BukkitVersionHelperGeneric.<init>(BukkitVersionHelperGeneric.java:159) ~[?:?]
        at org.dynmap.bukkit.helper.BukkitVersionHelperCB.<init>(BukkitVersionHelperCB.java:45) ~[?:?]
        at org.dynmap.bukkit.Helper.getHelper(Helper.java:46) ~[?:?]
        at org.dynmap.bukkit.DynmapPlugin.onLoad(DynmapPlugin.java:780) ~[?:?]
        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:365) ~[?:?]
        at com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:114) ~[?:?]
        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.14.2.jar:git-Paper-55]
        ... 17 more

i have latest plugin. i have latest paperspigot 1.14.2 version.

**Comment by mikeprimm** [comment]
You're running a build that isn't compatible with 1.14.2:

      Caused by: java.lang.IllegalArgumentException: Error initializing dynmap - bukkit version incompatible!

Try latest development build - https://dynmap.us/builds/dynmap/Dynmap-3.0-SNAPSHOT-spigot.jar
