### ISSUE TITLE
updaten please 1.14.2

### ISSUE THREAD

**Issue by xXjojojXx** [webbukkit/dynmap#2501]
Please update the plugin to the latest version would be happy to receive a positive response.

**Comment by xXjojojXx** [comment]
[12:43:37] [Server thread/INFO]: XXXXJOJOXXXX issued server command: /dynmap reload
[12:43:37] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'dynmap' in plugin dynmap v3.0-beta-3-160
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.14.2.jar:git-Paper-65]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.14.2.jar:git-Paper-65]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:736) ~[patched_1.14.2.jar:git-Paper-65]
	at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1832) ~[patched_1.14.2.jar:git-Paper-65]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1640) ~[patched_1.14.2.jar:git-Paper-65]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.14.2.jar:git-Paper-65]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.14.2.jar:git-Paper-65]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:18) ~[patched_1.14.2.jar:git-Paper-65]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.2.jar:git-Paper-65]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:127) ~[patched_1.14.2.jar:git-Paper-65]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.2.jar:git-Paper-65]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:105) ~[patched_1.14.2.jar:git-Paper-65]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:998) ~[patched_1.14.2.jar:git-Paper-65]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:991) ~[patched_1.14.2.jar:git-Paper-65]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:115) ~[patched_1.14.2.jar:git-Paper-65]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:975) ~[patched_1.14.2.jar:git-Paper-65]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:908) ~[patched_1.14.2.jar:git-Paper-65]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.NullPointerException
	at org.dynmap.bukkit.DynmapPlugin$BukkitPlayer.<init>(DynmapPlugin.java:577) ~[?:?]
	at org.dynmap.bukkit.DynmapPlugin.onCommand(DynmapPlugin.java:957) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.14.2.jar:git-Paper-65]
	... 17 more
****

**Comment by mpdk** [comment]
This one works, but some glitches in the water, but it will run
https://dynmap.us/builds/dynmap/Dynmap-3.0-SNAPSHOT-spigot.jar

**Comment by xXjojojXx** [comment]
thx

**Comment by mikeprimm** [comment]
See https://github.com/webbukkit/dynmap/issues/2469
