### ISSUE TITLE
Cannot load with 1.14.3-pre4

### ISSUE THREAD

**Issue by YourCoalAlt** [webbukkit/dynmap#2525]
Even though this is expected, just wanting to make sure you're aware. :)

> [10:05:44] [Server thread/INFO]: [dynmap] Loading dynmap v3.0-beta-4-213
[10:05:44] [Server thread/INFO]: [dynmap] version=git-Spigot-f16400e-38fa220 (MC: 1.14.3 Pre-Release 4)
[10:05:44] [Server thread/ERROR]: [dynmap] Unable to find method getById for net.minecraft.server.v1_14_R1.Block
[10:05:44] [Server thread/ERROR]: [dynmap] Unable to find method a for net.minecraft.server.v1_14_R1.BiomeBase
[10:05:44] [Server thread/INFO]: [dynmap] Unload queue not found - default to unload all chunks
[10:05:44] [Server thread/INFO]: [dynmap] inhabitedTicks field not found - inhabited shader not functional
[10:05:44] [Server thread/ERROR]: Error initializing dynmap - bukkit version incompatible! initializing dynmap v3.0-beta-4-213 (Is it up to date?)
java.lang.IllegalArgumentException: Error initializing dynmap - bukkit version incompatible!
	at org.dynmap.bukkit.helper.BukkitVersionHelperGeneric.<init>(BukkitVersionHelperGeneric.java:159) ~[?:?]
	at org.dynmap.bukkit.helper.BukkitVersionHelperCB.<init>(BukkitVersionHelperCB.java:45) ~[?:?]
	at org.dynmap.bukkit.Helper.getHelper(Helper.java:54) ~[?:?]
	at org.dynmap.bukkit.DynmapPlugin.onLoad(DynmapPlugin.java:791) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.loadPlugins(CraftServer.java:352) [spigot-1.14.3-pre4-SNAPSHOT.jar:git-Spigot-f16400e-38fa220]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:194) [spigot-1.14.3-pre4-SNAPSHOT.jar:git-Spigot-f16400e-38fa220]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:760) [spigot-1.14.3-pre4-SNAPSHOT.jar:git-Spigot-f16400e-38fa220]
	at java.lang.Thread.run(Thread.java:825) [?:?]

**Comment by Blueeyestar** [comment]
[14:48:45] [Server thread/INFO]: [dynmap] Loading dynmap v3.0-SNAPSHOT-215
[14:48:45] [Server thread/INFO]: [dynmap] version=git-Spigot-f16400e-8a3d3f4 (MC: 1.14.3 Pre-Release 4)
[14:48:45] [Server thread/ERROR]: [dynmap] Unable to find method getById for net.minecraft.server.v1_14_R1.Block
[14:48:45] [Server thread/ERROR]: [dynmap] Unable to find method a for net.minecraft.server.v1_14_R1.BiomeBase
[14:48:45] [Server thread/INFO]: [dynmap] Unload queue not found - default to unload all chunks
[14:48:45] [Server thread/INFO]: [dynmap] inhabitedTicks field not found - inhabited shader not functional
[14:48:45] [Server thread/ERROR]: Error initializing dynmap - bukkit version incompatible! initializing dynmap v3.0-SNAPSHOT-215 (Is it up to date?)
java.lang.IllegalArgumentException: Error initializing dynmap - bukkit version incompatible!
	at org.dynmap.bukkit.helper.BukkitVersionHelperGeneric.<init>(BukkitVersionHelperGeneric.java:159) ~[?:?]
	at org.dynmap.bukkit.helper.BukkitVersionHelperCB.<init>(BukkitVersionHelperCB.java:45) ~[?:?]
	at org.dynmap.bukkit.Helper.getHelper(Helper.java:54) ~[?:?]
	at org.dynmap.bukkit.DynmapPlugin.onLoad(DynmapPlugin.java:791) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.loadPlugins(CraftServer.java:352) [minecraft_server.jar:git-Spigot-f16400e-8a3d3f4]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:194) [minecraft_server.jar:git-Spigot-f16400e-8a3d3f4]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:760) [minecraft_server.jar:git-Spigot-f16400e-8a3d3f4]

**Comment by DefinePvP** [comment]
Works fine on release 1.14.3.  The pre-release in the version number must have made the plugin not able to identify what version it was running on, or something like that.

**Comment by YourCoalAlt** [comment]
Seems so.

**Comment by M1904** [comment]
which dynmap-version works with 1.14.3?
I've got: Error initializing dynmap - bukkit version incompatible! initializing dynmap v3.0-SNAPSHOT-202 (Is it up to date?)
