### ISSUE TITLE
Chisel blocks missing (1.12.2)

### ISSUE THREAD

**Issue by ghost** [webbukkit/dynmap#2534]
I use the latest Chisel version, and latest Dynmap Forge version.

How can I solve this ? Chisel blocks are missings :/

**Comment by ghost** [comment]
Anyone ? I tried with the latest "Beta" build, and same for Chisel...

**Comment by ghost** [comment]
They told me to see with u...

**Comment by lhns** [comment]
Hi! Maybe this will help you:
[https://github.com/webbukkit/DynmapBlockScan/pull/40](https://github.com/webbukkit/DynmapBlockScan/pull/40)

It doesn't work with all chisel blocks but with most of them.

**Comment by ghost** [comment]
It looks great ! But I don't understand, how can I obtain the .jar of this version of DynmapBlockScan ?

**Comment by lhns** [comment]
I've compiled a snapshot version for testing purposes:
https://github.com/LolHens/DynmapBlockScan/releases/tag/universal-renderer

**Comment by ghost** [comment]
Hmmmmm... it crashs at startup ?

https://www.hastebin.com/kadokolone.rb

**Comment by ghost** [comment]
Maybe u can just send me the .txt files to put in _/minecraft/dynmap/renderdata/_ ?

**Comment by lhns** [comment]
Here are the model files that I generated:
https://github.com/LolHens/DynmapBlockScan/releases/download/universal-renderer/example-renderdata.zip

Did you maybe install the DynmapBlockScan mod on the server?
Note that this mod can only run on the client and the exported files have to be copied to the server manually.

**Comment by ghost** [comment]
It works with the .txt files ! Thank's ! But as u said, some blocs are missing... can u explain me how can I add them ? Is it easy ?

**Comment by lhns** [comment]
I haven't yet debugged why this happens. But the wiki on this repo has some information how to write block models manually.

**Comment by ghost** [comment]
Okay, I will check that :)

Thank's once again.

**Comment by Pokihead** [comment]
Hey i have the same issue, but with your renderdata it works. But how did you get them? If i use DynmapBlockScan on client it will crash everytime i load a world and if i have it on a server it works but some mods like chisel don't work. 
I although noticed that some of my renderdata .txt are much smaller then yours so i think that there are although many textures missing

**Comment by lhns** [comment]
I don't want to hijack this repo too much for my experimental stuff but here are two possible errors:

You installed the mod on the server (it only works on the client):
```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from DynmapBlockScan (dynmapblockscan)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
```

You also have to install dynmap in addition to DynmapBlockScan on the client:
```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from DynmapBlockScan (dynmapblockscan)
Caused by: java.lang.NoClassDefFoundError: org/dynmap/modsupport/BlockSide
```

The model files should appear in dynmap\renderdata\modsupport in the client install directory.
They then have to be copied into dynmap\renderdata\custom on the server.

Hope this helps.

**Comment by ghost** [comment]
rip

**Comment by Pokihead** [comment]
ok i had not installed dynmap on client, but with dynmap iam getting another error while loading a world.

Time: 7/21/19 2:26 PM
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from DynmapBlockScan (dynmapblockscan)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at org.dynmap.blockscan.DynmapBlockScanPlugin$ModDynmapRec.registerTexture(DynmapBlockScanPlugin.java:710)
	at org.dynmap.blockscan.DynmapBlockScanPlugin.quads(DynmapBlockScanPlugin.java:403)
	at org.dynmap.blockscan.DynmapBlockScanPlugin.extractModelsFromRendererDispatcher(DynmapBlockScanPlugin.java:454)
	at org.dynmap.blockscan.DynmapBlockScanPlugin.serverStarting(DynmapBlockScanPlugin.java:461)
	at org.dynmap.blockscan.DynmapBlockScanMod.serverStarting(DynmapBlockScanMod.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.serverStarting(Loader.java:792)
	at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStarting(FMLCommonHandler.java:297)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.optifine.reflect.Reflector.callBoolean(Reflector.java:848)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:217)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Unknown Source)

**Comment by lhns** [comment]
Okay try this release. Now the whole game doesn't crash anymore if it encounters an exception on only one BlockState. It should just skip the failed BlockStates.
https://github.com/LolHens/DynmapBlockScan/releases/tag/universal-renderer-test2

You probably had one or more mods installed that do some funky things with textures.

**Comment by Pokihead** [comment]
Sorry for the late answer. This Version seems to be working. Which means it does^^ I'll test the new files now on my server but it looks very good. 118 Files with 178Mb size xD

**Comment by lhns** [comment]
Nice! Yes the files are indeed very unoptimized. XD

**Comment by Pokihead** [comment]
So i testet a lot of blocks now and yes it renders a few more then the "normal"dynmapblockscan, but there are many mods where only a few blocks are rendered. One example is decomegapack where the txt is about 48mb but not a single block is rendered^^ 
enderio doesnt work and the badest thing for me is that the oil spring from buildcraft are invisible, because they are normaly in the world and it looks very strange when there is nothing where they should be.
Dont know why they arent working because in 1.7.10 and dynmap they are working 

P.S. 
I think that all blocks which havent a normal form arent working, the only thing i dont get is why they were working in 1.7.10?

**Comment by lhns** [comment]
I have made a slight optimization in that the same block and metadata doesn't get generated multiple times anymore. This greatly reduces the size of the model files as you can see from the example renderdata package.
https://github.com/LolHens/DynmapBlockScan/releases/tag/universal-renderer-test3

At the moment I don't have the time to debug more mods but I'll let you know if I make some progress.

**Comment by Pokihead** [comment]
Ok sounds nice i'll test you're new file and report if everything is working like before :)

**Comment by Pokihead** [comment]
So I testet a little bit and the results are:
1. the new file works
2. the datas are much smaller
3. some textures dont work with the new files which worked before, like nearly all leaves and flowers/grass from Biomes o Plenty and maybe some other mods I didnt checked all mods

**Comment by ghost** [comment]
Can u upload ur files ? I tested the universal-render-test3 but still crash... :S

**Comment by Pokihead** [comment]
Sure I upload all my files so you can choose which you want to use.
It's a .rar file and in this is the folder custom which have to go into /dynmap/renderdata
Here is the link (will be available till Monday)
https://1drv.ms/u/s!AnIwGpIuCXMPkaVDjsExc0avXYHrYA?e=vjvUYL

**Comment by 82280zx** [comment]
So this works when I do it localy, but I try what you said here

The model files should appear in dynmap\renderdata\modsupport in the client install directory.
They then have to be copied into dynmap\renderdata\custom on the server.

And I still show missing textures? But yet it works when it's not on the server?

**Comment by sidboy55555** [comment]
Hi,
Does someone still have the model files which where generated by @LolHens ?
Since his mod doesn't work for me, gives a alot of errors, probably because I use the latest version of dynmap.
