### ISSUE TITLE
Task for dynmap generated an exception - java.util.ConcurrentModificationException: null 	

### ISSUE THREAD

**Issue by mibby** [webbukkit/dynmap#2549]
Paper dev 134 (Spigot 1.14.3)
Dynmap v3.0 dev 215

```
[09:08:23] [Server thread/WARN]: [dynmap] Task #441707 for dynmap v3.0-SNAPSHOT-215 generated an exception
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445) ~[?:1.8.0_212]
	at java.util.HashMap$ValueIterator.next(HashMap.java:1474) ~[?:1.8.0_212]
	at java.util.AbstractCollection.addAll(AbstractCollection.java:343) ~[?:1.8.0_212]
	at java.util.HashSet.<init>(HashSet.java:120) ~[?:1.8.0_212]
	at org.dynmap.markers.impl.MarkerSetImpl.getAreaMarkers(MarkerSetImpl.java:93) ~[?:?]
	at org.dynmap.markers.impl.MarkerAPIImpl.writeMarkersFile(MarkerAPIImpl.java:3015) ~[?:?]
	at org.dynmap.markers.impl.MarkerAPIImpl.access$500(MarkerAPIImpl.java:54) ~[?:?]
	at org.dynmap.markers.impl.MarkerAPIImpl$DoFileWrites.run(MarkerAPIImpl.java:351) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.3.jar:git-Paper-134]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.3.jar:git-Paper-134]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1132) ~[patched_1.14.3.jar:git-Paper-134]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:420) ~[patched_1.14.3.jar:git-Paper-134]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1064) ~[patched_1.14.3.jar:git-Paper-134]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:908) ~[patched_1.14.3.jar:git-Paper-134]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**Comment by mikeprimm** [comment]
Fix coded - will be in latest dev build: https://dynmap.us/builds/dynmap/Dynmap-3.0-SNAPSHOT-spigot.jar
