### ISSUE TITLE
API Breakage with 3.0 Beta X?

### ISSUE THREAD

**Issue by Kainzo** [webbukkit/dynmap#2559]
It seems that the API is broken with the latest beta... was this intended?

`````
[02:30:49] [Server thread/ERROR]: Error occurred while enabling FearTheReaper v1.0.4-b28 (Is it up to date?)
java.lang.NoClassDefFoundError: org/dynmap/DynmapAPI
	at com.herocraftonline.fearthereaper.FearTheReaper.onEnable(FearTheReaper.java:63) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-reborn-prod.jar:git-Paper-1613]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) ~[paper-reborn-prod.jar:git-Paper-1613]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[paper-reborn-prod.jar:git-Paper-1613]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) ~[paper-reborn-prod.jar:git-Paper-1613]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) ~[paper-reborn-prod.jar:git-Paper-1613]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) ~[paper-reborn-prod.jar:git-Paper-1613]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) ~[paper-reborn-prod.jar:git-Paper-1613]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) ~[paper-reborn-prod.jar:git-Paper-1613]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289) ~[paper-reborn-prod.jar:git-Paper-1613]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[paper-reborn-prod.jar:git-Paper-1613]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.ClassNotFoundException: org.dynmap.DynmapAPI
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_151]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:156) ~[paper-reborn-prod.jar:git-Paper-1613]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[paper-reborn-prod.jar:git-Paper-1613]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_151]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_151]
	... 12 more
```

**Comment by FedUpWith-Tech** [comment]
Assuming this is fixed in a later release or otherwise no longer relevant- please open a new issue if this persists.
