### ISSUE TITLE
Invalid plugin.yml file - Spigot 1.14.4

### ISSUE THREAD

**Issue by jakubwilk** [webbukkit/dynmap#2597]
Hi, I have DynMap v3.0-beta-5 and after upload file on server and start it, in my console I see these errors:
`[22:36:32] [Server thread/ERROR]: Could not load 'plugins/Dynmap-3.0-beta-5-spigot.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:168) ~[mc.jar:git-Spigot-798ea6a-2012f1e]
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:138) [mc.jar:git-Spigot-798ea6a-2012f1e]
at org.bukkit.craftbukkit.v1_14_R1.CraftServer.loadPlugins(CraftServer.java:350) [mc.jar:git-Spigot-798ea6a-2012f1e]
at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:202) [mc.jar:git-Spigot-798ea6a-2012f1e]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:775) [mc.jar:git-Spigot-798ea6a-2012f1e]
at java.lang.Thread.run(Thread.java:835) [?:?]
Caused by: java.util.zip.ZipException: zip file is empty
at java.util.zip.ZipFile$Source.zerror(ZipFile.java:1470) ~[?:?]
at java.util.zip.ZipFile$Source.findEND(ZipFile.java:1284) ~[?:?]
at java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1378) ~[?:?]
at java.util.zip.ZipFile$Source.<init>(ZipFile.java:1209) ~[?:?]
at java.util.zip.ZipFile$Source.get(ZipFile.java:1172) ~[?:?]
at java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:719) ~[?:?]
at java.util.zip.ZipFile.<init>(ZipFile.java:239) ~[?:?]
at java.util.zip.ZipFile.<init>(ZipFile.java:169) ~[?:?]
at java.util.jar.JarFile.<init>(JarFile.java:346) ~[?:?]
at java.util.jar.JarFile.<init>(JarFile.java:317) ~[?:?]
at java.util.jar.JarFile.<init>(JarFile.java:283) ~[?:?]
at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:156) ~[mc.jar:git-Spigot-798ea6a-2012f1e]`

**Comment by FedUpWith-Tech** [comment]
This is fixed in a later release- please open a new issue if this persists.
