### ISSUE TITLE
Error loading maptype

### ISSUE THREAD

**Issue by misaka00251** [webbukkit/dynmap#2601]
```
[21:13:25] [Server thread/INFO]: [dynmap] Enabling dynmap v3.0-beta-5-218
[21:13:26] [Server thread/INFO]: [dynmap] Using LuckPerms 4.4.1 for access control
[21:13:26] [Server thread/INFO]: [dynmap] Mod Support processing completed
[21:13:26] [Server thread/INFO]: [dynmap] Loaded 25 shaders.
[21:13:26] [Server thread/INFO]: [dynmap] Loaded 82 perspectives.
[21:13:26] [Server thread/INFO]: [dynmap] Loaded 14 lightings.
[21:13:26] [Server thread/ERROR]: [dynmap] Error loading maptype
java.lang.NullPointerException: null
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_221]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_221]
        at org.dynmap.ConfigurationNode.createInstance(ConfigurationNode.java:317) [Dynmap-3.0-beta-5-spigot.jar:?]
        at org.dynmap.ConfigurationNode.createInstances(ConfigurationNode.java:342) [Dynmap-3.0-beta-5-spigot.jar:?]
        at org.dynmap.DynmapCore.enableCore(DynmapCore.java:526) [Dynmap-3.0-beta-5-spigot.jar:?]
        at org.dynmap.bukkit.DynmapPlugin.doEnable(DynmapPlugin.java:909) [Dynmap-3.0-beta-5-spigot.jar:?]
        at org.dynmap.bukkit.DynmapPlugin.onEnable(DynmapPlugin.java:889) [Dynmap-3.0-beta-5-spigot.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) [spigot-1.14.4.jar:git-Spigot-798ea6a-44d675a]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [spigot-1.14.4.jar:git-Spigot-798ea6a-44d675a]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417) [spigot-1.14.4.jar:git-Spigot-798ea6a-44d675a]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:461) [spigot-1.14.4.jar:git-Spigot-798ea6a-44d675a]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:375) [spigot-1.14.4.jar:git-Spigot-798ea6a-44d675a]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:449) [spigot-1.14.4.jar:git-Spigot-798ea6a-44d675a]
        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:266) [spigot-1.14.4.jar:git-Spigot-798ea6a-44d675a]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:775) [spigot-1.14.4.jar:git-Spigot-798ea6a-44d675a]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
[21:13:26] [Server thread/WARN]: java.lang.NullPointerException
[21:13:26] [Server thread/WARN]:        at java.lang.Class.forName0(Native Method)
[21:13:26] [Server thread/WARN]:        at java.lang.Class.forName(Unknown Source)
[21:13:26] [Server thread/WARN]:        at org.dynmap.ConfigurationNode.createInstance(ConfigurationNode.java:317)
[21:13:26] [Server thread/WARN]:        at org.dynmap.ConfigurationNode.createInstances(ConfigurationNode.java:342)
[21:13:26] [Server thread/WARN]:        at org.dynmap.DynmapCore.enableCore(DynmapCore.java:526)
[21:13:26] [Server thread/WARN]:        at org.dynmap.bukkit.DynmapPlugin.doEnable(DynmapPlugin.java:909)
[21:13:26] [Server thread/WARN]:        at org.dynmap.bukkit.DynmapPlugin.onEnable(DynmapPlugin.java:889)
[21:13:26] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[21:13:26] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352)
[21:13:26] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417)
[21:13:26] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:461)
[21:13:26] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:375)
[21:13:26] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:449)
[21:13:26] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:266)
[21:13:26] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:775)
[21:13:26] [Server thread/WARN]:        at java.lang.Thread.run(Unknown Source)
[21:13:26] [Server thread/INFO]: [dynmap] Web server started on address 192.168.88.10:800
[21:13:26] [Server thread/INFO]: [dynmap] version 3.0-beta-5-218 is enabled - core version 3.0-beta-5-218
[21:13:26] [Server thread/INFO]: [dynmap] For support, visit https://forums.dynmap.us
[21:13:26] [Server thread/INFO]: [dynmap] To report or track bugs, visit https://github.com/webbukkit/dynmap/issues
[21:13:26] [Server thread/INFO]: [dynmap] Loaded 3 maps of world 'world'.
[21:13:26] [Server thread/INFO]: [dynmap] Loaded 2 maps of world 'world_nether'.
[21:13:26] [Server thread/INFO]: [dynmap] Loaded 2 maps of world 'world_the_end'.
[21:13:26] [Server thread/INFO]: [dynmap] Enabled
```

Using nginx on Windows.
Version: 3.0-beta-5-218

**Comment by FedUpWith-Tech** [comment]
Assuming this is fixed in a later release or otherwise no longer relevant- please open a new issue if this persists.
