### ISSUE TITLE
Fatal Exception ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by Remadon** [webbukkit/dynmap#2621]
SpongeForge 1.12.2-2838-7.1.7-RC3924
DynmapCore 3.0-beta5 forge
Dynmap 3.0-beta5
DynmapBlockScan 3.0-Snapshot
Forge 1.12.2-14.23.5.2838

Mapper reaches a specific chunk in the overworld and dies a horrible fate. We've mapped out other dimensions (Twilight Forest, Nether) without trouble. I see a common theme in here is that map corruption can cause this. If that's the consensus from reading these errors is there anything I can do to try to fix it? (Deleting the chunks in question and Regen them with world edit perhaps?)

```
[18:46:23] [Dynmap Render Thread/INFO] [Dynmap]: [Dynmap] Loading resource pack standard
[18:46:26] [Dynmap Render Thread/FATAL] [Dynmap]: [Dynmap] Exception during render job: world=Valitora, map=org.dynmap.hdmap.HDMap@6e65dbd4
[18:46:26] [Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$2:run:212]: java.lang.ArrayIndexOutOfBoundsException: 65535
[18:46:26] [Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$2:run:212]:   at org.dynmap.forge_1_12_2.ChunkSnapshot.<init>(ChunkSnapshot.java:228)
[18:46:26] [Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$2:run:212]:   at org.dynmap.forge_1_12_2.ForgeMapChunkCache.prepChunkSnapshot(ForgeMapChunkCache.java:1241)
[18:46:26] [Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$2:run:212]:   at org.dynmap.forge_1_12_2.ForgeMapChunkCache.readChunks(ForgeMapChunkCache.java:1407)
[18:46:26] [Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$2:run:212]:   at org.dynmap.forge_1_12_2.DynmapPlugin$ForgeServer.createMapChunkCache(DynmapPlugin.java:887)
[18:46:26] [Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$2:run:212]:   at org.dynmap.MapManager$FullWorldRenderState.processTile(MapManager.java:685)
[18:46:26] [Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$2:run:212]:   at org.dynmap.MapManager$FullWorldRenderState.run(MapManager.java:644)
[18:46:26] [Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$2:run:212]:   at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$2.run(MapManager.java:209)
[18:46:26] [Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$2:run:212]:   at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[18:46:26] [Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$2:run:212]:   at java.util.concurrent.FutureTask.run(Unknown Source)
[18:46:26] [Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$2:run:212]:   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
[18:46:26] [Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$2:run:212]:   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
[18:46:26] [Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$2:run:212]:   at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[18:46:26] [Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$2:run:212]:   at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[18:46:26] [Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$2:run:212]:   at java.lang.Thread.run(Unknown Source)
[18:48:50] [Dynmap Render Thread/FATAL] [Dynmap]: [Dynmap] Exception during render job: world=Valitora, map=null
[18:48:50] [Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]: java.lang.ArrayIndexOutOfBoundsException: 65535
[18:48:50] [Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]:   at org.dynmap.forge_1_12_2.ChunkSnapshot.<init>(ChunkSnapshot.java:228)
[18:48:50] [Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]:   at org.dynmap.forge_1_12_2.ForgeMapChunkCache.prepChunkSnapshot(ForgeMapChunkCache.java:1241)
[18:48:50] [Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]:   at org.dynmap.forge_1_12_2.ForgeMapChunkCache.readChunks(ForgeMapChunkCache.java:1407)
[18:48:50] [Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]:   at org.dynmap.forge_1_12_2.DynmapPlugin$ForgeServer.createMapChunkCache(DynmapPlugin.java:887)
[18:48:50] [Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]:   at org.dynmap.MapManager$FullWorldRenderState.processTile(MapManager.java:685)
[18:48:50] [Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]:   at org.dynmap.MapManager$FullWorldRenderState.run(MapManager.java:644)
[18:48:50] [Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]:   at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1.run(MapManager.java:193)
[18:48:50] [Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]:   at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$2.run(MapManager.java:209)
[18:48:50] [Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]:   at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[18:48:50] [Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]:   at java.util.concurrent.FutureTask.run(Unknown Source)
[18:48:50] [Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]:   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
[18:48:50] [Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]:   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
[18:48:50] [Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]:   at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[18:48:50] [Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]:   at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[18:48:50] [Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]:   at java.lang.Thread.run(Unknown Source)
[18:51:13] [Dynmap Render Thread/FATAL] [Dynmap]: [Dynmap] Exception during render job: world=Valitora, map=null
[18:51:13] [Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]: java.lang.ArrayIndexOutOfBoundsException
```

**Comment by Remadon** [comment]
Hi,

I may have opened this prematurely. I traveled to the place in the map having trouble and was able to map it by using /dynmap radiusrender after a cancelrender and purgequeue.

Thank you!
