### ISSUE TITLE
Exception while fetching chunks, search did not help

### ISSUE THREAD

**Issue by Aquariomel** [webbukkit/dynmap#2658]
Hello, I use: 
server version: git-Spigot-56f8471-7554e08 (MC: 1.14.4)
dynmap version: core=3.0-beta-5-218, plugin=3.0-beta-5-218

I have here is such a mistake:
```
[dynmap] Exception while fetching chunks: 
net.minecraft.server.v1_14_R1.ReportedException: Loading NBT data
	at net.minecraft.server.v1_14_R1.NBTTagCompound.a(SourceFile:444) ~[minecraft_server.jar:git-Spigot-56f8471-7554e08]
	at net.minecraft.server.v1_14_R1.NBTTagCompound.load(SourceFile:81) ~[minecraft_server.jar:git-Spigot-56f8471-7554e08]
	at net.minecraft.server.v1_14_R1.NBTTagList.load(SourceFile:65) ~[minecraft_server.jar:git-Spigot-56f8471-7554e08]
	at net.minecraft.server.v1_14_R1.NBTTagCompound.a(SourceFile:438) ~[minecraft_server.jar:git-Spigot-56f8471-7554e08]
	at net.minecraft.server.v1_14_R1.NBTTagCompound.load(SourceFile:81) ~[minecraft_server.jar:git-Spigot-56f8471-7554e08]
	at net.minecraft.server.v1_14_R1.NBTTagCompound.a(SourceFile:438) ~[minecraft_server.jar:git-Spigot-56f8471-7554e08]
	at net.minecraft.server.v1_14_R1.NBTTagCompound.load(SourceFile:81) ~[minecraft_server.jar:git-Spigot-56f8471-7554e08]
	at net.minecraft.server.v1_14_R1.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:114) ~[minecraft_server.jar:git-Spigot-56f8471-7554e08]
	at net.minecraft.server.v1_14_R1.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:83) ~[minecraft_server.jar:git-Spigot-56f8471-7554e08]
	at net.minecraft.server.v1_14_R1.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:73) ~[minecraft_server.jar:git-Spigot-56f8471-7554e08]
	at net.minecraft.server.v1_14_R1.RegionFileCache.read(RegionFileCache.java:55) ~[minecraft_server.jar:git-Spigot-56f8471-7554e08]
	at org.dynmap.bukkit.helper.v114_1.MapChunkCache114_1.loadChunkNBT(MapChunkCache114_1.java:316) ~[?:?]
	at org.dynmap.bukkit.helper.v114_1.MapChunkCache114_1.loadChunks(MapChunkCache114_1.java:407) ~[?:?]
	at org.dynmap.bukkit.DynmapPlugin$BukkitServer$6.call(DynmapPlugin.java:469) ~[?:?]
	at org.dynmap.bukkit.DynmapPlugin$BukkitServer$6.call(DynmapPlugin.java:456) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftFuture.run(CraftFuture.java:88) ~[minecraft_server.jar:git-Spigot-56f8471-7554e08]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) ~[minecraft_server.jar:git-Spigot-56f8471-7554e08]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1022) ~[minecraft_server.jar:git-Spigot-56f8471-7554e08]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:393) ~[minecraft_server.jar:git-Spigot-56f8471-7554e08]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:970) ~[minecraft_server.jar:git-Spigot-56f8471-7554e08]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:815) ~[minecraft_server.jar:git-Spigot-56f8471-7554e08]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_221]
Caused by: java.util.zip.ZipException: invalid distance too far back
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:164) ~[?:1.8.0_221]
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246) ~[?:1.8.0_221]
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286) ~[?:1.8.0_221]
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345) ~[?:1.8.0_221]
	at java.io.DataInputStream.readFully(DataInputStream.java:195) ~[?:1.8.0_221]
	at java.io.DataInputStream.readLong(DataInputStream.java:416) ~[?:1.8.0_221]
	at net.minecraft.server.v1_14_R1.NBTTagLongArray.load(SourceFile:66) ~[minecraft_server.jar:git-Spigot-56f8471-7554e08]
	at net.minecraft.server.v1_14_R1.NBTTagCompound.a(SourceFile:438) ~[minecraft_server.jar:git-Spigot-56f8471-7554e08]
	... 21 more
```

Because of what it can appear and how to fix it?

I do not really know your language, thanks to a friend translator :з

**Comment by baconwaifu** [comment]
The minecraft world file appears to be damaged. That exception is caused by attempting to read a chunk with an invalid format, and is not related to dynmap; the base game itself would throw the same exception if it tried to read that chunk.

**Comment by Aquariomel** [comment]
Can be as something turn auto mending? To skip this section, as for example "overviewer" downloaded the same map completely and without errors.
