### ISSUE TITLE
Incompatibility with LuckPerms v5 API

### ISSUE THREAD

**Issue by mibby** [webbukkit/dynmap#2665]
dynmap beta-6-220
LuckPerms 5.0.3 dev 925

```
[02:01:30] [Server thread/INFO]: [dynmap] Enabling dynmap v3.0-beta-6-220*
[02:01:30] [Server thread/ERROR]: Error occurred while enabling dynmap v3.0-beta-6-220 (Is it up to date?)
java.lang.NoClassDefFoundError: me/lucko/luckperms/api/LuckPermsApi
	at org.dynmap.bukkit.permissions.LuckPermsPermissions.create(LuckPermsPermissions.java:26) ~[?:?]
	at org.dynmap.bukkit.DynmapPlugin.onEnable(DynmapPlugin.java:848) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[paperclip.jar:git-Purpur-322]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[paperclip.jar:git-Purpur-322]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[paperclip.jar:git-Purpur-322]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467) ~[paperclip.jar:git-Purpur-322]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381) ~[paperclip.jar:git-Purpur-322]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:475) ~[paperclip.jar:git-Purpur-322]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:299) ~[paperclip.jar:git-Purpur-322]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:878) ~[paperclip.jar:git-Purpur-322]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
Caused by: java.lang.ClassNotFoundException: me.lucko.luckperms.api.LuckPermsApi
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_232]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:139) ~[paperclip.jar:git-Purpur-322]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:85) ~[paperclip.jar:git-Purpur-322]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_232]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_232]
	... 11 more
[02:01:30] [Server thread/INFO]: [dynmap] Disabling dynmap v3.0-beta-6-220
[02:01:30] [Server thread/ERROR]: Error occurred while disabling dynmap v3.0-beta-6-220 (Is it up to date?)
java.lang.NullPointerException: null
	at org.dynmap.bukkit.DynmapPlugin.onDisable(DynmapPlugin.java:946) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[paperclip.jar:git-Purpur-322]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:373) ~[paperclip.jar:git-Purpur-322]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:453) ~[paperclip.jar:git-Purpur-322]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[paperclip.jar:git-Purpur-322]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[paperclip.jar:git-Purpur-322]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467) ~[paperclip.jar:git-Purpur-322]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381) ~[paperclip.jar:git-Purpur-322]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:475) ~[paperclip.jar:git-Purpur-322]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:299) ~[paperclip.jar:git-Purpur-322]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:878) ~[paperclip.jar:git-Purpur-322]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
```

**Comment by christianbryant** [comment]
Ran into this problem as well! Would love for an update

**Comment by ZandercraftGames** [comment]
Seeing this issue as well.

**Comment by lwd-adam** [comment]
Choosing between Luckperms and Dynmap is really hard... I chose Dynmap for now.

**Comment by AnttiMK** [comment]
For everyone having this problem, a temporary fix is to download and install the legacy API extension for LuckPerms. Instructions [here.](https://github.com/lucko/LuckPerms/wiki/Upgrading-from-v4-to-v5#api-compatibility)

**Comment by rmalca** [comment]
@Kopo942 thanks! you saved my life :)
