### ISSUE TITLE
Brand new install wont work with luckperms

### ISSUE THREAD

**Issue by johncsuti** [webbukkit/dynmap#2675]
NEED AN UPDATE TO THE NEW API FOR LUCKPERMS
[10:07:30] [Server thread/ERROR]: Error occurred while enabling dynmap v3.0-beta-5-218 (Is it up to date?)
java.lang.NoClassDefFoundError: me/lucko/luckperms/api/LuckPermsApi
        at org.dynmap.bukkit.permissions.LuckPermsPermissions.create(LuckPermsPermissions.java:26) ~[?:?]
        at org.dynmap.bukkit.DynmapPlugin.onEnable(DynmapPlugin.java:848) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.14.4.jar:git-Paper-233]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.14.4.jar:git-Paper-233]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.14.4.jar:git-Paper-233]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467) ~[patched_1.14.4.jar:git-Paper-233]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381) ~[patched_1.14.4.jar:git-Paper-233]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474) ~[patched_1.14.4.jar:git-Paper-233]
        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:290) ~[patched_1.14.4.jar:git-Paper-233]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:876) ~[patched_1.14.4.jar:git-Paper-233]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
Caused by: java.lang.ClassNotFoundException: me.lucko.luckperms.api.LuckPermsApi
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_222]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:139) ~[patched_1.14.4.jar:git-Paper-233]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:85) ~[patched_1.14.4.jar:git-Paper-233]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_222]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_222]
        ... 11 more

**Comment by Tsoccerguy3** [comment]
Dynmap is not fully updated to work with 1.14.x you need to stay on the 4.x dev branch of LP

**Comment by johncsuti** [comment]
no turns out luck perms has an extension to fix this kind of issue its the extension legacy API that will allow the old calls till developers can fully update this should be a feature request for it to be updated to the new API

**Comment by Tsoccerguy3** [comment]
installing the legacy api is the same as being on 4.x dev and i dont see to many pulls happening here . so you could clone the dynmap repo and pull the relevant updates and compile your self . The LP ver 5 branch is for moving forward to 1.14.x , 1.15.x , but the lp 4.x is ok with beta 6 , it works
