### ISSUE TITLE
Render Trigger Log Spam

### ISSUE THREAD

**Issue by Remanent** [webbukkit/dynmap#2698]
Since the publishing of Spigot 1.15, and using Dynmap-3.0-beta-7-spigot.jar (build 241) and using Dynmap-3.0-SNAPSHOT-spigot.jar (build 243) i've seen these two errors spamming my chatlog a bunch.  i use the following rendertriggers.. these did occur while a fullrender was running, but i don't believe that has anything to do with the errors.  this is a world that was made in 1.14.4, and then --forceUpgrade 'd to 1.15.
```
render-triggers:
  - blockbreak
  - blockburn
  - blockfaded
  - blockformed
  - blockfromto
  - blockgrow
  - blockphysics
  - blockplaced
  #- blockredstone
  - blockspread
  - chunkgenerated
  - explosion
  - leavesdecay
  - pistonmoved
  - playerjoin
  #- playermove
  - structuregrow
```
I'm going to go onto the server, and try to see if i can make every one of these render triggers occur to force an update, and see if i get an error in the log file.

### Render Trigger - blockphysics (i think)
```
[00:10:39] [Server thread/ERROR]: Could not pass event BlockPhysicsEvent to dynmap v3.0-beta-7-241
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at net.minecraft.server.v1_15_R1.World.a(World.java:450) ~[spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at net.minecraft.server.v1_15_R1.World.applyPhysics(World.java:411) ~[spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at net.minecraft.server.v1_15_R1.World.update(World.java:398) ~[spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at net.minecraft.server.v1_15_R1.World.notifyAndUpdatePhysics(World.java:325) ~[spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at net.minecraft.server.v1_15_R1.World.setTypeAndData(World.java:297) ~[spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at net.minecraft.server.v1_15_R1.World.a(World.java:361) ~[spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at net.minecraft.server.v1_15_R1.BlockFire.a(BlockFire.java:233) ~[spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at net.minecraft.server.v1_15_R1.BlockFire.tick(BlockFire.java:148) ~[spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at net.minecraft.server.v1_15_R1.IBlockData.a(SourceFile:263) ~[spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at net.minecraft.server.v1_15_R1.WorldServer.b(WorldServer.java:590) ~[spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at net.minecraft.server.v1_15_R1.TickListServer.b(TickListServer.java:82) [spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:303) [spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1076) [spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:393) [spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:978) [spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:823) [spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
Caused by: java.lang.NoSuchMethodError: org.bukkit.block.Block.getTypeId()I
	at org.dynmap.bukkit.DynmapPlugin.checkBlock(DynmapPlugin.java:1179) ~[?:?]
	at org.dynmap.bukkit.DynmapPlugin.access$2900(DynmapPlugin.java:107) ~[?:?]
	at org.dynmap.bukkit.DynmapPlugin$8.onBlockPhysics(DynmapPlugin.java:1291) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	... 20 more
```

### Render Trigger - blockfromto
```
[00:10:41] [Server thread/ERROR]: Could not pass event BlockFromToEvent to dynmap v3.0-beta-7-241
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at net.minecraft.server.v1_15_R1.FluidTypeFlowing.a(FluidTypeFlowing.java:187) ~[spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at net.minecraft.server.v1_15_R1.FluidTypeFlowing.a(FluidTypeFlowing.java:159) ~[spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at net.minecraft.server.v1_15_R1.FluidTypeFlowing.a(FluidTypeFlowing.java:493) ~[spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at net.minecraft.server.v1_15_R1.Fluid.a(SourceFile:69) ~[spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at net.minecraft.server.v1_15_R1.WorldServer.a(WorldServer.java:581) ~[spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at net.minecraft.server.v1_15_R1.TickListServer.b(TickListServer.java:82) [spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:304) [spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1076) [spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:393) [spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:978) [spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:823) [spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
Caused by: java.lang.NoSuchFieldError: WOOD_PLATE
	at org.dynmap.bukkit.DynmapPlugin$9.onBlockFromTo(DynmapPlugin.java:1307) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_222]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_222]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	... 15 more
```

**Comment by ssterling** [comment]
This also seems to occur with build 244 on the latest 1.15.1 build of PaperMC, with any block-based render trigger.

**Comment by Remanent** [comment]
Yes, i can confirm it is still doing it with build 244 using Spigot 1.15.1.

**Comment by mikeprimm** [comment]
Dup of #2705

**Comment by Remanent** [comment]
~~*checks post made 2 days after i submitted issue for information*~~

**Comment by mikeprimm-triva** [comment]
Honestly not relevant - the other post had more information by the time I got to it.  It's not a contest or a race...

**Comment by Remanent** [comment]
I apologize, i'd been up for far too long without sleep, and having a rough morning (kids).  Thank you for all the work you've done on this mod, my brother and his friends whose server I host using this plugin absolutely love it.

**Comment by mikeprimm** [comment]
Nah - we're all good :)   I know what it's like (raised two kids myself, and crazy work schedule) - I just have very limited time for Dynmap, so I try to consolidate the folks associated with a given active issue into a single issue when I can, just so that we can all share information between the stakeholders more quickly - as often as not, it's just about which one either I saw first or which one seems to have more people already contributing to the thread (look at the 1.15 thread for #2689 for how this works out :) ).  Anyway, please chime in on the consolidated issue as you see fit!  And have a Happy Holidays with your family!
