### ISSUE TITLE
Could not pass event SignChangeEvent to dynmap v3.0-SNAPSHOT-243

### ISSUE THREAD

**Issue by HuJK** [webbukkit/dynmap#2699]
When I place a sign with enablesigns=true
Dynmap-3.0-beta-7-spigot.jar
spigot-1.14.4.jar
```
[16:27:26] [Server thread/ERROR]: Could not pass event SignChangeEvent to dynmap v3.0-beta-7-241
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot-1.14.4.jar:git-Spigot-56f8471-6567017]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.14.4.jar:git-Spigot-56f8471-6567017]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[spigot-1.14.4.jar:git-Spigot-56f8471-6567017]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[spigot-1.14.4.jar:git-Spigot-56f8471-6567017]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2381) ~[spigot-1.14.4.jar:git-Spigot-56f8471-6567017]
        at net.minecraft.server.v1_14_R1.PacketPlayInUpdateSign.a(SourceFile:44) ~[spigot-1.14.4.jar:git-Spigot-56f8471-6567017]
        at net.minecraft.server.v1_14_R1.PacketPlayInUpdateSign.a(SourceFile:10) ~[spigot-1.14.4.jar:git-Spigot-56f8471-6567017]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.14.4.jar:git-Spigot-56f8471-6567017]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot-1.14.4.jar:git-Spigot-56f8471-6567017]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot-1.14.4.jar:git-Spigot-56f8471-6567017]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.14.4.jar:git-Spigot-56f8471-6567017]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot-1.14.4.jar:git-Spigot-56f8471-6567017]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:909) [spigot-1.14.4.jar:git-Spigot-56f8471-6567017]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:902) [spigot-1.14.4.jar:git-Spigot-56f8471-6567017]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot-1.14.4.jar:git-Spigot-56f8471-6567017]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:886) [spigot-1.14.4.jar:git-Spigot-56f8471-6567017]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:819) [spigot-1.14.4.jar:git-Spigot-56f8471-6567017]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
Caused by: java.lang.IllegalArgumentException: Cannot get ID of Modern Material
        at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[spigot-1.14.4.jar:git-Spigot-56f8471-6567017]
        at org.bukkit.Material.getId(Material.java:3302) ~[spigot-1.14.4.jar:git-Spigot-56f8471-6567017]
        at org.dynmap.bukkit.DynmapPlugin$BukkitServer$5.onSignChange(DynmapPlugin.java:369) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.14.4.jar:git-Spigot-56f8471-6567017]
```

Latest SNAPSHOT also has same problem.
```
[16:45:13] [Server thread/ERROR]: Could not pass event SignChangeEvent to dynmap v3.0-SNAPSHOT-243
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot-1.14.4.jar:git-Spigot-56f8471-6567017]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.14.4.jar:git-Spigot-56f8471-6567017]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[spigot-1.14.4.jar:git-Spigot-56f8471-6567017]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[spigot-1.14.4.jar:git-Spigot-56f8471-6567017]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2381) ~[spigot-1.14.4.jar:git-Spigot-56f8471-6567017]
        at net.minecraft.server.v1_14_R1.PacketPlayInUpdateSign.a(SourceFile:44) ~[spigot-1.14.4.jar:git-Spigot-56f8471-6567017]
        at net.minecraft.server.v1_14_R1.PacketPlayInUpdateSign.a(SourceFile:10) ~[spigot-1.14.4.jar:git-Spigot-56f8471-6567017]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.14.4.jar:git-Spigot-56f8471-6567017]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot-1.14.4.jar:git-Spigot-56f8471-6567017]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot-1.14.4.jar:git-Spigot-56f8471-6567017]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.14.4.jar:git-Spigot-56f8471-6567017]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot-1.14.4.jar:git-Spigot-56f8471-6567017]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:909) [spigot-1.14.4.jar:git-Spigot-56f8471-6567017]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:902) [spigot-1.14.4.jar:git-Spigot-56f8471-6567017]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot-1.14.4.jar:git-Spigot-56f8471-6567017]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:886) [spigot-1.14.4.jar:git-Spigot-56f8471-6567017]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:819) [spigot-1.14.4.jar:git-Spigot-56f8471-6567017]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
Caused by: java.lang.IllegalArgumentException: Cannot get ID of Modern Material
        at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[spigot-1.14.4.jar:git-Spigot-56f8471-6567017]
        at org.bukkit.Material.getId(Material.java:3302) ~[spigot-1.14.4.jar:git-Spigot-56f8471-6567017]
        at org.dynmap.bukkit.DynmapPlugin$BukkitServer$5.onSignChange(DynmapPlugin.java:369) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.14.4.jar:git-Spigot-56f8471-6567017]
        ... 17 more
```

**Comment by RaidersPlay** [comment]
Getting the same issue when trying to use signs.
Running Paper 1.15 #21 
`[10:39:21] [Server thread/ERROR]: Could not pass event SignChangeEvent to dynmap v3.0-beta-7-241
java.lang.IllegalArgumentException: Cannot get ID of Modern Material
	at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[patched_1.15.jar:git-Paper-21]
	at org.bukkit.Material.getId(Material.java:3333) ~[patched_1.15.jar:git-Paper-21]
	at org.dynmap.bukkit.DynmapPlugin$BukkitServer$5.onSignChange(DynmapPlugin.java:369) ~[?:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.15.jar:git-Paper-21]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.jar:git-Paper-21]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.jar:git-Paper-21]
.......`

**Comment by MitchTalmadge** [comment]
Same error here, Paper 1.15.1:

```
[00:51:20] [Server thread/ERROR]: Could not pass event SignChangeEvent to dynmap v3.0-beta-8-244
java.lang.IllegalArgumentException: Cannot get ID of Modern Material
	at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[patched_1.15.1.jar:git-Paper-23]
	at org.bukkit.Material.getId(Material.java:3333) ~[patched_1.15.1.jar:git-Paper-23]
	at org.dynmap.bukkit.DynmapPlugin$BukkitServer$5.onSignChange(DynmapPlugin.java:369) ~[?:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.15.1.jar:git-Paper-23]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.1.jar:git-Paper-23]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.1.jar:git-Paper-23]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.15.1.jar:git-Paper-23]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:2581) ~[patched_1.15.1.jar:git-Paper-23]
	at net.minecraft.server.v1_15_R1.PacketPlayInUpdateSign.a(SourceFile:44) ~[patched_1.15.1.jar:git-Paper-23]
	at net.minecraft.server.v1_15_R1.PacketPlayInUpdateSign.a(SourceFile:10) ~[patched_1.15.1.jar:git-Paper-23]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.1.jar:git-Paper-23]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.1.jar:git-Paper-23]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.1.jar:git-Paper-23]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.1.jar:git-Paper-23]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.1.jar:git-Paper-23]
	at net.minecraft.server.v1_15_R1.MinecraftServer.aZ(MinecraftServer.java:1037) ~[patched_1.15.1.jar:git-Paper-23]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1030) ~[patched_1.15.1.jar:git-Paper-23]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.15.1.jar:git-Paper-23]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1166) ~[patched_1.15.1.jar:git-Paper-23]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:933) ~[patched_1.15.1.jar:git-Paper-23]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
```

Relevant lines: (Error on 369)

https://github.com/webbukkit/dynmap/blob/5dbb58dfdae494dbd7d311db530ef8c76e9ed96c/spigot/src/main/java/org/dynmap/bukkit/DynmapPlugin.java#L359-L373

It looks like `getId` on `Material` is deprecated, so since `blkid` in `processSignChangeEvent` is never actually used in any implementation of the event listeners, I suggest that it be removed entirely, or replaced with a string representation of `Material`. See this implementation where it's not even used:

https://github.com/webbukkit/dynmap/blob/be9aac072df471dc62e244d7477959a62106c905/DynmapCore/src/main/java/org/dynmap/markers/impl/MarkerSignManager.java#L31

I suppose there could be other plugins that use the API though. Not really familiar with Dynmap's API

**Comment by ryantheleach** [comment]
Whilst I'm not seeing spam, I'm not seeing sign markers either on 1.15.1

Can someone confirm that it's now possible for people to create sign markers with only the text

```
1: [dynmap]
2: signtest
3:
4:
```

and the permission dynmap.marker.sign ?

**Comment by RaidersPlay** [comment]
It's working on my server server for a while now.

**Comment by MitchTalmadge** [comment]
That configuration is exactly how my server is set up and it does work.
