### ISSUE TITLE
Spigot 1.15.1 sign problems?

### ISSUE THREAD

**Issue by Cassolotl** [webbukkit/dynmap#2708]
Server /version: 

>[16:36:05] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-2ee05fe-4499fec (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)
>[16:36:05] [Server thread/INFO]: Checking version, please wait...
>[16:36:06] [Thread-162/INFO]: You are 2 version(s) behind

Dynmap /version: 

>[16:36:33] [Server thread/INFO]: dynmap version 3.0-beta-8-244

Error in console:

```
[13:28:44] [Server thread/INFO]: [GriefPrevention] TacitaMysterium placed a sign @ world: x1291, z616;Step Two:;Wait For Bottom;Chest To Have All;Material From Top
[13:28:44] [Server thread/ERROR]: Could not pass event SignChangeEvent to dynmap v3.0-beta-8-244
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[minecraft_server.jar:git-Spigot-2ee05fe-4499fec]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[minecraft_server.jar:git-Spigot-2ee05fe-4499fec]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[minecraft_server.jar:git-Spigot-2ee05fe-4499fec]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[minecraft_server.jar:git-Spigot-2ee05fe-4499fec]
at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:2391) ~[minecraft_server.jar:git-Spigot-2ee05fe-4499fec]
at net.minecraft.server.v1_15_R1.PacketPlayInUpdateSign.a(SourceFile:44) ~[minecraft_server.jar:git-Spigot-2ee05fe-4499fec]
at net.minecraft.server.v1_15_R1.PacketPlayInUpdateSign.a(SourceFile:10) ~[minecraft_server.jar:git-Spigot-2ee05fe-4499fec]
at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[minecraft_server.jar:git-Spigot-2ee05fe-4499fec]
at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [minecraft_server.jar:git-Spigot-2ee05fe-4499fec]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [minecraft_server.jar:git-Spigot-2ee05fe-4499fec]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [minecraft_server.jar:git-Spigot-2ee05fe-4499fec]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [minecraft_server.jar:git-Spigot-2ee05fe-4499fec]
at net.minecraft.server.v1_15_R1.MinecraftServer.aZ(MinecraftServer.java:917) [minecraft_server.jar:git-Spigot-2ee05fe-4499fec]
at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:910) [minecraft_server.jar:git-Spigot-2ee05fe-4499fec]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [minecraft_server.jar:git-Spigot-2ee05fe-4499fec]
at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:894) [minecraft_server.jar:git-Spigot-2ee05fe-4499fec]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:827) [minecraft_server.jar:git-Spigot-2ee05fe-4499fec]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
Caused by: java.lang.IllegalArgumentException: Cannot get ID of Modern Material
at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[minecraft_server.jar:git-Spigot-2ee05fe-4499fec]
at org.bukkit.Material.getId(Material.java:3316) ~[minecraft_server.jar:git-Spigot-2ee05fe-4499fec]
at org.dynmap.bukkit.DynmapPlugin$BukkitServer$5.onSignChange(DynmapPlugin.java:369) ~[?:?]
at sun.reflect.GeneratedMethodAccessor123.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_232]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_232]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[minecraft_server.jar:git-Spigot-2ee05fe-4499fec]
... 17 more
```

**Comment by MitchTalmadge** [comment]
Duplicate of https://github.com/webbukkit/dynmap/issues/2699. I made a PR to fix this recently.

**Comment by Cassolotl** [comment]
@MitchTalmadge Ahh fantastic! Thanks. :)
