### ISSUE TITLE
File for Dynmap nowhere to be found.

### ISSUE THREAD

**Issue by arnekerke** [webbukkit/dynmap#2820]
so i have a server with some friends on server.pro.

we wanted to install dynmap on it but after i downloaded the spigot version for it (Dynmap-3.0-beta-5-spigot) i cant find the file for adjusting it.

this is what the console is saying:

[**WARNING] Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[WARNING] Legacy plugin dynmap v3.0-beta-5-218 does not specify an api-version.
[WARNING] Legacy plugin SetHome v5.1.2 does not specify an api-version.
[INFO] [CoreProtect] Loading CoreProtect v2.18.2
[INFO] [dynmap] Loading dynmap v3.0-beta-5-218
[INFO] [dynmap] version=git-Spigot-6de3d4b-a6f8093 (MC: 1.15.2)
[ERROR] [dynmap] Unable to find field biome for org.bukkit.craftbukkit.v1_15_R1.CraftChunkSnapshot
[ERROR] Error initializing dynmap - bukkit version incompatible! initializing dynmap v3.0-beta-5-218 (Is it up to date?)
java.lang.IllegalArgumentException: Error initializing dynmap - bukkit version incompatible!
at org.dynmap.bukkit.helper.BukkitVersionHelperGeneric.<init>(BukkitVersionHelperGeneric.java:159) ~[?:?]
at org.dynmap.bukkit.helper.BukkitVersionHelperCB.<init>(BukkitVersionHelperCB.java:45) ~[?:?]
at org.dynmap.bukkit.Helper.getHelper(Helper.java:55) ~[?:?]
at org.dynmap.bukkit.DynmapPlugin.onLoad(DynmapPlugin.java:791) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:358) [spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:210) [spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:784) [spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
at java.lang.Thread.run(Thread.java:813) [?:1.8.0_212]**

Many thanks for the help in advance!

**Comment by masterX244** [comment]
Outdated release. This one is the latest one: https://dynmap.us/releases/Dynmap-3.0-beta-10-spigot.jar

Link obtained via spigot plugin page
