### ISSUE TITLE
Dynmap v3.0 beta 10 Spigot MC: 1.15.2 invalid plugin.yml

### ISSUE THREAD

**Issue by agent-guardian** [webbukkit/dynmap#2852]
When starting the server I get an error saying invalid plugin.yml. Dynmap still works though for some reason.

MC: 1.15.2
Dynmap: v3.0 beta 10 spigot
Spigot: git-Spigot-a03b1fd-fc318cc API version 1.15.2-R0.1-SNAPSHOT
<details>
<summary>Here is the stacktrace</summary>

```[22:43:22] [Server thread/ERROR]: Could not load 'plugins/._Dynmap-3.0-beta-10-spigot.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:168) ~[spigot-1.15.2.jar:git-Spigot-a03b1fd-fc318cc]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:144) [spigot-1.15.2.jar:git-Spigot-a03b1fd-fc318cc]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:353) [spigot-1.15.2.jar:git-Spigot-a03b1fd-fc318cc]
        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:210) [spigot-1.15.2.jar:git-Spigot-a03b1fd-fc318cc]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:784) [spigot-1.15.2.jar:git-Spigot-a03b1fd-fc318cc]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.util.zip.ZipException: zip END header not found
        at java.util.zip.ZipFile$Source.zerror(ZipFile.java:1535) ~[?:?]
        at java.util.zip.ZipFile$Source.findEND(ZipFile.java:1436) ~[?:?]
        at java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1443) ~[?:?]
        at java.util.zip.ZipFile$Source.<init>(ZipFile.java:1274) ~[?:?]
        at java.util.zip.ZipFile$Source.get(ZipFile.java:1237) ~[?:?]
        at java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:727) ~[?:?]
        at java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:844) ~[?:?]
        at java.util.zip.ZipFile.<init>(ZipFile.java:247) ~[?:?]
        at java.util.zip.ZipFile.<init>(ZipFile.java:177) ~[?:?]
        at java.util.jar.JarFile.<init>(JarFile.java:346) ~[?:?]
        at java.util.jar.JarFile.<init>(JarFile.java:317) ~[?:?]
        at java.util.jar.JarFile.<init>(JarFile.java:283) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:156) ~[spigot-1.15.2.jar:git-Spigot-a03b1fd-fc318cc]
        ... 5 more
[22:43:23] [Server thread/WARN]: Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[22:43:30] [Server thread/WARN]: Legacy plugin dynmap v3.0-beta-10-257 does not specify an api-version.
[22:43:30] [Server thread/INFO]: [dynmap] Loading dynmap v3.0-beta-10-257
[22:43:30] [Server thread/INFO]: [dynmap] version=git-Spigot-a03b1fd-fc318cc (MC: 1.15.2)
[22:43:30] [Server thread/INFO]: [dynmap] Unload queue not found - default to unload all chunks
[22:43:30] [Server thread/INFO]: [dynmap] inhabitedTicks field not found - inhabited shader not functional
[22:43:30] [Server thread/INFO]: [dynmap] Mod Support API available
```
</details>

**Comment by steven30303** [comment]
Please upload your config.yml

**Comment by agent-guardian** [comment]
Where would I find config.yml, the only thing I can find about it online is
that it would be a part of the compiled jar for dynmap

**Comment by smmmadden** [comment]
the file in question is in your plugins/dynmap folder called configuration.txt

**Comment by agent-guardian** [comment]
Here's my configuration.txt
[configuration.txt](https://github.com/webbukkit/dynmap/files/4476830/configuration.txt)

**Comment by RobinWhitfield** [comment]
`timesliceinterval: 0.0`
sounds like a bad time.

Try making that >0 (default is 0.2 IIRC) and see what happens.

**Comment by RobinWhitfield** [comment]
`timesliceinterval: 0.0`
sounds like a bad time.

Try making that >0 (default is 0.2 IIRC) and see what happens.

**Comment by FedUpWith-Tech** [comment]
[Try the latest build ](https://www.spigotmc.org/resources/dynmap.274/) and let me if the issue still persists

**Comment by ghost** [comment]
i have this issue and im on the latest version, the configuration.txt file doesnt even exist for me

**Comment by ghost** [comment]
im on 1.16.5 papermc btw

**Comment by FedUpWith-Tech** [comment]
I've seen this issue several times now and it is always the result of the plugin not properly uploading or downloading to a server host. Assuming that is the same here.
