### ISSUE TITLE
Issue with Web Chat - java.lang.IllegalArgumentException: Illegal character in Base64 encoded data.

### ISSUE THREAD

**Issue by varachit** [webbukkit/dynmap#2885]
Issue with Web Chat - Every time player chat in game the stack trace above will come up and chat will not appear on web map.
PS. Using EssentialsXChat-2.17.2.59 with LuckPerms-Bukkit-5.0.72 for Chat Prefix

[15:42:50] [Async Chat Thread - #1/INFO]: [0;36;1m[Best][m <[0;37;1m[21m[[0;32;1m[21mSurvivor[0;37;1m[21m] Varachit223[m> Test[m

[15:42:50] [Server thread/WARN]: [dynmap] Task #30354 for dynmap v3.0-beta-10-257 generated an exception
java.lang.IllegalArgumentException: Illegal character in Base64 encoded data.
	at org.yaml.snakeyaml.external.biz.base64Coder.Base64Coder.decode(Base64Coder.java:288) ~[spigot-1.15.2.jar:git-Spigot-e7dc2f5-ce66f69]
	at org.yaml.snakeyaml.external.biz.base64Coder.Base64Coder.decode(Base64Coder.java:246) ~[spigot-1.15.2.jar:git-Spigot-e7dc2f5-ce66f69]
	at org.yaml.snakeyaml.external.biz.base64Coder.Base64Coder.decode(Base64Coder.java:232) ~[spigot-1.15.2.jar:git-Spigot-e7dc2f5-ce66f69]
	at org.dynmap.bukkit.helper.BukkitVersionHelperGeneric.getSkinURL(BukkitVersionHelperGeneric.java:569) ~[?:?]
	at org.dynmap.bukkit.DynmapPlugin$BukkitPlayer.<init>(DynmapPlugin.java:604) ~[?:?]
	at org.dynmap.bukkit.DynmapPlugin$BukkitServer$3$1.run(DynmapPlugin.java:341) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.15.2.jar:git-Spigot-e7dc2f5-ce66f69]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) [spigot-1.15.2.jar:git-Spigot-e7dc2f5-ce66f69]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1036) [spigot-1.15.2.jar:git-Spigot-e7dc2f5-ce66f69]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:406) [spigot-1.15.2.jar:git-Spigot-e7dc2f5-ce66f69]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:984) [spigot-1.15.2.jar:git-Spigot-e7dc2f5-ce66f69]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:824) [spigot-1.15.2.jar:git-Spigot-e7dc2f5-ce66f69]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]

**Comment by FedUpWith-Tech** [comment]
What chat plugins do you have installed?
