### ISSUE TITLE
Error during render

### ISSUE THREAD

**Issue by slitterell** [webbukkit/dynmap#2914]
It will render other maps fine. The custom nether maps it gives and error. I don't understand the error. It seems to stop repeatedly at tile 3800 on the netherroof map only.

[dynmap] Exception during render job: world=world_nether, map=org.dynmap.hdmap.HDMap@61a7f30b
Minecraft 1.15.2
Version: core=3.0-beta-10-257
              plugin=3.0-beta-10-257

All other maps work fine.
https://pastebin.com/YVgans7x configuration.txt
https://pastebin.com/19aFknPb worlds.txt
https://pastebin.com/gQfbw0LU custom-nether-hires.txt
https://pastebin.com/HrmrjyDV custom-perspectives.txt

I think I have everything there you may need. I bet it is something simple I am missing.

**Comment by otse** [comment]
Did you try to look at the chunk with mcedit? Maybe you can give the devs some data from there.

**Comment by slitterell** [comment]
It's 1.15 and I don't believe mcedit works with it unless you know how to and wish to disclose. :) I would happily, though, if it worked.

**Comment by slitterell** [comment]
Also, I verified disc space just to make sure. I even moved the whole server over to a new server to make sure. 

@otse I also wondered how you could tell which chunk* it is?

**Comment by slitterell** [comment]
sorry, fixed the sentence to makes sense @otse lol my fault :)

**Comment by slitterell** [comment]
Actually, just looked and got more errors when I just tried to run it again...


[18:00:19] [Dynmap Render Thread/ERROR]: [dynmap] Exception during render job: world=Bees Update_nether, map=org.dynmap.hdmap.HDMap@1b84dbc0
[18:00:19] [Dynmap Render Thread/WARN]: java.lang.ArrayIndexOutOfBoundsException: 16
[18:00:19] [Dynmap Render Thread/WARN]:         at org.dynmap.bukkit.helper.v115.MapChunkCache115$NBTSnapshot.getBlockType(MapChunkCache115.java:264)
[18:00:19] [Dynmap Render Thread/WARN]:         at org.dynmap.bukkit.helper.AbstractMapChunkCache$BasetMapIterator.getBlockType(AbstractMapChunkCache.java:138)
[18:00:19] [Dynmap Render Thread/WARN]:         at org.dynmap.hdmap.IsoHDPerspective.render(IsoHDPerspective.java:1260)
[18:00:19] [Dynmap Render Thread/WARN]:         at org.dynmap.hdmap.HDMapTile.render(HDMapTile.java:79)
[18:00:19] [Dynmap Render Thread/WARN]:         at org.dynmap.MapManager$FullWorldRenderState.processTile(MapManager.java:773)
[18:00:19] [Dynmap Render Thread/WARN]:         at org.dynmap.MapManager$FullWorldRenderState.run(MapManager.java:689)
[18:00:19] [Dynmap Render Thread/WARN]:         at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1.run(MapManager.java:198)
[18:00:19] [Dynmap Render Thread/WARN]:         at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$2.run(MapManager.java:214)
[18:00:19] [Dynmap Render Thread/WARN]:         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[18:00:19] [Dynmap Render Thread/WARN]:         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[18:00:19] [Dynmap Render Thread/WARN]:         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
[18:00:19] [Dynmap Render Thread/WARN]:         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
[18:00:19] [Dynmap Render Thread/WARN]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[18:00:19] [Dynmap Render Thread/WARN]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[18:00:19] [Dynmap Render Thread/WARN]:         at java.lang.Thread.run(Thread.java:748)

**Comment by slitterell** [comment]
Here is a link to my nether file zipped.

https://drive.google.com/open?id=1yWyEAM4iUA4p8LLRX9dTTpl1a3VUbJw8

**Comment by InsaneJ** [comment]
We seem to be having a similar issue with Dynmap-3.0-RC1-spigot.

```
[Dynmap Render Thread/ERROR]: [dynmap] Exception during render job: world=world_nether, map=org.dynmap.hdmap.HDMap@310f7899
[Dynmap Render Thread/WARN]: java.lang.ArrayIndexOutOfBoundsException: 16
[Dynmap Render Thread/WARN]:         at org.dynmap.bukkit.helper.v115.MapChunkCache115$NBTSnapshot.getBlockType(MapChunkCache115.java:265)
[Dynmap Render Thread/WARN]:         at org.dynmap.bukkit.helper.AbstractMapChunkCache$BasetMapIterator.getBlockType(AbstractMapChunkCache.java:138)
[Dynmap Render Thread/WARN]:         at org.dynmap.hdmap.IsoHDPerspective.render(IsoHDPerspective.java:1260)
[Dynmap Render Thread/WARN]:         at org.dynmap.hdmap.HDMapTile.render(HDMapTile.java:79)
[Dynmap Render Thread/WARN]:         at org.dynmap.MapManager$FullWorldRenderState.processTile(MapManager.java:773)
[Dynmap Render Thread/WARN]:         at org.dynmap.MapManager$FullWorldRenderState.run(MapManager.java:663)
[Dynmap Render Thread/WARN]:         at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$2.run(MapManager.java:214)
[Dynmap Render Thread/WARN]:         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[Dynmap Render Thread/WARN]:         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[Dynmap Render Thread/WARN]:         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
[Dynmap Render Thread/WARN]:         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
[Dynmap Render Thread/WARN]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[Dynmap Render Thread/WARN]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[Dynmap Render Thread/WARN]:         at java.lang.Thread.run(Thread.java:748)
```

I have added a flat and a surface map to the default nether map section. These two new maps render from Y-level 128 to 256 so we can see on top of the Bedrock ceiling.

Worlds configuration:
```
    -   class: org.dynmap.hdmap.HDMap
        name: flat_top
        title: Flat_Top
        icon: images/block_flat.png
        prefix: flat_top
        perspective: nether_top_map_scale16
        shader: stdtexture
        lighting: nethershadows
        background: '#300806'
        mapzoomin: 5
    -   class: org.dynmap.hdmap.HDMap
        name: nether_top
        title: Surface_Top
        icon: images/block_nether.png
        prefix: nether_top
        perspective: nether_iso_SE_scale16
        shader: stdtexture
        lighting: nethershadows
        background: '#300806'
        mapzoomin: 3
        boostzoom: 2
```
Custom perspectives:
```
  - class: org.dynmap.hdmap.IsoHDPerspective
    name: nether_top_map_scale16
    maximumheight: 256
    minimumheight: 128
    inclination: 90
    scale: 16
    azimuth: 180
  - class: org.dynmap.hdmap.IsoHDPerspective
    name: nether_iso_SE_scale16
    maximumheight: 256
    minimumheight: 128
    azimuth: 135
    inclination: 30
    scale: 16
```

**Comment by InsaneJ** [comment]
It looks like changing maximumheigh to 255 instead of 256 solved our issue. I have no idea why I put 256 there since Y-levels only go from 0-255 in unmodded Minecraft. Definitely user error. But perhaps a check on max Y-level instead of a crash might be something to add?

**Comment by slitterell** [comment]
Interesting. Same with mine. It's still processing but it continued past its previous limit. 

Easy to do as the build limit is 256, you'd think 256 is the limit. I did the same with mine. Seems like an error in programming but I'm am not a programmer.

**Comment by slitterell** [comment]
dang, I can't believe that was the issue. It appears to have rendered fine.
