### ISSUE TITLE
Cubic Chunks Support?

### ISSUE THREAD

**Issue by Tysseract** [webbukkit/dynmap#2925]
I realize this probably won't be fixed soon (if ever) but I thought I'd get it on your radar that Cubic Chunks throws an out-of-bounds error (obviously because of the way chunks work differently):
```
[Dynmap Render Thread/FATAL] [Dynmap]: [Dynmap] Exception while loading chunks java.lang.ArrayIndexOutOfBoundsException: -3
        at org.dynmap.forge_1_12_2.ChunkSnapshot.getBlockType(ChunkSnapshot.java:271) ~[ChunkSnapshot.class:?]
        at org.dynmap.forge_1_12_2.ForgeMapChunkCache.prepChunkSnapshot(ForgeMapChunkCache.java:1255) ~[ForgeMapChunkCache.class:?]
        at org.dynmap.forge_1_12_2.ForgeMapChunkCache.getLoadedChunks(ForgeMapChunkCache.java:1320) ~[ForgeMapChunkCache.class:?]
        at org.dynmap.forge_1_12_2.DynmapPlugin$ForgeServer$1.call(DynmapPlugin.java:865) ~[DynmapPlugin$ForgeServer$1.class:?]
        at org.dynmap.forge_1_12_2.DynmapPlugin$ForgeServer$1.call(DynmapPlugin.java:860) ~[DynmapPlugin$ForgeServer$1.class:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_212]
        at org.dynmap.forge_1_12_2.DynmapPlugin$ForgeServer.tickEvent(DynmapPlugin.java:952) ~[DynmapPlugin$ForgeServer.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_45_ForgeServer_tickEvent_ServerTickEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:266) ~[FMLCommonHandler.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:712) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) ~[MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**Comment by FedUpWith-Tech** [comment]
Yeah, there is no plans to support cubic chunks as its a very large change that would require a large rewrite of forge codebase. The dev has said he only plans to implement minor feature requests and bug fixes for now so I'm going to close this but if anything changes I'll update this issue.
