### ISSUE TITLE
paper spigot 205 : can't load plugin

### ISSUE THREAD

**Issue by Xeraccoon** [webbukkit/dynmap#2940]
21:24:55] [Server thread/ERROR]: [org.bukkit.craftbukkit.v1_15_R1.CraftServer] Error initializing dynmap - bukkit version incompatible! initializing dynmap v3.0-beta-1-129 (Is it up to date?)

java.lang.IllegalArgumentException: Error initializing dynmap - bukkit version incompatible!

at org.dynmap.bukkit.helper.BukkitVersionHelperGeneric.<init>(BukkitVersionHelperGeneric.java:159) ~[?:?]

at org.dynmap.bukkit.helper.BukkitVersionHelperCB.<init>(BukkitVersionHelperCB.java:43) ~[?:?]

at org.dynmap.bukkit.Helper.getHelper(Helper.java:42) ~[?:?]

at org.dynmap.bukkit.DynmapPlugin.onLoad(DynmapPlugin.java:779) ~[?:?]

at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:363) ~[patched_1.15.2.jar:git-Paper-205]

at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:234) ~[patched_1.15.2.jar:git-Paper-205]

at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:896) ~[patched_1.15.2.jar:git-Paper-205]

at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]

**Comment by Tsoccerguy3** [comment]
Use Paper build current

**Comment by Tsoccerguy3** [comment]
use Dynmap 3 RC 2 from here https://dynmap.us/builds/dynmap/

**Comment by Tsoccerguy3** [comment]
get latest dynmap here , https://dynmap.us/builds/dynmap/ ,

Dynmap-3.0-RC2-spigot.jar

**Comment by ice-fly** [comment]
Paper fixed, update to current: https://github.com/PaperMC/Paper/issues/3386
