### ISSUE TITLE
Error occurred while disabling

### ISSUE THREAD

**Issue by ice-fly** [webbukkit/dynmap#2948]
```
[dynmap] Stopping map renderer...
[01:36:40 ERROR]: Error occurred while disabling dynmap v3.0-RC2-318 (Is it up to date?)
java.util.ConcurrentModificationException: null
        at java.util.LinkedList$ListItr.checkForComodification(Unknown Source) ~[?:?]
        at java.util.LinkedList$ListItr.next(Unknown Source) ~[?:?]
        at org.dynmap.MapManager$FullWorldRenderState.saveState(MapManager.java:428) ~[?:?]
        at org.dynmap.MapManager.savePending(MapManager.java:1399) ~[?:?]
        at org.dynmap.MapManager.stopRendering(MapManager.java:1480) ~[?:?]
        at org.dynmap.DynmapCore.disableCore(DynmapCore.java:944) ~[?:?]
        at org.dynmap.bukkit.DynmapPlugin.onDisable(DynmapPlugin.java:989) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.15.2.jar:git-Paper-308]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415) ~[patched_1.15.2.jar:git-Paper-308]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[patched_1.15.2.jar:git-Paper-308]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:508) ~[patched_1.15.2.jar:git-Paper-308]
        at org.dynmap.bukkit.DynmapPlugin$BukkitServer.reload(DynmapPlugin.java:252) ~[?:?]
        at org.dynmap.DynmapCore.processCommand(DynmapCore.java:1464) ~[?:?]
        at org.dynmap.bukkit.DynmapPlugin.onCommand(DynmapPlugin.java:1025) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.15.2.jar:git-Paper-308]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.15.2.jar:git-Paper-308]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:761) ~[patched_1.15.2.jar:git-Paper-308]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchServerCommand(CraftServer.java:723) ~[patched_1.15.2.jar:git-Paper-308]
        at net.minecraft.server.v1_15_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:469) ~[patched_1.15.2.jar:git-Paper-308]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431) ~[patched_1.15.2.jar:git-Paper-308]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1173) ~[patched_1.15.2.jar:git-Paper-308]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:962) ~[patched_1.15.2.jar:git-Paper-308]
        at java.lang.Thread.run(Unknown Source) [?:?]
[01:36:40 INFO]: [dynmap] Enabling dynmap v3.0-RC2-318*
```

**Comment by FedUpWith-Tech** [comment]
Does this issue occur on the latest dynmap version?
