### ISSUE TITLE
 [Dynmap Render Thread/ERROR]: [dynmap] Exception while reading JSON-file. java.io.IOException: Stream closed

### ISSUE THREAD

**Issue by kbulgrien** [webbukkit/dynmap#2966]
I had rendered with 3.0 RC 2 without issues of this nature.  I'm running a remote MySQL database and webserver.

I loaded 3.0.1 today, wiped/deleted/re-created the ISO map because after fullrendering the flat and cave maps, it refsed to fullrender the surface map (said it was complete immediately - same log second).  After starting to render, it ran for hours and the map looked great, but then this happened:

[21:53:02] [Dynmap Render Thread/INFO]: Full render of map 'surface' of 'Bulgraria' in progress - 104600 tiles rendered (422.73 msec/tile, 378.21 msec per render)21:53:08] [Dynmap Render Thread/ERROR]: [dynmap] Exception during render job: org.dynmap.JsonFileClientUpdateComponent$9@552f5f09
[21:53:08] [Dynmap Render Thread/WARN]: java.lang.ClassCastException: org.dynmap.json.simple.JSONArray cannot be cast to java.util.Map
[21:53:08] [Dynmap Render Thread/ERROR]: [dynmap] Exception while parsing JSON-file.
org.dynmap.json.simple.parser.ParseException: null
        at org.dynmap.json.simple.parser.Yylex.yylex(Yylex.java:610) ~[Dynmap-3.0.1-spigot.jar:?]
        at org.dynmap.json.simple.parser.JSONParser.nextToken(JSONParser.java:269) ~[Dynmap-3.0.1-spigot.jar:?]
        at org.dynmap.json.simple.parser.JSONParser.parse(JSONParser.java:118) ~[Dynmap-3.0.1-spigot.jar:?]
        at org.dynmap.json.simple.parser.JSONParser.parse(JSONParser.java:92) ~[Dynmap-3.0.1-spigot.jar:?]
        at org.dynmap.JsonFileClientUpdateComponent$9.run(JsonFileClientUpdateComponent.java:472) [Dynmap-3.0.1-spigot.jar:?]
        at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1.run(MapManager.java:229) [Dynmap-3.0.1-spigot.jar:?]
        at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$2.run(MapManager.java:245) [Dynmap-3.0.1-spigot.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_241]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_241]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_241]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_241]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_241]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_241]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]
[21:53:08] [Dynmap Render Thread/WARN]:         at org.dynmap.json.simple.parser.JSONParser.parse(JSONParser.java:186)
[21:53:08] [Dynmap Render Thread/WARN]:         at org.dynmap.json.simple.parser.JSONParser.parse(JSONParser.java:92)
[21:53:08] [Dynmap Render Thread/WARN]:         at org.dynmap.JsonFileClientUpdateComponent$9.run(JsonFileClientUpdateComponent.java:472)
[21:53:08] [Dynmap Render Thread/WARN]:         at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1.run(MapManager.java:229)
[21:53:08] [Dynmap Render Thread/WARN]:         at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$2.run(MapManager.java:245)
[21:53:08] [Dynmap Render Thread/WARN]:         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[21:53:08] [Dynmap Render Thread/WARN]:         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[21:53:08] [Dynmap Render Thread/WARN]:         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
[21:53:08] [Dynmap Render Thread/WARN]:         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
[21:53:08] [Dynmap Render Thread/WARN]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[21:53:08] [Dynmap Render Thread/WARN]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[21:53:08] [Dynmap Render Thread/WARN]:         at java.lang.Thread.run(Thread.java:748)

then:

[23:48:11] [Dynmap Render Thread/INFO]: Full render of map 'surface' of 'Bulgraria' in progress - 122100 tiles rendered (410.88 msec/tile, 365.79 msec per render)
[23:48:13] [Dynmap Render Thread/ERROR]: [dynmap] Exception while reading JSON-file.
java.io.IOException: Stream closed
        at sun.nio.cs.StreamDecoder.ensureOpen(StreamDecoder.java:46) ~[?:1.8.0_241]
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:148) ~[?:1.8.0_241]
        at java.io.InputStreamReader.read(InputStreamReader.java:184) ~[?:1.8.0_241]
        at org.dynmap.json.simple.parser.Yylex.zzRefill(Yylex.java:345) ~[Dynmap-3.0.1-spigot.jar:?]
        at org.dynmap.json.simple.parser.Yylex.yylex(Yylex.java:541) ~[Dynmap-3.0.1-spigot.jar:?]
        at org.dynmap.json.simple.parser.JSONParser.nextToken(JSONParser.java:269) ~[Dynmap-3.0.1-spigot.jar:?]
        at org.dynmap.json.simple.parser.JSONParser.parse(JSONParser.java:118) ~[Dynmap-3.0.1-spigot.jar:?]
        at org.dynmap.json.simple.parser.JSONParser.parse(JSONParser.java:92) ~[Dynmap-3.0.1-spigot.jar:?]
        at org.dynmap.JsonFileClientUpdateComponent$9.run(JsonFileClientUpdateComponent.java:472) [Dynmap-3.0.1-spigot.jar:?]
        at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1.run(MapManager.java:229) [Dynmap-3.0.1-spigot.jar:?]
        at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$2.run(MapManager.java:245) [Dynmap-3.0.1-spigot.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_241]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_241]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_241]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_241]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_241]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_241]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]

Now the flat map looks like this (and iso/cave maps have the same anomalies in their own rights):

![Screenshot_2020-06-09-Dynmap-3 0 1-Minecraft Spigot](https://user-images.githubusercontent.com/37119764/84111959-7dbb6d80-a9ed-11ea-889e-f57684aa4cac.png)

Nobody was logged in at the time of the first exception, then a brief stint when one person logged in, and later the second exception.  Aside from a handful of widely spaced single notes about lags of about 100 ticks, the log contains nothing except the single player login/logout and render messages. 

The weirdness of the map shows up on all maps (flat, surface, cave).

**Comment by mikeprimm** [comment]
Delete your standalone/dynmap_webchat.json file - it looks to be invalid,  This usually happens if the file system fills up and the file is unable to be fully written.  When using an external web server, this file is how web chat is communicated back to the MC server - if the file is bad, or is unreadable, you will have this sort of problem.
