### ISSUE TITLE
IndexOutOfBoundsException: Index 2 out of bounds for length 0

### ISSUE THREAD

**Issue by mibby** [webbukkit/dynmap#2969]
Dynmap-HEAD-spigot.jar - 2020-06-07 21:20

```
[07:54:20] [Server thread/WARN]: [dynmap] Task #182519 for dynmap v3.0-SNAPSHOT-338 generated an exception
java.lang.IndexOutOfBoundsException: Index 2 out of bounds for length 0
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248) ~[?:?]
	at java.util.Objects.checkIndex(Objects.java:373) ~[?:?]
	at java.util.ArrayList.get(ArrayList.java:426) ~[?:?]
	at org.dynmap.markers.impl.AreaMarkerImpl.getCornerZ(AreaMarkerImpl.java:343) ~[?:?]
	at org.dynmap.markers.impl.MarkerAPIImpl.writeMarkersFile(MarkerAPIImpl.java:3101) ~[?:?]
	at org.dynmap.markers.impl.MarkerAPIImpl.access$500(MarkerAPIImpl.java:56) ~[?:?]
	at org.dynmap.markers.impl.MarkerAPIImpl$DoFileWrites.run(MarkerAPIImpl.java:353) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.15.2.jar:git-Tuinity-"188307c"]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.15.2.jar:git-Tuinity-"188307c"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1323) ~[patched_1.15.2.jar:git-Tuinity-"188307c"]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431) ~[patched_1.15.2.jar:git-Tuinity-"188307c"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1238) ~[patched_1.15.2.jar:git-Tuinity-"188307c"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:969) ~[patched_1.15.2.jar:git-Tuinity-"188307c"]
	at java.lang.Thread.run(Thread.java:832) [?:?]
```

**Comment by mikeprimm** [comment]
You've got something provided an invalid Area marker - are you using any Dynmap-* (dynmap enabled plugins, like Dynmap-WorldGuard)?

**Comment by mibby** [comment]
I am not, nope.

**Comment by FedUpWith-Tech** [comment]
Try updating to the latest version, you are a couple versions out of date. Let me know if the issue persists
