### ISSUE TITLE
[Dynmap Render Thread/WARN]: java.util.NoSuchElementException

### ISSUE THREAD

**Issue by kbulgrien** [webbukkit/dynmap#2973]
Getting a crazy number of exceptions during fullrender with dynmap 3.0.1.  Here's another with context:

[10:12:13] [Dynmap Render Thread/INFO]: [dynmap] Full render of map 'surface' of 'Bulgraria' in progress - 556600 tiles rendered (388.40 msec/tile, 318.80 msec per render)
[10:12:21] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 5164ms or 103 ticks behind
[10:12:43] [Dynmap Render Thread/ERROR]: [dynmap] Exception while reading JSON-file.
java.io.IOException: Stream closed
        at sun.nio.cs.StreamDecoder.ensureOpen(StreamDecoder.java:46) ~[?:1.8.0_241]
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:148) ~[?:1.8.0_241]
        at java.io.InputStreamReader.read(InputStreamReader.java:184) ~[?:1.8.0_241]
        at org.dynmap.json.simple.parser.Yylex.zzRefill(Yylex.java:345) ~[Dynmap-3.0.1-spigot.jar:?]
        at org.dynmap.json.simple.parser.Yylex.yylex(Yylex.java:541) ~[Dynmap-3.0.1-spigot.jar:?]
        at org.dynmap.json.simple.parser.JSONParser.nextToken(JSONParser.java:269) ~[Dynmap-3.0.1-spigot.jar:?]
        at org.dynmap.json.simple.parser.JSONParser.parse(JSONParser.java:118) ~[Dynmap-3.0.1-spigot.jar:?]
        at org.dynmap.json.simple.parser.JSONParser.parse(JSONParser.java:92) ~[Dynmap-3.0.1-spigot.jar:?]
        at org.dynmap.JsonFileClientUpdateComponent$9.run(JsonFileClientUpdateComponent.java:472) [Dynmap-3.0.1-spigot.jar:?]
        at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1.run(MapManager.java:229) [Dynmap-3.0.1-spigot.jar:?]
        at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$2.run(MapManager.java:245) [Dynmap-3.0.1-spigot.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_241]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_241]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_241]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_241]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_241]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_241]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]
[10:12:57] [Dynmap Render Thread/ERROR]: [dynmap] Exception during render job: org.dynmap.JsonFileClientUpdateComponent$9@44b3ca77
[10:12:57] [Dynmap Render Thread/WARN]: java.util.NoSuchElementException
[10:12:57] [Dynmap Render Thread/WARN]:         at java.util.LinkedList.removeFirst(LinkedList.java:270)
[10:12:57] [Dynmap Render Thread/WARN]:         at org.dynmap.json.simple.parser.JSONParser.parse(JSONParser.java:144)
[10:12:57] [Dynmap Render Thread/WARN]:         at org.dynmap.json.simple.parser.JSONParser.parse(JSONParser.java:92)
[10:12:57] [Dynmap Render Thread/WARN]:         at org.dynmap.JsonFileClientUpdateComponent$9.run(JsonFileClientUpdateComponent.java:472)
[10:12:57] [Dynmap Render Thread/WARN]:         at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1.run(MapManager.java:229)
[10:12:57] [Dynmap Render Thread/WARN]:         at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$2.run(MapManager.java:245)
[10:12:57] [Dynmap Render Thread/WARN]:         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[10:12:57] [Dynmap Render Thread/WARN]:         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[10:12:57] [Dynmap Render Thread/WARN]:         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
[10:12:57] [Dynmap Render Thread/WARN]:         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
[10:12:57] [Dynmap Render Thread/WARN]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[10:12:57] [Dynmap Render Thread/WARN]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[10:12:57] [Dynmap Render Thread/WARN]:         at java.lang.Thread.run(Thread.java:748)
[10:15:43] [Dynmap Render Thread/INFO]: [dynmap] Full render of map 'surface' of 'Bulgraria' in progress - 556700 tiles rendered (388.58 msec/tile, 319.10 msec per render)

**Comment by FedUpWith-Tech** [comment]
Sorry to resurrect this thread from the dead- is this issue still present on the lastest dynmap build?
