### ISSUE TITLE
Errors with Dynmap {Solved}

### ISSUE THREAD

**Issue by PaninGitHub** [webbukkit/dynmap#2977]
Log:
[16:28:53 INFO]: [dynmap] Enabling dynmap v3.0-SNAPSHOT-338*
[16:28:54 INFO]: [dynmap] Using LuckPerms 5.0.72 for access control
[16:28:54 INFO]: [dynmap] Mod Support processing completed
[16:28:54 ERROR]: [dynmap] Error parsing plugins\dynmap\worlds.txt. Use http://yamllint.com to debug the YAML syntax.
[16:28:54 ERROR]: Error occurred while enabling dynmap v3.0-SNAPSHOT-338 (Is it up to date?)
org.dynmap.snakeyaml.parser.ParserException: while parsing a block collection
 in 'reader', line 22, column 7:
          - x: -10752
          ^
expected <block end>, but found '<block mapping start>'
 in 'reader', line 23, column 8:
           y: 64
           ^

        at org.dynmap.snakeyaml.parser.ParserImpl$ParseBlockSequenceEntry.produce(ParserImpl.java:516) ~[?:?]
        at org.dynmap.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[?:?]
        at org.dynmap.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148) ~[?:?]
        at org.dynmap.snakeyaml.composer.Composer.composeSequenceNode(Composer.java:188) ~[?:?]
        at org.dynmap.snakeyaml.composer.Composer.composeNode(Composer.java:142) ~[?:?]
        at org.dynmap.snakeyaml.composer.Composer.composeValueNode(Composer.java:236) ~[?:?]
        at org.dynmap.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:227) ~[?:?]
        at org.dynmap.snakeyaml.composer.Composer.composeMappingNode(Composer.java:215) ~[?:?]
        at org.dynmap.snakeyaml.composer.Composer.composeNode(Composer.java:144) ~[?:?]
        at org.dynmap.snakeyaml.composer.Composer.composeSequenceNode(Composer.java:189) ~[?:?]
        at org.dynmap.snakeyaml.composer.Composer.composeNode(Composer.java:142) ~[?:?]
        at org.dynmap.snakeyaml.composer.Composer.composeValueNode(Composer.java:236) ~[?:?]
        at org.dynmap.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:227) ~[?:?]
        at org.dynmap.snakeyaml.composer.Composer.composeMappingNode(Composer.java:215) ~[?:?]
        at org.dynmap.snakeyaml.composer.Composer.composeNode(Composer.java:144) ~[?:?]
        at org.dynmap.snakeyaml.composer.Composer.getNode(Composer.java:85) ~[?:?]
        at org.dynmap.snakeyaml.composer.Composer.getSingleNode(Composer.java:108) ~[?:?]
        at org.dynmap.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:139) ~[?:?]
        at org.dynmap.snakeyaml.Yaml.loadFromReader(Yaml.java:524) ~[?:?]
        at org.dynmap.snakeyaml.Yaml.load(Yaml.java:467) ~[?:?]
        at org.dynmap.ConfigurationNode.load(ConfigurationNode.java:87) ~[?:?]
        at org.dynmap.DynmapCore.enableCore(DynmapCore.java:490) ~[?:?]
        at org.dynmap.bukkit.DynmapPlugin.doEnable(DynmapPlugin.java:961) ~[?:?]
        at org.dynmap.bukkit.DynmapPlugin.onEnable(DynmapPlugin.java:941) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-178]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) ~[patched_1.15.2.jar:git-Paper-178]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-178]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:470) ~[patched_1.15.2.jar:git-Paper-178]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:384) ~[patched_1.15.2.jar:git-Paper-178]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:487) ~[patched_1.15.2.jar:git-Paper-178]
        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-178]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:891) ~[patched_1.15.2.jar:git-Paper-178]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
[16:28:54 INFO]: [dynmap] Disabling dynmap v3.0-SNAPSHOT-338
[16:28:54 INFO]: [dynmap] Unloaded 0 components.
[16:28:54 INFO]: [dynmap] Disabled
File where the error's at:
[worlds.txt](https://github.com/webbukkit/dynmap/files/4777238/worlds.txt)
I think I might have done the spacing wrong but idk

**Comment by RobinWhitfield** [comment]
You've hit the nail on the head there and the console messages in fact tell you where the issue in your file is.

Look at line 23 and compare it to the section immediately below.
You're missing a space before "y" and a space before "z"

**Comment by PaninGitHub** [comment]
> You've hit the nail on the head there and the console messages in fact tell you where the issue in your file is.
> 
> Look at line 23 and compare it to the section immediately below.
> You're missing a space before "y" and a space before "z"

Silly me. I fixed it up and now it's working. Thx m8

**Comment by RobinWhitfield** [comment]
Glad to hear it. It's easy done with YAML

Do you want to close this issue?

**Comment by RobinWhitfield** [comment]
@dinidusam, can you close this issue now?
