### ISSUE TITLE
1.16.1 Spigot Errors

### ISSUE THREAD

**Issue by MJRLegends** [webbukkit/dynmap#2989]
```
[22:20:42] [Server thread/INFO]: [dynmap] Loading dynmap v3.0-SNAPSHOT-338
[22:20:42] [Server thread/INFO]: [dynmap] version=git-Spigot-758abbe-2b00831 (MC: 1.16.1)
[22:20:42] [Server thread/ERROR]: [dynmap] Unable to find method getById for net.minecraft.server.v1_16_R1.Block
[22:20:42] [Server thread/ERROR]: [dynmap] Unable to find field material for net.minecraft.server.v1_16_R1.Block
[22:20:42] [Server thread/ERROR]: [dynmap] Unable to find method a for net.minecraft.server.v1_16_R1.BiomeBase
[22:20:42] [Server thread/ERROR]: [dynmap] Unable to find field y for net.minecraft.server.v1_16_R1.BiomeBase
[22:20:42] [Server thread/ERROR]: [dynmap] Unable to find field chunkProvider for net.minecraft.server.v1_16_R1.World
[22:20:42] [Server thread/INFO]: [dynmap] Unload queue not found - default to unload all chunks
[22:20:42] [Server thread/INFO]: [dynmap] inhabitedTicks field not found - inhabited shader not functional
[22:20:42] [Server thread/ERROR]: [dynmap] Unable to find method d for net.minecraft.server.v1_16_R1.WorldBorder
[22:20:42] [Server thread/ERROR]: Error initializing dynmap - bukkit version incompatible! initializing dynmap v3.0-SNAPSHOT-338 (Is it up to date?)
java.lang.IllegalArgumentException: Error initializing dynmap - bukkit version incompatible!
	at org.dynmap.bukkit.helper.BukkitVersionHelperGeneric.<init>(BukkitVersionHelperGeneric.java:166) ~[?:?]
	at org.dynmap.bukkit.helper.BukkitVersionHelperCB.<init>(BukkitVersionHelperCB.java:45) ~[?:?]
	at org.dynmap.bukkit.Helper.getHelper(Helper.java:47) ~[?:?]
	at org.dynmap.bukkit.DynmapPlugin.onLoad(DynmapPlugin.java:821) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.loadPlugins(CraftServer.java:382) ~[server.jar:git-Spigot-758abbe-2b00831]
	at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:186) ~[server.jar:git-Spigot-758abbe-2b00831]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:808) ~[server.jar:git-Spigot-758abbe-2b00831]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[server.jar:git-Spigot-758abbe-2b00831]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
```

**Comment by Blueeyestar** [comment]
I can confirm that. But that was clear to me ..... is the problem with every version. Now new materials are also being added. Let's keep our fingers crossed that they can fix it again :)

**Comment by aBitEmberous** [comment]
Most likely wont take that long, but we'll see

**Comment by mikeprimm** [comment]
Not supported - not accepting bugs until I say it is

**Comment by mikeprimm** [comment]
See https://www.reddit.com/r/Dynmap/ - I'll be posting status there (and on Patreon)
