### ISSUE TITLE
[Spigot 1.16.1] dynmap can't find some methods and fields

### ISSUE THREAD

**Issue by BluCobalt** [webbukkit/dynmap#2990]
When loading dynmap with the latest spigot release, the console says:
```
[23:05:43 INFO]: [dynmap] Loading dynmap v3.0-SNAPSHOT-338
[23:05:43 INFO]: [dynmap] version=git-Spigot-758abbe-2b00831 (MC: 1.16.1)
[23:05:43 ERROR]: [dynmap] Unable to find method getById for net.minecraft.server.v1_16_R1.Block
[23:05:43 ERROR]: [dynmap] Unable to find field material for net.minecraft.server.v1_16_R1.Block
[23:05:43 ERROR]: [dynmap] Unable to find method a for net.minecraft.server.v1_16_R1.BiomeBase
[23:05:43 ERROR]: [dynmap] Unable to find field y for net.minecraft.server.v1_16_R1.BiomeBase
[23:05:43 ERROR]: [dynmap] Unable to find field chunkProvider for net.minecraft.server.v1_16_R1.World
[23:05:43 INFO]: [dynmap] Unload queue not found - default to unload all chunks
[23:05:43 INFO]: [dynmap] inhabitedTicks field not found - inhabited shader not functional
[23:05:43 ERROR]: [dynmap] Unable to find method d for net.minecraft.server.v1_16_R1.WorldBorder
[23:05:43 ERROR]: Error initializing dynmap - bukkit version incompatible! initializing dynmap v3.0-SNAPSHOT-338 (Is it up to date?)
java.lang.IllegalArgumentException: Error initializing dynmap - bukkit version incompatible!
	at org.dynmap.bukkit.helper.BukkitVersionHelperGeneric.<init>(BukkitVersionHelperGeneric.java:166) ~[?:?]
	at org.dynmap.bukkit.helper.BukkitVersionHelperCB.<init>(BukkitVersionHelperCB.java:45) ~[?:?]
	at org.dynmap.bukkit.Helper.getHelper(Helper.java:47) ~[?:?]
	at org.dynmap.bukkit.DynmapPlugin.onLoad(DynmapPlugin.java:821) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.loadPlugins(CraftServer.java:382) [spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:186) [spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:808) [spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164) [spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at net.minecraft.server.v1_16_R1.MinecraftServer$$Lambda$2920/1264384309.run(Unknown Source) [spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_51]

```

...

```
[23:06:06 INFO]: [dynmap] Enabling dynmap v3.0-SNAPSHOT-338
[23:06:06 INFO]: [dynmap] Dynmap is disabled (unsupported platform)
```

**Comment by Blueeyestar** [comment]
Same problem as here - >>  https://github.com/webbukkit/dynmap/issues/2989

**Comment by EuanM199** [comment]
here's my source from my  console 
25.06 13:01:30 [Server] Server thread/INFO Loading dynmap v3.0-SNAPSHOT-338
25.06 13:01:30 [Server] Server thread/INFO version=git-Spigot-758abbe-2b00831 (MC: 1.16.1)
25.06 13:01:30 [Server] Server thread/ERROR Unable to find method getById for net.minecraft.server.v1_16_R1.Block
25.06 13:01:30 [Server] Server thread/ERROR Unable to find field material for net.minecraft.server.v1_16_R1.Block
25.06 13:01:30 [Server] Server thread/ERROR Unable to find method a for net.minecraft.server.v1_16_R1.BiomeBase
25.06 13:01:30 [Server] Server thread/ERROR Unable to find field y for net.minecraft.server.v1_16_R1.BiomeBase
25.06 13:01:30 [Server] Server thread/ERROR Unable to find field chunkProvider for net.minecraft.server.v1_16_R1.World
25.06 13:01:30 [Server] Server thread/INFO Unload queue not found - default to unload all chunks
25.06 13:01:30 [Server] Server thread/INFO inhabitedTicks field not found - inhabited shader not functional
25.06 13:01:30 [Server] Server thread/ERROR Unable to find method d for net.minecraft.server.v1_16_R1.WorldBorder
25.06 13:01:30 [Server] Server thread/ERROR Error initializing dynmap - bukkit version incompatible! initializing dynmap v3.0-SNAPSHOT-338 (Is it up to date?)

**Comment by Blueeyestar** [comment]
can nobody fix the dynmap? Such a big problem this time?

**Comment by keco185** [comment]
There's a new commit that looks like it provides some 1.16 support. Try compiling with that?

**Comment by Undeadllama** [comment]
See here and have patience:
https://www.reddit.com/r/Dynmap/comments/hft4sc/spigot_1161_support_status/

**Comment by mikeprimm** [comment]
Existing release doesn't support 1.16.1 - need to use new development builds or wait for a release that does
