### ISSUE TITLE
[dynmap] Exception while fetching chunks: java.lang.RuntimeException: Invalid length given for storage,

### ISSUE THREAD

**Issue by Blueeyestar** [webbukkit/dynmap#2992]
> [17:45:10] [Dynmap Render Thread/ERROR]: [dynmap] Exception while fetching chunks:
java.lang.RuntimeException: Invalid length given for storage, got: 320 but expected: 256
at net.minecraft.server.v1_16_R1.DataBits.<init>(SourceFile:111) ~[server.jar:git-Spigot-6f4ff1b-983305b]
at org.dynmap.bukkit.helper.v116.MapChunkCache115$NBTSnapshot.<init>(MapChunkCache115.java:214) ~[?:?]
at org.dynmap.bukkit.helper.v116.MapChunkCache115.loadChunks(MapChunkCache115.java:441) ~[?:?]
at org.dynmap.bukkit.DynmapPlugin$BukkitServer$6.call(DynmapPlugin.java:490) ~[?:?]
at org.dynmap.bukkit.DynmapPlugin$BukkitServer$6.call(DynmapPlugin.java:477) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftFuture.run(CraftFuture.java:88) ~[server.jar:git-Spigot-6f4ff1b-983305b]
at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) ~[server.jar:git-Spigot-6f4ff1b-983305b]
at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1061) ~[server.jar:git-Spigot-6f4ff1b-983305b]
at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:354) ~[server.jar:git-Spigot-6f4ff1b-983305b]
at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1009) ~[server.jar:git-Spigot-6f4ff1b-983305b]
at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:848) ~[server.jar:git-Spigot-6f4ff1b-983305b]
at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[server.jar:git-Spigot-6f4ff1b-983305b]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
> [17:45:10] [Dynmap Render Thread/ERROR]: [dynmap] Exception while fetching chunks:
java.lang.RuntimeException: Invalid length given for storage, got: 320 but expected: 256
at net.minecraft.server.v1_16_R1.DataBits.<init>(SourceFile:111) ~[server.jar:git-Spigot-6f4ff1b-983305b]
at org.dynmap.bukkit.helper.v116.MapChunkCache115$NBTSnapshot.<init>(MapChunkCache115.java:214) ~[?:?]
at org.dynmap.bukkit.helper.v116.MapChunkCache115.loadChunks(MapChunkCache115.java:441) ~[?:?]
at org.dynmap.bukkit.DynmapPlugin$BukkitServer$6.call(DynmapPlugin.java:490) ~[?:?]
at org.dynmap.bukkit.DynmapPlugin$BukkitServer$6.call(DynmapPlugin.java:477) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftFuture.run(CraftFuture.java:88) ~[server.jar:git-Spigot-6f4ff1b-983305b]
at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) ~[server.jar:git-Spigot-6f4ff1b-983305b]
at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1061) ~[server.jar:git-Spigot-6f4ff1b-983305b]
at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:354) ~[server.jar:git-Spigot-6f4ff1b-983305b]
at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1009) ~[server.jar:git-Spigot-6f4ff1b-983305b]
at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:848) ~[server.jar:git-Spigot-6f4ff1b-983305b]
at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[server.jar:git-Spigot-6f4ff1b-983305b]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
> [17:45:10] [Craft Scheduler Thread - 2/INFO]: [ajTNTRun] You are up to date! (1.2.4)
> [17:45:10] [Server thread/INFO]: [ShopChest] Loaded shop amounts
> [17:45:10] [Server thread/INFO]: [ShopChest] Loaded 24 shops in already loaded chunks
> [17:45:12] [Server thread/INFO]: [LuLuLotterie] Plugin successfully linked with vault!
> [17:45:13] [Craft Scheduler Thread - 16/INFO]: [Images] Loaded 273 images...
> [17:45:15] [User Authenticator #1/INFO]: UUID of player Cloude_Lecaw is f24df990-9c6b-4f32-938a-4c91a26d31f4
> [17:45:16] [Server thread/INFO]: [Thirst] Adding player Cloude_Lecaw with thirst 99
> [17:45:16] [Server thread/INFO]: [DiscordSRV] Player Cloude_Lecaw joined with silent joining permission, not sending a join message
> [17:45:17] [Server thread/INFO]: Cloude_Lecaw[/94.139.1.186:52488] logged in with entity id 1530 at ([world]1394.0246959253516, 19.699886750355244, -879.1408282868697)

**Comment by mikeprimm** [comment]
Fixed in newer build
