### ISSUE TITLE
Redprotect or Dynmap issues?

### ISSUE THREAD

**Issue by CloudeLecaw** [webbukkit/dynmap#3004]
We are using hte Plugin Redprotect on our Server.

At loading and reloading of the plugin we got this error in console comming out from Redprotect itself.

```
[00:02:46] [Server thread/INFO]: [RedProtect] - Loading world_nether's regions...
[00:02:46] [Server thread/INFO]: [RedProtect] - Loading world_the_end's regions...
[00:02:47] [Server thread/INFO]: [RedProtect] Auto-save Scheduler: Saving yml database every 60 minutes!
[00:02:47] [Server thread/INFO]: [RedProtect] There are 302 regions on (yml) database!
[00:02:47] [Server thread/INFO]: [RedProtect] Dynmap found. Hooked.
[00:02:47] [Server thread/INFO]: [RedProtect] Loading dynmap markers...
[00:02:47] [Server thread/WARN]: java.lang.NullPointerException
[00:02:47] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.Bukkit.hooks.DynmapHook.<init>(DynmapHook.java:51)
[00:02:47] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.Bukkit.hooks.HooksManager.registerHooksLast(HooksManager.java:183)
[00:02:47] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.Bukkit.RedProtect.startLoad(RedProtect.java:215)
[00:02:47] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.Bukkit.RedProtect.reload(RedProtect.java:152)
[00:02:47] [Server thread/WARN]: 	at br.net.fabiozumbi12.RedProtect.Bukkit.commands.CommandHandler.onCommand(CommandHandler.java:584)
[00:02:47] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[00:02:47] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[00:02:47] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:792)
[00:02:47] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchServerCommand(CraftServer.java:754)
[00:02:47] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:411)
[00:02:47] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:378)
[00:02:47] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1212)
[00:02:47] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000)
[00:02:47] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[00:02:47] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:832)
```

We are not sure if this error is related to RedProtect or Dynmap so we postet this issues in both githubs

**Comment by PryPurity** [comment]
If you are still experiencing this, have you tried unloading Dynmap/RedProtect one at a time?

**Comment by CloudeLecaw** [comment]
```
>.... [21:28:38 INFO]: [RedProtect] Loading dynmap markers...
>.... [21:28:38 WARN]: java.lang.NullPointerException
>.... [21:28:38 WARN]: at br.net.fabiozumbi12.RedProtect.Bukkit.hooks.DynmapHook.<init>(DynmapHook.java:51)
>.... [21:28:38 WARN]: at br.net.fabiozumbi12.RedProtect.Bukkit.hooks.HooksManager.registerHooksLast(HooksManager.java:183)
>.... [21:28:38 WARN]: at br.net.fabiozumbi12.RedProtect.Bukkit.RedProtect.startLoad(RedProtect.java:230)
>.... [21:28:38 WARN]: at br.net.fabiozumbi12.RedProtect.Bukkit.RedProtect.reload(RedProtect.java:168)
>.... [21:28:38 WARN]: at br.net.fabiozumbi12.RedProtect.Bukkit.commands.CommandHandler.onCommand(CommandHandler.java:584)
>.... [21:28:38 WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
>.... [21:28:38 WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
>.... [21:28:38 WARN]: at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:794)
>.... [21:28:38 WARN]: at net.minecraft.server.v1_16_R1.PlayerConnection.handleCommand(PlayerConnection.java:1912)
>.... [21:28:38 WARN]: at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1723)
>.... [21:28:38 WARN]: at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
>.... [21:28:38 WARN]: at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
>.... [21:28:38 WARN]: at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23)
>.... [21:28:38 WARN]: at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18)
>.... [21:28:38 WARN]: at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
>.... [21:28:38 WARN]: at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
>.... [21:28:38 WARN]: at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
>.... [21:28:38 WARN]: at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1136)
>.... [21:28:38 WARN]: at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1129)
>.... [21:28:38 WARN]: at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
>.... [21:28:38 WARN]: at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1090)
>.... [21:28:38 WARN]: at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1004)
>.... [21:28:38 WARN]: at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
>.... [21:28:38 WARN]: at java.lang.Thread.run(Thread.java:748)
```
happend when i  do /rp reload to reload RedProted config

**Comment by PryPurity** [comment]
Is this with Dynmap still loaded? Or with just RedProtect by itself?

**Comment by FedUpWith-Tech** [comment]
This is an issue with RedProtect not dynmap, the error log clearly shows that redprotect is unable to hook into dynmap which means they will need to fix it. Please take up a github issue with them
