### ISSUE TITLE
crashes the game

### ISSUE THREAD

**Issue by pro100flemeng** [webbukkit/dynmap#3017]
after clicking on a wooden or stone button inside the game it crashes out of the game (1.15.2)

---- Minecraft Crash Report ----
// Don't do that.

Time: 09.07.20 10:46
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at org.dynmap.forge_1_15_2.DynmapPlugin$WorldTracker.handleBlockEvent(DynmapPlugin.java:1793) ~[?:?] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_27_WorldTracker_handleBlockEvent_BlockEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onNeighborNotify(ForgeEventFactory.java:158) ~[?:?] {re:classloading}
	at net.minecraft.world.World.func_195593_d(World.java:274) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.block.AbstractButtonBlock.func_196368_e(SourceFile:201) ~[?:?] {re:classloading}
	at net.minecraft.block.AbstractButtonBlock.func_226910_d_(SourceFile:118) ~[?:?] {re:classloading}
	at net.minecraft.block.AbstractButtonBlock.func_225533_a_(SourceFile:111) ~[?:?] {re:classloading}
	at net.minecraft.block.BlockState.func_227031_a_(BlockState.java:401) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.multiplayer.PlayerController.func_217292_a(PlayerController.java:287) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.optifine.override.PlayerControllerOF.func_217292_a(PlayerControllerOF.java:98) ~[?:?] {re:classloading}
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1281) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:1542) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1375) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:904) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:553) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:204) ~[SURVIVAL.jar:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.15.2-31.2.30.jar:31.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.0.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.dynmap.forge_1_15_2.DynmapPlugin$WorldTracker.handleBlockEvent(DynmapPlugin.java:1793)
	at net.minecraftforge.eventbus.ASMEventHandler_27_WorldTracker_handleBlockEvent_BlockEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.event.ForgeEventFactory.onNeighborNotify(ForgeEventFactory.java:158)
	at net.minecraft.world.World.func_195593_d(World.java:274)
	at net.minecraft.block.AbstractButtonBlock.func_196368_e(SourceFile:201)
	at net.minecraft.block.AbstractButtonBlock.func_226910_d_(SourceFile:118)
	at net.minecraft.block.AbstractButtonBlock.func_225533_a_(SourceFile:111)
	at net.minecraft.block.BlockState.func_227031_a_(BlockState.java:401)
	at net.minecraft.client.multiplayer.PlayerController.func_217292_a(PlayerController.java:287)
	at net.optifine.override.PlayerControllerOF.func_217292_a(PlayerControllerOF.java:98)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1281)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:1542)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['FLEMENG'/139, l='MpServer', x=4758.68, y=69.00, z=-270.63]]
	Chunk stats: Client Chunk Cache: 441, 255
	Level dimension: DimensionType{minecraft:overworld}
	Level name: MpServer
	Level seed: 5760506714578077967
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (0,63,5), Chunk: (at 0,3,5 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1214622 game time, 1801363 day time
	Known server brands: 
	Level was modded: false
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:611)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1763)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:572)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_251, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 15303729528 bytes (14594 MB) / 17112760320 bytes (16320 MB) up to 17112760320 bytes (16320 MB)
	CPUs: 6
	JVM Flags: 10 total; -Xmn128M -Xmx16297M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.1.0+69+master.79f13f7
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.2.30.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.30.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.3-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.2.30.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.30.jar runtimedistcleaner PLUGINSERVICE 
		/preview_OptiFine_1.15.2_HD_U_G1_pre30.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.15.2-31.2.30.jar fml TRANSFORMATIONSERVICE 
	FML: 31.2
	Forge: net.minecraftforge:31.2.30
	FML Language Providers: 
		javafml@31.2
		minecraft@1
	Mod List: 
		forge-1.15.2-31.2.30-client.jar Minecraft {minecraft@1.15.2 DONE}
		Dynmap-3.0.1-forge-1.15.2.jar Dynmap {dynmap@3.0.1-343 DONE}
		%5b1.15.2%5d+BobLib+v0.1.9.jar BobLib {boblib@0.1.9 DONE}
		forge-1.15.2-31.2.30-universal.jar Forge {forge@31.2.30 DONE}
		%5b1.15.2%5d+Armor+Status+HUD+v1.3.5.jar Armor Status HUD {armorstatushud@1.3.5 DONE}
		LagsLib-1.15.2-1.0.0.jar Lag's Lib {lagslib@1.0.0 DONE}
		ironchest_1.15.2_10.0.3.jar Iron Chests {ironchest@1.15.2-10.0.1 DONE}
		jei-1.15.2-6.0.2.12.jar Just Enough Items {jei@6.0.2.12 DONE}
	Launched Version: SURVIVAL
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 451.48, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: Русский (Россия)
	CPU: 6x Intel(R) Core(TM) i5-9500F CPU @ 3.00GHz
	OptiFine Version: OptiFine_1.15.2_HD_U_G1_pre30
	OptiFine Build: 20200622-083032
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 451.48
	OpenGlRenderer: GeForce GTX 1060 6GB/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 6

**Comment by FedUpWith-Tech** [comment]
dynmap is a server side plugin not a client side plugin. It appears that you are trying to create a client-side server (open to lan) and run dynmap which is not supported
