### ISSUE TITLE
ArrayIndexOutOfBoundsException when trying to render the nether roof

### ISSUE THREAD

**Issue by dkfdevil** [webbukkit/dynmap#3043]
[11:11:32 ERROR]: [dynmap] Exception during render job: world=WLLBYUG_nether, map=null
[11:11:32 WARN]: java.lang.ArrayIndexOutOfBoundsException: 16
[11:11:32 WARN]: 	at org.dynmap.bukkit.helper.v116.MapChunkCache115$NBTSnapshot.getBlockType(MapChunkCache115.java:284)
[11:11:32 WARN]: 	at org.dynmap.bukkit.helper.AbstractMapChunkCache$BasetMapIterator.getBlockType(AbstractMapChunkCache.java:138)
[11:11:32 WARN]: 	at org.dynmap.hdmap.IsoHDPerspective.render(IsoHDPerspective.java:1260)
[11:11:32 WARN]: 	at org.dynmap.hdmap.HDMapTile.render(HDMapTile.java:79)
[11:11:32 WARN]: 	at org.dynmap.MapManager$FullWorldRenderState.processTile(MapManager.java:789)
[11:11:32 WARN]: 	at org.dynmap.MapManager$FullWorldRenderState.run(MapManager.java:720)
[11:11:32 WARN]: 	at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1.run(MapManager.java:229)
[11:11:32 WARN]: 	at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$2.run(MapManager.java:245)
[11:11:32 WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[11:11:32 WARN]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[11:11:32 WARN]: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
[11:11:32 WARN]: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
[11:11:32 WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[11:11:32 WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[11:11:32 WARN]: 	at java.lang.Thread.run(Unknown Source)
[11:11:46 ERROR]: [dynmap] Exception during render job: world=WLLBYUG_nether, map=null
[11:11:46 WARN]: java.lang.ArrayIndexOutOfBoundsException
[11:11:57 ERROR]: [dynmap] Exception during render job: world=WLLBYUG_nether, map=null
[11:11:57 WARN]: java.lang.ArrayIndexOutOfBoundsException
[11:11:57 ERROR]: [dynmap] Exception during render job: world=WLLBYUG_nether, map=null
[11:11:57 WARN]: java.lang.ArrayIndexOutOfBoundsException

[11:12:06 ERROR]: [dynmap] Exception during render job: world=WLLBYUG_nether, map=null
[11:12:06 WARN]: java.lang.ArrayIndexOutOfBoundsException

[11:12:14 ERROR]: [dynmap] Exception during render job: world=WLLBYUG_nether, map=null
[11:12:14 WARN]: java.lang.ArrayIndexOutOfBoundsException
[11:12:15 ERROR]: [dynmap] Exception during render job: world=WLLBYUG_nether, map=null
[11:12:15 WARN]: java.lang.ArrayIndexOutOfBoundsException
[11:12:19 INFO]: dkfd3vil issued server command: /dynmap updaterender
[11:12:23 ERROR]: [dynmap] Exception during render job: world=WLLBYUG_nether, map=null
[11:12:23 WARN]: java.lang.ArrayIndexOutOfBoundsException

**Comment by FedUpWith-Tech** [comment]
its because your map is "null" can you pastebin your configuration.txt, worlds.txt, and customperspectives.txt

**Comment by dkfdevil** [comment]
I fixed it when i changed the nether roof maxium height from 256 to 200
