### ISSUE TITLE
Forge Server Crash 1.16.1

### ISSUE THREAD

**Issue by Marbel** [webbukkit/dynmap#3044]
My Forge Server crash directly at startup with dynmap installed. Do you have an idea what it could be?

Forge Server: forge-1.16.1-32.0.70
Java Version: openjdk version "1.8.0_252"
Dynmap Version: Dynmap-3.1-beta-2-forge-1.16.1

logs: https://pastebin.com/TCJDdkE5

logs raw: 
```
[27Jul2020 10:16:27.228] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: net.minecraftforge.fml.event.server.FMLServerStartingEvent.getCommandDispatcher()Lcom/mojang/brigadier/CommandDispatcher;
        Index: 5
        Listeners:
                0: NORMAL
                1: net.minecraftforge.eventbus.EventBus$$Lambda$2542/1531416235@3cc72488
                2: ASM: class com.lilypuree.decorative_blocks.setup.ModSetup onServerSetUp(Lnet/minecraftforge/fml/event/server/FMLServerStartingEvent;)V
                3: ASM: com.jaquadro.minecraft.storagedrawers.StorageDrawers@76f64716 onServerStarting(Lnet/minecraftforge/fml/event/server/FMLServerStartingEvent;)V
                4: net.minecraftforge.eventbus.EventBus$$Lambda$2542/1531416235@76f4687
                5: ASM: org.dynmap.forge_1_16_1.DynmapMod@1ac380bd onServerStarting(Lnet/minecraftforge/fml/event/server/FMLServerStartingEvent;)V
                6: net.minecraftforge.eventbus.EventBus$$Lambda$2542/1531416235@687742fd
                7: net.minecraftforge.eventbus.EventBus$$Lambda$2542/1531416235@149c46fe
                8: net.minecraftforge.eventbus.EventBus$$Lambda$2542/1531416235@117ad381
                9: net.minecraftforge.eventbus.EventBus$$Lambda$2542/1531416235@6c5ce457
java.lang.NoSuchMethodError: net.minecraftforge.fml.event.server.FMLServerStartingEvent.getCommandDispatcher()Lcom/mojang/brigadier/CommandDispatcher;
        at org.dynmap.forge_1_16_1.DynmapMod.onServerStarting(DynmapMod.java:112)
        at net.minecraftforge.eventbus.ASMEventHandler_168_DynmapMod_onServerStarting_FMLServerStartingEvent.invoke(.dynamic)
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
        at net.minecraftforge.fml.server.ServerLifecycleHooks.handleServerStarting(ServerLifecycleHooks.java:104)
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:200)
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:622)
        at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:230)
        at java.lang.Thread.run(Thread.java:748)

[27Jul2020 10:16:27.229] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
java.lang.NoSuchMethodError: net.minecraftforge.fml.event.server.FMLServerStartingEvent.getCommandDispatcher()Lcom/mojang/brigadier/CommandDispatcher;
        at org.dynmap.forge_1_16_1.DynmapMod.onServerStarting(DynmapMod.java:112) ~[?:?]
        at net.minecraftforge.eventbus.ASMEventHandler_168_DynmapMod_onServerStarting_FMLServerStartingEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.2.0-service.jar:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.0-service.jar:?]
        at net.minecraftforge.fml.server.ServerLifecycleHooks.handleServerStarting(ServerLifecycleHooks.java:104) ~[?:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:200) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:622) ~[?:?]
        at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:230) ~[?:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
```

**Comment by NickPancakes** [comment]
This is due to getCommandDispatcher() being removed in Forge 32.0.67 via this PR: https://github.com/MinecraftForge/MinecraftForge/pull/6969

You'll either need to downgrade to 32.0.66 (if that doesn't break any other mods you're using), or wait dynmap is updated to use Forge's new API for registering commands.

**Comment by Marbel** [comment]
Thanks for the explanation :)

**Comment by LeScooter** [comment]
Same issue I had with my own mod. I hope this gets fixed soon because I find Dynmap incredibly useful for my build server. 😄

**Comment by mikeprimm** [comment]
Obsolete at this point - only 1.16.5 supported for Forge 1.16.x
