### ISSUE TITLE
[dynmap] Task #8526 for dynmap v3.1-beta-2-389 generated an exception 

### ISSUE THREAD

**Issue by svenlameir** [webbukkit/dynmap#3066]
[dynmap] Task #8526 for dynmap v3.1-beta-2-389 generated an exception
java.util.ConcurrentModificationException: null
at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445) ~[?:1.8.0_262]
at java.util.HashMap$KeyIterator.next(HashMap.java:1469) ~[?:1.8.0_262]
at org.dynmap.markers.impl.MarkerAPIImpl$DoFileWrites.run(MarkerAPIImpl.java:352) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.1.jar:git-Paper-131]
at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.1.jar:git-Paper-131]
at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1292) ~[patched_1.16.1.jar:git-Paper-131]
at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.1.jar:git-Paper-131]
at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1213) ~[patched_1.16.1.jar:git-Paper-131]
at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1001) ~[patched_1.16.1.jar:git-Paper-131]
at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-131]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]

**Comment by FedUpWith-Tech** [comment]
Hey! Can you please give us some more info on this error? What happened right before this, is a repeating error? does it cause a server crash? What other plugins do you have installed? This almost looks to me like a write permissions error or a filesystem lockup error but I can't tell with the limited information given.

**Comment by svenlameir** [comment]
Nothing special happend before, no commands or anything where used. This is a random error i get multiple times a day.
It doesn NOT cause a crash.
Here is a plugin list:
`AdvancedHelp, BetterEnd, BlockyRanks, ChatManager, CoreProtect, CosmicVaults, CrazyCrates, dynmap*, Dynmap-Towny, Essentials, EssentialsProtect, EssentialsSpawn, HolographicDisplays, HolographicPlaceholders, Jobs, LuckPerms, LWC, Maintenance, Matrix, mcMMO, PlaceholderAPI, Plan, PlayerHeads, ProtocolLib, StaffPlus, TAB, Towny, TownyChat, TownyNameUpdater, Vault, Virtualshop, Votifier, VotingPlugin, WorldEdit, WorldGuard`

If you need any more info let me know!

**Comment by Bjarno** [comment]
I just had a similar error happen when I was shutting down my server (via /stop). The error is not exactly the same (different stack trace), but it's also a `java.util.ConcurrentModificationException` so it might be related (hurray for multi-threading!). If not, I'll make a separate issue.

```
[16:34:50] [Server thread/INFO]: [dynmap] Disabling dynmap v3.1-beta-2-389
[16:34:50] [Server thread/INFO]: [dynmap] Unloaded 11 components.
[16:34:50] [Server thread/INFO]: [dynmap] Stopping map renderer...
[16:34:50] [Server thread/INFO]: [dynmap] Saved 1397 pending tile renders in world 'world'
[16:34:50] [Server thread/ERROR]: Error occurred while disabling dynmap v3.1-beta-2-389 (Is it up to date?)
java.util.ConcurrentModificationException: null
        at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:966) ~[?:1.8.0_262]
        at java.util.LinkedList$ListItr.next(LinkedList.java:888) ~[?:1.8.0_262]
        at org.dynmap.MapManager$FullWorldRenderState.saveState(MapManager.java:459) ~[?:?]
        at org.dynmap.MapManager.savePending(MapManager.java:1532) ~[?:?]
        at org.dynmap.MapManager.stopRendering(MapManager.java:1618) ~[?:?]
        at org.dynmap.DynmapCore.disableCore(DynmapCore.java:961) ~[?:?]
        at org.dynmap.bukkit.DynmapPlugin.onDisable(DynmapPlugin.java:998) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.16.1.jar:git-Paper-131]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415) ~[patched_1.16.1.jar:git-Paper-131]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[patched_1.16.1.jar:git-Paper-131]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:502) ~[patched_1.16.1.jar:git-Paper-131]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:495) ~[patched_1.16.1.jar:git-Paper-131]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.disablePlugins(CraftServer.java:434) ~[patched_1.16.1.jar:git-Paper-131]
        at net.minecraft.server.v1_16_R1.MinecraftServer.stop(MinecraftServer.java:775) ~[patched_1.16.1.jar:git-Paper-131]
        at net.minecraft.server.v1_16_R1.DedicatedServer.stop(DedicatedServer.java:699) ~[patched_1.16.1.jar:git-Paper-131]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1048) ~[patched_1.16.1.jar:git-Paper-131]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-131]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
[16:34:50] [Dynmap Render Thread/INFO]: [dynmap] Paused Full render for world 'world' - world unloaded
```

**Comment by FedUpWith-Tech** [comment]
So I think this is a paper specific bug unfortunately, if either of you can test this on a spigot server (changing no other configs) that would be greatly appreciated. I don't get this error on my paper server and havent seen any similar traces on spigot yet. 

If I'd have to guess paper tries to run something async that isn't async capable on dynmap

**Comment by Bjarno** [comment]
I'll try to do that later this week. The issue is that it's difficult to replicate this behaviour as even on Spigot, I don't always get this error at all when stopping the server, and I have not observed this error while the server is running (unlike @ArtamaMeyer).

**Comment by FedUpWith-Tech** [comment]
You basically described 90% of the open issues lol, many people experience them but I can't replicate them

**Comment by FedUpWith-Tech** [comment]
@Bjarno were you able to replicate this?
