### ISSUE TITLE
Can not load Dynmap with paper 1.16.3

### ISSUE THREAD

**Issue by k-jiang** [webbukkit/dynmap#3130]
**Issue Description:** *Can not load Dynmap with Paperspigot 1.16.3. Exception during server startup*

* **Dynmap Version:** *3.1 beta 3a*
* **Server Version:** *Paper 1.16.3 build 199*
* **Error**: *
```
[15:57:00] [Server thread/INFO]: [dynmap] Enabling dynmap v3.1-beta3a-409*
[15:57:05] [Server thread/ERROR]: Error occurred while enabling dynmap v3.1-beta3a-409 (Is it up to date?)
java.lang.NoSuchMethodError: net/minecraft/server/v1_16_R2/MinecraftServer.aX()Lnet/minecraft/server/v1_16_R2/IRegistryCustom; (loaded from file:/server/dynmap-paper/cache/patched_1.16.3.jar by sun.misc$
        at org.dynmap.bukkit.helper.v116_2.BukkitVersionHelperSpigot116_2.getBiomeReg(BukkitVersionHelperSpigot116_2.java:70) ~[?:?]
        at org.dynmap.bukkit.helper.v116_2.BukkitVersionHelperSpigot116_2.getBiomeBaseList(BukkitVersionHelperSpigot116_2.java:84) ~[?:?]
        at org.dynmap.bukkit.DynmapPlugin.loadExtraBiomes(DynmapPlugin.java:781) ~[?:?]
        at org.dynmap.bukkit.DynmapPlugin.onEnable(DynmapPlugin.java:856) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.3.jar:git-Paper-197]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.3.jar:git-Paper-197]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.3.jar:git-Paper-197]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.3.jar:git-Paper-197]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.3.jar:git-Paper-197]
        at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.3.jar:git-Paper-197]
        at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:237) ~[patched_1.16.3.jar:git-Paper-197]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.3.jar:git-Paper-197]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-197]
        at net.minecraft.server.v1_16_R2.MinecraftServer$$Lambda$3051.00000000CD411FB0.run(Unknown Source) ~[?:?]
        at java.lang.Thread.run(Thread.java:813) [?:1.8.0_212]
[16:02:33 INFO]: [dynmap] Disabling dynmap v3.1-beta3a-409
```

 [ ] *I have looked at all other issues and this is not a duplicate*  
 [ ] *I have been able to replicate this*

**Comment by FedUpWith-Tech** [comment]
Please use the latest dev build for 1.16.3

Release beta 3a doesn't work for 1.16.3
