### ISSUE TITLE
Dynmap doesn't even start

### ISSUE THREAD

**Issue by Polda18** [webbukkit/dynmap#3135]
**Issue Description:** When enabling (we're using PlugMan for this purpose), it doesn't even start. This is console dump:
```
plugman enable dynmap
[20:24:45 INFO]: [dynmap] Enabling dynmap v3.1-beta3a-409*
[20:24:45 WARN]: Enabled plugin with unregistered PluginClassLoader dynmap v3.1-beta3a-409
[20:24:45 ERROR]: Error occurred while enabling dynmap v3.1-beta3a-409 (Is it up to date?)
java.lang.IllegalStateException: zip file closed
at java.util.zip.ZipFile.ensureOpen(ZipFile.java:686) ~[?:1.8.0_262]
at java.util.zip.ZipFile.getEntry(ZipFile.java:315) ~[?:1.8.0_262]
at java.util.jar.JarFile.getEntry(JarFile.java:240) ~[?:1.8.0_262]
at java.util.jar.JarFile.getJarEntry(JarFile.java:223) ~[?:1.8.0_262]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:133) ~[patched_1.16.3.jar:git-Paper-195]
at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:216) ~[patched_1.16.3.jar:git-Paper-195]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[patched_1.16.3.jar:git-Paper-195]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.16.3.jar:git-Paper-195]
at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_262]
at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_262]
at org.dynmap.bukkit.DynmapPlugin.registerPlayerLoginListener(DynmapPlugin.java:1154) ~[?:?]
at org.dynmap.bukkit.DynmapPlugin.onEnable(DynmapPlugin.java:859) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.3.jar:git-Paper-195]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.3.jar:git-Paper-195]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.3.jar:git-Paper-195]
at com.rylinaux.plugman.util.PluginUtil.enable(PluginUtil.java:62) ~[?:?]
at com.rylinaux.plugman.command.EnableCommand.execute(EnableCommand.java:127) ~[?:?]
at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.3.jar:git-Paper-195]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.3.jar:git-Paper-195]
at org.bukkit.craftbukkit.v1_16_R2.CraftServer.dispatchCommand(CraftServer.java:800) ~[patched_1.16.3.jar:git-Paper-195]
at org.bukkit.craftbukkit.v1_16_R2.CraftServer.dispatchServerCommand(CraftServer.java:762) ~[patched_1.16.3.jar:git-Paper-195]
at net.minecraft.server.v1_16_R2.DedicatedServer.handleCommandQueue(DedicatedServer.java:405) ~[patched_1.16.3.jar:git-Paper-195]
at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:372) ~[patched_1.16.3.jar:git-Paper-195]
at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211) ~[patched_1.16.3.jar:git-Paper-195]
at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.3.jar:git-Paper-195]
at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-195]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
[20:24:45 INFO]: [dynmap] Disabling dynmap v3.1-beta3a-409
[20:24:45 ERROR]: Error occurred while disabling dynmap v3.1-beta3a-409 (Is it up to date?)
java.lang.NullPointerException: null
at org.dynmap.bukkit.DynmapPlugin.onDisable(DynmapPlugin.java:998) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.16.3.jar:git-Paper-195]
at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415) ~[patched_1.16.3.jar:git-Paper-195]
at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[patched_1.16.3.jar:git-Paper-195]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:384) ~[patched_1.16.3.jar:git-Paper-195]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.3.jar:git-Paper-195]
at com.rylinaux.plugman.util.PluginUtil.enable(PluginUtil.java:62) ~[?:?]
at com.rylinaux.plugman.command.EnableCommand.execute(EnableCommand.java:127) ~[?:?]
at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.3.jar:git-Paper-195]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.3.jar:git-Paper-195]
at org.bukkit.craftbukkit.v1_16_R2.CraftServer.dispatchCommand(CraftServer.java:800) ~[patched_1.16.3.jar:git-Paper-195]
at org.bukkit.craftbukkit.v1_16_R2.CraftServer.dispatchServerCommand(CraftServer.java:762) ~[patched_1.16.3.jar:git-Paper-195]
at net.minecraft.server.v1_16_R2.DedicatedServer.handleCommandQueue(DedicatedServer.java:405) ~[patched_1.16.3.jar:git-Paper-195]
at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:372) ~[patched_1.16.3.jar:git-Paper-195]
at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211) ~[patched_1.16.3.jar:git-Paper-195]
at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.3.jar:git-Paper-195]
at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-195]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
```

* **Dynmap Version:** v3.1-beta-3a
* **Server Version:** paper 1.16.3 build git-Paper-195
* **Pastebin of Configuration.txt:** https://hasteb.in/upuwevub.yaml
* **Server Host (if applicable):** self-hosted (server domain: mc.7biom.cz or play.7biom.cz)
* **Pastebin of crashlogs or other relevant logs:** No idea where to find this file 🤷‍♂️
* **Other Relevant Data/Screenshots:** Not applicable
* **Steps to Replicate:** Enable plugin or restart server.

 [ ] *I have looked at all other issues and this is not a duplicate* - This issue should be fixed ASAP, feel free to merge with another issue if duplicate...
 [x] *I have been able to replicate this*

**Comment by Polda18** [comment]
Nevermind, beta4 seems to have this issue fixed. You should update Spigot listing page, though...
