### ISSUE TITLE
Exception during render job in nether

### ISSUE THREAD

**Issue by gitlias** [webbukkit/dynmap#3149]
**Issue Description:** *I get the following error when rendering anything other than top down perspective in the nether.*

> [09:54:53 ERROR]: [dynmap] Exception during render job: world=world_nether, map=org.dynmap.hdmap.HDMap@2e9de739
> [09:54:53 WARN]: java.lang.ArrayIndexOutOfBoundsException: Index 16 out of bounds for length 16
> [09:54:53 WARN]:        at org.dynmap.bukkit.helper.v116_3.MapChunkCache116_3$NBTSnapshot.getBlockType(MapChunkCache116_3.java:282)
> [09:54:53 WARN]:        at org.dynmap.bukkit.helper.AbstractMapChunkCache$BasetMapIterator.getBlockType(AbstractMapChunkCache.java:138)
> [09:54:53 WARN]:        at org.dynmap.hdmap.IsoHDPerspective.render(IsoHDPerspective.java:1260)
> [09:54:53 WARN]:        at org.dynmap.hdmap.HDMapTile.render(HDMapTile.java:79)
> [09:54:53 WARN]:        at org.dynmap.MapManager$FullWorldRenderState.processTile(MapManager.java:804)
> [09:54:53 WARN]:        at org.dynmap.MapManager$FullWorldRenderState.run(MapManager.java:720)
> [09:54:53 WARN]:        at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1.run(MapManager.java:229)
> [09:54:53 WARN]:        at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$2.run(MapManager.java:245)
> [09:54:53 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
> [09:54:53 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> [09:54:53 WARN]:        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
> [09:54:53 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> [09:54:53 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> [09:54:53 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)

* **Dynmap Version:** *Dynmap-3.1-beta4-spigot*
* **Server Version:** *paper 1.16.3 220*
* **Pastebin of Configuration.txt:** *https://pastebin.com/b0jRDz24*
* **Server Host (if applicable):** *Selfhosted*
* **Pastebin of worlds.txt:** *https://pastebin.com/25ZJDn19*
* **Pastebin of custom-perspectives.txt used:** *https://pastebin.com/yZ1UuwtU*
* **Steps to Replicate:** *Use the supplied files and start a full render for the nether, works for a few chunks and then errors out*

-  [X] *I have looked at all other issues and this is not a duplicate (I did find one but it was closed due to no answer)*  
-  [X] *I have been able to replicate this*

**Comment by Numerok** [comment]
Getting the same "java.lang.ArrayIndexOutOfBoundsException: 16" on "Dynmap-3.1-beta4-fabric-1.16.2" fabric server in overworld

**Comment by MitchTalmadge** [comment]
Same problem:

```
[dynmap]: Execution exception while processing tile:
java.lang.ArrayIndexOutOfBoundsException: Index 16 out of bounds for length 16
at org.dynmap.bukkit.helper.v116_4.MapChunkCache116_4$NBTSnapshot.getBlockType(MapChunkCache116_4.java:273) ~[?:?]
at org.dynmap.bukkit.helper.AbstractMapChunkCache$BasetMapIterator.getBlockType(AbstractMapChunkCache.java:138) ~[?:?]
at org.dynmap.hdmap.IsoHDPerspective.render(IsoHDPerspective.java:1260) ~[?:?]
at org.dynmap.hdmap.HDMapTile.render(HDMapTile.java:79) ~[?:?]
at org.dynmap.MapManager$FullWorldRenderState.processTile(MapManager.java:804) ~[?:?]
at org.dynmap.MapManager$FullWorldRenderState.access$1300(MapManager.java:262) ~[?:?]
at org.dynmap.MapManager$FullWorldRenderState$3.call(MapManager.java:686) ~[?:?]
at org.dynmap.MapManager$FullWorldRenderState$3.call(MapManager.java:684) ~[?:?]
at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
at java.lang.Thread.run(Thread.java:834) [?:?]
```



**Edit: Solved;** my bad. I was using a custom perspective where I had set the max height to 256, should have been 255.

**Comment by FedUpWith-Tech** [comment]
Assuming this is fixed in a later release or otherwise no longer relevant- please open a new issue if this persists.
