### ISSUE TITLE
[Fabric 1.16.4] Crash on world load, after a big part got pregenerated. 

### ISSUE THREAD

**Issue by canitzp** [webbukkit/dynmap#3204]
This October I get this crash after starting the server with dynmap installed. Without it the world loads fine and is perfectly playable. I waited for beta-5 but the problem wasn't resolved. I also reinstalled fabric and checked all the other mods for updates today.
Providing the world for testing is possible but hard, since the compressed world folder alone is over 9GB in size. I also ran the world locally through the "Minecraft Region Fixer" tool and started it with vanilla 1.6.4 with the --forceUpgrade and --eraseCache argument.

<details>
  <summary>crash report</summary>
  
  ```
  ---- Minecraft Crash Report ----
// My bad.

Time: 11/27/20, 3:08 PM
Description: Exception in server tick loop

java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at org.dynmap.utils.TileFlags.load(TileFlags.java:53)
	at org.dynmap.MapTypeState.restore(MapTypeState.java:107)
	at org.dynmap.MapManager.loadPending(MapManager.java:1446)
	at org.dynmap.MapManager.loadWorld(MapManager.java:1413)
	at org.dynmap.DynmapCore.processWorldLoad(DynmapCore.java:2087)
	at org.dynmap.fabric_1_16_2.DynmapPlugin.onStart(DynmapPlugin.java:526)
	at org.dynmap.fabric_1_16_2.DynmapPlugin.serverStarted(DynmapPlugin.java:291)
	at net.minecraft.server.MinecraftServer.handler$zfp000$loadWorld(MinecraftServer.java:2201)
	at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java)
	at net.minecraft.class_3176.method_3823(class_3176.java:179)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:645)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:834)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Linux (amd64) version 5.4.73-1-pve
	Java Version: 11.0.6, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 7558135808 bytes (7208 MB) / 9663676416 bytes (9216 MB) up to 9663676416 bytes (9216 MB)
	CPUs: 4
	JVM Flags: 14 total; -Xmx9216M -Xms9216M -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:-OmitStackTraceInFastThrow -XX:G1NewSizePercent=40 -XX:G1MaxNewSizePercent=50 -XX:G1HeapRegionSize=16M -XX:G1ReservePercent=15 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=8
	Fabric Mods: 
		chunkpregen: Fabric Chunk Pregenerator 0.3.3
		dynmap: Dynmap 3.1-beta5
		fabric: Fabric API 0.26.3+1.16
		fabric-api-base: Fabric API Base 0.2.0+ab87788d3a
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.0+2e23b97c3a
		fabric-command-api-v1: Fabric Command API (v1) 1.0.9+6a2618f53a
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+6a2618f53a
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+6a2618f53a
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+6a2618f53a
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d3a
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+6a2618f53a
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+6a2618f53a
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.3+a4467d2a3a
		fabric-item-api-v1: Fabric Item API (v1) 1.2.0+6a2618f53a
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.1+6a2618f53a
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+6a2618f53a
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+6a2618f53a
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+6a2618f53a
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+6a2618f53a
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+6a2618f53a
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.2+6a2618f53a
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.1+6a2618f53a
		fabric-particles-v1: fabric-particles-v1 0.2.2+6a2618f53a
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.1+285766753a
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+6a2618f53a
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.3.2+1944f3e03a
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+6a2618f53a
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.1+f1d8af063a
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.0.3+6a2618f53a
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.5+6a2618f53a
		fabricloader: Fabric Loader 0.10.8
		leaf-decay: Leaf Decay 1.2.0-1.16.1
		lithium: Lithium 0.6.0
		lithium-api: Lithium API 0.6.0
		minecraft: Minecraft 1.16.4
		phosphor: Phosphor 0.6.0+build.7
	Player Count: 0 / 15; []
	Data Packs: vanilla, file/multiplayer_sleep_1.0.1 (incompatible), file/anti_enderman_grief_v1.0.0, fabric/fabric-tool-attribute-api-v1
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)
  ```
  
</details>

**Comment by Genau6502** [comment]
You need to use the fabric 1.16.4 version, still in PR here https://github.com/webbukkit/dynmap/pull/3174 and build yourself

**Comment by canitzp** [comment]
@yitzy299 I can confirm the issue you linked, but the issue I had is different. To solve it I had to delete the dynmap folder and let it recreate (While recreating I noticed the 1.16.4 Fabric problem)
