### ISSUE TITLE
Error in Console on reloadof plugin (RedProtect)

### ISSUE THREAD

**Issue by CloudeLecaw** [webbukkit/dynmap#3256]
issue accour when your using dynmap together with Redportect and try to reload the  plugin with /rp reload

Issue still exists on RP Reload

it this bug comming from dynmap? or from RedProtect?
There seems to be a problem with reloading the markers..

```
>.... [09:06:47 INFO]: [RedProtect] There are 357 regions on (yml) database!
>.... [09:06:47 INFO]: [RedProtect] Dynmap found. Hooked.
>.... [09:06:47 INFO]: [RedProtect] Loading dynmap markers...
>.... [09:06:47 WARN]: java.lang.NullPointerException
>.... [09:06:47 WARN]: at br.net.fabiozumbi12.RedProtect.Bukkit.hooks.DynmapHook.<init>(DynmapHook.java:57)
>.... [09:06:47 WARN]: at br.net.fabiozumbi12.RedProtect.Bukkit.hooks.HooksManager.registerHooksLast(HooksManager.java:183)
>.... [09:06:47 WARN]: at br.net.fabiozumbi12.RedProtect.Bukkit.RedProtect.startLoad(RedProtect.java:238)
>.... [09:06:47 WARN]: at br.net.fabiozumbi12.RedProtect.Bukkit.RedProtect.reload(RedProtect.java:174)
>.... [09:06:47 WARN]: at br.net.fabiozumbi12.RedProtect.Bukkit.commands.CommandHandler.onCommand(CommandHandler.java:584)
>.... [09:06:47 WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
>.... [09:06:47 WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
>.... [09:06:47 WARN]: at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:807)
>.... [09:06:47 WARN]: at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:769)
>.... [09:06:47 WARN]: at net.minecraft.server.v1_16_R3.DedicatedServer.handleCommandQueue(DedicatedServer.java:411)
>.... [09:06:47 WARN]: at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:378)
>.... [09:06:47 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1208)
>.... [09:06:47 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:996)
>.... [09:06:47 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173)
>.... [09:06:47 WARN]: at java.lang.Thread.run(Thread.java:748)
>.... [09:06:47 INFO]: [RedProtect] Helper version: Latest
>.... [09:06:47 INFO]: [RedProtect] Loading GuiFlags for 1.14+
>.... [09:06:47 INFO]: [LuluLand] RedProtect Plus reloaded!
```

Redprotect 7.7.2 - Build 385
Dynmap v3.1-beta-6
PaperMC: 1.16.5 - Build 445

I postet this issue also on the github of Redprotect

**Comment by CloudeLecaw** [comment]
semms to be fixed. may it was a dynmap update or an rp update
