### ISSUE TITLE
Issue ( not up to date 1.16.4 )

### ISSUE THREAD

**Issue by squeaky2137** [webbukkit/dynmap#3263]
**Issue Description:** *Dynmap says it’s not up to date when I’m on 1.16.4 using 1.16.4*

* **Dynmap Version:** *newest spigot one v3.1-beta-6*
* **Server Version:** *spigot 1.16.4 (could be 1.16.5 if that’s released or thing ) / the newest one*
* **Pastebin of Configuration.txt:** * https://pastebin.com/B01bGjNc *
* **Server Host (if applicable):** *WitherHosting*
* **Pastebin of crashlogs or other relevant logs:** * https://pastebin.com/cg8cw1QF*
* **Other Relevant Data/Screenshots:** * [dynmap] Enabling dynmap v3.1-beta6-438
> [14:06:47] [Server thread/INFO]: [dynmap] Using Vault provider SuperPerms for access control
> [14:06:48] [Server thread/ERROR]: [dynmap] Error parsing plugins/dynmap/configuration.txt. Use http://yamllint.com to debug the YAML syntax.
> [14:06:48] [Server thread/ERROR]: Error occurred while enabling dynmap v3.1-beta6-438 (Is it up to date?)
org.dynmap.snakeyaml.parser.ParserException: while parsing a block mapping
in 'reader', line 16, column 1:
deftemplatesuffix: lowres
expected <block end>, but found '<scalar>'
in 'reader', line 329, column 2:
The TCP-port the webserver will ...
at org.dynmap.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:572) ~[?:?]
at org.dynmap.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[?:?]
at org.dynmap.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148) ~[?:?]
at org.dynmap.snakeyaml.composer.Composer.composeMappingNode(Composer.java:214) ~[?:?]
at org.dynmap.snakeyaml.composer.Composer.composeNode(Composer.java:144) ~[?:?]
at org.dynmap.snakeyaml.composer.Composer.getNode(Composer.java:85) ~[?:?]
at org.dynmap.snakeyaml.composer.Composer.getSingleNode(Composer.java:108) ~[?:?]
at org.dynmap.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:139) ~[?:?]
at org.dynmap.snakeyaml.Yaml.loadFromReader(Yaml.java:524) ~[?:?]
at org.dynmap.snakeyaml.Yaml.load(Yaml.java:467) ~[?:?] is logs lol*
* **Steps to Replicate:** *Dowload newest version of dynmap on spigot and try running it ( could also just be my config error*

 [ ] *I have looked at all other issues and this is not a duplicate*  si 
 [ ] *I have been able to replicate this* si

**Comment by squeaky2137** [comment]
I’m sorry I messed up configs didn’t know you needed , but it all fixed now sorry for this
