### ISSUE TITLE
I broke my worlds.txt i think

### ISSUE THREAD

**Issue by imaron85** [webbukkit/dynmap#3291]
So erm, i am probably dumb, but i tried to change my worlds.txt to make almost perspectives render.
So this is what i put there:

\#  tileupdatedelay: 30
 \#  maps:
  \#    - class: org.dynmap.hdmap.HDMap
        name: flat
        title: "Flat"
        prefix: flat
        perspective: iso_S_90_lowres
        shader: stdtexture
        lighting: brightnightandday
        mapzoomin: 1
      - class: org.dynmap.hdmap.HDMap
        name: surface
        title: "Surface SE30"
        prefix: t
        perspective: iso_SE_30_hires
        shader: stdtexture
        lighting: brightnightandday
        mapzoomin: 1
      - class: org.dynmap.hdmap.HDMap
        name: surface2
        title: "Surface E30"
        prefix: t2
        perspective iso_E_30_hires
        shader: sdtexture
        lighting: brightnightandday
        mapzoomin: 1
      - class: org.dynmap.hdmap.HDMap
        name: surface3
        title: "Surface NE30"
        prefix: t3
        perspective: iso_NE_30_hires
        shader: stdtexture
        lighting: brightnightandday
        mapzoomin: 1
      - class: org.dynmap.hdmap.HDMap
        name: surface4
        title: "Surface N30"
        prefix: t4
        perspective: iso_N_30_hires
        shader: stdtexture
        lighting: brightnightandday
        mapzoomin: 1
      - class: org.dynmap.hdmap.HDMap
        name: surface5
        title: "Surface NW30"
        prefix: t5
        perspective: iso_NW_30_hires
        shader: stdtexture
        lighting: brightnightandday
        mapzoomin: 1
      - class: org.dynmap.hdmap.HDMap
        name: surface6
        title: "Surface W30"
        prefix: t6
        perspective: iso_W_30_hires
        shader: stdtexture
        lighting: brightnightandday
        mapzoomin: 1
      - class: org.dynmap.hdmap.HDMap
        name: surface7
        title: "Surface SW30"
        prefix: t7
        perspective: iso_SW_30_hires
        shader: stdtexture
        lighting: brightnightandday
        mapzoomin: 1
      - class: org.dynmap.hdmap.HDMap
        name: surface8
        title: "Surface S30"
        prefix: t8
        perspective: iso_S_30_hires
        shader: stdtexture
        lighting: brightnightandday
        mapzoomin: 1
      - class: org.dynmap.hdmap.HDMap
        name: surface9
        title: "Surface SE3´60"
        prefix: t9
        perspective: iso_SE_60_hires
        shader: stdtexture
        lighting: brightnightandday
        mapzoomin: 1
      - class: org.dynmap.hdmap.HDMap
        name: surface10
        title: "Surface E60"
        prefix: t10
        perspective iso_E_60_hires
        shader: sdtexture
        lighting: brightnightandday
        mapzoomin: 1
      - class: org.dynmap.hdmap.HDMap
        name: surface11
        title: "Surface NE60"
        prefix: t11
        perspective: iso_NE_60_hires
        shader: stdtexture
        lighting: brightnightandday
        mapzoomin: 1
      - class: org.dynmap.hdmap.HDMap
        name: surface12
        title: "Surface N60"
        prefix: t12
        perspective: iso_N_60_hires
        shader: stdtexture
        lighting: brightnightandday
        mapzoomin: 1
      - class: org.dynmap.hdmap.HDMap
        name: surface13
        title: "Surface NW60"
        prefix: t13
        perspective: iso_NW_60_hires
        shader: stdtexture
        lighting: brightnightandday
        mapzoomin: 1
      - class: org.dynmap.hdmap.HDMap
        name: surface14
        title: "Surface W60"
        prefix: t14
        perspective: iso_W_60_hires
        shader: stdtexture
        lighting: brightnightandday
        mapzoomin: 1
      - class: org.dynmap.hdmap.HDMap
        name: surface15
        title: "Surface SW60"
        prefix: t15
        perspective: iso_SW_60_hires
        shader: stdtexture
        lighting: brightnightandday
        mapzoomin: 1
      - class: org.dynmap.hdmap.HDMap
        name: surface16
        title: "Surface S60"
        prefix: t16
        perspective: iso_S_60_hires
        shader: stdtexture
        lighting: brightnightandday
        mapzoomin: 1
      - class: org.dynmap.hdmap.HDMap
        name: cave
        title: "Cave"
        prefix: ct
        perspective: iso_SE_60_lowres
        shader: cave
        lighting: default
        mapzoomin: 3

And here is the error, or rather the no error i am getting:

[dynmap]: Enabling dynmap v3.1-beta7-449
[dynmap]: Using Bukkit Permissions (superperms) for access control
[dynmap]: Web interface permissions only available for online users
Console13:02:22
at org.dynmap.snakeyaml.composer.Composer.composeNode(Composer.java:144) ~[?:?]
at org.dynmap.snakeyaml.composer.Composer.composeSequenceNode(Composer.java:189) ~[?:?]
at org.dynmap.snakeyaml.composer.Composer.composeNode(Composer.java:142) ~[?:?]
at org.dynmap.snakeyaml.composer.Composer.composeValueNode(Composer.java:236) ~[?:?]
at org.dynmap.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:227) ~[?:?]
at org.dynmap.snakeyaml.composer.Composer.composeMappingNode(Composer.java:215) ~[?:?]
at org.dynmap.snakeyaml.composer.Composer.composeNode(Composer.java:144) ~[?:?]
at org.dynmap.snakeyaml.composer.Composer.getNode(Composer.java:85) ~[?:?]
at org.dynmap.snakeyaml.composer.Composer.getSingleNode(Composer.java:108) ~[?:?]
at org.dynmap.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:139) ~[?:?]
at org.dynmap.snakeyaml.Yaml.loadFromReader(Yaml.java:524) ~[?:?]
at org.dynmap.snakeyaml.Yaml.load(Yaml.java:467) ~[?:?]
at org.dynmap.ConfigurationNode.load(ConfigurationNode.java:87) ~[?:?]
at org.dynmap.DynmapCore.enableCore(DynmapCore.java:570) ~[?:?]
at org.dynmap.bukkit.DynmapPlugin.doEnable(DynmapPlugin.java:961) ~[?:?]
at org.dynmap.bukkit.DynmapPlugin.onEnable(DynmapPlugin.java:941) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.16.4.jar:git-Spigot-628435a-768d7fc]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) ~[spigot-1.16.4.jar:git-Spigot-628435a-768d7fc]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-1.16.4.jar:git-Spigot-628435a-768d7fc]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:494) ~[spigot-1.16.4.jar:git-Spigot-628435a-768d7fc]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:408) ~[spigot-1.16.4.jar:git-Spigot-628435a-768d7fc]
at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:435) ~[spigot-1.16.4.jar:git-Spigot-628435a-768d7fc]
at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:218) ~[spigot-1.16.4.jar:git-Spigot-628435a-768d7fc]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:809) ~[spigot-1.16.4.jar:git-Spigot-628435a-768d7fc]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.4.jar:git-Spigot-628435a-768d7fc]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]

Can anyone tell what I am doing wrong, 'cause at this point I have no idea how to fix my config whilst keeping all the perspectives. But I'm probably just missing something obvious.. Thanks a lot in advance

**Comment by imaron85** [comment]
So tried running my worlds.txt through https://codebeautify.org/yaml-validator and it throws me a:
Error : Indentation problem.
Line : 70 - class: org.dynmap.hdmap.HDMap

Heres my full worlds.txt:
[worlds.txt](https://github.com/webbukkit/dynmap/files/6021561/worlds.txt)

I tried googling for Identation Problem, but it only brings up threads concerning tabs not being allowed in yaml, but i already removed all of them using Notepad++...
Other than that, as far as my .0000000001% yaml knowledge goes, my identation seems to be fine, but there must be something I'm missing.

**Comment by imaron85** [comment]
Okay I'm sorry, I just realized this belongs on the reddit. My apoliges
