### ISSUE TITLE
After deleting a map in the folder tiles, the dynmap doesn't work anymore

### ISSUE THREAD

**Issue by sez76** [webbukkit/dynmap#3380]
Hello, after deleting map in the folder tiles, the dynmap doesn't work anymore, if start the dynmap web page I have black screen, and the web page crash,

my dynmap version is core=3.1-457, plugin=3.1-457

I have error message if I reload the dynmap:
[20:04:51] [Server thread/WARN]: Enabled plugin with unregistered PluginClassLoader dynmap v3.1-457
[20:04:51] [Server thread/INFO]: [dynmap] Starting Scheduled Write Job (markerAPI).
[20:04:51] [Server thread/WARN]: Error: DynmapBlockState updated after arrays generated
[20:04:51] [Server thread/WARN]: java.lang.Exception: Stack trace
[20:04:51] [Server thread/WARN]: 	at java.base/java.lang.Thread.dumpStack(Thread.java:1388)
[20:04:51] [Server thread/WARN]: 	at org.dynmap.renderer.DynmapBlockState.<init>(DynmapBlockState.java:121)
[20:04:51] [Server thread/WARN]: 	at org.dynmap.renderer.DynmapBlockState.<init>(DynmapBlockState.java:104)
[20:04:51] [Server thread/WARN]: 	at org.dynmap.bukkit.helper.v116_4.BukkitVersionHelperSpigot116_4.initializeBlockStates(BukkitVersionHelperSpigot116_4.java:110)
[20:04:51] [Server thread/WARN]: 	at org.dynmap.bukkit.DynmapPlugin.onEnable(DynmapPlugin.java:853)
[20:04:51] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[20:04:51] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[20:04:51] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[20:04:51] [Server thread/WARN]: 	at org.dynmap.bukkit.DynmapPlugin$BukkitServer.reload(DynmapPlugin.java:253)
[20:04:51] [Server thread/WARN]: 	at org.dynmap.DynmapCore.processCommand(DynmapCore.java:1595)
[20:04:51] [Server thread/WARN]: 	at org.dynmap.bukkit.DynmapPlugin.onCommand(DynmapPlugin.java:1039)
[20:04:51] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[20:04:51] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[20:04:51] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:810)
[20:04:51] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:772)
[20:04:51] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.DedicatedServer.handleCommandQueue(DedicatedServer.java:453)
[20:04:51] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:420)
[20:04:51] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1339)
[20:04:51] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1127)
[20:04:51] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290)
[20:04:51] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[20:04:51] [Server thread/INFO]: [dynmap] Using LuckPerms 5.3.3 for access control
[20:04:51] [Server thread/INFO]: [dynmap] Mod Support processing completed
[20:04:52] [Server thread/WARN]: [dynmap] Blocks missing texture definition:

Do you have a idea please,
If you have a question let me know,
Many Thanks.

**Comment by sez76** [comment]
the problem is the version and the DDNS redirection.
