### ISSUE TITLE
Error when starting the server

### ISSUE THREAD

**Issue by Tugdual44120** [webbukkit/dynmap#3383]
Hello, I have the latest version of Dynmap available. I am under a modded minecraft server in 1.12.2. I am not using PaperSpigot or Magma but Mohist. I can't use the plugin, as soon as I put it my server quits / doesn't launch anymore

Here is the only error code that appears in the console :

java.lang.NullPointerException: null
    at org.dynmap.bukkit.DynmapPlugin.onDisable(DynmapPlugin.java:1003) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:179) ~[JavaPlugin.class:1.12.2-dde44c8]
    at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:341) [JavaPluginLoader.class:1.12.2-dde44c8]
    at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:417) [SimplePluginManager.class:1.12.2-dde44c8]
    at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:411) [SimplePluginManager.class:1.12.2-dde44c8]
    at org.bukkit.craftbukkit.v1_12_R1.CraftServer.disablePlugins(CraftServer.java:440) [CraftServer.class:1.12.2-dde44c8]
    at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:506) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:674) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]

**Comment by FedUpWith-Tech** [comment]
Try using the forge version of Dynmap on mohist, don't use the plugin version

**Comment by rautamiekka** [comment]
I guess OP missed Mohist's website saying it's a Forge variant.
