### ISSUE TITLE
Some issue we run with testing for Spigot 1.17

### ISSUE THREAD

**Issue by CloudeLecaw** [webbukkit/dynmap#3384]
```
[08:35:11] [Server thread/ERROR]: [dynmap] Cannot find net.minecraft.server.BiomeStorage
[08:35:11] [Server thread/ERROR]: Error initializing dynmap - bukkit version incompatible! initializing dynmap v3.2-SNAPSHOT-458 (Is it up to date?)
java.lang.IllegalArgumentException: Error initializing dynmap - bukkit version incompatible!
	at org.dynmap.bukkit.helper.BukkitVersionHelperGeneric.<init>(BukkitVersionHelperGeneric.java:166) ~[?:?]
	at org.dynmap.bukkit.helper.BukkitVersionHelperCB.<init>(BukkitVersionHelperCB.java:45) ~[?:?]
	at org.dynmap.bukkit.Helper.getHelper(Helper.java:67) ~[?:?]
	at org.dynmap.bukkit.DynmapPlugin.onLoad(DynmapPlugin.java:821) ~[?:?]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:389) ~[server.jar:3100-Spigot-c9cea60-5182f92]
	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:232) ~[server.jar:3100-Spigot-c9cea60-5182f92]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:986) ~[server.jar:3100-Spigot-c9cea60-5182f92]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[server.jar:3100-Spigot-c9cea60-5182f92]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by ghost** [comment]
Considering the spigot page doesnt state it supports 1.17 this doesnt surprise me? Just wait for an update like everyone else.

**Comment by Cassolotl** [comment]
@Carbonixx This bug report is useful for the developers, who need information about bugs before they can fix them. It's also useful for users, who might come here to find out if there are any issues with Dynmap on 1.17 before updating their servers (me). That's what the issue list is *for*.

**Comment by mikeprimm-triva** [comment]
Follow status here - https://www.reddit.com/r/Dynmap/comments/nygq3k/spigot_117_support_in_progress/

**Comment by mikeprimm** [comment]
Follow status here - https://www.reddit.com/r/Dynmap/comments/nygq3k/spigot_117_support_in_progress/
