### ISSUE TITLE
error after the command /dynmap reload

### ISSUE THREAD

**Issue by rkfsociety** [webbukkit/dynmap#3406]
[пт, 25. июн. 2021 20:53:45 UTC INFO] rkfsociety issued server command: /dynmap reload
[пт, 25. июн. 2021 20:53:45 UTC INFO] Disabling dynmap v3.2-beta-1-470
[пт, 25. июн. 2021 20:53:45 UTC INFO] Unloaded 11 components.
[пт, 25. июн. 2021 20:53:45 UTC INFO] Stopping map renderer...
[пт, 25. июн. 2021 20:53:46 UTC INFO] Disabled
[пт, 25. июн. 2021 20:53:46 UTC INFO] Enabling dynmap v3.2-beta-1-470*
[пт, 25. июн. 2021 20:53:46 UTC WARN] Enabled plugin with unregistered PluginClassLoader dynmap v3.2-beta-1-470
[пт, 25. июн. 2021 20:53:46 UTC INFO] Starting Scheduled Write Job (markerAPI).
[пт, 25. июн. 2021 20:53:46 UTC WARN] Error: DynmapBlockState updated after arrays generated
[пт, 25. июн. 2021 20:53:46 UTC WARN] java.lang.Exception: Stack trace
[пт, 25. июн. 2021 20:53:46 UTC WARN] at java.base/java.lang.Thread.dumpStack(Thread.java:1377)
[пт, 25. июн. 2021 20:53:46 UTC WARN] at org.dynmap.renderer.DynmapBlockState.<init>(DynmapBlockState.java:121)
[пт, 25. июн. 2021 20:53:46 UTC WARN] at org.dynmap.renderer.DynmapBlockState.<init>(DynmapBlockState.java:104)
[пт, 25. июн. 2021 20:53:46 UTC WARN] at org.dynmap.bukkit.helper.v117.BukkitVersionHelperSpigot117.initializeBlockStates(BukkitVersionHelperSpigot117.java:139)
[пт, 25. июн. 2021 20:53:46 UTC WARN] at org.dynmap.bukkit.DynmapPlugin.onEnable(DynmapPlugin.java:853)
[пт, 25. июн. 2021 20:53:46 UTC WARN] at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[пт, 25. июн. 2021 20:53:46 UTC WARN] at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[пт, 25. июн. 2021 20:53:46 UTC WARN] at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[пт, 25. июн. 2021 20:53:46 UTC WARN] at org.dynmap.bukkit.DynmapPlugin$BukkitServer.reload(DynmapPlugin.java:253)
[пт, 25. июн. 2021 20:53:46 UTC WARN] at org.dynmap.DynmapCore.processCommand(DynmapCore.java:1595)
[пт, 25. июн. 2021 20:53:46 UTC WARN] at org.dynmap.bukkit.DynmapPlugin.onCommand(DynmapPlugin.java:1039)
[пт, 25. июн. 2021 20:53:46 UTC WARN] at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[пт, 25. июн. 2021 20:53:46 UTC WARN] at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[пт, 25. июн. 2021 20:53:46 UTC WARN] at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:821)
[пт, 25. июн. 2021 20:53:46 UTC WARN] at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2185)
[пт, 25. июн. 2021 20:53:46 UTC WARN] at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1996)
[пт, 25. июн. 2021 20:53:46 UTC WARN] at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1977)
[пт, 25. июн. 2021 20:53:46 UTC WARN] at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[пт, 25. июн. 2021 20:53:46 UTC WARN] at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[пт, 25. июн. 2021 20:53:46 UTC WARN] at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:36)
[пт, 25. июн. 2021 20:53:46 UTC WARN] at net.minecraft.server.TickTask.run(TickTask.java:18)
[пт, 25. июн. 2021 20:53:46 UTC WARN] at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[пт, 25. июн. 2021 20:53:46 UTC WARN] at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[пт, 25. июн. 2021 20:53:46 UTC WARN] at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1340)
[пт, 25. июн. 2021 20:53:46 UTC WARN] at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:193)
[пт, 25. июн. 2021 20:53:46 UTC WARN] at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[пт, 25. июн. 2021 20:53:46 UTC WARN] at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1319)
[пт, 25. июн. 2021 20:53:46 UTC WARN] at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1312)
[пт, 25. июн. 2021 20:53:46 UTC WARN] at net.minecraft.util.thread.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:110)
[пт, 25. июн. 2021 20:53:46 UTC WARN] at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1456)
[пт, 25. июн. 2021 20:53:46 UTC WARN] at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1180)
[пт, 25. июн. 2021 20:53:46 UTC WARN] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[пт, 25. июн. 2021 20:53:46 UTC WARN] at java.base/java.lang.Thread.run(Thread.java:831)
[пт, 25. июн. 2021 20:53:47 UTC ERROR] Error occurred while enabling dynmap v3.2-beta-1-470 (Is it up to date?)
[пт, 25. июн. 2021 20:53:47 UTC INFO] Disabling dynmap v3.2-beta-1-470
[пт, 25. июн. 2021 20:53:47 UTC INFO] Unloaded 0 components.
[пт, 25. июн. 2021 20:53:47 UTC INFO] Disabled

This server is running Paper version git-Paper-46 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: 9e07703)
You are running the latest version
Previous version: git-Paper-43 (MC: 1.17)

dynmap version 3.2-beta-1-470

**Comment by mibby** [comment]
Can also reproduce as of dynmap v3.2-SNAPSHOT-484

```
[03:48:08] [Server thread/INFO]: mibby issued server command: /dynmap reload
[03:48:08] [Server thread/INFO]: [dynmap] Disabling dynmap v3.2-SNAPSHOT-484
[03:48:08] [Server thread/INFO]: [dynmap] Unloaded 8 components.
[03:48:08] [Server thread/INFO]: [dynmap] Stopping map renderer...
[03:48:09] [Server thread/INFO]: [dynmap] Disabled
[03:48:09] [Server thread/INFO]: [dynmap] Enabling dynmap v3.2-SNAPSHOT-484
[03:48:09] [Server thread/WARN]: Enabled plugin with unregistered PluginClassLoader dynmap v3.2-SNAPSHOT-484
[03:48:09] [Server thread/INFO]: [dynmap] Starting Scheduled Write Job (markerAPI).
[03:48:09] [Server thread/WARN]: (org.dynmap.renderer.DynmapBlockState:120) Error: DynmapBlockState updated after arrays generated
[03:48:09] [Server thread/WARN]: java.lang.Exception: Stack trace
[03:48:09] [Server thread/WARN]: 	at java.base/java.lang.Thread.dumpStack(Thread.java:1377)
[03:48:09] [Server thread/WARN]: 	at org.dynmap.renderer.DynmapBlockState.<init>(DynmapBlockState.java:121)
[03:48:09] [Server thread/WARN]: 	at org.dynmap.renderer.DynmapBlockState.<init>(DynmapBlockState.java:104)
[03:48:09] [Server thread/WARN]: 	at org.dynmap.bukkit.helper.v117.BukkitVersionHelperSpigot117.initializeBlockStates(BukkitVersionHelperSpigot117.java:139)
[03:48:09] [Server thread/WARN]: 	at org.dynmap.bukkit.DynmapPlugin.onEnable(DynmapPlugin.java:853)
[03:48:09] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[03:48:09] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[03:48:09] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[03:48:09] [Server thread/WARN]: 	at org.dynmap.bukkit.DynmapPlugin$BukkitServer.reload(DynmapPlugin.java:253)
[03:48:09] [Server thread/WARN]: 	at org.dynmap.DynmapCore.processCommand(DynmapCore.java:1595)
[03:48:09] [Server thread/WARN]: 	at org.dynmap.bukkit.DynmapPlugin.onCommand(DynmapPlugin.java:1039)
[03:48:09] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[03:48:09] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172)
[03:48:09] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:821)
[03:48:09] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2315)
[03:48:09] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2126)
[03:48:09] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2107)
[03:48:09] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[03:48:09] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[03:48:09] [Server thread/WARN]: 	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[03:48:09] [Server thread/WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[03:48:09] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[03:48:09] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[03:48:09] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1413)
[03:48:09] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:193)
[03:48:09] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[03:48:09] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1391)
[03:48:09] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1384)
[03:48:09] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
[03:48:09] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1360)
[03:48:09] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1271)
[03:48:09] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322)
[03:48:09] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[03:48:09] [Server thread/ERROR]: Error occurred while enabling dynmap v3.2-SNAPSHOT-484 (Is it up to date?)
java.lang.IllegalStateException: zip file closed
	at java.util.zip.ZipFile.ensureOpen(ZipFile.java:828) ~[?:?]
	at java.util.zip.ZipFile.getEntry(ZipFile.java:327) ~[?:?]
	at java.util.jar.JarFile.getEntry(JarFile.java:513) ~[?:?]
	at java.util.jar.JarFile.getJarEntry(JarFile.java:468) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:159) ~[patched_1.17.jar:git-AirplanePurpur-8]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:586) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:108) ~[patched_1.17.jar:git-AirplanePurpur-8]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[patched_1.17.jar:git-AirplanePurpur-8]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:375) ~[?:?]
	at org.dynmap.bukkit.permissions.LuckPermsPermissions.create(LuckPermsPermissions.java:25) ~[?:?]
	at org.dynmap.bukkit.DynmapPlugin.onEnable(DynmapPlugin.java:879) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.17.jar:git-AirplanePurpur-8]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.jar:git-AirplanePurpur-8]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.jar:git-AirplanePurpur-8]
	at org.dynmap.bukkit.DynmapPlugin$BukkitServer.reload(DynmapPlugin.java:253) ~[?:?]
	at org.dynmap.DynmapCore.processCommand(DynmapCore.java:1595) ~[?:?]
	at org.dynmap.bukkit.DynmapPlugin.onCommand(DynmapPlugin.java:1039) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.17.jar:git-AirplanePurpur-8]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[patched_1.17.jar:git-AirplanePurpur-8]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:821) ~[patched_1.17.jar:git-AirplanePurpur-8]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2315) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2126) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2107) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:6) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.jar:git-AirplanePurpur-8]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1413) ~[patched_1.17.jar:git-AirplanePurpur-8]
	at net.minecraft.server.MinecraftServer.shouldRun(MinecraftServer.java:193) ~[patched_1.17.jar:git-AirplanePurpur-8]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1391) ~[patched_1.17.jar:git-AirplanePurpur-8]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1384) ~[patched_1.17.jar:git-AirplanePurpur-8]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1360) ~[patched_1.17.jar:git-AirplanePurpur-8]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1271) ~[patched_1.17.jar:git-AirplanePurpur-8]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[patched_1.17.jar:git-AirplanePurpur-8]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[03:48:09] [Server thread/INFO]: [dynmap] Disabling dynmap v3.2-SNAPSHOT-484
[03:48:09] [Server thread/INFO]: [dynmap] Unloaded 0 components.
[03:48:09] [Server thread/INFO]: [dynmap] Disabled
```

**Comment by mikeprimm** [comment]
Dupe of #3350
