### ISSUE TITLE
SkinsRestorer integration not working

### ISSUE THREAD

**Issue by Pirito10** [webbukkit/dynmap#3408]
**Issue Description:** *Skins restorer integration is not working. When setting `skinsrestorer-integration` to true in configuration.txt, the following error shows up on server start up.*

* **Dynmap Version:** *3.2-beta-1-470*
* **Server Version:** *Purpur 1.17 build 1198*
* **Pastebin of Configuration.txt:** *https://pastebin.com/YCRbjCN6*
* **Pastebin of crashlogs or other relevant logs:** *https://pastebin.com/uvnyLqS6*
* **SkinsRestorer Version:** *14.1.0*
* **Steps to Replicate:** *Set `skinsrestorer-integration` to true and start the server*

 [x] *I have looked at all other issues and this is not a duplicate*  
 [x] *I have been able to replicate this*

**Comment by exore13** [comment]
I have the same issue with the following versions

- Server: Paper 1.16.5 - 778
- Dynmap: v3.1 GA
- SkinsRestorer: v14.1.0


SkinsRestorer loads first with no issue
```
[14:09:16] [Server thread/INFO]: [SkinsRestorer] Enabling SkinsRestorer v14.1.0
[14:09:16] [Server thread/INFO]: [SkinsRestorer] Using PaperSkinRefresher
[14:09:16] [Server thread/INFO]: [SkinsRestorer] Detected Minecraft v1_16_R3, using SkinApplierBukkit.
[14:09:16] [Server thread/INFO]: [SkinsRestorer] Updater Disabled
[14:09:16] [Server thread/INFO]: [SkinsRestorer] MineskinAPIKey is missing in config.yml! Using default value.
[14:09:16] [Server thread/INFO]: [SkinsRestorer] [ACF] Enabled Asynchronous Tab Completion Support!
```

When dynmap tries to start it gives an error about SkinsRestorereAPI
```
[14:09:18] [Server thread/INFO]: [dynmap] Enabling dynmap v3.1-457*
[14:09:18] [Server thread/INFO]: [dynmap] Using LuckPerms 5.3.48 for access control
[14:09:18] [Server thread/INFO]: [dynmap] Opening SQLite file /home/fxserver/serverCreeper/plugins/dynmap/dynmap.db as map store
[14:09:18] [Server thread/ERROR]: Error occurred while enabling dynmap v3.1-457 (Is it up to date?)
java.lang.NoSuchMethodError: 'net.skinsrestorer.api.SkinsRestorerAPI net.skinsrestorer.bukkit.SkinsRestorer.getSkinsRestorerBukkitAPI()'
	at org.dynmap.bukkit.SkinsRestorerSkinUrlProvider.<init>(SkinsRestorerSkinUrlProvider.java:22) ~[?:?]
	at org.dynmap.bukkit.DynmapPlugin.onEnable(DynmapPlugin.java:920) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-778]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Paper-778]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Paper-778]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Paper-778]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Paper-778]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:594) ~[patched_1.16.5.jar:git-Paper-778]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.16.5.jar:git-Paper-778]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069) ~[patched_1.16.5.jar:git-Paper-778]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-778]
	at java.lang.Thread.run(Thread.java:829) [?:?]
[14:09:18] [Server thread/INFO]: [dynmap] Disabling dynmap v3.1-457
[14:09:18] [Server thread/INFO]: [dynmap] Unloaded 0 components.
[14:09:18] [Server thread/INFO]: [dynmap] Disabled
```

The strange thing is that I build the server on my Windows machine using jdk11, and it worked flawless, but after switching to my ubuntu server machine, forcing the use of openjdk11 specifying `exec /usr/lib/jvm/java-11-openjdk-amd64/bin/java` on the .sh startup script, it wouldn't work...

**Comment by mikeprimm** [comment]
Support for 14.1 of SkinRestorer was added in 3.2-beta-2.   The integration contributed is not version-robust, as SkinRestorer lacks a published API to do what is needed - I'll probably drop it if it break again...

**Comment by theFurstyFerret** [comment]
Hi ive been consistantly getting skinsrestorer errors it sais i need an older version of skinsrestorer.

Server: Paper 1.21.7-32.
Dynmap: v3.7-SNAPSHOT-991 (core v3.7-SNAPSHOT-1002).
SkinsRestorer: v15.7.7.
v15.7.7 is supported or if a newer build exists.

[03:07:21] [Server thread/WARN]: [dynmap] You are using unsupported version of SkinsRestorer. Use v14.1 or newer.
[03:07:21] [Server thread/WARN]: [dynmap] Disabled SkinsRestorer integration for this session
