### ISSUE TITLE
 [dynmap] Cannot find [Lnet.minecraft.server.BiomeBase;

### ISSUE THREAD

**Issue by DNAmaster10** [webbukkit/dynmap#3416]
Hello!

This bug report might be a bit cheeky, as I'm using a server that I don't believe is supported by Dynmap, but I'm posting anyway just encase I'm missing something that could easily be fixed. 

I've been hosting a paper mc server for a long while now and have had no issues with Dynmap whatsoever. The server i host relies on the use of Towny, as well as dynmap towny. We recently decided that we would really like to see mods with the server, and after a while of searching, i came across Mohist, which integrates paper and forge together to run mods alongside plugins.

When i try to add Dynmap to the plugins folder however, i get the following error when starting up the server in the console
`[12:22:09 ERROR]: [dynmap] Cannot find [Lnet.minecraft.server.BiomeBase;
[12:22:09 ERROR]: [dynmap] Cannot find net.minecraft.server.BiomeStorage
[12:22:10 ERROR]: Error initializing dynmap - bukkit version incompatible! initializing dynmap v3.2-beta-2-483 (Is it up to date?)
java.lang.IllegalArgumentException: Error initializing dynmap - bukkit version incompatible!
        at org.dynmap.bukkit.helper.BukkitVersionHelperGeneric.<init>(BukkitVersionHelperGeneric.java:166) ~[?:?]
        at org.dynmap.bukkit.helper.v116_4.BukkitVersionHelperSpigot116_4.<init>(BukkitVersionHelperSpigot116_4.java:31) ~[?:?]
        at org.dynmap.bukkit.Helper.getHelper(Helper.java:54) ~[?:?]
        at org.dynmap.bukkit.DynmapPlugin.onLoad(DynmapPlugin.java:821) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:391) ~[forge:7e29f765-296df566-9fb885e8]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:208) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:728) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:271) ~[?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]`

Being curious, I decided to set up a fresh Mohist server and do a bit of experimenting. I found that even without other plugins, the dynmap still will not work correctly, and produces this error. Furthermore, i found that the forge version of Dynmap actually appears to be working correctly, however as mentioned, i'm unable to use this version of Dynmap as i doesn't seem to be compatible with Dynmap. I've tried using multiple version of Dynmap and Mohist to no avail. If this is something i would be able to fix on my own, please let me know. Thanks.

Mohist version: mohist-1.16.5-680-server (tried other versions)
Dynmap version: Dynmap-3.2-beta-2-spigot (tried other versions)

If a more detailed log is required, please let me know.
Thankyou!

**Comment by mikeprimm** [comment]
Mohist isn't supported, per se.  If it works at all, it'd be the Forge version that'll work.  The helper modules are very particular to the Spigot/Paper codebase, so will not work for variants that don't preserve the internal package and symbols from the Spigot/Paper versions.
