### ISSUE TITLE
Exception while fetching chunks

### ISSUE THREAD

**Issue by F1akee** [webbukkit/dynmap#3557]
I am getting this error while attempting a fullrender of my world:

[ERROR] .... [dynmap] Exception while fetching chunks:

java.lang.RuntimeException: java.nio.file.AccessDeniedException: ./World/Earth1000/region/r.1.-8.mca

at net.minecraft.server.level.ServerLevel$2.computeForRegionFile(ServerLevel.java:355) ~[app:?]

at com.destroystokyo.paper.io.PaperFileIOThread.lambda$scheduleRead$5(PaperFileIOThread.java:344) ~[patched_1.17.1.jar:git-Paper-397]

at java.util.concurrent.ConcurrentHashMap.compute(Unknown Source) ~[?:?]

at com.destroystokyo.paper.io.PaperFileIOThread.scheduleRead(PaperFileIOThread.java:340) ~[patched_1.17.1.jar:git-Paper-397]

at com.destroystokyo.paper.io.PaperFileIOThread.loadChunkDataAsync(PaperFileIOThread.java:308) ~[patched_1.17.1.jar:git-Paper-397]

at com.destroystokyo.paper.io.PaperFileIOThread.loadChunkDataAsyncFuture(PaperFileIOThread.java:242) ~[patched_1.17.1.jar:git-Paper-397]

at net.minecraft.server.level.ChunkMap.read(ChunkMap.java:1683) ~[patched_1.17.1.jar:git-Paper-397]

at org.dynmap.bukkit.helper.v117.MapChunkCache117.loadChunkNBT(MapChunkCache117.java:372) ~[Dynmap-3.2.1-spigot.jar:?]

at org.dynmap.bukkit.helper.v117.MapChunkCache117.loadChunks(MapChunkCache117.java:463) ~[Dynmap-3.2.1-spigot.jar:?]

at org.dynmap.bukkit.DynmapPlugin$BukkitServer$6.call(DynmapPlugin.java:521) ~[Dynmap-3.2.1-spigot.jar:?]

at org.dynmap.bukkit.DynmapPlugin$BukkitServer$6.call(DynmapPlugin.java:508) ~[Dynmap-3.2.1-spigot.jar:?]

at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftFuture.run(CraftFuture.java:88) ~[patched_1.17.1.jar:git-Paper-397]

at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-397]

at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1567) ~[patched_1.17.1.jar:git-Paper-397]

at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:490) ~[patched_1.17.1.jar:git-Paper-397]

at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1483) ~[patched_1.17.1.jar:git-Paper-397]

at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1282) ~[patched_1.17.1.jar:git-Paper-397]

at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-397]

at java.lang.Thread.run(Unknown Source) ~[?:?]

Caused by: java.nio.file.AccessDeniedException: ./World/Earth1000/region/r.1.-8.mca

at sun.nio.fs.UnixException.translateToIOException(Unknown Source) ~[?:?]

at sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) ~[?:?]

at sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) ~[?:?]

at sun.nio.fs.UnixFileSystemProvider.newFileChannel(Unknown Source) ~[?:?]

at java.nio.channels.FileChannel.open(Unknown Source) ~[?:?]

at java.nio.channels.FileChannel.open(Unknown Source) ~[?:?]

at net.minecraft.world.level.chunk.storage.RegionFile.<init>(RegionFile.java:463) ~[patched_1.17.1.jar:git-Paper-397]

at net.minecraft.world.level.chunk.storage.RegionFile.<init>(RegionFile.java:436) ~[patched_1.17.1.jar:git-Paper-397]

at net.minecraft.world.level.chunk.storage.RegionFileStorage.getFile(RegionFileStorage.java:103) ~[app:?]

at net.minecraft.world.level.chunk.storage.RegionFileStorage.getFile(RegionFileStorage.java:75) ~[app:?]

at net.minecraft.server.level.ServerLevel$2.computeForRegionFile(ServerLevel.java:353) ~[app:?]

... 18 more

What could be causing this?

**Comment by mikeprimm** [comment]
That's a file permissions issue - nothing to do with Dynmap - the world data file in question isn't readable by the  server process.  Need to check that the owning UID and GID for the files, as well as the mode flags, are appropriate for the account running your server.
