### ISSUE TITLE
A small error that occurs when restarting the server. 

### ISSUE THREAD

**Issue by itcools** [webbukkit/dynmap#3681]
A small error that occurs when restarting the server. It's not a problem with your use, but it's not good to look at.

//

[10:51:30] [Server thread/INFO]: [dynmap] Saved 1411118 pending tile renders in world 'Biomes'
[10:51:30] [Server thread/INFO]: [dynmap] Saved 1068095 pending tile renders in world 'Taurus'
[10:51:30] [Server thread/INFO]: [dynmap] Saved 1141917 pending tile renders in world 'Wild'
[10:51:30] [Server thread/INFO]: [dynmap] Full render job saved for world 'Wild'
[10:51:31] [Server thread/INFO]: [dynmap] Saved 41 pending tile renders in world 'Wild_nether'
[10:51:36] [Dynmap Render Thread/ERROR]: [dynmap] Exception occured: 
java.lang.InterruptedException: null
	at java.lang.Object.wait(Native Method) ~[?:?]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftFuture.get(CraftFuture.java:53) ~[paper-1.18.1.jar:git-Paper-198]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftFuture.get(CraftFuture.java:40) ~[paper-1.18.1.jar:git-Paper-198]
	at org.dynmap.bukkit.DynmapPlugin$BukkitServer.createMapChunkCache(DynmapPlugin.java:543) ~[Dynmap-3.3.2-spigot.jar:?]
	at org.dynmap.MapManager$FullWorldRenderState.processTile(MapManager.java:761) ~[Dynmap-3.3.2-spigot.jar:?]
	at org.dynmap.MapManager$FullWorldRenderState.run(MapManager.java:720) ~[Dynmap-3.3.2-spigot.jar:?]
	at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1.run(MapManager.java:229) ~[Dynmap-3.3.2-spigot.jar:?]
	at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$2.run(MapManager.java:245) ~[Dynmap-3.3.2-spigot.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[10:51:36] [Dynmap Render Thread/ERROR]: [dynmap] Exception occured: 
java.lang.InterruptedException: null
	at java.lang.Object.wait(Native Method) ~[?:?]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftFuture.get(CraftFuture.java:53) ~[paper-1.18.1.jar:git-Paper-198]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftFuture.get(CraftFuture.java:40) ~[paper-1.18.1.jar:git-Paper-198]
	at org.dynmap.bukkit.DynmapPlugin$BukkitServer.createMapChunkCache(DynmapPlugin.java:543) ~[Dynmap-3.3.2-spigot.jar:?]
	at org.dynmap.MapManager$FullWorldRenderState.processTile(MapManager.java:761) ~[Dynmap-3.3.2-spigot.jar:?]
	at org.dynmap.MapManager$FullWorldRenderState.run(MapManager.java:720) ~[Dynmap-3.3.2-spigot.jar:?]
	at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1.run(MapManager.java:229) ~[Dynmap-3.3.2-spigot.jar:?]
	at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$2.run(MapManager.java:245) ~[Dynmap-3.3.2-spigot.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[10:51:36] [Dynmap Render Thread/ERROR]: [dynmap] Exception occured: 
java.lang.InterruptedException: null
	at java.lang.Object.wait(Native Method) ~[?:?]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftFuture.get(CraftFuture.java:53) ~[paper-1.18.1.jar:git-Paper-198]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftFuture.get(CraftFuture.java:40) ~[paper-1.18.1.jar:git-Paper-198]
	at org.dynmap.bukkit.DynmapPlugin$BukkitServer.createMapChunkCache(DynmapPlugin.java:543) ~[Dynmap-3.3.2-spigot.jar:?]
	at org.dynmap.MapManager$FullWorldRenderState.processTile(MapManager.java:761) ~[Dynmap-3.3.2-spigot.jar:?]
	at org.dynmap.MapManager$FullWorldRenderState.run(MapManager.java:694) ~[Dynmap-3.3.2-spigot.jar:?]
	at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1.run(MapManager.java:229) ~[Dynmap-3.3.2-spigot.jar:?]
	at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$2.run(MapManager.java:245) ~[Dynmap-3.3.2-spigot.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[10:51:36] [Dynmap Render Thread/ERROR]: [dynmap] Exception occured: 
java.lang.InterruptedException: null
	at java.lang.Object.wait(Native Method) ~[?:?]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftFuture.get(CraftFuture.java:53) ~[paper-1.18.1.jar:git-Paper-198]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftFuture.get(CraftFuture.java:40) ~[paper-1.18.1.jar:git-Paper-198]
	at org.dynmap.bukkit.DynmapPlugin$BukkitServer.createMapChunkCache(DynmapPlugin.java:543) ~[Dynmap-3.3.2-spigot.jar:?]
	at org.dynmap.MapManager$FullWorldRenderState.processTile(MapManager.java:761) ~[Dynmap-3.3.2-spigot.jar:?]
	at org.dynmap.MapManager$FullWorldRenderState.access$1300(MapManager.java:262) ~[Dynmap-3.3.2-spigot.jar:?]
	at org.dynmap.MapManager$FullWorldRenderState$3.call(MapManager.java:686) ~[Dynmap-3.3.2-spigot.jar:?]
	at org.dynmap.MapManager$FullWorldRenderState$3.call(MapManager.java:684) ~[Dynmap-3.3.2-spigot.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[10:51:36] [Server thread/INFO]: [dynmap] Disabled

**Comment by RadegasTCZ** [comment]
It does something similar on my Spigot server as well, that is not only for restart, just whenever it need to save data and disable itself (shutdown, reload, whatnot...).

**Comment by mikeprimm** [comment]
Already fixed in SNAPSHOTs
