### ISSUE TITLE
Maptype error that occurred after updating from Dynamap-3.3.2-spigot to Dynamap-3.3-beta-2-spigot.

### ISSUE THREAD

**Issue by itcools** [webbukkit/dynmap#3682]
Maptype error that occurred after updating from Dynamap-3.3.2-spigot to Dynamap-3.3-beta-2-spigot.

----

[10:59:50] [Server thread/INFO]: [dynmap] Loading templates...
[10:59:50] [Server thread/INFO]: [dynmap] Loading shaders...
[10:59:52] [Server thread/ERROR]: [dynmap] Error loading maptype
java.lang.ClassNotFoundException: org.dynmap.hdmap.ChunkVersionHDShader
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:375) ~[?:?]
	at org.dynmap.ConfigurationNode.createInstance(ConfigurationNode.java:333) ~[Dynmap-3.3-beta-2-spigot.jar:?]
	at org.dynmap.ConfigurationNode.createInstances(ConfigurationNode.java:358) ~[Dynmap-3.3-beta-2-spigot.jar:?]
	at org.dynmap.hdmap.HDMapManager.loadHDShaders(HDMapManager.java:36) ~[Dynmap-3.3-beta-2-spigot.jar:?]
	at org.dynmap.MapManager.<init>(MapManager.java:1136) ~[Dynmap-3.3-beta-2-spigot.jar:?]
	at org.dynmap.DynmapCore.enableCore(DynmapCore.java:590) ~[Dynmap-3.3-beta-2-spigot.jar:?]
	at org.dynmap.bukkit.DynmapPlugin.doEnable(DynmapPlugin.java:1014) ~[Dynmap-3.3-beta-2-spigot.jar:?]
	at org.dynmap.bukkit.DynmapPlugin.onEnable(DynmapPlugin.java:994) ~[Dynmap-3.3-beta-2-spigot.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[paper-1.18.1.jar:git-Paper-198]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[paper-1.18.1.jar:git-Paper-198]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727) ~[paper-1.18.1.jar:git-Paper-198]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503) ~[paper-1.18.1.jar:git-Paper-198]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313) ~[paper-1.18.1.jar:git-Paper-198]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[paper-1.18.1.jar:git-Paper-198]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-198]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[10:59:52] [Server thread/WARN]: java.lang.ClassNotFoundException: org.dynmap.hdmap.ChunkVersionHDShader
[10:59:52] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151)
[10:59:52] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
[10:59:52] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[10:59:52] [Server thread/WARN]: 	at java.base/java.lang.Class.forName0(Native Method)
[10:59:52] [Server thread/WARN]: 	at java.base/java.lang.Class.forName(Class.java:375)
[10:59:52] [Server thread/WARN]: 	at Dynmap-3.3-beta-2-spigot.jar//org.dynmap.ConfigurationNode.createInstance(ConfigurationNode.java:333)
[10:59:52] [Server thread/WARN]: 	at Dynmap-3.3-beta-2-spigot.jar//org.dynmap.ConfigurationNode.createInstances(ConfigurationNode.java:358)
[10:59:52] [Server thread/WARN]: 	at Dynmap-3.3-beta-2-spigot.jar//org.dynmap.hdmap.HDMapManager.loadHDShaders(HDMapManager.java:36)
[10:59:52] [Server thread/WARN]: 	at Dynmap-3.3-beta-2-spigot.jar//org.dynmap.MapManager.<init>(MapManager.java:1136)
[10:59:52] [Server thread/WARN]: 	at Dynmap-3.3-beta-2-spigot.jar//org.dynmap.DynmapCore.enableCore(DynmapCore.java:590)
[10:59:52] [Server thread/WARN]: 	at Dynmap-3.3-beta-2-spigot.jar//org.dynmap.bukkit.DynmapPlugin.doEnable(DynmapPlugin.java:1014)
[10:59:52] [Server thread/WARN]: 	at Dynmap-3.3-beta-2-spigot.jar//org.dynmap.bukkit.DynmapPlugin.onEnable(DynmapPlugin.java:994)
[10:59:52] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[10:59:52] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[10:59:52] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501)
[10:59:52] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:561)
[10:59:52] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:475)
[10:59:52] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727)
[10:59:52] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503)
[10:59:52] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:313)
[10:59:52] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1202)
[10:59:52] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[10:59:52] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[10:59:52] [Server thread/ERROR]: [dynmap] Error loading maptype
java.lang.ClassNotFoundException: org.dynmap.hdmap.ChunkStatusHDShader
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:375) ~[?:?]
	at org.dynmap.ConfigurationNode.createInstance(ConfigurationNode.java:333) ~[Dynmap-3.3-beta-2-spigot.jar:?]
	at org.dynmap.ConfigurationNode.createInstances(ConfigurationNode.java:358) ~[Dynmap-3.3-beta-2-spigot.jar:?]
	at org.dynmap.hdmap.HDMapManager.loadHDShaders(HDMapManager.java:36) ~[Dynmap-3.3-beta-2-spigot.jar:?]
	at org.dynmap.MapManager.<init>(MapManager.java:1136) ~[Dynmap-3.3-beta-2-spigot.jar:?]
	at org.dynmap.DynmapCore.enableCore(DynmapCore.java:590) ~[Dynmap-3.3-beta-2-spigot.jar:?]
	at org.dynmap.bukkit.DynmapPlugin.doEnable(DynmapPlugin.java:1014) ~[Dynmap-3.3-beta-2-spigot.jar:?]
	at org.dynmap.bukkit.DynmapPlugin.onEnable(DynmapPlugin.java:994) ~[Dynmap-3.3-beta-2-spigot.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[paper-1.18.1.jar:git-Paper-198]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[paper-1.18.1.jar:git-Paper-198]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727) ~[paper-1.18.1.jar:git-Paper-198]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503) ~[paper-1.18.1.jar:git-Paper-198]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313) ~[paper-1.18.1.jar:git-Paper-198]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[paper-1.18.1.jar:git-Paper-198]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-198]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[10:59:52] [Server thread/WARN]: java.lang.ClassNotFoundException: org.dynmap.hdmap.ChunkStatusHDShader
[10:59:52] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151)
[10:59:52] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
[10:59:52] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[10:59:52] [Server thread/WARN]: 	at java.base/java.lang.Class.forName0(Native Method)
[10:59:52] [Server thread/WARN]: 	at java.base/java.lang.Class.forName(Class.java:375)
[10:59:52] [Server thread/WARN]: 	at Dynmap-3.3-beta-2-spigot.jar//org.dynmap.ConfigurationNode.createInstance(ConfigurationNode.java:333)
[10:59:52] [Server thread/WARN]: 	at Dynmap-3.3-beta-2-spigot.jar//org.dynmap.ConfigurationNode.createInstances(ConfigurationNode.java:358)
[10:59:52] [Server thread/WARN]: 	at Dynmap-3.3-beta-2-spigot.jar//org.dynmap.hdmap.HDMapManager.loadHDShaders(HDMapManager.java:36)
[10:59:52] [Server thread/WARN]: 	at Dynmap-3.3-beta-2-spigot.jar//org.dynmap.MapManager.<init>(MapManager.java:1136)
[10:59:52] [Server thread/WARN]: 	at Dynmap-3.3-beta-2-spigot.jar//org.dynmap.DynmapCore.enableCore(DynmapCore.java:590)
[10:59:52] [Server thread/WARN]: 	at Dynmap-3.3-beta-2-spigot.jar//org.dynmap.bukkit.DynmapPlugin.doEnable(DynmapPlugin.java:1014)
[10:59:52] [Server thread/WARN]: 	at Dynmap-3.3-beta-2-spigot.jar//org.dynmap.bukkit.DynmapPlugin.onEnable(DynmapPlugin.java:994)
[10:59:52] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[10:59:52] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[10:59:52] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501)
[10:59:52] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:561)
[10:59:52] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:475)
[10:59:52] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727)
[10:59:52] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503)
[10:59:52] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:313)
[10:59:52] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1202)
[10:59:52] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[10:59:52] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by mikeprimm-triva** [comment]
Thats a downgrade (3.3.2 > 3.3-beta) - not supported (and you are using ChunkVersion map type, which didn't exist back in 3.3-beta-2)

**Comment by itcools** [comment]
> Thats a downgrade (3.3.2 > 3.3-beta) - not supported (and you are using ChunkVersion map type, which didn't exist back in 3.3-beta-2)

Ahaha, was it downgrade? I thought it was an upgrade. Thank you for your wise answer to the silly feedback.

**Comment by generrosity** [comment]
@itcools you are now back working on 3.3.2 ?

**Comment by itcools** [comment]
> @itcools you are now back working on 3.3.2 ?

sure
