### ISSUE TITLE
Cannot find net.minecraft.server.BiomeStorage

### ISSUE THREAD

**Issue by leaked42** [webbukkit/dynmap#3699]
Latest dynmap + Latest Purpur for 1.18.1
`[14:09:26] [Server thread/INFO]: [dynmap] Loading dynmap v3.2.1-531
[14:09:26] [Server thread/INFO]: [dynmap] version=git-Purpur-1566 (MC: 1.18.1)
[14:09:26] [Server thread/ERROR]: [dynmap] Cannot find [Lnet.minecraft.server.BiomeBase;
[14:09:26] [Server thread/ERROR]: [dynmap] Cannot find net.minecraft.server.BiomeStorage
[14:09:26] [Server thread/ERROR]: [org.bukkit.craftbukkit.v1_18_R1.CraftServer] Error initializing dynmap - bukkit version incompatible! initializing dynmap v3.2.1-531 (Is it up to date?)
java.lang.IllegalArgumentException: Error initializing dynmap - bukkit version incompatible!
	at org.dynmap.bukkit.helper.BukkitVersionHelperGeneric.<init>(BukkitVersionHelperGeneric.java:166) ~[Dynmap.jar:?]
	at org.dynmap.bukkit.helper.BukkitVersionHelperCB.<init>(BukkitVersionHelperCB.java:45) ~[Dynmap.jar:?]
	at org.dynmap.bukkit.Helper.getHelper(Helper.java:71) ~[Dynmap.jar:?]
	at org.dynmap.bukkit.DynmapPlugin.onLoad(DynmapPlugin.java:852) ~[Dynmap.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.loadPlugins(CraftServer.java:426) ~[purpur-1.18.1.jar:git-Purpur-1566]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:320) ~[purpur-1.18.1.jar:git-Purpur-1566]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1227) ~[purpur-1.18.1.jar:git-Purpur-1566]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[purpur-1.18.1.jar:git-Purpur-1566]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
`

Latest dynmap + Latest PufferFish for 1.18.1
```
[13:38:13] [Server thread/INFO]: [dynmap] Loading dynmap v3.2.1-531
[13:38:13] [Server thread/INFO]: [dynmap] version=git-Pufferfish-47 (MC: 1.18.1)
[13:38:13] [Server thread/ERROR]: [dynmap] Cannot find [Lnet.minecraft.server.BiomeBase;
[13:38:13] [Server thread/ERROR]: [dynmap] Cannot find net.minecraft.server.BiomeStorage
[13:38:13] [Server thread/ERROR]: [org.bukkit.craftbukkit.v1_18_R1.CraftServer] Error initializing dynmap - bukkit version incompatible! initializing dynmap v3.2.1-531 (Is it up to date?)
java.lang.IllegalArgumentException: Error initializing dynmap - bukkit version incompatible!
	at org.dynmap.bukkit.helper.BukkitVersionHelperGeneric.<init>(BukkitVersionHelperGeneric.java:166) ~[Dynmap.jar:?]
	at org.dynmap.bukkit.helper.BukkitVersionHelperCB.<init>(BukkitVersionHelperCB.java:45) ~[Dynmap.jar:?]
	at org.dynmap.bukkit.Helper.getHelper(Helper.java:71) ~[Dynmap.jar:?]
	at org.dynmap.bukkit.DynmapPlugin.onLoad(DynmapPlugin.java:852) ~[Dynmap.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.loadPlugins(CraftServer.java:425) ~[pufferfish-1.18.1.jar:git-Pufferfish-47]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.reload(CraftServer.java:1015) ~[pufferfish-1.18.1.jar:git-Pufferfish-47]
	at org.bukkit.Bukkit.reload(Bukkit.java:897) ~[pufferfish-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:54) ~[pufferfish-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[pufferfish-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:907) ~[pufferfish-1.18.1.jar:git-Pufferfish-47]
	at github.scarsz.discordsrv.listeners.DiscordConsoleListener.lambda$onGuildMessageReceived$0(DiscordConsoleListener.java:115) ~[DiscordSRV.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[pufferfish-1.18.1.jar:git-Pufferfish-47]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[pufferfish-1.18.1.jar:git-Pufferfish-47]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1550) ~[pufferfish-1.18.1.jar:git-Pufferfish-47]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[pufferfish-1.18.1.jar:git-Pufferfish-47]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1473) ~[pufferfish-1.18.1.jar:git-Pufferfish-47]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1266) ~[pufferfish-1.18.1.jar:git-Pufferfish-47]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:319) ~[pufferfish-1.18.1.jar:git-Pufferfish-47]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by JurgenKuyper** [comment]
Dynmap hasn't got support for pufferfish (purper) or any other ports besides paper, fabric and forge, the dev has too little time to support most active versions on all of those platforms too, it might work, it might not. sorry
