### ISSUE TITLE
Zoom Out Exception and 500 error

### ISSUE THREAD

**Issue by jaykijay** [webbukkit/dynmap#3708]
**Issue Description:** Exception is thrown while rendering Zoom Out Tiles and Tiles not shown on Web

* **Dynmap Version:** 3.4-beta-2
* **Server Version:** git-Paper-232 (MC: 1.18.2)
* **Pastebin of Configuration.txt:** https://pastebin.com/4DJ7aSNd
* **Server Host (if applicable):** Selfhosted, Archlinux

* **Other Relevant Data/Screenshots:** 
[00:15:31 ERROR]: [dynmap] Exception during render job: org.dynmap.MapManager_DoZoomOutProcessing@754d2820
[00:15:31 WARN]: java.lang.StringIndexOutOfBoundsException: begin 0, end 17, length 16
[00:15:31 WARN]:        at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4601)
[00:15:31 WARN]:        at java.base/java.lang.String.substring(String.java:2704)
[00:15:31 WARN]:        at Dynmap-3.4-beta-2-spigot.jar//org.dynmap.storage.filetree.FileTreeMapStorage$StorageTile.<init>(FileTreeMapStorage.java:47)
[00:15:31 WARN]:        at Dynmap-3.4-beta-2-spigot.jar//org.dynmap.storage.filetree.FileTreeMapStorage$StorageTile.getZoomOutTile(FileTreeMapStorage.java:219)
[00:15:31 WARN]:        at Dynmap-3.4-beta-2-spigot.jar//org.dynmap.DynmapWorld.processZoomFile(DynmapWorld.java:138)
[00:15:31 WARN]:        at Dynmap-3.4-beta-2-spigot.jar//org.dynmap.DynmapWorld.freshenZoomOutFiles(DynmapWorld.java:119)
[00:15:31 WARN]:        at Dynmap-3.4-beta-2-spigot.jar//org.dynmap.MapManager$DoZoomOutProcessing.run(MapManager.java:951)
[00:15:31 WARN]:        at Dynmap-3.4-beta-2-spigot.jar//org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$2.run(MapManager.java:252)
[00:15:31 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[00:15:31 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[00:15:31 WARN]:        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
[00:15:31 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[00:15:31 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[00:15:31 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

* **Steps to Replicate:** don't know, appears on every start of Server and always when Zoom Out tiles are beeing processed.., even on absolute fresh Server, new fullrender, and completly different map...

 [x] *I have looked at all other issues and this is not a duplicate*  
 [x] *I have been able to replicate this*

**Comment by mikeprimm-triva** [comment]
Current code has implementation limit on zoom levels (at 16), which is the root of this problem.  The current SNAPSHOT build should address this (767 or later).

**Comment by jaykijay** [comment]
works fine, thank you
