### ISSUE TITLE
Issue with MySql

### ISSUE THREAD

**Issue by BitOMOn** [webbukkit/dynmap#3753]
plugin version: v3.4-beta-3 for Spigot/Paper

I am running a selfhosted minecraft srever and i am getting an issue when setting up mysql. I have got 2 servers running on proxmox one to host the mysql server and external webserver and then my minecraft server. This server is part of a bungee cord network

I am followint this totorial: [https://github.com/webbukkit/dynmap/wiki/%5BTutorial%5D-Setting-up-a-standalone-web-server-with-MySQL-SQLite]

Error: 
[09:38:36] [Server thread/INFO]: [dynmap] Loading dynmap v3.4-beta-3-774
[09:38:36] [Server thread/INFO]: [dynmap] version=git-Paper-288 (MC: 1.18.2)
[09:38:36] [Server thread/INFO]: [dynmap] Mod Support API available

[09:39:07] [Server thread/INFO]: [dynmap] Enabling dynmap v3.4-beta-3-774
[09:39:07] [Server thread/INFO]: [dynmap] Added 18 custom biome mappings
[09:39:08] [Server thread/INFO]: [dynmap] Using LuckPerms 5.4.16 for access control
[09:39:08] [Server thread/ERROR]: [dynmap] Error parsing plugins/dynmap/configuration.txt. Use http://yamllint.com to debug the YAML syntax.
[09:39:08] [Server thread/ERROR]: Error occurred while enabling dynmap v3.4-beta-3-774 (Is it up to date?)
org.dynmap.snakeyaml.parser.ParserException: while parsing a block collection
 in 'reader', line 39, column 3:
      - class: org.dynmap.ClientConfig ... 
      ^
expected <block end>, but found '<block sequence start>'
 in 'reader', line 75, column 4:
       - class: org.dynmap.JsonFileClie ... 
       ^

	at org.dynmap.snakeyaml.parser.ParserImpl$ParseBlockSequenceEntry.produce(ParserImpl.java:516) ~[Dynmap-3.4-beta-3-spigot.jar:?]
	at org.dynmap.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[Dynmap-3.4-beta-3-spigot.jar:?]
	at org.dynmap.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148) ~[Dynmap-3.4-beta-3-spigot.jar:?]
	at org.dynmap.snakeyaml.composer.Composer.composeSequenceNode(Composer.java:188) ~[Dynmap-3.4-beta-3-spigot.jar:?]
	at org.dynmap.snakeyaml.composer.Composer.composeNode(Composer.java:142) ~[Dynmap-3.4-beta-3-spigot.jar:?]
	at org.dynmap.snakeyaml.composer.Composer.composeValueNode(Composer.java:236) ~[Dynmap-3.4-beta-3-spigot.jar:?]
	at org.dynmap.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:227) ~[Dynmap-3.4-beta-3-spigot.jar:?]
	at org.dynmap.snakeyaml.composer.Composer.composeMappingNode(Composer.java:215) ~[Dynmap-3.4-beta-3-spigot.jar:?]
	at org.dynmap.snakeyaml.composer.Composer.composeNode(Composer.java:144) ~[Dynmap-3.4-beta-3-spigot.jar:?]
	at org.dynmap.snakeyaml.composer.Composer.getNode(Composer.java:85) ~[Dynmap-3.4-beta-3-spigot.jar:?]
	at org.dynmap.snakeyaml.composer.Composer.getSingleNode(Composer.java:108) ~[Dynmap-3.4-beta-3-spigot.jar:?]
	at org.dynmap.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:139) ~[Dynmap-3.4-beta-3-spigot.jar:?]
	at org.dynmap.snakeyaml.Yaml.loadFromReader(Yaml.java:524) ~[Dynmap-3.4-beta-3-spigot.jar:?]
	at org.dynmap.snakeyaml.Yaml.load(Yaml.java:467) ~[Dynmap-3.4-beta-3-spigot.jar:?]
	at org.dynmap.ConfigurationNode.load(ConfigurationNode.java:88) ~[Dynmap-3.4-beta-3-spigot.jar:?]
	at org.dynmap.DynmapCore.initConfiguration(DynmapCore.java:408) ~[Dynmap-3.4-beta-3-spigot.jar:?]
	at org.dynmap.bukkit.DynmapPlugin.onEnable(DynmapPlugin.java:955) ~[Dynmap-3.4-beta-3-spigot.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559) ~[paper-1.18.2.jar:git-Paper-288]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473) ~[paper-1.18.2.jar:git-Paper-288]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:664) ~[paper-1.18.2.jar:git-Paper-288]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.18.2.jar:git-Paper-288]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-288]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1163) ~[paper-1.18.2.jar:git-Paper-288]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-288]
	at java.lang.Thread.run(Thread.java:831) ~[?:?]
[09:39:08] [Server thread/INFO]: [dynmap] Disabling dynmap v3.4-beta-3-774
[09:39:08] [Server thread/INFO]: [dynmap] Unloaded 0 components.
[09:39:08] [Server thread/INFO]: [dynmap] Disabled

LOG:
[latest.txt](https://github.com/webbukkit/dynmap/files/8677041/latest.txt)

Config:
[configuration.txt](https://github.com/webbukkit/dynmap/files/8677075/configuration.txt)

**Comment by masmc05** [comment]
[configuration.txt](https://github.com/webbukkit/dynmap/files/8677268/configuration.txt)
try this config

**Comment by masmc05** [comment]
oh, no, better this 
[configuration.txt](https://github.com/webbukkit/dynmap/files/8677298/configuration.txt)
Edit: seems like not better

**Comment by JurgenKuyper** [comment]
> oh, no, better this [configuration.txt](https://github.com/webbukkit/dynmap/files/8677298/configuration.txt)

your indentation doesn't seem correct at line 39.

@BitOMOn remove the extra space before the - at line 75 and it should work

**Comment by BitOMOn** [comment]
Thanks @JurgenKuyper and @mastermc05 for the help thsi helped now it is quering with mysql. I am sill haveing an isuse with authentication but i think it is relatd to my mysql server. I will close this then i get it sorted.
