### ISSUE TITLE
Dynmap fails to load in 1.19, "Error initializing dynmap - bukkit version incompatible!"

### ISSUE THREAD

**Issue by surfrock66** [webbukkit/dynmap#3775]
*Upon testing dynmap on builds of Paper 1.19 (git commit d1b1c6f), the plugin fails to load.  It appears a version incompatibility instead of something explicitly technical?*

* **Dynmap Version:** *v3.4-beta-2-761*
* **Server Version:** *git-Paper-"d1b1c6f" (MC: 1.19)*
* **Pastebin of Configuration.txt:** *https://paste.gg/p/anonymous/3fd532917234482c81a49441135808c7/files/6e0829fd75474e0281b8f63b8eba863c/raw*
* **Server Host (if applicable):** *Selfhosted*
* **Pastebin of crashlogs or other relevant logs:** 
```
[21:26:21 INFO]: [dynmap] Loading dynmap v3.4-beta-2-761
[21:26:21 INFO]: [dynmap] version=git-Paper-"d1b1c6f" (MC: 1.19)
[21:26:21 ERROR]: [dynmap] Cannot find [Lnet.minecraft.server.BiomeBase;
[21:26:21 ERROR]: [dynmap] Cannot find net.minecraft.server.BiomeStorage
[21:26:21 ERROR]: [org.bukkit.craftbukkit.v1_19_R1.CraftServer] Error initializing dynmap - bukkit version incompatible! initializing dynmap v3.4-beta-2-761 (Is it up to date?)
java.lang.IllegalArgumentException: Error initializing dynmap - bukkit version incompatible!
	at org.dynmap.bukkit.helper.BukkitVersionHelperGeneric.<init>(BukkitVersionHelperGeneric.java:165) ~[Dynmap-3.4-beta-2-spigot.jar:?]
	at org.dynmap.bukkit.helper.BukkitVersionHelperCB.<init>(BukkitVersionHelperCB.java:44) ~[Dynmap-3.4-beta-2-spigot.jar:?]
	at org.dynmap.bukkit.Helper.getHelper(Helper.java:79) ~[Dynmap-3.4-beta-2-spigot.jar:?]
	at org.dynmap.bukkit.DynmapPlugin.onLoad(DynmapPlugin.java:871) ~[Dynmap-3.4-beta-2-spigot.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.loadPlugins(CraftServer.java:418) ~[paper-1.19.jar:git-Paper-"d1b1c6f"]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.reload(CraftServer.java:1007) ~[paper-1.19.jar:git-Paper-"d1b1c6f"]
	at org.bukkit.Bukkit.reload(Bukkit.java:909) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:54) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:900) ~[paper-1.19.jar:git-Paper-"d1b1c6f"]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2376) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$18(ServerGamePacketListenerImpl.java:2147) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.jar:git-Paper-"d1b1c6f"]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1358) ~[paper-1.19.jar:git-Paper-"d1b1c6f"]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183) ~[paper-1.19.jar:git-Paper-"d1b1c6f"]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1335) ~[paper-1.19.jar:git-Paper-"d1b1c6f"]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1328) ~[paper-1.19.jar:git-Paper-"d1b1c6f"]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1306) ~[paper-1.19.jar:git-Paper-"d1b1c6f"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1191) ~[paper-1.19.jar:git-Paper-"d1b1c6f"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-"d1b1c6f"]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

```
* **Steps to Replicate:** *Compiled paper, added the snapshot of dynmap to the plugins folder, and ran it.  The server failed to load the plugin but otherwise worked.*

 [X] *I have looked at all other issues and this is not a duplicate*  
 [X] *I have been able to replicate this*

**Comment by JurgenKuyper** [comment]
you are using an old version of dynmap, the newest snapshot is the only one working for 1.19, links are: 
- For Forge 1.19.- https://dynmap.us/builds/dynmap/Dynmap-3.4-SNAPSHOT-forge-1.19.jar
- For Fabric 1.19 - https://dynmap.us/builds/dynmap/Dynmap-3.4-SNAPSHOT-fabric-1.19.jar
- For Spigot/Paper 1.19 - https://dynmap.us/builds/dynmap/Dynmap-3.4-SNAPSHOT-spigot.jar

**Comment by surfrock66** [comment]
Weird, I thought I had downloaded it from this page:

https://www.reddit.com/r/Dynmap/comments/v76g95/dynmap_support_for_119_is_in_progress/

Maybe it got shuffled when I was pulling files from my prod environment to the testing environment; I have the correct jar but I guess it never made it to the new plugins folder.  Thanks, total derp on my part.
