### ISSUE TITLE
Can you make this plugin to bedrock server like Nukkit

### ISSUE THREAD

**Issue by EagleDotNet** [webbukkit/dynmap#3875]
> template is **bold**
> sample data is *italicized*

**Feature Description:** *Dynmap sample feature request description. This description would include as much and as little detail necessary for us to understand the feature in its entirety.*

Now the players is so much on bedrock edition more then java edition, and the Nukkit server is run with java like bukkit, i think you don't need more time or experinece to convert this plugin to Nukkit ^_^

* **Additional context:** *Please add any additional information you feel will help us understand the feature*

**Comment by JurgenKuyper** [comment]
Did you try whether it works on nukkit? I don't think the dev will support more platforms than atm are supported, as he is really busy

**Comment by EagleDotNet** [comment]
I tried and this is what happens :

17:56:50 [INFO ] Loading dynmap v3.4-828
17:56:50 [ERROR] Throwing
java.lang.NoClassDefFoundError: org/bukkit/plugin/java/JavaPlugin
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_352]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756) ~[?:1.8.0_352]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_352]
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:473) ~[?:1.8.0_352]
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74) ~[?:1.8.0_352]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369) ~[?:1.8.0_352]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363) ~[?:1.8.0_352]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_352]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362) ~[?:1.8.0_352]
        at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:44) ~[minecraft_server.jar:?]
        at cn.nukkit.plugin.JavaPluginLoader.getClassByName(JavaPluginLoader.java:145) ~[minecraft_server.jar:?]
        at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:40) ~[minecraft_server.jar:?]
        at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:28) ~[minecraft_server.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_352]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_352]
        at cn.nukkit.plugin.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:47) ~[minecraft_server.jar:?]
        at cn.nukkit.plugin.PluginManager.loadPlugin(PluginManager.java:95) ~[minecraft_server.jar:?]
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:285) ~[minecraft_server.jar:?]
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:132) ~[minecraft_server.jar:?]
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:124) ~[minecraft_server.jar:?]
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:120) ~[minecraft_server.jar:?]
        at cn.nukkit.Server.<init>(Server.java:505) ~[minecraft_server.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:120) [minecraft_server.jar:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.plugin.java.JavaPlugin
        at java.net.URLClassLoader.findClass(URLClassLoader.java:387) ~[?:1.8.0_352]
        at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:44) ~[minecraft_server.jar:?]
        at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:28) ~[minecraft_server.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_352]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_352]
        ... 23 more
17:56:50 [INFO ] Stopping other threads
________________________________
من: JurgenKuyper ***@***.***>
‏‏تم الإرسال: 18 نوفمبر, 2022 05:15 م
إلى: webbukkit/dynmap ***@***.***>
نسخة: EagleDotNet ***@***.***>; Author ***@***.***>
‏‏الموضوع: Re: [webbukkit/dynmap] Can you make this plugin to bedrock server like Nukkit (Issue #3875)


Did you try whether it works on nukkit? I don't think the dev will support more platforms than atm are supported, as he is really busy

**Comment by JurgenKuyper** [comment]
then no, it is not supported, and most likely won't be supported in the future.
