### ISSUE TITLE
All dynmap plugins are disabled

### ISSUE THREAD

**Issue by NBS-Paste** [webbukkit/dynmap#3876]
**Issue Description:** I was trying to add a new view above the nether roof and it wasn't working so I looked at my console and  it said
[14:01:11 ERROR]: [dynmap] Error parsing plugins\dynmap\custom-perspectives.txt. Use http://yamllint.com to debug the YAML syntax.
[14:01:11 ERROR]: Error occurred while enabling dynmap v3.4-828 (Is it up to date?)
org.dynmap.snakeyaml.scanner.ScannerException: mapping values are not allowed here
 in 'reader', line 5, column 9:
        name: nether_roof
            ^

        at org.dynmap.snakeyaml.scanner.ScannerImpl.fetchValue(ScannerImpl.java:870) ~[Dynmap-3.4-spigot (4).jar:?]
        at org.dynmap.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:358) ~[Dynmap-3.4-spigot (4).jar:?]
        at org.dynmap.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:227) ~[Dynmap-3.4-spigot (4).jar:?]
        at org.dynmap.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:558) ~[Dynmap-3.4-spigot (4).jar:?]
        at org.dynmap.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[Dynmap-3.4-spigot (4).jar:?]
        at org.dynmap.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148) ~[Dynmap-3.4-spigot (4).jar:?]
        at org.dynmap.snakeyaml.composer.Composer.composeMappingNode(Composer.java:214) ~[Dynmap-3.4-spigot (4).jar:?]
        at org.dynmap.snakeyaml.composer.Composer.composeNode(Composer.java:144) ~[Dynmap-3.4-spigot (4).jar:?]
        at org.dynmap.snakeyaml.composer.Composer.composeSequenceNode(Composer.java:189) ~[Dynmap-3.4-spigot (4).jar:?]
        at org.dynmap.snakeyaml.composer.Composer.composeNode(Composer.java:142) ~[Dynmap-3.4-spigot (4).jar:?]
        at org.dynmap.snakeyaml.composer.Composer.composeValueNode(Composer.java:236) ~[Dynmap-3.4-spigot (4).jar:?]
        at org.dynmap.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:227) ~[Dynmap-3.4-spigot (4).jar:?]
        at org.dynmap.snakeyaml.composer.Composer.composeMappingNode(Composer.java:215) ~[Dynmap-3.4-spigot (4).jar:?]
        at org.dynmap.snakeyaml.composer.Composer.composeNode(Composer.java:144) ~[Dynmap-3.4-spigot (4).jar:?]
        at org.dynmap.snakeyaml.composer.Composer.getNode(Composer.java:85) ~[Dynmap-3.4-spigot (4).jar:?]
        at org.dynmap.snakeyaml.composer.Composer.getSingleNode(Composer.java:108) ~[Dynmap-3.4-spigot (4).jar:?]
        at org.dynmap.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:139) ~[Dynmap-3.4-spigot (4).jar:?]
        at org.dynmap.snakeyaml.Yaml.loadFromReader(Yaml.java:524) ~[Dynmap-3.4-spigot (4).jar:?]
        at org.dynmap.snakeyaml.Yaml.load(Yaml.java:467) ~[Dynmap-3.4-spigot (4).jar:?]
        at org.dynmap.ConfigurationNode.load(ConfigurationNode.java:88) ~[Dynmap-3.4-spigot (4).jar:?]
        at org.dynmap.hdmap.HDMapManager.loadHDPerspectives(HDMapManager.java:74) ~[Dynmap-3.4-spigot (4).jar:?]
        at org.dynmap.MapManager.<init>(MapManager.java:1145) ~[Dynmap-3.4-spigot (4).jar:?]
        at org.dynmap.DynmapCore.enableCore(DynmapCore.java:622) ~[Dynmap-3.4-spigot (4).jar:?]
        at org.dynmap.bukkit.DynmapPlugin.doEnable(DynmapPlugin.java:1040) ~[Dynmap-3.4-spigot (4).jar:?]
        at org.dynmap.bukkit.DynmapPlugin.onEnable(DynmapPlugin.java:1020) ~[Dynmap-3.4-spigot (4).jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565) ~[paper-1.19.2.jar:git-Paper-282]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479) ~[paper-1.19.2.jar:git-Paper-282]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.19.2.jar:git-Paper-282]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422) ~[paper-1.19.2.jar:git-Paper-282]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.2.jar:git-Paper-282]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.19.2.jar:git-Paper-282]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-282]

 

* **Dynmap Version:** *3.4*
* **Server Version:** *paper 1.19.2 paper version 220*
* **Pastebin of Configuration.txt:** *https://pastebin.com/2Yy2hg3J*
* **Server Host (if applicable):** *personal pc.*
* **Pastebin of crashlogs or other relevant logs:** no crashes

* **Steps to Replicate /plugins dynmap plugins are red while others are green

 [yes ] *I have looked at all other issues and this is not a duplicate*  
 [yes ] *I have been able to replicate this*

**Comment by JurgenKuyper** [comment]
https://gist.github.com/depwl9992/626bf2c20269abe9cda79eeab0de58af
Did you follow this guide?
It looks like you have an error in your yaml syntax

**Comment by NBS-Paste** [comment]
yes  I did use that guide and I just copied and pasted everything
was I not supposed to have the dash in front of class?

**Comment by JurgenKuyper** [comment]
Can you send the edited perspectives file?

**Comment by NBS-Paste** [comment]
[perspectives.txt](https://github.com/webbukkit/dynmap/files/10078990/perspectives.txt)

**Comment by JurgenKuyper** [comment]
That file doesn't contain the set perspective

**Comment by NBS-Paste** [comment]
Would deleting it make dynmap work?

**Comment by NBS-Paste** [comment]
How would I get it to show me a view above the nether roof then?

**Comment by JurgenKuyper** [comment]
send the proper perspective file over in which you added your custom perspective, then I can help fixing the error, and after that dynmap should work.

**Comment by NBS-Paste** [comment]
What do you mean by the proper perspective file?

**Comment by JurgenKuyper** [comment]
I mean the file in which you added the nether_roof perspective as stated in the guide

**Comment by NBS-Paste** [comment]
[custom-perspectives.txt](https://github.com/webbukkit/dynmap/files/10079444/custom-perspectives.txt)

**Comment by JurgenKuyper** [comment]
your indentation of line 4 is wrong, it misses a space before the dash

**Comment by NBS-Paste** [comment]
[custom-perspectives.txt](https://github.com/webbukkit/dynmap/files/10079459/custom-perspectives.txt)
like this?

**Comment by JurgenKuyper** [comment]
that should work yes

**Comment by NBS-Paste** [comment]
I'll try it

**Comment by NBS-Paste** [comment]
I tried it and got to step 10 but it didn't work it just said 
[16:26:23 ERROR]: [dynmap] Exception during render job: world=World_nether, map=org.dynmap.hdmap.HDMap@74b389df
[16:26:23 WARN]: java.lang.IndexOutOfBoundsException: Index 2 out of bounds for length 2
[16:26:23 WARN]:        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
[16:26:23 WARN]:        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
[16:26:23 WARN]:        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
[16:26:23 WARN]:        at java.base/java.util.Objects.checkIndex(Objects.java:385)
[16:26:23 WARN]:        at java.base/java.util.ArrayList.get(ArrayList.java:427)
[16:26:23 WARN]:        at Dynmap-3.4-spigot (4).jar//org.dynmap.DynmapWorld.getMapState(DynmapWorld.java:550)
[16:26:23 WARN]:        at Dynmap-3.4-spigot (4).jar//org.dynmap.hdmap.IsoHDPerspective.render(IsoHDPerspective.java:1271)
[16:26:23 WARN]:        at Dynmap-3.4-spigot (4).jar//org.dynmap.hdmap.HDMapTile.render(HDMapTile.java:91)
[16:26:23 WARN]:        at Dynmap-3.4-spigot (4).jar//org.dynmap.MapManager$FullWorldRenderState.processTile(MapManager.java:810)
[16:26:23 WARN]:        at Dynmap-3.4-spigot (4).jar//org.dynmap.MapManager$FullWorldRenderState.run(MapManager.java:726)
[16:26:23 WARN]:        at Dynmap-3.4-spigot (4).jar//org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1.run(MapManager.java:234)
[16:26:23 WARN]:        at Dynmap-3.4-spigot (4).jar//org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$2.run(MapManager.java:252)
[16:26:23 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
[16:26:23 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[16:26:23 WARN]:        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
[16:26:23 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[16:26:23 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[16:26:23 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1589)

**Comment by JurgenKuyper** [comment]
try a purgemap, purgequeue and a new fullrender

**Comment by JurgenKuyper** [comment]
closing issue because user didn't respond, thus deeming issue fixed
