### ISSUE TITLE
Dynmap 3.4-Spigot not starting for Spigot 1.19.3

### ISSUE THREAD

**Issue by neotherack** [webbukkit/dynmap#3887]
**Dynmap 3.4-Spigot not starting:** 
*My DynMap plugin for Spigot was working fine for Spigot 1.19.2 but it's not starting for 1.19.3 (just upgraded a few minutes ago)*

* **Dynmap Version:** v3.4-828
* **Server Version:** Spigot 1.19.3
* **Pastebin of Configuration.txt:** same which was working with 1.19.2
* **Server Host (if applicable):** My own linux server
* **Other Relevant Data/Screenshots:** Nothing relevant
* **Steps to Replicate:** Just start it with the new 1.19.3 (JAR created on my own following build steps from spigot manual

 [x] *I have looked at all other issues and this is not a duplicate*  
 [x] *I have been able to replicate this*

Error on logs:
[00:36:43] [Server thread/INFO]: [dynmap] Enabling dynmap v3.4-828
[00:36:43] [Server thread/ERROR]: Error occurred while enabling dynmap v3.4-828 (Is it up to date?)
java.lang.NoSuchFieldError: V
        at org.dynmap.bukkit.helper.v119.BukkitVersionHelperSpigot119.initializeBlockStates(BukkitVersionHelperSpigot119.java:167) ~[?:?]
        at org.dynmap.bukkit.DynmapPlugin.onEnable(DynmapPlugin.java:921) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:539) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3612-Spigot-61bffe0-e85280e]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:453) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3612-Spigot-61bffe0-e85280e]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:587) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3612-Spigot-61bffe0-e85280e]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:412) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3612-Spigot-61bffe0-e85280e]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3612-Spigot-61bffe0-e85280e]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:973) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3612-Spigot-61bffe0-e85280e]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:301) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3612-Spigot-61bffe0-e85280e]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by tobfos2611** [comment]
Same issue here.

**Comment by JurgenKuyper** [comment]
1.19.3 is not yet supported as it only came out a few hours ago, please wait untill we broadcast the new version on the regular channels.

**Comment by mikeprimm** [comment]
Development builds available for 3.5 (3.5-SNAPSHOT), including 1.19.3 support - see https://dynmap.us/builds/dynmap for appropriate files.   3.5-beta-1 is intended for release sometime Sunday night.

**Comment by tohasu** [comment]
Jan 7 - Just built 1.19.3 (Spigot) as I have done many times before.. Ran my world using the new build.  Dynmap 3.4 fails -- I get a white screen.  Trying a shift-reload does not help.  
I went through this a month ago and thought maybe the 1.19.3 build had some problems with dynmap yet to be resolved.  I was able to go back to using 1.19.2 and got my map back.
From the MC terminal I cannot do anything with dnymap.  
I will chase down the new build mikep[rimm mentiones above and try  that.   Stay tuned.

**Comment by tohasu** [comment]
the builds page mikeprimm links above lists several flavors of dynmap-3.5.  Can someone he;lp me ID the one I want from the list that includes "bets" "forge" api" "SNAPSHOT"  the one I tried did not start a new dynmap.
Thanks.

**Comment by mikeprimm-mirific** [comment]
3.5-beta-1 has been released for weeks, on the usual places (dev.bukkit.org. spigotmc.org).   https://dev.bukkit.org/projects/dynmap/files/4167109

**Comment by tohasu** [comment]
thanks for the guidance

On January 7, 2023, Michael Primm ***@***.***> wrote:
> 3.5-beta-1 has been released for weeks, on the usual places
> (dev.bukkit.org. spigotmc.org).
>

—
Reply to this email directly, view it on GitHub
<https://github.com/webbukkit/dynmap/issues/3887#issuecomment-
1374693814>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AOSDPYNR5RMJEHDHZOGVWA3WRIUDZANCNFSM6AAAAAASXQPEX4>.
You are receiving this because you commented.Message ID:
***@***.***>
