### ISSUE TITLE
add new perspective

### ISSUE THREAD

**Issue by NBS-Paste** [webbukkit/dynmap#3902]
I need help adding a new perspective.  I want one like the surface perspective but on the left side

**Comment by JurgenKuyper** [comment]
https://github.com/webbukkit/dynmap/wiki/HD-Map-Configuration
You'd need to add a new map using the dmap mapadd command, with instead of the default perspective the one you want, so for example: `/dmap mapadd world:surface2 perspective:iso_NW_60_hires title:"Surface 2" prefix:t2 shader:stdtexture lighting: shadows mapzoomin:1`

**Comment by NBS-Paste** [comment]
That is all one command right?

**Comment by JurgenKuyper** [comment]
Affirmative, but it's an example

**Comment by NBS-Paste** [comment]
Is this the opposite of the surface view?

**Comment by JurgenKuyper** [comment]
> Is this the opposite of the surface view?
https://github.com/webbukkit/dynmap/wiki/HD-Map-Configuration.

**Comment by NBS-Paste** [comment]
Would I put that in the custom perspectives file or use the command

**Comment by JurgenKuyper** [comment]
It's a command, so maybe try and see what it does

**Comment by JurgenKuyper** [comment]
closing issue bc user did not respond here, and didn't reply to the answer in discord.

**Comment by NBS-Paste** [comment]
i put in the command and then di /dynmap fullrender world surface2 but it said it wasnt defined/loaded

**Comment by JurgenKuyper** [comment]
1. What command did you use, 2. What was the output, 3. You didn't respond on the answer given to you on discord so the support question so it was assumed fixed.

**Comment by NBS-Paste** [comment]
I use the command you gave me. It then said the map was created, so I tried to render the new view.

**Comment by JurgenKuyper** [comment]
please answer all the questions asked propperly.

**Comment by NBS-Paste** [comment]
I figured on the discord it was more how to do it so I didn’t need to respond. I tried it and it still didn’t work.

**Comment by JurgenKuyper** [comment]
please answer all the questions asked properly.

**Comment by NBS-Paste** [comment]
> I use the command you gave me. It then said the map was created, so I tried to render the new view.

It said that the map didn’t exist.

**Comment by JurgenKuyper** [comment]
you still didn't answer my 1 and 2 question.

**Comment by NBS-Paste** [comment]
I used /dmap mapadd world:surface2 perspective:iso_NW_60_hires title:"Surface 2" prefix:t2 shader:stdtexture lighting: shadows mapzoomin:1 

the output was it said the map was created but I couldn’t get it to render.

**Comment by JurgenKuyper** [comment]
what command did you issue to try the render.

**Comment by JurgenKuyper** [comment]
invalid syntax. https://github.com/webbukkit/dynmap/wiki/Commands

**Comment by NBS-Paste** [comment]
Would it be /dynmap fullrender world: surface2

**Comment by JurgenKuyper** [comment]
invalid syntax. https://github.com/webbukkit/dynmap/wiki/Commands

**Comment by NBS-Paste** [comment]
I just tired putting in the command again and it gave me this

[09:41:54 INFO]: Perspective not found: iao_NW_60_hires
[09:41:54 INFO]: If you are done editing map data, run '/dynmap pause none' to resume rendering
>

**Comment by JurgenKuyper** [comment]
🤦

**Comment by JurgenKuyper** [comment]
just issue a fullrender on the whole world and be done with it.

**Comment by NBS-Paste** [comment]
it has been five minutes and it has only said [09:48:50 INFO]: Full render starting on world 'World'...

Is this normal when adding a new view?

**Comment by JurgenKuyper** [comment]
Be patient. If unpaused it will render

**Comment by NBS-Paste** [comment]
it was paused.

**Comment by NBS-Paste** [comment]
it is rendering my flat view rather than my new view. Is there a way to get it to render my new view first?

**Comment by JurgenKuyper** [comment]
You failed to copy the proper command earlier, so no, with your competence, no it isn't

**Comment by NBS-Paste** [comment]
I just tried /dynmap fullrender world:surface2 and it gave me this

[10:08:54 ERROR]: [dynmap] Exception during render job: world=World, map=org.dynmap.hdmap.HDMap@b0ad53c
[10:08:54 WARN]: java.lang.IndexOutOfBoundsException: Index 3 out of bounds for length 3
[10:08:54 WARN]:        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
[10:08:54 WARN]:        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
[10:08:54 WARN]:        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
[10:08:54 WARN]:        at java.base/java.util.Objects.checkIndex(Objects.java:385)
[10:08:54 WARN]:        at java.base/java.util.ArrayList.get(ArrayList.java:427)
[10:08:54 WARN]:        at Dynmap-3.5-beta-1-spigot.jar//org.dynmap.DynmapWorld.getMapState(DynmapWorld.java:550)
[10:08:54 WARN]:        at Dynmap-3.5-beta-1-spigot.jar//org.dynmap.hdmap.IsoHDPerspective.render(IsoHDPerspective.java:1271)
[10:08:54 WARN]:        at Dynmap-3.5-beta-1-spigot.jar//org.dynmap.hdmap.HDMapTile.render(HDMapTile.java:91)
[10:08:54 WARN]:        at Dynmap-3.5-beta-1-spigot.jar//org.dynmap.MapManager$FullWorldRenderState.processTile(MapManager.java:810)
[10:08:54 WARN]:        at Dynmap-3.5-beta-1-spigot.jar//org.dynmap.MapManager$FullWorldRenderState.run(MapManager.java:726)
[10:08:54 WARN]:        at Dynmap-3.5-beta-1-spigot.jar//org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1.run(MapManager.java:234)
[10:08:54 WARN]:        at Dynmap-3.5-beta-1-spigot.jar//org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$2.run(MapManager.java:252)
[10:08:54 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
[10:08:54 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[10:08:54 WARN]:        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
[10:08:54 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[10:08:54 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[10:08:54 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1589)
[10:08:56 WARN]: [MorePotions] Plugin MorePotions v1.8 generated an exception while executing task 6
java.lang.NoSuchMethodError: 'org.bukkit.entity.Player[] org.bukkit.Server.getOnlinePlayers()'
        at com.ells1231.Stats.Metrics.postPlugin(Metrics.java:335) ~[MorePotions.jar:?]
        at com.ells1231.Stats.Metrics.access$4(Metrics.java:328) ~[MorePotions.jar:?]
        at com.ells1231.Stats.Metrics$1.run(Metrics.java:223) ~[MorePotions.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.3.jar:git-Paper-349]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.3.jar:git-Paper-349]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.3.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]

**Comment by JurgenKuyper** [comment]
you cannot run dual fullrenders on the same world, wait untill the original one finished

**Comment by NBS-Paste** [comment]
Oh

**Comment by NBS-Paste** [comment]
it is working now. sorry for bugging you so much.

**Comment by onlyhappythoughts** [comment]
Just stumbled upon this.
@JurgenKuyper kudos for showing so much patience, even though your frustration was showing a bit at some points. xD

**Comment by JurgenKuyper** [comment]
yeah, just re-read it, and I was quite savage in some of the comments, but also on discord they were so not self-investigative, was really quite frustrating to ask the same questions multiple times
