### ISSUE TITLE
Not compatible

### ISSUE THREAD

**Issue by 5UP3RTH30B4G** [webbukkit/dynmap#3931]
**Issue Description:** *Not compatible with Mohist ?*

**Dynmap Version:** *v3.4-828*
**Server Version:** *Mohist-1.12.2-320 (MC: 1.12.2)*
**Server Host (if applicable):** *BisectHosting*

**Pastebin of crashlogs or other relevant logs:**
[08.02 18:41:52] [Server] [INFO] [dynmap] version=git-Mohist-1.12.2-320 (MC: 1.12.2)
[08.02 18:41:52] [Server] [ERROR] [dynmap] Error finding net.minecraft.server packages
[08.02 18:41:52] [Server] [ERROR] [dynmap] Cannot find [Lnet.minecraft.server.BiomeBase;
[08.02 18:41:52] [Server] [ERROR] [dynmap] Cannot find net.minecraft.server.BiomeStorage
[08.02 18:41:52] [Server] [ERROR] Error initializing dynmap - bukkit version incompatible! initializing dynmap v3.4-828 (Is it up to date?)
[08.02 18:41:52] [Server]  java.lang.IllegalArgumentExceptionError initializing dynmap - bukkit version incompatible!
[08.02 18:41:52] [Server] 	at org.dynmap.bukkit.helper.BukkitVersionHelperGeneric.<init>(BukkitVersionHelperGeneric.java:165) ~[?:?]
[08.02 18:41:52] [Server] 	at org.dynmap.bukkit.helper.BukkitVersionHelperCB.<init>(BukkitVersionHelperCB.java:44) ~[?:?]
[08.02 18:41:52] [Server] 	at org.dynmap.bukkit.Helper.getHelper(Helper.java:83) ~[?:?]
[08.02 18:41:52] [Server] 	at org.dynmap.bukkit.DynmapPlugin.onLoad(DynmapPlugin.java:889) ~[?:?]
[08.02 18:41:52] [Server] 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:397) [CraftServer.class:?]
[08.02 18:41:52] [Server] 	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:339) [MinecraftServer.class:?]
[08.02 18:41:52] [Server] 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:315) [nz.class:?]
[08.02 18:41:52] [Server] 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:590) [MinecraftServer.class:?]
[08.02 18:41:52] [Server] 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_311]

**Comment by JurgenKuyper** [comment]
we don't support mohist, and we are against the use of it; https://essentialsx.net/do-not-use-mohist.html
please use either spigot, paper, forge or fabric
