### ISSUE TITLE
Dynmap 3.5 Beta 2 error with Paper 1.19.3-420

### ISSUE THREAD

**Issue by scysys** [webbukkit/dynmap#3938]
**Issue Description:**

Using Dynmap-3.5-beta-2-spigot.jar will not working.

**Dynmap Version:** *dynmap-version*

Dynmap-3.5-beta-2-spigot.jar

**Server Version:** *forge 1.16 build x, or paper 1.15.2 build x*

paper-1.19.3-420.jar

**Pastebin of crashlogs or other relevant logs:**

```
[13:32:50 ERROR]: [dynmap] Error loading maptype
java.lang.reflect.InvocationTargetException: null
        at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:77) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:483) ~[?:?]
        at org.dynmap.ConfigurationNode.createInstance(ConfigurationNode.java:344) ~[Dynmap-3.5-beta-2-spigot.jar:?]
        at org.dynmap.ConfigurationNode.createInstances(ConfigurationNode.java:358) ~[Dynmap-3.5-beta-2-spigot.jar:?]
        at org.dynmap.DynmapCore.enableCore(DynmapCore.java:659) ~[Dynmap-3.5-beta-2-spigot.jar:?]
        at org.dynmap.bukkit.DynmapPlugin.doEnable(DynmapPlugin.java:1041) ~[Dynmap-3.5-beta-2-spigot.jar:?]
        at org.dynmap.bukkit.DynmapPlugin.onEnable(DynmapPlugin.java:1021) ~[Dynmap-3.5-beta-2-spigot.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192) ~[paper-1.19.3.jar:git-Paper-420]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.19.3.jar:git-Paper-420]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:561) ~[paper-1.19.3.jar:git-Paper-420]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:472) ~[paper-1.19.3.jar:git-Paper-420]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635) ~[paper-1.19.3.jar:git-Paper-420]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434) ~[paper-1.19.3.jar:git-Paper-420]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.19.3.jar:git-Paper-420]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.19.3.jar:git-Paper-420]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-420]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "org.dynmap.web.HandlerRouter.addServlet(String, org.dynmap.javax.servlet.Servlet)" because "this.router" is null
        at org.dynmap.DynmapCore.addServlet(DynmapCore.java:1070) ~[Dynmap-3.5-beta-2-spigot.jar:?]
        at org.dynmap.InternalClientUpdateComponent.<init>(InternalClientUpdateComponent.java:24) ~[Dynmap-3.5-beta-2-spigot.jar:?]
        at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67) ~[?:?]
        ... 19 more
[13:32:50 WARN]: java.lang.reflect.InvocationTargetException
[13:32:50 WARN]:        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:77)
[13:32:50 WARN]:        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[13:32:50 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:483)
[13:32:50 WARN]:        at Dynmap-3.5-beta-2-spigot.jar//org.dynmap.ConfigurationNode.createInstance(ConfigurationNode.java:344)
[13:32:50 WARN]:        at Dynmap-3.5-beta-2-spigot.jar//org.dynmap.ConfigurationNode.createInstances(ConfigurationNode.java:358)
[13:32:50 WARN]:        at Dynmap-3.5-beta-2-spigot.jar//org.dynmap.DynmapCore.enableCore(DynmapCore.java:659)
[13:32:50 WARN]:        at Dynmap-3.5-beta-2-spigot.jar//org.dynmap.bukkit.DynmapPlugin.doEnable(DynmapPlugin.java:1041)
[13:32:50 WARN]:        at Dynmap-3.5-beta-2-spigot.jar//org.dynmap.bukkit.DynmapPlugin.onEnable(DynmapPlugin.java:1021)
[13:32:50 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279)
[13:32:50 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192)
[13:32:50 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[13:32:50 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[13:32:50 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:561)
[13:32:50 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:472)
[13:32:50 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635)
[13:32:50 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434)
[13:32:50 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
[13:32:50 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1101)
[13:32:50 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[13:32:50 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[13:32:50 WARN]: Caused by: java.lang.NullPointerException: Cannot invoke "org.dynmap.web.HandlerRouter.addServlet(String, org.dynmap.javax.servlet.Servlet)" because "this.router" is null
[13:32:50 WARN]:        at Dynmap-3.5-beta-2-spigot.jar//org.dynmap.DynmapCore.addServlet(DynmapCore.java:1070)
[13:32:50 WARN]:        at Dynmap-3.5-beta-2-spigot.jar//org.dynmap.InternalClientUpdateComponent.<init>(InternalClientUpdateComponent.java:24)
[13:32:50 WARN]:        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
[13:32:50 WARN]:        ... 19 more
[13:32:50 WARN]: [dynmap] Using external server, but class org.dynmap.JsonFileClientUpdateComponent is DISABLED!
[13:32:50 WARN]: [dynmap] If the website is missing files or not loading/updating, this might be why.
[13:32:50 WARN]: [dynmap] For more info, read this: https://github.com/webbukkit/dynmap/wiki/Component-Configuration
```

* **Steps to Replicate:**

Start Paper Server

**Comment by JurgenKuyper** [comment]
Read the last 3 lines.
