### ISSUE TITLE
Last Spigot relase 3.7 beta 1 refused to load on paper 1.20.1

### ISSUE THREAD

**Issue by CloudeLecaw** [webbukkit/dynmap#4021]
> template is **bold**
> sample data is *italicized*

**Issue Description:** *Dynmap sample issue description. This description would include as much and as little detail necessary for us to understand the issue in its entirety.*
The plugin refuses to load on start of an 1.20.1 server in the relased 3.7 beta (see error below)
```
[06:00:50] [Server thread/INFO]: [dynmap] Enabling dynmap v3.7-beta-1-917
[06:00:50] [Server thread/ERROR]: Error occurred while enabling dynmap v3.7-beta-1-917 (Is it up to date?)
java.lang.NoSuchMethodError: 'net.minecraft.core.IRegistryCustom$Dimension net.minecraft.server.MinecraftServer.aU()'
	at org.dynmap.bukkit.helper.v120_2.BukkitVersionHelperSpigot120_2.getBiomeReg(BukkitVersionHelperSpigot120_2.java:118) ~[Dynmap_3.7-Beta1.jar:?]
	at org.dynmap.bukkit.helper.v120_2.BukkitVersionHelperSpigot120_2.getBiomeBaseList(BukkitVersionHelperSpigot120_2.java:131) ~[Dynmap_3.7-Beta1.jar:?]
	at org.dynmap.bukkit.DynmapPlugin.loadExtraBiomes(DynmapPlugin.java:852) ~[Dynmap_3.7-Beta1.jar:?]
	at org.dynmap.bukkit.DynmapPlugin.onEnable(DynmapPlugin.java:937) ~[Dynmap_3.7-Beta1.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.1.jar:git-Paper-196]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-196]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:642) ~[paper-1.20.1.jar:git-Paper-196]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:553) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-196]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[06:00:50] [Server thread/INFO]: [dynmap] Disabling dynmap v3.7-beta-1-917
[06:00:50] [Server thread/ERROR]: Error occurred (in the plugin loader) while disabling dynmap v3.7-beta-1-917 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "org.dynmap.DynmapCore.disableCore()" because "this.core" is null
	at org.dynmap.bukkit.DynmapPlugin.onDisable(DynmapPlugin.java:1095) ~[Dynmap_3.7-Beta1.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:283) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:224) ~[paper-1.20.1.jar:git-Paper-196]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.1.jar:git-Paper-196]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:193) ~[paper-1.20.1.jar:git-Paper-196]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-196]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:642) ~[paper-1.20.1.jar:git-Paper-196]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:553) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-196]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

* **Steps to Replicate:** *Please be clear in this section so we can replicate your issue*
use a paperserver 1.20.1 together with latest spigot release of dynmap 3.7.beta 1
 [ X] *I have looked at all other issues and this is not a duplicate*  
 [ X] *I have been able to replicate this*

**Comment by f1refa11** [comment]
I have the same problem btw.

**Comment by f1refa11** [comment]
Tried using stable v3.6, it worked.

**Comment by JurgenKuyper** [comment]
The latest snapshot, 3.7-beta-2 fixes this

**Comment by CloudeLecaw** [comment]
oh i need to take a lookfor beta -2 then right?:D

**Comment by CloudeLecaw** [comment]
i can agree switching to 3.7-Beta 2 fixed the issue
So i close this ticket.

Thank you for your fast reaction <3
