### ISSUE TITLE
Crash on latest 1.20.2 spigot server

### ISSUE THREAD

**Issue by erdostamasa** [webbukkit/dynmap#4022]
**Issue Description:** Error when startyng dynmap on a fresh Spigot server

* **Dynmap Version:** *Dynmap-3.7-beta-1-spigot*
* **Server Version:** *spigot 1.20.2 built on 2023.09.28. with command: java -jar BuildTools.jar --rev 1.20.2*
* **Pastebin of Configuration.txt:** *no changes to any config files, default spigot server*
* **Server Host (if applicable):** *hosted on a Linux machine*
* **Pastebin of crashlogs or other relevant logs:**

`[10:32:08] [Server thread/INFO]: [dynmap] Enabling dynmap v3.7-beta-1-917
[10:32:08] [Server thread/ERROR]: Error occurred while enabling dynmap v3.7-beta-1-917 (Is it up to date?)
java.lang.NoSuchFieldError: Class net.minecraft.world.level.block.Block does not have member field 'net.minecraft.core.RegistryBlockID o'
        at org.dynmap.bukkit.helper.v120_2.BukkitVersionHelperSpigot120_2.initializeBlockStates(BukkitVersionHelperSpigot120_2.java:159) ~[?:?]
        at org.dynmap.bukkit.DynmapPlugin.onEnable(DynmapPlugin.java:934) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:548) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3894-Spigot-a0f3d48-851a32c]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:462) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3894-Spigot-a0f3d48-851a32c]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:577) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3894-Spigot-a0f3d48-851a32c]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:400) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3894-Spigot-a0f3d48-851a32c]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:250) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3894-Spigot-a0f3d48-851a32c]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:954) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3894-Spigot-a0f3d48-851a32c]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:298) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3894-Spigot-a0f3d48-851a32c]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
`

**Steps to Replicate:** *
1. build latest spigot 1.20.2
2. add Dynmap plugin
3. Run server
4. Dynmap crashes

 [x] *I have looked at all other issues and this is not a duplicate*  
 [x] *I have been able to replicate this*

**Comment by JurgenKuyper** [comment]
known issue, please use spigot build 3895 or higher, they did something that breaks our plugin (and probably many more ones)
