### ISSUE TITLE
Directory failed to load!

### ISSUE THREAD

**Issue by Justman100** [webbukkit/dynmap#4063]
Get this, if i try to start the plugin on my Purpur 1.20.4

> java.lang.RuntimeException: Directory 'plugins/DynmapCore-3.7-SNAPSHOT.jar' failed to load!
   at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:59) ~[purpur-1.20.4.jar:git-Purpur-2114]
   at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.lambda$registerProviders$1(DirectoryProviderSource.java:34) ~[purpur-1.20.4.jar:git-Purpur-2114]
   at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
   at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
   at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
   at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
   at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?]
   at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
   at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
   at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
   at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
   at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
   at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
   at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:32) ~[purpur-1.20.4.jar:git-Purpur-2114]
   at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:14) ~[purpur-1.20.4.jar:git-Purpur-2114]
   at io.papermc.paper.plugin.util.EntrypointUtil.registerProvidersFromSource(EntrypointUtil.java:14) ~[purpur-1.20.4.jar:git-Purpur-2114]
   at io.papermc.paper.plugin.PluginInitializerManager.load(PluginInitializerManager.java:100) ~[purpur-1.20.4.jar:git-Purpur-2114]
   at net.minecraft.server.Main.main(Main.java:131) ~[purpur-1.20.4.jar:git-Purpur-2114]
   at org.bukkit.craftbukkit.Main.main(Main.java:339) ~[purpur-1.20.4.jar:git-Purpur-2114]
   at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
   at java.lang.Thread.run(Thread.java:842) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Directory 'plugins/DynmapCore-3.7-SNAPSHOT.jar' does not contain a paper-plugin.yml or plugin.yml! Could not determine plugin type, cannot load a plugin from it!

**Comment by JurgenKuyper** [comment]
you cannot use dynmapcore as a plugin, we also don't support hybrids, only fabric, forge, paper or spigot. please get the dynmap mod from the regular download locations like: https://modrinth.com/plugin/dynmap/versions and [https://www.spigotmc.org/resources/dynmap®.274/](https://www.spigotmc.org/resources/dynmap%C2%AE.274/)
