### ISSUE TITLE
Support 1.20.5

### ISSUE THREAD

**Issue by sfphoton** [webbukkit/dynmap#4105]
**Issue Description:** *Dynmap cannot be enabled in Spigot 1.20.5*

*It will throw the following exception:*
```
[Server thread/INFO]: [dynmap] Enabling dynmap v3.7-beta-4-935
[Server thread/ERROR]: Error occurred while enabling dynmap v3.7-beta-4-935 (Is it up to date?)
java.lang.NoSuchFieldError: Class net.minecraft.core.BlockPosition does not have member field 'net.minecraft.core.BlockPosition b'
         at org.dynmap.bukkit.helper.v120_4.BukkitVersionHelperSpigot120_4.initializeBlockStates(BukkitVersionHelperSpigot120_4.java:184) ~[?:?]
         at org.dynmap.bukkit.DynmapPlugin.onEnable(DynmapPlugin.java:933) ~[?:?]
         at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot-api-1.20.5-R0.1-SNAPSHOT.jar:?]
         at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.20.5-R0.1-SNAPSHOT.jar:?]
         at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:491) ~[spigot-api-1.20.5-R0.1-SNAPSHOT.jar:?]
         at org.bukkit.craftbukkit.v1_20_R4.CraftServer.enablePlugin(CraftServer.java:541) ~[spigot-1.20.5-R0.1-SNAPSHOT.jar:4123-Spigot-b698b49-90f1059]
         at org.bukkit.craftbukkit.v1_20_R4.CraftServer.enablePlugins(CraftServer.java:455) ~[spigot-1.20.5-R0.1-SNAPSHOT.jar:4123-Spigot-b698b49-90f105>
         at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:634) ~[spigot-1.20.5-R0.1-SNAPSHOT.jar:4123-Spigot-b698b49-90f1059]
         at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:419) ~[spigot-1.20.5-R0.1-SNAPSHOT.jar:4123-Spigot-b698b49-90f1059]
         at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:265) ~[spigot-1.20.5-R0.1-SNAPSHOT.jar:4123-Spigot-b698b49-90f1059]
         at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1010) ~[spigot-1.20.5-R0.1-SNAPSHOT.jar:4123-Spigot-b698b49-90f1059]
         at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:311) ~[spigot-1.20.5-R0.1-SNAPSHOT.jar:4123-Spigot-b698b49-90f1059]
         at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
```

* **Dynmap Version:** *v3.7-beta-4-935*
* **Server Version:** *spigot 1.20.5 (4123-Spigot-b698b49-90f1059)*
* **Steps to Replicate:**
    1. *Download SpigotMC's BuildTools and build version 1.20.5*
    2. *Install dynmap by dropping the jar file into the Plugins folder*
    3. *Start the server*

 [x] *I have looked at all other issues and this is not a duplicate*  
 [x] *I have been able to replicate this*

*Thanks for your help!*

**Comment by JurgenKuyper** [comment]
1.20.5 is not supported yet, please be patient.

**Comment by MrClassicT** [comment]
I have been able to get my server to run using dynmap (self build jar) where I just added 1.20.5 to the allowed versions. Though it does not function as desired which makes it not really useful lol. Best just wait until they fix it properly. :)
Can't say I'm not curious for when that'll be!

**Comment by sfphoton** [comment]
I have just built the spigot version from the source with the latest commits of @mikeprimm and it now seems to be fixed. Thank you by the way, that was quick!

Thus, I'm closing this issue.
