### ISSUE TITLE
Failed to load resources across mods

### ISSUE THREAD

**Issue by ST-DDT** [webbukkit/dynmap#4111]
**Issue Description:**

* **Dynmap Version:** Dynmap-3.6-fabric-1.20.jar + DynmapBlockScan-3.6-fabric-1.20.jar
* **Server Version:** Fabric 1.20.1 (0.15.7)
* **Pastebin of Configuration.txt:** Default 
* **Server Host (if applicable):** Serverminer
* **Pastebin of crashlogs or other relevant logs:**

<details>
<summary>Stacktrace</summary>

````txt
[17:29:38] [Dynmap Render Thread/FATAL]: [Dynmap] Failed to load resource of mod :createoreexcavation
java.nio.file.NoSuchFileException: /assets/create/textures/block/copper_casing_connected.png
	at jdk.nio.zipfs.ZipFileSystem.newInputStream(ZipFileSystem.java:856) ~[jdk.zipfs:?]
	at jdk.nio.zipfs.ZipPath.newInputStream(ZipPath.java:749) ~[jdk.zipfs:?]
	at jdk.nio.zipfs.ZipFileSystemProvider.newInputStream(ZipFileSystemProvider.java:261) ~[jdk.zipfs:?]
	at java.nio.file.Files.newInputStream(Files.java:160) ~[?:?]
	at org.dynmap.fabric_1_20.FabricServer.lambda$openResource$4(FabricServer.java:583) ~[Dynmap-3.6-fabric-1.20.jar:?]
	at java.util.Optional.map(Optional.java:260) ~[?:?]
	at org.dynmap.fabric_1_20.FabricServer.openResource(FabricServer.java:581) ~[Dynmap-3.6-fabric-1.20.jar:?]
	at org.dynmap.hdmap.TexturePackLoader.openModTPResource(TexturePackLoader.java:76) ~[Dynmap-3.6-fabric-1.20.jar:?]
	at org.dynmap.hdmap.TexturePack.<init>(TexturePack.java:683) ~[Dynmap-3.6-fabric-1.20.jar:?]
	at org.dynmap.hdmap.TexturePack.getTexturePack(TexturePack.java:615) ~[Dynmap-3.6-fabric-1.20.jar:?]
	at org.dynmap.hdmap.TexturePackHDShader.getTexturePack(TexturePackHDShader.java:58) ~[Dynmap-3.6-fabric-1.20.jar:?]
	at org.dynmap.hdmap.TexturePackHDShader.access$000(TexturePackHDShader.java:23) ~[Dynmap-3.6-fabric-1.20.jar:?]
	at org.dynmap.hdmap.TexturePackHDShader$ShaderState.<init>(TexturePackHDShader.java:130) ~[Dynmap-3.6-fabric-1.20.jar:?]
	at org.dynmap.hdmap.TexturePackHDShader.getStateInstance(TexturePackHDShader.java:342) ~[Dynmap-3.6-fabric-1.20.jar:?]
	at org.dynmap.hdmap.HDMapManager.getShaderStateForTile(HDMapManager.java:134) ~[Dynmap-3.6-fabric-1.20.jar:?]
	at org.dynmap.hdmap.IsoHDPerspective.render(IsoHDPerspective.java:1241) ~[Dynmap-3.6-fabric-1.20.jar:?]
	at org.dynmap.hdmap.HDMapTile.render(HDMapTile.java:91) ~[Dynmap-3.6-fabric-1.20.jar:?]
	at org.dynmap.MapManager$FullWorldRenderState.processTile(MapManager.java:795) ~[Dynmap-3.6-fabric-1.20.jar:?]
	at org.dynmap.MapManager$FullWorldRenderState.run(MapManager.java:726) ~[Dynmap-3.6-fabric-1.20.jar:?]
	at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1.run(MapManager.java:234) ~[Dynmap-3.6-fabric-1.20.jar:?]
	at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$2.run(MapManager.java:252) ~[Dynmap-3.6-fabric-1.20.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[17:29:38] [Dynmap Render Thread/WARN]: [Dynmap] Resource assets/create/textures/block/copper_casing_connected.png for mod createoreexcavation not found
````

</details>

* **Other Relevant Data/Screenshots:**
  * The map is from 1.20
  * The file `assets/create/textures/block/copper_casing_connected.png` exists in `mods/create-fabric-0.5.1-f-build.1335+mc1.20.1.jar`
* **Steps to Replicate:**
  * Run the server with fabric, dynmap, dynmapblockScan, create and createoreexavation
  * Wait for the renderer to initialize

 [x] *I have looked at all other issues and this is not a duplicate*  
 [x] *I have been able to replicate this*

**Comment by JurgenKuyper** [comment]
if blockscan does not find it, they are not using the standard blockstates as vanilla, thus, dynmap can't render them
