### ISSUE TITLE
I downloaded the Dynmap plugin to the server with the magma 1.20.1 kernel and spammed it into the console. how to solve

### ISSUE THREAD

**Issue by aktosezz** [webbukkit/dynmap#4127]
[21:12:26] [Server thread/WARN] [or.dy.bu.DynmapPlugin/]: [dynmap] Task #1404 for dynmap v3.7-SNAPSHOT-948 generated an exception
java.lang.IllegalAccessError: class org.dynmap.bukkit.helper.v120.MapChunkCache120 tried to access private field net.minecraft.world.level.chunk.LevelChunk.f_62775_ (org.dynmap.bukkit.helper.v120.MapChunkCache120 is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @4d5fe866; net.minecraft.world.level.chunk.LevelChunk is in module minecraft@1.20.1 of loader 'TRANSFORMER' @db99785)
        at org.dynmap.bukkit.helper.v120.MapChunkCache120.getLoadedChunk(MapChunkCache120.java:56) ~[?:?] {}
        at org.dynmap.common.chunk.GenericMapChunkCache.getLoadedChunks(GenericMapChunkCache.java:762) ~[?:?] {}
        at org.dynmap.common.chunk.GenericMapChunkCache.loadChunks(GenericMapChunkCache.java:854) ~[?:?] {}
        at org.dynmap.bukkit.DynmapPlugin$BukkitServer$6.call(DynmapPlugin.java:536) ~[?:?] {}
        at org.dynmap.bukkit.DynmapPlugin$BukkitServer$6.call(DynmapPlugin.java:523) ~[?:?] {}
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftFuture.run(CraftFuture.java:88) ~[forge-1.20.1-47.2.20-universal.jar%2398!/:?] {re:classloading}
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:408) ~[forge-1.20.1-47.2.20-universal.jar%2398!/:?] {re:classloading}
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:1267) ~[server-1.20.1-20230612.114412-srg.jar%2393!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
        at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:400) ~[server-1.20.1-20230612.114412-srg.jar%2393!/:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:1201) ~[server-1.20.1-20230612.114412-srg.jar%2393!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:1012) ~[server-1.20.1-20230612.114412-srg.jar%2393!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:285) ~[server-1.20.1-20230612.114412-srg.jar%2393!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
        at java.lang.Thread.run(Thread.java:1583) [?:?] {re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin}

**Comment by JurgenKuyper** [comment]
please follow the template

**Comment by aktosezz** [comment]
I don't understand English well. What exactly should I do?

**Comment by JurgenKuyper** [comment]
during creation of your ticket there was a template, fill it in in a new ticket and then we can help
