### ISSUE TITLE
[Dynmap] Error while raytracing tile - when used on Fabric together with Shearable Vines mod

### ISSUE THREAD

**Issue by Noshire** [webbukkit/dynmap#4145]
**Issue Description:** Ever since we installed the [Shearable Vines](https://modrinth.com/mod/shearable-vines) mod, the console gets flooded with exceptions and all vines are rendered black, both in overhead and isometric view.

The error:
```
[14:25:57] [Dynmap Render Thread/FATAL]: [Dynmap] Error while raytracing tile: perspective=iso_SE_60_lowres, coord=-4173,55,-2068, blockid=minecraft:vine[west=false,sheared=false,north=false,up=true,east=false,south=true], lighting=0:6, biome=PLAINS(minecraft:plains)
java.lang.ArrayIndexOutOfBoundsException: Index 57 out of bounds for length 32
        at org.dynmap.hdmap.renderer.VineStateRenderer.getRenderPatchList(VineStateRenderer.java:53) ~[Dynmap-3.7-beta-6-fabric-1.21.jar:?]
        at org.dynmap.hdmap.CustomBlockModel.getMeshForBlock(CustomBlockModel.java:53) ~[Dynmap-3.7-beta-6-fabric-1.21.jar:?]
        at org.dynmap.hdmap.IsoHDPerspective$OurPerspectiveState.getPatches(IsoHDPerspective.java:577) ~[Dynmap-3.7-beta-6-fabric-1.21.jar:?]
        at org.dynmap.hdmap.IsoHDPerspective$OurPerspectiveState.visit_block(IsoHDPerspective.java:605) ~[Dynmap-3.7-beta-6-fabric-1.21.jar:?]
        at org.dynmap.hdmap.IsoHDPerspective$OurPerspectiveState.raytrace(IsoHDPerspective.java:726) ~[Dynmap-3.7-beta-6-fabric-1.21.jar:?]
        at org.dynmap.hdmap.IsoHDPerspective$OurPerspectiveState.access$400(IsoHDPerspective.java:81) ~[Dynmap-3.7-beta-6-fabric-1.21.jar:?]
        at org.dynmap.hdmap.IsoHDPerspective.render(IsoHDPerspective.java:1312) ~[Dynmap-3.7-beta-6-fabric-1.21.jar:?]
        at org.dynmap.hdmap.HDMapTile.render(HDMapTile.java:91) ~[Dynmap-3.7-beta-6-fabric-1.21.jar:?]
        at org.dynmap.MapManager$FullWorldRenderState.processTile(MapManager.java:797) ~[Dynmap-3.7-beta-6-fabric-1.21.jar:?]
        at org.dynmap.MapManager$FullWorldRenderState.run(MapManager.java:728) ~[Dynmap-3.7-beta-6-fabric-1.21.jar:?]
        at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1.run(MapManager.java:234) ~[Dynmap-3.7-beta-6-fabric-1.21.jar:?]
        at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$2.run(MapManager.java:252) ~[Dynmap-3.7-beta-6-fabric-1.21.jar:?]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
```

Render screenshots:
![image](https://github.com/user-attachments/assets/018ec1d1-f420-47d3-9ece-34140f0090fe)
![image](https://github.com/user-attachments/assets/8c3795a4-c7b4-4bd1-8a49-c03b0ca7cf16)

I'm aware that this is probably an issue with the plugin adding a property to the block data (`sheared=false`), and dynmap probably not being set up to parse this. I was just wondering if there's any way to get dynmap to work with any mods that add custom data.

* **Dynmap Version:** Dynmap-3.7-beta-6-fabric-1.21
* **Server Version:** fabric-server-mc.1.21-loader.0.16.0-launcher.1.0.1
* **Pastebin of Configuration.txt:** https://pastebin.com/PzXRtVNW
* **Server Host (if applicable):** Selfhosted (Ubuntu Noble)

 [x] *I have looked at all other issues and this is not a duplicate*  
 [x] *I have been able to replicate this*

**Comment by Allerek** [comment]
Im not using Shearable wines, still getting this error on
Dynmap-3.7-beta-6-fabric-1.20.jar
`
Error while raytracing tile: perspective=iso_SE_30_hires, coord=-80,73,24, blockid=minecraft:vine[east=false,north=true,snow_layers=0,south=false,up=false,west=false], lighting=9:0, biome=FOREST(minecraft:forest)
`

Straight out clugging my console.

**Comment by MK12U** [comment]
Hi, I can confirm this still happens with Dynmap 3.7-beta-8 for Fabric v1.21.3/1.21.4 and Shearable Vines 1.4.0 for 1.21.2-1.21.4.

I've tried adding an alias for vines in configuration.txt: `block-alias: "minecraft:vine": "minecraft:air"` and creating a file named minecraft_vine.json in dynmap/renderdata with this:

`{
  "blockname": "minecraft:vine",
  "texture": {
    "all": "minecraft:block/vine"
  },
  "model": {
    "type": "vine" 
  },
  "rendertype": "CUTOUT"
}`

In both cases I still get the same error, here's my log, hope it helps and would love to get a fix on this, thanks!!

`[16:34:18] [Dynmap Render Thread/INFO]: [Dynmap] Loading resource pack standard
[16:34:24] [Dynmap Render Thread/FATAL]: [Dynmap] Error while raytracing tile: perspective=iso_SE_60_lowres, coord=147,25,-75, blockid=minecraft:vine[up=true,south=false,east=false,west=false,north=false,sheared=false], lighting=0:2, biome=LUSH_CAVES(minecraft:lush_caves)
java.lang.ArrayIndexOutOfBoundsException: Index 61 out of bounds for length 32
	at knot/org.dynmap.hdmap.renderer.VineStateRenderer.getRenderPatchList(VineStateRenderer.java:53) ~[Dynmap-3.7-beta-8-fabric-1.21.3.jar:?]
	at knot/org.dynmap.hdmap.CustomBlockModel.getMeshForBlock(CustomBlockModel.java:53) ~[Dynmap-3.7-beta-8-fabric-1.21.3.jar:?]
	at knot/org.dynmap.hdmap.IsoHDPerspective$OurPerspectiveState.getPatches(IsoHDPerspective.java:577) ~[Dynmap-3.7-beta-8-fabric-1.21.3.jar:?]
	at knot/org.dynmap.hdmap.IsoHDPerspective$OurPerspectiveState.visit_block(IsoHDPerspective.java:605) ~[Dynmap-3.7-beta-8-fabric-1.21.3.jar:?]
	at knot/org.dynmap.hdmap.IsoHDPerspective$OurPerspectiveState.raytrace(IsoHDPerspective.java:726) ~[Dynmap-3.7-beta-8-fabric-1.21.3.jar:?]
	at knot/org.dynmap.hdmap.IsoHDPerspective$OurPerspectiveState.access$400(IsoHDPerspective.java:81) ~[Dynmap-3.7-beta-8-fabric-1.21.3.jar:?]
	at knot/org.dynmap.hdmap.IsoHDPerspective.render(IsoHDPerspective.java:1312) ~[Dynmap-3.7-beta-8-fabric-1.21.3.jar:?]
	at knot/org.dynmap.hdmap.HDMapTile.render(HDMapTile.java:91) ~[Dynmap-3.7-beta-8-fabric-1.21.3.jar:?]
	at knot/org.dynmap.MapManager$FullWorldRenderState.processTile(MapManager.java:797) ~[Dynmap-3.7-beta-8-fabric-1.21.3.jar:?]
	at knot/org.dynmap.MapManager$FullWorldRenderState.run(MapManager.java:728) ~[Dynmap-3.7-beta-8-fabric-1.21.3.jar:?]
	at knot/org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1.run(MapManager.java:234) ~[Dynmap-3.7-beta-8-fabric-1.21.3.jar:?]
	at knot/org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$2.run(MapManager.java:252) ~[Dynmap-3.7-beta-8-fabric-1.21.3.jar:?]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
[16:34:24] [Dynmap Render Thread/INFO]: [STDERR]: java.lang.ArrayIndexOutOfBoundsException: Index 61 out of bounds for length 32
[16:34:24] [Dynmap Render Thread/INFO]: [STDERR]: 	at knot//org.dynmap.hdmap.renderer.VineStateRenderer.getRenderPatchList(VineStateRenderer.java:53)
[16:34:24] [Dynmap Render Thread/INFO]: [STDERR]: 	at knot//org.dynmap.hdmap.CustomBlockModel.getMeshForBlock(CustomBlockModel.java:53)
[16:34:24] [Dynmap Render Thread/INFO]: [STDERR]: 	at knot//org.dynmap.hdmap.IsoHDPerspective$OurPerspectiveState.getPatches(IsoHDPerspective.java:577)
[16:34:24] [Dynmap Render Thread/INFO]: [STDERR]: 	at knot//org.dynmap.hdmap.IsoHDPerspective$OurPerspectiveState.visit_block(IsoHDPerspective.java:605)
[16:34:24] [Dynmap Render Thread/INFO]: [STDERR]: 	at knot//org.dynmap.hdmap.IsoHDPerspective$OurPerspectiveState.raytrace(IsoHDPerspective.java:726)
[16:34:24] [Dynmap Render Thread/INFO]: [STDERR]: 	at knot//org.dynmap.hdmap.IsoHDPerspective$OurPerspectiveState.access$400(IsoHDPerspective.java:81)
[16:34:24] [Dynmap Render Thread/INFO]: [STDERR]: 	at knot//org.dynmap.hdmap.IsoHDPerspective.render(IsoHDPerspective.java:1312)
[16:34:24] [Dynmap Render Thread/INFO]: [STDERR]: 	at knot//org.dynmap.hdmap.HDMapTile.render(HDMapTile.java:91)
[16:34:24] [Dynmap Render Thread/INFO]: [STDERR]: 	at knot//org.dynmap.MapManager$FullWorldRenderState.processTile(MapManager.java:797)
[16:34:24] [Dynmap Render Thread/INFO]: [STDERR]: 	at knot//org.dynmap.MapManager$FullWorldRenderState.run(MapManager.java:728)
[16:34:24] [Dynmap Render Thread/INFO]: [STDERR]: 	at knot//org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1.run(MapManager.java:234)
[16:34:24] [Dynmap Render Thread/INFO]: [STDERR]: 	at knot//org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$2.run(MapManager.java:252)
[16:34:24] [Dynmap Render Thread/INFO]: [STDERR]: 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
[16:34:24] [Dynmap Render Thread/INFO]: [STDERR]: 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[16:34:24] [Dynmap Render Thread/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
[16:34:24] [Dynmap Render Thread/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[16:34:24] [Dynmap Render Thread/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[16:34:24] [Dynmap Render Thread/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:1583)`
