### ISSUE TITLE
Dynmap  v3.7 Snapshot 948 on Spigot 1.21.3 server : NoSuchMethodError

### ISSUE THREAD

**Issue by Selunie** [webbukkit/dynmap#4160]
> template is **bold**
> sample data is *italicized*

**Issue Description:** *Dynmap semi-crashes at the server startup (NoSuchMethodError and unable to access to commands).*

* **Dynmap Version:** *3.7 /s948*
* **Server Version:** *CraftBukkit version 4358-Spigot-5eb8a94-6bb0db5 (MC: 1.21.3) (Implementing API version 1.21.3-R0.1-SNAPSHOT)*
* **Pastebin of Configuration.txt:** *https://pastebin.com/p1Vhcmab*
* **Server Host (if applicable):** *OVH*
* **Pastebin of crashlogs or other relevant logs:** *https://pastebin.com/bitxqhUf*
* **Other Relevant Data/Screenshots:** /
* **Steps to Replicate:** *Rebuilt with the recent official BuildTools.jar file and upgraded the Spigot server from 1.21.2 to 1.21.3 yesterday*

 [x] *I have looked at all other issues and this is not a duplicate*  
 [x] *I have been able to replicate this*

**Comment by SomethingGeneric** [comment]
commenting to subscribe

**Comment by SomethingGeneric** [comment]
(encountering same error)

**Comment by NukeWorker** [comment]
ditto!

**Comment by AxiusAran** [comment]
Also having this issue. 

`INFO22:24:33
[dynmap]: Enabling dynmap v3.7-SNAPSHOT-948
ERROR22:24:33
Error occurred while enabling dynmap v3.7-SNAPSHOT-948 (Is it up to date?)
Console22:24:33
java.lang.NoSuchMethodError: 'int net.minecraft.world.level.block.state.BlockState.b(net.minecraft.world.level.BlockGetter, net.minecraft.core.BlockPos)'
	at Dynmap-3.7-beta-7-spigot.jar/org.dynmap.bukkit.helper.v121.BukkitVersionHelperSpigot121.initializeBlockStates(BukkitVersionHelperSpigot121.java:184) ~[Dynmap-3.7-beta-7-spigot.jar:?]
	at Dynmap-3.7-beta-7-spigot.jar/org.dynmap.bukkit.DynmapPlugin.onEnable(DynmapPlugin.java:933) ~[Dynmap-3.7-beta-7-spigot.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.3.jar:1.21.3-10-92131ad]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.3.jar:1.21.3-10-92131ad]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:643) ~[paper-1.21.3.jar:1.21.3-10-92131ad]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:592) ~[paper-1.21.3.jar:1.21.3-10-92131ad]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:767) ~[paper-1.21.3.jar:1.21.3-10-92131ad]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:529) ~[paper-1.21.3.jar:1.21.3-10-92131ad]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:326) ~[paper-1.21.3.jar:1.21.3-10-92131ad]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1233) ~[paper-1.21.3.jar:1.21.3-10-92131ad]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:339) ~[paper-1.21.3.jar:1.21.3-10-92131ad]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
INFO22:24:33
[dynmap]: Disabling dynmap v3.7-SNAPSHOT-948
ERROR22:24:33
Error occurred while disabling dynmap v3.7-SNAPSHOT-948
Console22:24:33
java.lang.NullPointerException: Cannot invoke "org.dynmap.DynmapCore.disableCore()" because "this.core" is null
	at Dynmap-3.7-beta-7-spigot.jar/org.dynmap.bukkit.DynmapPlugin.onDisable(DynmapPlugin.java:1094) ~[Dynmap-3.7-beta-7-spigot.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[paper-1.21.3.jar:1.21.3-10-92131ad]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:114) ~[paper-1.21.3.jar:1.21.3-10-92131ad]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:550) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:206) ~[paper-1.21.3.jar:1.21.3-10-92131ad]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.3.jar:1.21.3-10-92131ad]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:643) ~[paper-1.21.3.jar:1.21.3-10-92131ad]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:592) ~[paper-1.21.3.jar:1.21.3-10-92131ad]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:767) ~[paper-1.21.3.jar:1.21.3-10-92131ad]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:529) ~[paper-1.21.3.jar:1.21.3-10-92131ad]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:326) ~[paper-1.21.3.jar:1.21.3-10-92131ad]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1233) ~[paper-1.21.3.jar:1.21.3-10-92131ad]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:339) ~[paper-1.21.3.jar:1.21.3-10-92131ad]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]`

**Comment by Cassolotl** [comment]
Same here, I [reported on Reddit](https://www.reddit.com/r/Dynmap/comments/1gdaldv/just_updated_from_spigot_1211_to_spigot_1213_and/) a few days ago.

**Comment by AmkSoft** [comment]
My dynmap crashes with this on startup:

[Server thread/INFO]: This server is running CraftBukkit version 4378-Spigot-e65d67a-8ef9079 (MC: 1.21.3) (Implementing API version 1.21.3-R0.1-SNAPSHOT)
[Server thread/INFO]: [dynmap] Enabling dynmap v3.7-SNAPSHOT-948
[Server thread/INFO]: Send: Error occurred while enabling dynmap v3.7-SNAPSHOT-948 (Is it up to date?)
[Server thread/ERROR]: Error occurred while enabling dynmap v3.7-SNAPSHOT-948 (Is it up to date?)
java.lang.NoSuchMethodError: 'int net.minecraft.world.level.block.state.IBlockData.b(net.minecraft.world.level.IBlockAccess, net.minecraft.core.BlockPosition)'
        at org.dynmap.bukkit.helper.v121.BukkitVersionHelperSpigot121.initializeBlockStates(BukkitVersionHelperSpigot121.java:184) ~[?:?]
        at org.dynmap.bukkit.DynmapPlugin.onEnable(DynmapPlugin.java:933) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:267) ~[spigot-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:492) ~[spigot-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_21_R2.CraftServer.enablePlugin(CraftServer.java:579) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4378-Spigot-e65d67a-8ef9079]
        at org.bukkit.craftbukkit.v1_21_R2.CraftServer.enablePlugins(CraftServer.java:493) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4378-Spigot-e65d67a-8ef9079]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:656) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4378-Spigot-e65d67a-8ef9079]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:441) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4378-Spigot-e65d67a-8ef9079]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:268) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4378-Spigot-e65d67a-8ef9079]
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1032) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4378-Spigot-e65d67a-8ef9079]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4378-Spigot-e65d67a-8ef9079]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]

**Comment by ThomasGITH** [comment]
Commenting to subscribe

**Comment by rautamiekka** [comment]
> Commenting to subscribe

Literally not necessary, just press a button.

**Comment by jacob1** [comment]
There's a PR that fixes it here: https://github.com/webbukkit/dynmap/pull/4164

And a .jar download too for anyone who needs it.

**Comment by SomethingGeneric** [comment]
Yooo sweet

**Comment by Tweaky1** [comment]
Commenting to subscribe
Edit -
Commented before fully reading all the subsequent posts. The .jar attached to the PR jacob1 linked works for me.

**Comment by Brokkonaut** [comment]
> Commenting to subscribe

There is a subscribe button on the right, no need to spam bugreports with this :)

**Comment by cbrunnkvist** [comment]
the same

  ```
[22:16:09 INFO]: [dynmap] Loading server plugin dynmap v3.7-SNAPSHOT-948
  [22:16:09 INFO]: [dynmap] version=1.21.3-82-5a60ffb (MC: 1.21.3)
  [22:16:09 INFO]: [dynmap] Mod Support API available
  [22:16:14 INFO]: [dynmap] Enabling dynmap v3.7-SNAPSHOT-948
  [22:16:14 ERROR]: Error occurred while enabling dynmap v3.7-SNAPSHOT-948 (Is it up to date?)
	  at Dynmap-3.7-beta-7-spigot.jar/org.dynmap.bukkit.helper.v121.BukkitVersionHelperSpigot121.initializeBlockStates(BukkitVersionHelperSpigot121.java:184) ~[Dynmap-3.7-beta-7-spigot.jar:?]
	  at Dynmap-3.7-beta-7-spigot.jar/org.dynmap.bukkit.DynmapPlugin.onEnable(DynmapPlugin.java:933) ~[Dynmap-3.7-beta-7-spigot.jar:?]
  [22:16:14 INFO]: [dynmap] Disabling dynmap v3.7-SNAPSHOT-948
  [22:16:14 ERROR]: Error occurred while disabling dynmap v3.7-SNAPSHOT-948
  java.lang.NullPointerException: Cannot invoke "org.dynmap.DynmapCore.disableCore()" because "this.core" is null
	  at Dynmap-3.7-beta-7-spigot.jar/org.dynmap.bukkit.DynmapPlugin.onDisable(DynmapPlugin.java:1094) ~[Dynmap-3.7-beta-7-spigot.jar:?]

```

_<sub>I'll have to use Bluemap in the meantime...</sub>_
