### ISSUE TITLE
Forge immediate server crash on 1.21.4

### ISSUE THREAD

**Issue by pancake-tongs** [webbukkit/dynmap#4178]
**Issue Description:** After deploying the dynmap jar in the mods directory, the server crashes immediately upon the next startup with the stack trace shown below in the pastebin. The short version:

```java.lang.NoSuchMethodError: 'net.minecraft.core.Registry net.minecraft.core.RegistryAccess$Frozen.registryOrThrow(net.minecraft.resources.ResourceKey)'```

* **Dynmap Version:** 3.7-beta-6-forge-1.21
* **Server Version:** forge 1.21.4-54.0.12
* **Pastebin of Configuration.txt:** Dynmap does not run long enough to produce a configuration.txt. A default configuration.txt may be used.
* **Server Host (if applicable):** self-hosted, arch linux, OpenJDK 21.0.5
* **Pastebin of crashlogs or other relevant logs:** https://pastebin.com/LdJE7DnJ
* **Other Relevant Data/Screenshots:** None
* **Steps to Replicate:** 

* 1. Download installer for forge 1.21.4-54.0.12 and execute with --installServer parameter
* 2. Edit eula.txt and launch server once to generate directory structure and configuration files
* 3. Deploy Dynmap jar to mods directory
* 4. Relaunch server using run.sh
* 5. Observe error 

No changes need to be made to any configuration for Minecraft, Forge, or Dynmap to produce the error.

 [X] *I have looked at all other issues and this is not a duplicate*  
    (#4160 is superficially similar, but this is a different error)
 [X] *I have been able to replicate this*

**Comment by freeradicalx** [comment]
+1 here, new install of forge-1.21.4.0.6 with Dynmap-3.7-beta-6-forge-1.21, no other mods installed, server crashes at run. Full error below.

```
[03:36:31] [Server thread/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: 'net.minecraft.core.Registry net.minecraft.core.RegistryAccess$Frozen.registryOrThrow(net.minecraft.resources.ResourceKey)'
        Index: 1
        Listeners:
                0: NORMAL
                1: ASM: org.dynmap.forge_1_21.DynmapMod@83f1e35 onServerStarting(Lnet/minecraftforge/event/server/ServerAboutToStartEvent;)V
                2: net.minecraftforge.eventbus.EventBus$$Lambda/0x0000000301c596e0@1e0c0a76
java.lang.NoSuchMethodError: 'net.minecraft.core.Registry net.minecraft.core.RegistryAccess$Frozen.registryOrThrow(net.minecraft.resources.ResourceKey)'
        at TRANSFORMER/dynmap@3.7-SNAPSHOT-949/org.dynmap.forge_1_21.DynmapPlugin.getBiomeReg(DynmapPlugin.java:202)
        at TRANSFORMER/dynmap@3.7-SNAPSHOT-949/org.dynmap.forge_1_21.DynmapPlugin.getBiomeList(DynmapPlugin.java:290)
        at TRANSFORMER/dynmap@3.7-SNAPSHOT-949/org.dynmap.forge_1_21.DynmapPlugin.loadExtraBiomes(DynmapPlugin.java:1417)
        at TRANSFORMER/dynmap@3.7-SNAPSHOT-949/org.dynmap.forge_1_21.DynmapPlugin.onEnable(DynmapPlugin.java:1473)
        at TRANSFORMER/dynmap@3.7-SNAPSHOT-949/org.dynmap.forge_1_21.Proxy.startServer(Proxy.java:17)
        at TRANSFORMER/dynmap@3.7-SNAPSHOT-949/org.dynmap.forge_1_21.DynmapMod.onServerStarting(DynmapMod.java:119)
        at TRANSFORMER/dynmap@3.7-SNAPSHOT-949/org.dynmap.forge_1_21.__DynmapMod_onServerStarting_ServerAboutToStartEvent.invoke(.dynamic)
        at SECURE-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:48)
        at SECURE-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:304)
        at SECURE-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:290)
        at TRANSFORMER/net.minecraftforge.forge@54.0.6/net.minecraftforge.server.ServerLifecycleHooks.handleServerAboutToStart(ServerLifecycleHooks.java:80)
        at TRANSFORMER/minecraft@1.21.4/net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:188)
        at TRANSFORMER/minecraft@1.21.4/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:679)
        at TRANSFORMER/minecraft@1.21.4/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:278)
        at java.base/java.lang.Thread.run(Thread.java:1583)

[03:36:31] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
java.lang.NoSuchMethodError: 'net.minecraft.core.Registry net.minecraft.core.RegistryAccess$Frozen.registryOrThrow(net.minecraft.resources.ResourceKey)'
        at TRANSFORMER/dynmap@3.7-SNAPSHOT-949/org.dynmap.forge_1_21.DynmapPlugin.getBiomeReg(DynmapPlugin.java:202) ~[Dynmap-3.7-beta-6-forge-1.21.jar!/:?]
        at TRANSFORMER/dynmap@3.7-SNAPSHOT-949/org.dynmap.forge_1_21.DynmapPlugin.getBiomeList(DynmapPlugin.java:290) ~[Dynmap-3.7-beta-6-forge-1.21.jar!/:?]
        at TRANSFORMER/dynmap@3.7-SNAPSHOT-949/org.dynmap.forge_1_21.DynmapPlugin.loadExtraBiomes(DynmapPlugin.java:1417) ~[Dynmap-3.7-beta-6-forge-1.21.jar!/:?]
        at TRANSFORMER/dynmap@3.7-SNAPSHOT-949/org.dynmap.forge_1_21.DynmapPlugin.onEnable(DynmapPlugin.java:1473) ~[Dynmap-3.7-beta-6-forge-1.21.jar!/:?]
        at TRANSFORMER/dynmap@3.7-SNAPSHOT-949/org.dynmap.forge_1_21.Proxy.startServer(Proxy.java:17) ~[Dynmap-3.7-beta-6-forge-1.21.jar!/:?]
        at TRANSFORMER/dynmap@3.7-SNAPSHOT-949/org.dynmap.forge_1_21.DynmapMod.onServerStarting(DynmapMod.java:119) ~[Dynmap-3.7-beta-6-forge-1.21.jar!/:?]
        at TRANSFORMER/dynmap@3.7-SNAPSHOT-949/org.dynmap.forge_1_21.__DynmapMod_onServerStarting_ServerAboutToStartEvent.invoke(.dynamic) ~[Dynmap-3.7-beta-6-forge-1.21.jar!/:?]
        at SECURE-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:48) ~[eventbus-6.2.8.jar!/:?]
        at SECURE-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:304) ~[eventbus-6.2.8.jar!/:?]
        at SECURE-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:290) ~[eventbus-6.2.8.jar!/:?]
        at TRANSFORMER/net.minecraftforge.forge@54.0.6/net.minecraftforge.server.ServerLifecycleHooks.handleServerAboutToStart(ServerLifecycleHooks.java:80) ~[forge-1.21.4-54.0.6-universal.jar!/:?]
        at TRANSFORMER/minecraft@1.21.4/net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:188) ~[forge-1.21.4-54.0.6-server.jar!/:?]
        at TRANSFORMER/minecraft@1.21.4/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:679) ~[forge-1.21.4-54.0.6-server.jar!/:?]
        at TRANSFORMER/minecraft@1.21.4/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:278) ~[forge-1.21.4-54.0.6-server.jar!/:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Transformer Audit:
  net.minecraft.server.MinecraftServer
    REASON: classloading
    PLUGIN: accesstransformer:BEFORE
  net.minecraft.server.dedicated.DedicatedServer
    REASON: classloading
    PLUGIN: accesstransformer:BEFORE
  net.minecraftforge.server.ServerLifecycleHooks
    REASON: classloading
  org.dynmap.forge_1_21.DynmapMod
    REASON: classloading
  org.dynmap.forge_1_21.DynmapPlugin
    REASON: classloading
  org.dynmap.forge_1_21.Proxy
    REASON: classloading
  org.dynmap.forge_1_21.__DynmapMod_onServerStarting_ServerAboutToStartEvent
    REASON: classloading
    PLUGIN: eventbus:BEFORE
[03:36:32] [Server thread/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID a2da7252-9587-4768-95f9-ab072a62afc8
[03:36:32] [Server thread/ERROR] [minecraft/MinecraftServer]: This crash report has been saved to: /opt/minecraft/crash-reports/crash-2024-12-27_03.36.32-server.txt
```

**Comment by mikeprimm** [comment]
Forge 1.21.4 will need a new port (existing 1.21 will not work, unfortunately) - will try to look into this in next few days.

**Comment by Qutatos** [comment]
> Forge 1.21.4 will need a new port (existing 1.21 will not work, unfortunately) - will try to look into this in next few days.

Fabric too =(

**Comment by pancake-tongs** [comment]
Did the release from 1/15/25 resolve this issue?
